import { TestBed } from '@angular/core/testing';

import { sampleWithNewData, sampleWithRequiredData } from '../fiche-von-willebrand.test-samples';

import { FicheVonWillebrandFormService } from './fiche-von-willebrand-form.service';

describe('FicheVonWillebrand Form Service', () => {
  let service: FicheVonWillebrandFormService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(FicheVonWillebrandFormService);
  });

  describe('Service methods', () => {
    describe('createFicheVonWillebrandFormGroup', () => {
      it('should create a new form with FormControl', () => {
        const formGroup = service.createFicheVonWillebrandFormGroup();

        expect(formGroup.controls).toEqual(
          expect.objectContaining({
            id: expect.any(Object),
            dossierNumber: expect.any(Object),
            ordreNumber: expect.any(Object),
            indexNumber: expect.any(Object),
            prenom: expect.any(Object),
            nom: expect.any(Object),
            nomJeuneFille: expect.any(Object),
            profession: expect.any(Object),
            etatCivil: expect.any(Object),
            serviceClinique: expect.any(Object),
            autreServiceClinique: expect.any(Object),
            couvertureSociale: expect.any(Object),
            sexe: expect.any(Object),
            dateNaissance: expect.any(Object),
            ageActuel: expect.any(Object),
            origine: expect.any(Object),
            autreOrigine: expect.any(Object),
            adresse: expect.any(Object),
            telephone: expect.any(Object),
            prenomPere: expect.any(Object),
            professionPere: expect.any(Object),
            nomPrenomMere: expect.any(Object),
            professionMere: expect.any(Object),
            medecinTraitant: expect.any(Object),
            serviceOrigine: expect.any(Object),
            biologisteResponsableDg: expect.any(Object),
            diagnostic: expect.any(Object),
            autreDiagnostic: expect.any(Object),
            anneeDiagnostic: expect.any(Object),
            dateEnregistrementRegistre: expect.any(Object),
            consentementRegistre: expect.any(Object),
            parentsConsanguins: expect.any(Object),
            degreParenteConsanguins: expect.any(Object),
            casSimilaires: expect.any(Object),
            nombreCas: expect.any(Object),
            cas1Numero: expect.any(Object),
            lienParenteCas1: expect.any(Object),
            degreParenteCas1: expect.any(Object),
            typeHemorragieCas1: expect.any(Object),
            cas2Numero: expect.any(Object),
            lienParenteCas2: expect.any(Object),
            degreParenteCas2: expect.any(Object),
            typeHemorragieCas2: expect.any(Object),
            cas3Numero: expect.any(Object),
            lienParenteCas3: expect.any(Object),
            degreParenteCas3: expect.any(Object),
            typeHemorragieCas3: expect.any(Object),
            decesSyndromeHemorragique: expect.any(Object),
            nombreDeces: expect.any(Object),
            deces1Numero: expect.any(Object),
            lienParenteDeces1: expect.any(Object),
            causeDeces1: expect.any(Object),
            deces2Numero: expect.any(Object),
            lienParenteDeces2: expect.any(Object),
            causeDeces2: expect.any(Object),
            deces3Numero: expect.any(Object),
            lienParenteDeces3: expect.any(Object),
            causeDeces3: expect.any(Object),
            enqueteFamiliale: expect.any(Object),
            circonstancesDecouverte: expect.any(Object),
            circonstancesDecouvertePrecision: expect.any(Object),
            jamaisSaigne: expect.any(Object),
            agePremierSigneCliniqueJours: expect.any(Object),
            agePremierSigneCliniqueMois: expect.any(Object),
            agePremierSigneCliniqueAnnees: expect.any(Object),
            symptomeEcchymose: expect.any(Object),
            symptomeEpistaxis: expect.any(Object),
            symptomeGingivorragies: expect.any(Object),
            symptomeMetrorragies: expect.any(Object),
            symptomeMelena: expect.any(Object),
            symptomeHemoptysie: expect.any(Object),
            symptomeHemorragiePostAmygdalectomie: expect.any(Object),
            symptomeHemorragiePostAvulsionDentaire: expect.any(Object),
            symptomeHemorragieChuteCordon: expect.any(Object),
            symptomeAutre: expect.any(Object),
            symptomeAutreDescription: expect.any(Object),
            datePremiereConsultation: expect.any(Object),
            agePremiereConsultationJours: expect.any(Object),
            agePremiereConsultationMois: expect.any(Object),
            agePremiereConsultationAnnees: expect.any(Object),
            ageDiagnosticJours: expect.any(Object),
            ageDiagnosticMois: expect.any(Object),
            ageDiagnosticAnnees: expect.any(Object),
            typeMvW: expect.any(Object),
            sousTypeMvW: expect.any(Object),
            pathologiesAssociees: expect.any(Object),
            dateTestConfirmation: expect.any(Object),
            gs: expect.any(Object),
            hb: expect.any(Object),
            hte: expect.any(Object),
            plaquettes: expect.any(Object),
            tp: expect.any(Object),
            tcaMT: expect.any(Object),
            tcaMPlusT: expect.any(Object),
            tcaMPlusT2H: expect.any(Object),
            fibrinogene: expect.any(Object),
            tsResultat: expect.any(Object),
            tsValeur: expect.any(Object),
            occlusionPlaquettaire: expect.any(Object),
            collageneEpinephrine: expect.any(Object),
            collageneADP: expect.any(Object),
            fvwag: expect.any(Object),
            fvwact: expect.any(Object),
            f8c: expect.any(Object),
            ratioFvwactFvwag: expect.any(Object),
            ratioF8cFvwag: expect.any(Object),
            autresTestsSpecifiques: expect.any(Object),
            vwfCB: expect.any(Object),
            vwfCBResultat: expect.any(Object),
            ripa: expect.any(Object),
            ripaResultat: expect.any(Object),
            multimereHPM: expect.any(Object),
            liaisonFvwF8: expect.any(Object),
            liaisonFvwF8Resultat: expect.any(Object),
            fvwpp: expect.any(Object),
            fvwppResultat: expect.any(Object),
            mutationGenetique: expect.any(Object),
            mutationPresente: expect.any(Object),
            mutationNom: expect.any(Object),
            mutationZygote: expect.any(Object),
            ecchymoses: expect.any(Object),
            ecchymosesSpontanees: expect.any(Object),
            ecchymosesProvoquees: expect.any(Object),
            ecchymosesSiege: expect.any(Object),
            ecchymosesFrequence: expect.any(Object),
            hemorragieMuqueuses: expect.any(Object),
            epistaxis: expect.any(Object),
            epistaxisFrequence: expect.any(Object),
            hemorragiesIntrabuccales: expect.any(Object),
            hemorragiesIntrabuccalesFrequence: expect.any(Object),
            menoragie: expect.any(Object),
            menoragieFrequence: expect.any(Object),
            scoreHighamFait: expect.any(Object),
            scoreHighamValeur: expect.any(Object),
            hematome: expect.any(Object),
            hematomeSpontane: expect.any(Object),
            hematomeProvoque: expect.any(Object),
            hematomeSousCutane: expect.any(Object),
            hematomeMusculaire: expect.any(Object),
            hematomeTissusMous: expect.any(Object),
            hematomeFrequence: expect.any(Object),
            hemarthrose: expect.any(Object),
            hemarthroseSpontane: expect.any(Object),
            hemarthroseProvoque: expect.any(Object),
            hemarthroseSiege: expect.any(Object),
            hemarthroseFrequence: expect.any(Object),
            hemorragieAmygdalienne: expect.any(Object),
            hemorragieAmygdalienneFrequence: expect.any(Object),
            avulsionDentaire: expect.any(Object),
            avulsionPrepare: expect.any(Object),
            avulsionBienDeroule: expect.any(Object),
            traumatisme: expect.any(Object),
            traumatismeType: expect.any(Object),
            chirurgie: expect.any(Object),
            chirurgieType: expect.any(Object),
            chirurgiePrepare: expect.any(Object),
            chirurgieBienDeroule: expect.any(Object),
            accouchement: expect.any(Object),
            hemorragiePostpartum: expect.any(Object),
            circoncision: expect.any(Object),
            ageCirconcision: expect.any(Object),
            circoncisionPrepare: expect.any(Object),
            circoncisionBienDeroule: expect.any(Object),
            hemorragieVisceres: expect.any(Object),
            hemorragieVisceresSpontane: expect.any(Object),
            hemorragieVisceresProvoque: expect.any(Object),
            hemorragieVisceresType: expect.any(Object),
            autreHemorragieVisceres: expect.any(Object),
            explorationVisceres: expect.any(Object),
            lesionSousJacente: expect.any(Object),
            hemorragieGrave: expect.any(Object),
            graveDeglobulisation: expect.any(Object),
            graveEtatDeChoc: expect.any(Object),
            graveParLocalisation: expect.any(Object),
            siegeGraviteLocalisation: expect.any(Object),
            nombreHospitalisations: expect.any(Object),
            nombreTransfusions: expect.any(Object),
            scoreISTHBAT: expect.any(Object),
            desmopressine: expect.any(Object),
            traitementSubstitutifPrevention: expect.any(Object),
            traitementPreparation: expect.any(Object),
            traitementSubstitutifCuratif: expect.any(Object),
            cryoprecipite: expect.any(Object),
            pfc: expect.any(Object),
            concentreFVIIIFVW: expect.any(Object),
            concentreFVW: expect.any(Object),
            concentreFVIII: expect.any(Object),
            agentBypassant: expect.any(Object),
            antifibrinolytiques: expect.any(Object),
            voieOrale: expect.any(Object),
            voieIV: expect.any(Object),
            voieLocale: expect.any(Object),
            oestroprogestatifs: expect.any(Object),
            traitementAntalgique: expect.any(Object),
            corticotherapie: expect.any(Object),
            kinesitherapie: expect.any(Object),
            traitementMartial: expect.any(Object),
            culotsGlobulaires: expect.any(Object),
            nombreCulotsGlobulaires: expect.any(Object),
            immunosuppresseur: expect.any(Object),
            nomImmunosuppresseur: expect.any(Object),
            anemie: expect.any(Object),
            anemieSevere: expect.any(Object),
            tauxHb: expect.any(Object),
            anticorpsAntiFVW: expect.any(Object),
            anticorpsAntiFVIII: expect.any(Object),
            hepatiteB: expect.any(Object),
            hepatiteC: expect.any(Object),
            hiv: expect.any(Object),
            thrombose: expect.any(Object),
            reactionAllergique: expect.any(Object),
            autreComplication: expect.any(Object),
            autreComplicationDescription: expect.any(Object),
            adherenceTherapeutique: expect.any(Object),
            causeNonAdherence: expect.any(Object),
            statutSocial: expect.any(Object),
            marie: expect.any(Object),
            enfants: expect.any(Object),
            activitePhysique: expect.any(Object),
            typeActivitePhysique: expect.any(Object),
            sequelles: expect.any(Object),
            typeSequelles: expect.any(Object),
            patientDecede: expect.any(Object),
            dateDeces: expect.any(Object),
            ageDeces: expect.any(Object),
            causeDeces: expect.any(Object),
          }),
        );
      });

      it('passing IFicheVonWillebrand should create a new form with FormGroup', () => {
        const formGroup = service.createFicheVonWillebrandFormGroup(sampleWithRequiredData);

        expect(formGroup.controls).toEqual(
          expect.objectContaining({
            id: expect.any(Object),
            dossierNumber: expect.any(Object),
            ordreNumber: expect.any(Object),
            indexNumber: expect.any(Object),
            prenom: expect.any(Object),
            nom: expect.any(Object),
            nomJeuneFille: expect.any(Object),
            profession: expect.any(Object),
            etatCivil: expect.any(Object),
            serviceClinique: expect.any(Object),
            autreServiceClinique: expect.any(Object),
            couvertureSociale: expect.any(Object),
            sexe: expect.any(Object),
            dateNaissance: expect.any(Object),
            ageActuel: expect.any(Object),
            origine: expect.any(Object),
            autreOrigine: expect.any(Object),
            adresse: expect.any(Object),
            telephone: expect.any(Object),
            prenomPere: expect.any(Object),
            professionPere: expect.any(Object),
            nomPrenomMere: expect.any(Object),
            professionMere: expect.any(Object),
            medecinTraitant: expect.any(Object),
            serviceOrigine: expect.any(Object),
            biologisteResponsableDg: expect.any(Object),
            diagnostic: expect.any(Object),
            autreDiagnostic: expect.any(Object),
            anneeDiagnostic: expect.any(Object),
            dateEnregistrementRegistre: expect.any(Object),
            consentementRegistre: expect.any(Object),
            parentsConsanguins: expect.any(Object),
            degreParenteConsanguins: expect.any(Object),
            casSimilaires: expect.any(Object),
            nombreCas: expect.any(Object),
            cas1Numero: expect.any(Object),
            lienParenteCas1: expect.any(Object),
            degreParenteCas1: expect.any(Object),
            typeHemorragieCas1: expect.any(Object),
            cas2Numero: expect.any(Object),
            lienParenteCas2: expect.any(Object),
            degreParenteCas2: expect.any(Object),
            typeHemorragieCas2: expect.any(Object),
            cas3Numero: expect.any(Object),
            lienParenteCas3: expect.any(Object),
            degreParenteCas3: expect.any(Object),
            typeHemorragieCas3: expect.any(Object),
            decesSyndromeHemorragique: expect.any(Object),
            nombreDeces: expect.any(Object),
            deces1Numero: expect.any(Object),
            lienParenteDeces1: expect.any(Object),
            causeDeces1: expect.any(Object),
            deces2Numero: expect.any(Object),
            lienParenteDeces2: expect.any(Object),
            causeDeces2: expect.any(Object),
            deces3Numero: expect.any(Object),
            lienParenteDeces3: expect.any(Object),
            causeDeces3: expect.any(Object),
            enqueteFamiliale: expect.any(Object),
            circonstancesDecouverte: expect.any(Object),
            circonstancesDecouvertePrecision: expect.any(Object),
            jamaisSaigne: expect.any(Object),
            agePremierSigneCliniqueJours: expect.any(Object),
            agePremierSigneCliniqueMois: expect.any(Object),
            agePremierSigneCliniqueAnnees: expect.any(Object),
            symptomeEcchymose: expect.any(Object),
            symptomeEpistaxis: expect.any(Object),
            symptomeGingivorragies: expect.any(Object),
            symptomeMetrorragies: expect.any(Object),
            symptomeMelena: expect.any(Object),
            symptomeHemoptysie: expect.any(Object),
            symptomeHemorragiePostAmygdalectomie: expect.any(Object),
            symptomeHemorragiePostAvulsionDentaire: expect.any(Object),
            symptomeHemorragieChuteCordon: expect.any(Object),
            symptomeAutre: expect.any(Object),
            symptomeAutreDescription: expect.any(Object),
            datePremiereConsultation: expect.any(Object),
            agePremiereConsultationJours: expect.any(Object),
            agePremiereConsultationMois: expect.any(Object),
            agePremiereConsultationAnnees: expect.any(Object),
            ageDiagnosticJours: expect.any(Object),
            ageDiagnosticMois: expect.any(Object),
            ageDiagnosticAnnees: expect.any(Object),
            typeMvW: expect.any(Object),
            sousTypeMvW: expect.any(Object),
            pathologiesAssociees: expect.any(Object),
            dateTestConfirmation: expect.any(Object),
            gs: expect.any(Object),
            hb: expect.any(Object),
            hte: expect.any(Object),
            plaquettes: expect.any(Object),
            tp: expect.any(Object),
            tcaMT: expect.any(Object),
            tcaMPlusT: expect.any(Object),
            tcaMPlusT2H: expect.any(Object),
            fibrinogene: expect.any(Object),
            tsResultat: expect.any(Object),
            tsValeur: expect.any(Object),
            occlusionPlaquettaire: expect.any(Object),
            collageneEpinephrine: expect.any(Object),
            collageneADP: expect.any(Object),
            fvwag: expect.any(Object),
            fvwact: expect.any(Object),
            f8c: expect.any(Object),
            ratioFvwactFvwag: expect.any(Object),
            ratioF8cFvwag: expect.any(Object),
            autresTestsSpecifiques: expect.any(Object),
            vwfCB: expect.any(Object),
            vwfCBResultat: expect.any(Object),
            ripa: expect.any(Object),
            ripaResultat: expect.any(Object),
            multimereHPM: expect.any(Object),
            liaisonFvwF8: expect.any(Object),
            liaisonFvwF8Resultat: expect.any(Object),
            fvwpp: expect.any(Object),
            fvwppResultat: expect.any(Object),
            mutationGenetique: expect.any(Object),
            mutationPresente: expect.any(Object),
            mutationNom: expect.any(Object),
            mutationZygote: expect.any(Object),
            ecchymoses: expect.any(Object),
            ecchymosesSpontanees: expect.any(Object),
            ecchymosesProvoquees: expect.any(Object),
            ecchymosesSiege: expect.any(Object),
            ecchymosesFrequence: expect.any(Object),
            hemorragieMuqueuses: expect.any(Object),
            epistaxis: expect.any(Object),
            epistaxisFrequence: expect.any(Object),
            hemorragiesIntrabuccales: expect.any(Object),
            hemorragiesIntrabuccalesFrequence: expect.any(Object),
            menoragie: expect.any(Object),
            menoragieFrequence: expect.any(Object),
            scoreHighamFait: expect.any(Object),
            scoreHighamValeur: expect.any(Object),
            hematome: expect.any(Object),
            hematomeSpontane: expect.any(Object),
            hematomeProvoque: expect.any(Object),
            hematomeSousCutane: expect.any(Object),
            hematomeMusculaire: expect.any(Object),
            hematomeTissusMous: expect.any(Object),
            hematomeFrequence: expect.any(Object),
            hemarthrose: expect.any(Object),
            hemarthroseSpontane: expect.any(Object),
            hemarthroseProvoque: expect.any(Object),
            hemarthroseSiege: expect.any(Object),
            hemarthroseFrequence: expect.any(Object),
            hemorragieAmygdalienne: expect.any(Object),
            hemorragieAmygdalienneFrequence: expect.any(Object),
            avulsionDentaire: expect.any(Object),
            avulsionPrepare: expect.any(Object),
            avulsionBienDeroule: expect.any(Object),
            traumatisme: expect.any(Object),
            traumatismeType: expect.any(Object),
            chirurgie: expect.any(Object),
            chirurgieType: expect.any(Object),
            chirurgiePrepare: expect.any(Object),
            chirurgieBienDeroule: expect.any(Object),
            accouchement: expect.any(Object),
            hemorragiePostpartum: expect.any(Object),
            circoncision: expect.any(Object),
            ageCirconcision: expect.any(Object),
            circoncisionPrepare: expect.any(Object),
            circoncisionBienDeroule: expect.any(Object),
            hemorragieVisceres: expect.any(Object),
            hemorragieVisceresSpontane: expect.any(Object),
            hemorragieVisceresProvoque: expect.any(Object),
            hemorragieVisceresType: expect.any(Object),
            autreHemorragieVisceres: expect.any(Object),
            explorationVisceres: expect.any(Object),
            lesionSousJacente: expect.any(Object),
            hemorragieGrave: expect.any(Object),
            graveDeglobulisation: expect.any(Object),
            graveEtatDeChoc: expect.any(Object),
            graveParLocalisation: expect.any(Object),
            siegeGraviteLocalisation: expect.any(Object),
            nombreHospitalisations: expect.any(Object),
            nombreTransfusions: expect.any(Object),
            scoreISTHBAT: expect.any(Object),
            desmopressine: expect.any(Object),
            traitementSubstitutifPrevention: expect.any(Object),
            traitementPreparation: expect.any(Object),
            traitementSubstitutifCuratif: expect.any(Object),
            cryoprecipite: expect.any(Object),
            pfc: expect.any(Object),
            concentreFVIIIFVW: expect.any(Object),
            concentreFVW: expect.any(Object),
            concentreFVIII: expect.any(Object),
            agentBypassant: expect.any(Object),
            antifibrinolytiques: expect.any(Object),
            voieOrale: expect.any(Object),
            voieIV: expect.any(Object),
            voieLocale: expect.any(Object),
            oestroprogestatifs: expect.any(Object),
            traitementAntalgique: expect.any(Object),
            corticotherapie: expect.any(Object),
            kinesitherapie: expect.any(Object),
            traitementMartial: expect.any(Object),
            culotsGlobulaires: expect.any(Object),
            nombreCulotsGlobulaires: expect.any(Object),
            immunosuppresseur: expect.any(Object),
            nomImmunosuppresseur: expect.any(Object),
            anemie: expect.any(Object),
            anemieSevere: expect.any(Object),
            tauxHb: expect.any(Object),
            anticorpsAntiFVW: expect.any(Object),
            anticorpsAntiFVIII: expect.any(Object),
            hepatiteB: expect.any(Object),
            hepatiteC: expect.any(Object),
            hiv: expect.any(Object),
            thrombose: expect.any(Object),
            reactionAllergique: expect.any(Object),
            autreComplication: expect.any(Object),
            autreComplicationDescription: expect.any(Object),
            adherenceTherapeutique: expect.any(Object),
            causeNonAdherence: expect.any(Object),
            statutSocial: expect.any(Object),
            marie: expect.any(Object),
            enfants: expect.any(Object),
            activitePhysique: expect.any(Object),
            typeActivitePhysique: expect.any(Object),
            sequelles: expect.any(Object),
            typeSequelles: expect.any(Object),
            patientDecede: expect.any(Object),
            dateDeces: expect.any(Object),
            ageDeces: expect.any(Object),
            causeDeces: expect.any(Object),
          }),
        );
      });
    });

    describe('getFicheVonWillebrand', () => {
      it('should return NewFicheVonWillebrand for default FicheVonWillebrand initial value', () => {
        const formGroup = service.createFicheVonWillebrandFormGroup(sampleWithNewData);

        const ficheVonWillebrand = service.getFicheVonWillebrand(formGroup) as any;

        expect(ficheVonWillebrand).toMatchObject(sampleWithNewData);
      });

      it('should return NewFicheVonWillebrand for empty FicheVonWillebrand initial value', () => {
        const formGroup = service.createFicheVonWillebrandFormGroup();

        const ficheVonWillebrand = service.getFicheVonWillebrand(formGroup) as any;

        expect(ficheVonWillebrand).toMatchObject({});
      });

      it('should return IFicheVonWillebrand', () => {
        const formGroup = service.createFicheVonWillebrandFormGroup(sampleWithRequiredData);

        const ficheVonWillebrand = service.getFicheVonWillebrand(formGroup) as any;

        expect(ficheVonWillebrand).toMatchObject(sampleWithRequiredData);
      });
    });

    describe('resetForm', () => {
      it('passing IFicheVonWillebrand should not enable id FormControl', () => {
        const formGroup = service.createFicheVonWillebrandFormGroup();
        expect(formGroup.controls.id.disabled).toBe(true);

        service.resetForm(formGroup, sampleWithRequiredData);

        expect(formGroup.controls.id.disabled).toBe(true);
      });

      it('passing NewFicheVonWillebrand should disable id FormControl', () => {
        const formGroup = service.createFicheVonWillebrandFormGroup(sampleWithRequiredData);
        expect(formGroup.controls.id.disabled).toBe(true);

        service.resetForm(formGroup, { id: null });

        expect(formGroup.controls.id.disabled).toBe(true);
      });
    });
  });
});
