export enum ArticulationCible {
  GENOU_GAUCHE = 'GENOU_GAUCHE',

  GENOU_DROIT = 'GENOU_DROIT',

  COUDE_GAUCHE = 'COUDE_GAUCHE',

  COUDE_DROIT = 'COUDE_DROIT',

  CHEVILLE_GAUCHE = 'CHEVILLE_GAUCHE',

  CHEVILLE_DROITE = 'CHEVILLE_DROITE',
}
