export enum ArticulationCible {
  GENOU_GAUCHE = 'GENOU_GAUCHE',

  GENOU_DROIT = 'GENOU_DROIT',

  COUDE_GAUCHE = 'COUDE_GAUCHE',

  COUDE_DROIT = 'COUDE_DROIT',

  CHEVILLE_GAUCHE = 'CHEVILLE_GAUCHE',

  CHEVILLE_DROITE = 'CHEVILLE_DROITE',

  EPAULE_GAUCHE = 'EPAULE_GAUCHE',

  EPAULE_DROITE = 'EPAULE_DROITE',

  POIGNET_GAUCHE = 'POIGNET_GAUCHE',

  POIGNET_DROIT = 'POIGNET_DROIT',

  HANCHE_GAUCHE = 'HANCHE_GAUCHE',

  HANCHE_DROITE = 'HANCHE_DROITE',
}
