export enum CauseDeces {
  HEMORRAGIE_SNC = 'HEMORRAGIE_SNC',

  HEMORRAGIE_AUTRE = 'HEMORRAGIE_AUTRE',

  HIV = 'HIV',

  INFECTION_AUTRE = 'INFECTION_AUTRE',

  THROMBOEMBOLIQUE = 'THROMBOEMBOLIQUE',

  CANCER = 'CANCER',

  COVID19 = 'COVID19',

  INCONNUE = 'INCONNUE',

  AUTRE = 'AUTRE',
}
