export enum DiagnosticType {
  HEMOPHILIE = 'HEMOPHILIE',

  WILLEBRAND = 'WILLEBRAND',

  THROMBOPATHIE = 'THROMBOPATHIE',

  DEFICIT_FACTEUR_VII = 'DEFICIT_FACTEUR_VII',

  DEFICIT_FACTEUR_XI = 'DEFICIT_FACTEUR_XI',

  DEFICIT_FACTEUR_XIII = 'DEFICIT_FACTEUR_XIII',

  DEFICIT_COMBINE = 'DEFICIT_COMBINE',
}
