export enum ExplorationType {
  CUTANEO_MUQUEUX = 'CUTANEO_MUQUEUX',

  METRORRAGIE = 'METRORRAGIE',

  HEMORRAGIE_CEREBRALE_NN = 'HEMORRAGIE_CEREBRALE_NN',

  HEMORRAGIE_DIGESTIVE = 'HEMORRAGIE_DIGESTIVE',

  HEMARTHROSE = 'HEMARTHROSE',

  HEMORRAGIE_POSTPARTUM = 'HEMORRAGIE_POSTPARTUM',
}
