export enum TypeComplicationsOrthopediques {
  SYNOVITE = 'SYNOVITE',

  ARTHROPATHIE_HEMOPHILIQUE_CHRONIQUE = 'ARTHROPATHIE_HEMOPHILIQUE_CHRONIQUE',

  PSEUDOTUMEURS = 'PSEUDOTUMEURS',

  FRACTURES = 'FRACTURES',
}
