export enum TypeHemorragieCutaneoMuqueuse {
  CHUTE_DENTAIRE = 'CHUTE_DENTAIRE',

  PLAIE_LANGUE = 'PLAIE_LANGUE',

  GINGIVORRAGIES = 'GINGIVORRAGIES',

  EPISTAXIS = 'EPISTAXIS',

  ECHYMOSES = 'ECHYMOSES',
}
