export enum TypeAccidentHemorragiqueGrave {
  HEMATOMES_CEREBRALES = 'HEMATOMES_CEREBRALES',

  HEMOTHORAX = 'HEMOTHORAX',

  EDC_HEMORRAGIQUE = 'EDC_HEMORRAGIQUE',

  HEMATOME_COMPRESSIF = 'HEMATOME_COMPRESSIF',
}
