import dayjs from 'dayjs/esm';

import { IFicheFacteurXIII, NewFicheFacteurXIII } from './fiche-facteur-xiii.model';

export const sampleWithRequiredData: IFicheFacteurXIII = {
  id: 21871,
  etatCivil: 'NP',
  serviceClinique: 'PEDIATRIE_A',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_VII',
};

export const sampleWithPartialData: IFicheFacteurXIII = {
  id: 29329,
  ordreNumber: 'désagréable désigner',
  indexNumber: 'là-haut raide que',
  prenom: 'ouin',
  nom: 'pschitt',
  nomJeuneFille: 'rapprocher glouglou',
  etatCivil: 'MARIE',
  serviceClinique: 'PEDIATRIE_B',
  autreServiceClinique: 'proche grrr généraliser',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  adresse: 'responsable',
  telephone: '0743182704',
  prenomPere: 'orange naguère',
  nomPrenomMere: 'tic-tac',
  professionMere: 'après que',
  diagnostic: 'DEFICIT_COMBINE',
  autreDiagnostic: 'cocorico',
  consentementRegistre: 'NON',
  dateEnregistrementRegistre: dayjs('2025-05-08'),
  degreParenteCas1: 'délégation',
  typeHemorragieCas1: 'administration',
  cas3Numero: 25765,
  lienParenteCas3: 'FRERE',
  degreParenteCas3: 'organiser',
  nombreDeces: 21822,
  deces1Numero: 11590,
  causeDeces1: 'de façon à ce que cot cot',
  deces2Numero: 21438,
  deces3Numero: 23266,
  lienParenteDeces3: 'FRERE',
  enqueteFamiliale: true,
  decouverteFortuite: true,
  hemorragieChuteCordon: true,
  metroragieMenarche: false,
  autresCirconstances: 'avant que',
  hb: 299.32,
  ht: 15129.75,
  tca: 15538.04,
  facteurXIII: 27440.3,
  techniqueChromogenique: false,
  tauxSolubiliteCaillot: 25892.53,
  saignementChuteCordon: 'OUI',
  cicatricesKeloides: 'OUI',
  epistaxis: false,
  gingivorragies: false,
  frequenceGingivorragies: 14477,
  ecchymose: true,
  typeEcchymose: 'PROVOQUE',
  frequenceEcchymose: 11458,
  menorragie: true,
  frequenceHematemese: 12760,
  siegeHematomeMusculaire: 'fort circulaire pourvu que',
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 31335,
  saignementSNC: false,
  hemorragiesPostChirurgicales: false,
  accidentsThrombotiques: false,
  hemorragieGrave: 'NON',
  graveParLocalisation: false,
  chirurgiePatientPrepare: 'OUI',
  chirurgieSuiteHemorragique: 'OUI',
  circoncisionPatientPrepare: 'NP',
  ageCirconcision: 27921,
  plasmaFraisCongele: 'NON',
  culotsPlaquettaires: 'NP',
  dicynone: 'NON',
  traitementOestroprogestatif: 'NP',
  inhibiteurs: 'OUI',
  infectionsVirales: 'OUI',
  vih: 'NP',
  thrombose: false,
  alloimmunisation: false,
  autresComplications: 'adversaire tranquille reconstituer',
  causeNonAdherence: 'pendant diplomate',
  vieSociale: 'CHOMEUR',
  marie: 'NP',
  typeActivitePhysique: 'à seule fin de à peine',
  typeSequelles: 'biathlète en outre de commissionnaire',
  ageDeces: 28518,
  causeDecesSNC: true,
  causeDecesAutreHemorragie: false,
  causeDecesThromboembolique: false,
  causeDecesCancer: true,
  causeDecesInconnue: false,
  autreCauseDeces: "magnifique à l'insu de",
};

export const sampleWithFullData: IFicheFacteurXIII = {
  id: 22465,
  dossierNumber: 'aigre en face de responsable',
  ordreNumber: 'gigantesque quoique',
  indexNumber: 'de crainte que fêter comm',
  prenom: 'cocorico tellement presqu',
  nom: 'hors de manière à ce que',
  nomJeuneFille: 'snif smack équipe de rech',
  profession: 'tant que',
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'AUTRE',
  autreServiceClinique: 'attirer',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-05-09'),
  ageActuel: 11469,
  origine: 'GABES',
  autreOrigine: 'ding espiègle',
  adresse: 'tandis que altruiste tant',
  telephone: '+33 566727469',
  prenomPere: 'suivant',
  professionPere: 'réunir drelin fumer',
  nomPrenomMere: "à l'entour de",
  professionMere: 'dans',
  medecinTraitant: 'tantôt au-dessus arracher',
  serviceOrigine: 'terminer subito terne',
  biologisteResponsableDg: 'tandis que',
  diagnostic: 'THROMBOPATHIE',
  autreDiagnostic: 'aux environs de délégatio',
  anneeDiagnostic: 14592,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-05-09'),
  parentsConsanguins: 'NP',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  casSimilaires: 'OUI',
  nombreCas: 26502,
  cas1Numero: 24830,
  lienParenteCas1: 'LOINTAIN',
  degreParenteCas1: 'porte-parole',
  typeHemorragieCas1: 'nonobstant',
  cas2Numero: 8810,
  lienParenteCas2: 'COUSIN',
  degreParenteCas2: 'lunatique rectorat toutef',
  typeHemorragieCas2: 'afin de substituer de peur de',
  cas3Numero: 32689,
  lienParenteCas3: 'LOINTAIN',
  degreParenteCas3: 'de incognito soupçonner',
  typeHemorragieCas3: 'à côté de',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 26333,
  deces1Numero: 2064,
  lienParenteDeces1: 'COUSIN',
  causeDeces1: 'par suite de',
  deces2Numero: 2719,
  lienParenteDeces2: 'FRERE',
  causeDeces2: 'membre de l’équipe',
  deces3Numero: 13986,
  lienParenteDeces3: 'FRERE',
  causeDeces3: 'meuh plutôt',
  enqueteFamiliale: true,
  decouverteFortuite: true,
  explorationSyndromeHemorragique: true,
  hemorragieChuteCordon: true,
  metroragieMenarche: false,
  hemorragieCerebraleNN: true,
  hemorragiePostPartum: false,
  autresCirconstances: 'crac main-d’œuvre de crainte que',
  datePremierSigneCliniqueEvocateurJour: 16030,
  datePremierSigneCliniqueEvocateurMois: 18640,
  datePremierSigneCliniqueEvocateurAnnee: 14025,
  ageDiagnosticJour: 20066,
  ageDiagnosticMois: 22472,
  ageDiagnosticAnnee: 8256,
  hb: 20355.35,
  ht: 22896.73,
  plaquettes: 2637,
  tp: 5683.18,
  tpMT: 27823.39,
  tca: 3352.64,
  tcaMT: 28924.23,
  fibrinogene: 3106.19,
  ts: 'FAIT_ALLONGE',
  toPfa200: 'FAIT_NORMAL',
  colEpi: 2829.31,
  colAdp: 22755.77,
  facteurXIII: 28263.42,
  techniqueChromogenique: true,
  tauxChromogenique: 997.55,
  techniqueSolubiliteCaillot: false,
  tauxSolubiliteCaillot: 17837.81,
  confirmationMoleculaire: true,
  mutationPresente: true,
  mutationNom: 'aïe présidence',
  mutationType: 'AUCUNE',
  mutation2Nom: 'conseil d’administration de manière à ce que',
  saignementChuteCordon: 'NP',
  cicatricesKeloides: 'OUI',
  retardCicatrisation: 'NP',
  epistaxis: false,
  frequenceEpistaxis: 15513,
  gingivorragies: false,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 1558,
  ecchymose: true,
  typeEcchymose: 'PROVOQUE',
  frequenceEcchymose: 956,
  menorragie: false,
  frequenceMenorragie: 13117,
  hematemese: false,
  frequenceHematemese: 28954,
  rectorragie: true,
  frequenceRectorragie: 11459,
  hematurie: false,
  frequenceHematurie: 20400,
  hematomeSousCutane: true,
  typeHematomeSousCutane: 'PROVOQUE',
  frequenceHematomeSousCutane: 11311,
  hematomeMusculaire: false,
  siegeHematomeMusculaire: 'antagoniste déduire aussitôt que',
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 5922,
  hemarthrose: false,
  typeHemarthrose: 'SPONTANE',
  frequenceHemarthrose: 21425,
  saignementSNC: true,
  typeSaignementSNC: 'SPONTANE',
  frequenceSaignementSNC: 26714,
  ruptureKystesHemorragiques: true,
  hemorragiesPostChirurgicales: false,
  hemoperitone: true,
  accidentsThrombotiques: true,
  typeAccidentsThrombotiques: 'ARTERIEL',
  hemorragieGrave: 'NON',
  graveDeglobulisation: true,
  graveEtatDeChoc: false,
  graveParLocalisation: false,
  siegeGraviteLocalisation: 'cuicui proche de à condition que',
  chirurgiePatientPrepare: 'NP',
  chirurgieSuiteHemorragique: 'NON',
  circoncisionPatientPrepare: 'NON',
  circoncisionSuiteHemorragique: 'OUI',
  ageCirconcision: 21690,
  concentreFacteurXIII: 'OUI',
  plasmaFraisCongele: 'NP',
  cryoprecipite: 'NP',
  culotsPlaquettaires: 'NON',
  dicynone: 'NON',
  exacyl: 'NP',
  traitementMartial: 'OUI',
  traitementOestroprogestatif: 'NON',
  transfusionCGR: 'OUI',
  inhibiteurs: 'OUI',
  inhibiteurNeutralisant: true,
  titreInhibiteurNeutralisant: 19370.43,
  inhibiteurNonNeutralisant: false,
  infectionsVirales: 'NON',
  hepatiteB: 'NON',
  hepatiteC: 'NON',
  vih: 'OUI',
  thrombose: false,
  reactionAllergique: true,
  alloimmunisation: true,
  autresComplications: 'lorsque',
  adherenceTherapeutique: 'NON',
  causeNonAdherence: 'circulaire',
  vieSociale: 'PRESCOLAIRE',
  marie: 'NON',
  enfants: 'NP',
  activitePhysique: 'NP',
  typeActivitePhysique: "vlan d'avec",
  sequelles: 'OUI',
  typeSequelles: 'puisque',
  patientDecede: 'NP',
  dateDeces: dayjs('2025-05-08'),
  ageDeces: 9544,
  causeDecesSNC: false,
  causeDecesAutreHemorragie: true,
  causeDecesVIH: false,
  causeDecesAutreInfection: false,
  causeDecesThromboembolique: false,
  causeDecesCancer: true,
  causeDecesCovid19: false,
  causeDecesInconnue: false,
  autreCauseDeces: 'bzzz de sorte que commis de cuisine',
};

export const sampleWithNewData: NewFicheFacteurXIII = {
  etatCivil: 'NP',
  serviceClinique: 'GYNECO',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_COMBINE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
