import dayjs from 'dayjs/esm';
import { CivilStatus } from 'app/entities/enumerations/civil-status.model';
import { ServiceCliniqueType } from 'app/entities/enumerations/service-clinique-type.model';
import { CouvertureSociale } from 'app/entities/enumerations/couverture-sociale.model';
import { Gender } from 'app/entities/enumerations/gender.model';
import { Region } from 'app/entities/enumerations/region.model';
import { DiagnosticType } from 'app/entities/enumerations/diagnostic-type.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { DegreParente } from 'app/entities/enumerations/degre-parente.model';
import { LienParente } from 'app/entities/enumerations/lien-parente.model';
import { TypeFaitOuNonFaitEtResultat } from 'app/entities/enumerations/type-fait-ou-non-fait-et-resultat.model';
import { MutationType } from 'app/entities/enumerations/mutation-type.model';
import { TypeManifestation } from 'app/entities/enumerations/type-manifestation.model';
import { AccidentsThrombotiquesType } from 'app/entities/enumerations/accidents-thrombotiques-type.model';
import { VieSociale } from 'app/entities/enumerations/vie-sociale.model';

export interface IFicheFacteurXIII {
  id: number;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  prenom?: string | null;
  nom?: string | null;
  nomJeuneFille?: string | null;
  profession?: string | null;
  etatCivil?: keyof typeof CivilStatus | null;
  serviceClinique?: keyof typeof ServiceCliniqueType | null;
  autreServiceClinique?: string | null;
  couvertureSociale?: keyof typeof CouvertureSociale | null;
  sexe?: keyof typeof Gender | null;
  dateNaissance?: dayjs.Dayjs | null;
  ageActuel?: number | null;
  origine?: keyof typeof Region | null;
  autreOrigine?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  prenomPere?: string | null;
  professionPere?: string | null;
  nomPrenomMere?: string | null;
  professionMere?: string | null;
  medecinTraitant?: string | null;
  serviceOrigine?: string | null;
  biologisteResponsableDg?: string | null;
  diagnostic?: keyof typeof DiagnosticType | null;
  autreDiagnostic?: string | null;
  anneeDiagnostic?: number | null;
  consentementRegistre?: keyof typeof OuiNonNP | null;
  dateEnregistrementRegistre?: dayjs.Dayjs | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: keyof typeof DegreParente | null;
  casSimilaires?: keyof typeof OuiNonNP | null;
  nombreCas?: number | null;
  cas1Numero?: number | null;
  lienParenteCas1?: keyof typeof LienParente | null;
  degreParenteCas1?: string | null;
  typeHemorragieCas1?: string | null;
  cas2Numero?: number | null;
  lienParenteCas2?: keyof typeof LienParente | null;
  degreParenteCas2?: string | null;
  typeHemorragieCas2?: string | null;
  cas3Numero?: number | null;
  lienParenteCas3?: keyof typeof LienParente | null;
  degreParenteCas3?: string | null;
  typeHemorragieCas3?: string | null;
  decesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nombreDeces?: number | null;
  deces1Numero?: number | null;
  lienParenteDeces1?: keyof typeof LienParente | null;
  causeDeces1?: string | null;
  deces2Numero?: number | null;
  lienParenteDeces2?: keyof typeof LienParente | null;
  causeDeces2?: string | null;
  deces3Numero?: number | null;
  lienParenteDeces3?: keyof typeof LienParente | null;
  causeDeces3?: string | null;
  enqueteFamiliale?: boolean | null;
  decouverteFortuite?: boolean | null;
  explorationSyndromeHemorragique?: boolean | null;
  hemorragieChuteCordon?: boolean | null;
  metroragieMenarche?: boolean | null;
  hemorragieCerebraleNN?: boolean | null;
  hemorragiePostPartum?: boolean | null;
  autresCirconstances?: string | null;
  datePremierSigneCliniqueEvocateurJour?: number | null;
  datePremierSigneCliniqueEvocateurMois?: number | null;
  datePremierSigneCliniqueEvocateurAnnee?: number | null;
  ageDiagnosticJour?: number | null;
  ageDiagnosticMois?: number | null;
  ageDiagnosticAnnee?: number | null;
  hb?: number | null;
  ht?: number | null;
  plaquettes?: number | null;
  tp?: number | null;
  tpMT?: number | null;
  tca?: number | null;
  tcaMT?: number | null;
  fibrinogene?: number | null;
  ts?: keyof typeof TypeFaitOuNonFaitEtResultat | null;
  toPfa200?: keyof typeof TypeFaitOuNonFaitEtResultat | null;
  colEpi?: number | null;
  colAdp?: number | null;
  facteurXIII?: number | null;
  techniqueChromogenique?: boolean | null;
  tauxChromogenique?: number | null;
  techniqueSolubiliteCaillot?: boolean | null;
  tauxSolubiliteCaillot?: number | null;
  confirmationMoleculaire?: boolean | null;
  mutationPresente?: boolean | null;
  mutationNom?: string | null;
  mutationType?: keyof typeof MutationType | null;
  mutation2Nom?: string | null;
  saignementChuteCordon?: keyof typeof OuiNonNP | null;
  cicatricesKeloides?: keyof typeof OuiNonNP | null;
  retardCicatrisation?: keyof typeof OuiNonNP | null;
  epistaxis?: boolean | null;
  frequenceEpistaxis?: number | null;
  gingivorragies?: boolean | null;
  typeGingivorragies?: keyof typeof TypeManifestation | null;
  frequenceGingivorragies?: number | null;
  ecchymose?: boolean | null;
  typeEcchymose?: keyof typeof TypeManifestation | null;
  frequenceEcchymose?: number | null;
  menorragie?: boolean | null;
  frequenceMenorragie?: number | null;
  hematemese?: boolean | null;
  frequenceHematemese?: number | null;
  rectorragie?: boolean | null;
  frequenceRectorragie?: number | null;
  hematurie?: boolean | null;
  frequenceHematurie?: number | null;
  hematomeSousCutane?: boolean | null;
  typeHematomeSousCutane?: keyof typeof TypeManifestation | null;
  frequenceHematomeSousCutane?: number | null;
  hematomeMusculaire?: boolean | null;
  siegeHematomeMusculaire?: string | null;
  typeHematomeMusculaire?: keyof typeof TypeManifestation | null;
  frequenceHematomeMusculaire?: number | null;
  hemarthrose?: boolean | null;
  typeHemarthrose?: keyof typeof TypeManifestation | null;
  frequenceHemarthrose?: number | null;
  saignementSNC?: boolean | null;
  typeSaignementSNC?: keyof typeof TypeManifestation | null;
  frequenceSaignementSNC?: number | null;
  ruptureKystesHemorragiques?: boolean | null;
  hemorragiesPostChirurgicales?: boolean | null;
  hemoperitone?: boolean | null;
  accidentsThrombotiques?: boolean | null;
  typeAccidentsThrombotiques?: keyof typeof AccidentsThrombotiquesType | null;
  hemorragieGrave?: keyof typeof OuiNonNP | null;
  graveDeglobulisation?: boolean | null;
  graveEtatDeChoc?: boolean | null;
  graveParLocalisation?: boolean | null;
  siegeGraviteLocalisation?: string | null;
  chirurgiePatientPrepare?: keyof typeof OuiNonNP | null;
  chirurgieSuiteHemorragique?: keyof typeof OuiNonNP | null;
  circoncisionPatientPrepare?: keyof typeof OuiNonNP | null;
  circoncisionSuiteHemorragique?: keyof typeof OuiNonNP | null;
  ageCirconcision?: number | null;
  concentreFacteurXIII?: keyof typeof OuiNonNP | null;
  plasmaFraisCongele?: keyof typeof OuiNonNP | null;
  cryoprecipite?: keyof typeof OuiNonNP | null;
  culotsPlaquettaires?: keyof typeof OuiNonNP | null;
  dicynone?: keyof typeof OuiNonNP | null;
  exacyl?: keyof typeof OuiNonNP | null;
  traitementMartial?: keyof typeof OuiNonNP | null;
  traitementOestroprogestatif?: keyof typeof OuiNonNP | null;
  transfusionCGR?: keyof typeof OuiNonNP | null;
  inhibiteurs?: keyof typeof OuiNonNP | null;
  inhibiteurNeutralisant?: boolean | null;
  titreInhibiteurNeutralisant?: number | null;
  inhibiteurNonNeutralisant?: boolean | null;
  infectionsVirales?: keyof typeof OuiNonNP | null;
  hepatiteB?: keyof typeof OuiNonNP | null;
  hepatiteC?: keyof typeof OuiNonNP | null;
  vih?: keyof typeof OuiNonNP | null;
  thrombose?: boolean | null;
  reactionAllergique?: boolean | null;
  alloimmunisation?: boolean | null;
  autresComplications?: string | null;
  adherenceTherapeutique?: keyof typeof OuiNonNP | null;
  causeNonAdherence?: string | null;
  vieSociale?: keyof typeof VieSociale | null;
  marie?: keyof typeof OuiNonNP | null;
  enfants?: keyof typeof OuiNonNP | null;
  activitePhysique?: keyof typeof OuiNonNP | null;
  typeActivitePhysique?: string | null;
  sequelles?: keyof typeof OuiNonNP | null;
  typeSequelles?: string | null;
  patientDecede?: keyof typeof OuiNonNP | null;
  dateDeces?: dayjs.Dayjs | null;
  ageDeces?: number | null;
  causeDecesSNC?: boolean | null;
  causeDecesAutreHemorragie?: boolean | null;
  causeDecesVIH?: boolean | null;
  causeDecesAutreInfection?: boolean | null;
  causeDecesThromboembolique?: boolean | null;
  causeDecesCancer?: boolean | null;
  causeDecesCovid19?: boolean | null;
  causeDecesInconnue?: boolean | null;
  autreCauseDeces?: string | null;
}

export type NewFicheFacteurXIII = Omit<IFicheFacteurXIII, 'id'> & { id: null };
