import dayjs from 'dayjs/esm';
import { CivilStatus } from 'app/entities/enumerations/civil-status.model';
import { ServiceCliniqueType } from 'app/entities/enumerations/service-clinique-type.model';
import { CouvertureSociale } from 'app/entities/enumerations/couverture-sociale.model';
import { Gender } from 'app/entities/enumerations/gender.model';
import { Region } from 'app/entities/enumerations/region.model';
import { DiagnosticType } from 'app/entities/enumerations/diagnostic-type.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { DegreParente } from 'app/entities/enumerations/degre-parente.model';
import { LienParente } from 'app/entities/enumerations/lien-parente.model';
import { FaiteNonFaite } from 'app/entities/enumerations/faite-non-faite.model';
import { ExplorationType } from 'app/entities/enumerations/exploration-type.model';
import { NormalAllonge } from 'app/entities/enumerations/normal-allonge.model';
import { MutationType } from 'app/entities/enumerations/mutation-type.model';
import { TypeManifestation } from 'app/entities/enumerations/type-manifestation.model';
import { TypeAccidentsThrombotiques } from 'app/entities/enumerations/type-accidents-thrombotiques.model';
import { TypeHemorragieGrave } from 'app/entities/enumerations/type-hemorragie-grave.model';
import { VieSocialeType } from 'app/entities/enumerations/vie-sociale-type.model';

export interface IFicheFacteurVIII {
  id: number;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  prenom?: string | null;
  nom?: string | null;
  nomJeuneFille?: string | null;
  profession?: string | null;
  etatCivil?: keyof typeof CivilStatus | null;
  serviceClinique?: keyof typeof ServiceCliniqueType | null;
  autreServiceClinique?: string | null;
  couvertureSociale?: keyof typeof CouvertureSociale | null;
  sexe?: keyof typeof Gender | null;
  dateNaissance?: dayjs.Dayjs | null;
  ageActuel?: number | null;
  origine?: keyof typeof Region | null;
  autreOrigine?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  prenomPere?: string | null;
  professionPere?: string | null;
  nomPrenomMere?: string | null;
  professionMere?: string | null;
  medecinTraitant?: string | null;
  serviceOrigine?: string | null;
  biologisteResponsableDg?: string | null;
  diagnostic?: keyof typeof DiagnosticType | null;
  autreDiagnostic?: string | null;
  anneeDiagnostic?: number | null;
  consentementRegistre?: keyof typeof OuiNonNP | null;
  dateEnregistrementRegistre?: dayjs.Dayjs | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: keyof typeof DegreParente | null;
  casSimilaires?: keyof typeof OuiNonNP | null;
  nombreCas?: number | null;
  cas1Numero?: number | null;
  lienParenteCas1?: keyof typeof LienParente | null;
  degreParenteCas1?: string | null;
  typeHemorragieCas1?: string | null;
  cas2Numero?: number | null;
  lienParenteCas2?: keyof typeof LienParente | null;
  degreParenteCas2?: string | null;
  typeHemorragieCas2?: string | null;
  cas3Numero?: number | null;
  lienParenteCas3?: keyof typeof LienParente | null;
  degreParenteCas3?: string | null;
  typeHemorragieCas3?: string | null;
  decesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nombreDeces?: number | null;
  deces1Numero?: number | null;
  lienParenteDeces1?: keyof typeof LienParente | null;
  causeDeces1?: string | null;
  deces2Numero?: number | null;
  lienParenteDeces2?: keyof typeof LienParente | null;
  causeDeces2?: string | null;
  deces3Numero?: number | null;
  lienParenteDeces3?: keyof typeof LienParente | null;
  causeDeces3?: string | null;
  enqueteFamiliale?: keyof typeof FaiteNonFaite | null;
  decouverteFortuite?: boolean | null;
  enqueteFamilialeBool?: boolean | null;
  explorationSyndromeHemorragique?: boolean | null;
  typeExplorationSyndromeHemorragique?: keyof typeof ExplorationType | null;
  datePremierSigneClinique?: dayjs.Dayjs | null;
  ageDiagnosticJour?: number | null;
  ageDiagnosticMois?: number | null;
  ageDiagnosticAnnee?: number | null;
  tp?: number | null;
  tpMT?: number | null;
  tca?: number | null;
  tcaMT?: number | null;
  fibrinogene?: number | null;
  ts?: keyof typeof FaiteNonFaite | null;
  tsFait?: keyof typeof NormalAllonge | null;
  toPfa?: keyof typeof NormalAllonge | null;
  toPfa200ColEpi?: number | null;
  toPfa200ColAdp?: number | null;
  tauxDosageFacteurXIII?: number | null;
  hb?: number | null;
  ht?: number | null;
  plaquettes?: number | null;
  techniqueChromogenique?: boolean | null;
  tauxTechniqueChromogenique?: number | null;
  techniqueSolubiliteCaillot?: boolean | null;
  tauxTechniqueSolubiliteCaillot?: number | null;
  confirmationMoleculaire?: keyof typeof FaiteNonFaite | null;
  mutationPresence?: boolean | null;
  mutationType?: keyof typeof MutationType | null;
  epistaxis?: boolean | null;
  frequenceEpistaxis?: number | null;
  gingivorragies?: boolean | null;
  typeGingivorragies?: keyof typeof TypeManifestation | null;
  frequenceGingivorragies?: number | null;
  ecchymose?: boolean | null;
  typeEcchymose?: keyof typeof TypeManifestation | null;
  frequenceEcchymose?: number | null;
  menorragie?: boolean | null;
  frequenceMenorragie?: number | null;
  hematemese?: boolean | null;
  frequenceHematemese?: number | null;
  rectorragie?: boolean | null;
  frequenceRectorragie?: number | null;
  hematurie?: boolean | null;
  frequenceHematurie?: number | null;
  hematomeSousCutane?: boolean | null;
  typeHematomeSousCutane?: keyof typeof TypeManifestation | null;
  frequenceHematomeSousCutane?: number | null;
  hematomeMusculaire?: boolean | null;
  siegeHematomeMusculaire?: string | null;
  typeHematomeMusculaire?: keyof typeof TypeManifestation | null;
  frequenceHematomeMusculaire?: number | null;
  hemarthrose?: boolean | null;
  typeHemarthrose?: keyof typeof TypeManifestation | null;
  frequenceHemarthrose?: number | null;
  saignementSNC?: boolean | null;
  typeSaignementSNC?: keyof typeof TypeManifestation | null;
  frequenceSaignementSNC?: number | null;
  ruptureKystesHemorragiques?: boolean | null;
  hemorragiesPostChirurgicales?: boolean | null;
  hemoperitone?: boolean | null;
  accidentsThrombotiques?: boolean | null;
  typeAccidentsThrombotiques?: keyof typeof TypeAccidentsThrombotiques | null;
  hemorragieGrave?: boolean | null;
  typeHemorragieGrave?: keyof typeof TypeHemorragieGrave | null;
  chirurgiePrepare?: keyof typeof OuiNonNP | null;
  suiteOperatoireHemorragique?: keyof typeof OuiNonNP | null;
  circoncisionPrepare?: keyof typeof OuiNonNP | null;
  suiteOperatoireCirconcision?: keyof typeof OuiNonNP | null;
  ageCirconcision?: number | null;
  facteurVIIIRecombinant?: keyof typeof OuiNonNP | null;
  plasmaFraisCongele?: keyof typeof OuiNonNP | null;
  cryoprecipite?: keyof typeof OuiNonNP | null;
  culotsPlaquettaires?: keyof typeof OuiNonNP | null;
  dicynone?: keyof typeof OuiNonNP | null;
  exacyl?: keyof typeof OuiNonNP | null;
  traitementMartial?: keyof typeof OuiNonNP | null;
  traitementOestroprogestatif?: keyof typeof OuiNonNP | null;
  transfusionCGR?: keyof typeof OuiNonNP | null;
  inhibiteurs?: keyof typeof OuiNonNP | null;
  inhibiteurNeutralisant?: boolean | null;
  titreUB?: number | null;
  inhibiteurNonNeutralisant?: boolean | null;
  infectionsVirales?: keyof typeof OuiNonNP | null;
  thrombose?: keyof typeof OuiNonNP | null;
  reactionAllergique?: keyof typeof OuiNonNP | null;
  alloImmunisation?: keyof typeof OuiNonNP | null;
  adhesionTherapeutique?: keyof typeof OuiNonNP | null;
  causeNonAdhesion?: string | null;
  vieSociale?: keyof typeof VieSocialeType | null;
  mariage?: keyof typeof OuiNonNP | null;
  enfants?: keyof typeof OuiNonNP | null;
  activitePhysique?: keyof typeof OuiNonNP | null;
  typeActivitePhysique?: string | null;
  sequelles?: keyof typeof OuiNonNP | null;
  typeSequelles?: string | null;
  patientDecede?: keyof typeof OuiNonNP | null;
  dateDeces?: dayjs.Dayjs | null;
  ageDeces?: number | null;
  hemorragieSnc?: boolean | null;
  hemorragieAutreQueSnc?: boolean | null;
  hiv?: boolean | null;
  autreInfection?: boolean | null;
  evenementThromboembolique?: boolean | null;
  cancer?: boolean | null;
  covid19?: boolean | null;
  inconnue?: boolean | null;
  autreEvenement?: boolean | null;
  autreEvenementDetails?: string | null;
}

export type NewFicheFacteurVIII = Omit<IFicheFacteurVIII, 'id'> & { id: null };
