import dayjs from 'dayjs/esm';

import { IFicheFacteurVIII, NewFicheFacteurVIII } from './fiche-facteur-viii.model';

export const sampleWithRequiredData: IFicheFacteurVIII = {
  id: 26160,
  etatCivil: 'NP',
  serviceClinique: 'PRIVE',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  diagnostic: 'WILLEBRAND',
};

export const sampleWithPartialData: IFicheFacteurVIII = {
  id: 13894,
  dossierNumber: 'quant à fourbe areu areu',
  nomJeuneFille: 'avex innombrable miam',
  etatCivil: 'DIVORCE',
  serviceClinique: 'GYNECO',
  autreServiceClinique: 'direction',
  couvertureSociale: 'INDIGENT',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-22'),
  ageActuel: 4021,
  adresse: 'à cause de loufoque',
  prenomPere: 'coupable ignorer',
  professionPere: 'répéter',
  biologisteResponsableDg: 'lectorat tantôt virer',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  anneeDiagnostic: 27090,
  lienParenteCas1: 'FRERE',
  cas2Numero: 21855,
  degreParenteCas2: 'minuscule désagréable glo',
  typeHemorragieCas2: 'envers trop de',
  cas3Numero: 26435,
  typeHemorragieCas3: 'aussitôt',
  decesSyndromeHemorragique: 'NON',
  lienParenteDeces1: 'LOINTAIN',
  causeDeces1: "concurrence à l'égard de",
  deces2Numero: 15676,
  causeDeces2: 'a parlementaire',
  lienParenteDeces3: 'FRERE',
  causeDeces3: 'fidèle tant que',
  enqueteFamiliale: 'FAITE',
  decouverteFortuite: false,
  enqueteFamilialeBool: false,
  datePremierSigneClinique: dayjs('2025-02-23'),
  tca: 25320.08,
  ts: 'NONFAITE',
  tsFait: 'NORMAL',
  toPfa: 'ALLONGE',
  toPfa200ColEpi: 153.72,
  hb: 7014.82,
  ht: 6347.03,
  techniqueChromogenique: true,
  tauxTechniqueChromogenique: 14556.32,
  techniqueSolubiliteCaillot: false,
  tauxTechniqueSolubiliteCaillot: 7344.58,
  mutationPresence: false,
  frequenceEpistaxis: 26296,
  gingivorragies: true,
  typeGingivorragies: 'SPONTANE',
  frequenceGingivorragies: 3864,
  frequenceEcchymose: 24274,
  frequenceMenorragie: 5640,
  rectorragie: true,
  hematomeSousCutane: true,
  typeHematomeSousCutane: 'SPONTANE',
  hematomeMusculaire: false,
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 14514,
  frequenceHemarthrose: 8989,
  typeSaignementSNC: 'PROVOQUE',
  ruptureKystesHemorragiques: true,
  accidentsThrombotiques: false,
  typeHemorragieGrave: 'ETAT_DE_CHOC',
  circoncisionPrepare: 'OUI',
  ageCirconcision: 25378,
  facteurVIIIRecombinant: 'NON',
  plasmaFraisCongele: 'OUI',
  transfusionCGR: 'NON',
  inhibiteurs: 'NP',
  infectionsVirales: 'NP',
  thrombose: 'NP',
  adhesionTherapeutique: 'OUI',
  vieSociale: 'PRESCOLARISE',
  enfants: 'NP',
  typeActivitePhysique: 'bof',
  sequelles: 'NON',
  patientDecede: 'NON',
  dateDeces: dayjs('2025-02-23'),
  hemorragieAutreQueSnc: false,
  hiv: false,
  covid19: true,
};

export const sampleWithFullData: IFicheFacteurVIII = {
  id: 25519,
  dossierNumber: 'au-dessus de',
  ordreNumber: 'après',
  indexNumber: 'aigre gouverner élargir',
  prenom: 'si bien que de façon à ce',
  nom: 'protester',
  nomJeuneFille: 'tandis que attendrir four',
  profession: 'rectorat',
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'AUTRE',
  autreServiceClinique: 'bien que',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-22'),
  ageActuel: 20700,
  origine: 'MAHDIA',
  autreOrigine: 'entièrement triste',
  adresse: 'contre juriste tandis que',
  telephone: '0386001185',
  prenomPere: 'effrayer de crainte que',
  professionPere: 'du moment que bzzz pour q',
  nomPrenomMere: 'main-d’œuvre céans boum',
  professionMere: "également aujourd'hui",
  medecinTraitant: 'lentement membre titulair',
  serviceOrigine: 'plutôt',
  biologisteResponsableDg: 'tandis que de sorte que l',
  diagnostic: 'DEFICIT_COMBINE',
  autreDiagnostic: 'juriste sans que',
  anneeDiagnostic: 6213,
  consentementRegistre: 'NON',
  dateEnregistrementRegistre: dayjs('2025-02-22'),
  parentsConsanguins: 'NON',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  casSimilaires: 'NP',
  nombreCas: 23541,
  cas1Numero: 20631,
  lienParenteCas1: 'FRERE',
  degreParenteCas1: 'trop',
  typeHemorragieCas1: 'commenter jeune enfant',
  cas2Numero: 7790,
  lienParenteCas2: 'FRERE',
  degreParenteCas2: 'prononcer lâche',
  typeHemorragieCas2: 'sitôt dans la mesure où',
  cas3Numero: 1331,
  lienParenteCas3: 'LOINTAIN',
  degreParenteCas3: 'céans',
  typeHemorragieCas3: 'pacifique jusqu’à ce que atchoum',
  decesSyndromeHemorragique: 'NON',
  nombreDeces: 6017,
  deces1Numero: 5706,
  lienParenteDeces1: 'FRERE',
  causeDeces1: 'diététiste en guise de corps enseignant',
  deces2Numero: 1582,
  lienParenteDeces2: 'LOINTAIN',
  causeDeces2: 'vroum',
  deces3Numero: 11451,
  lienParenteDeces3: 'LOINTAIN',
  causeDeces3: 'à condition que présidence',
  enqueteFamiliale: 'NONFAITE',
  decouverteFortuite: false,
  enqueteFamilialeBool: false,
  explorationSyndromeHemorragique: false,
  typeExplorationSyndromeHemorragique: 'METRORRAGIE',
  datePremierSigneClinique: dayjs('2025-02-22'),
  ageDiagnosticJour: 4502,
  ageDiagnosticMois: 12964,
  ageDiagnosticAnnee: 18372,
  tp: 26620.99,
  tpMT: 10005.65,
  tca: 31111.8,
  tcaMT: 5766.69,
  fibrinogene: 2321.94,
  ts: 'NONFAITE',
  tsFait: 'ALLONGE',
  toPfa: 'NORMAL',
  toPfa200ColEpi: 13691.42,
  toPfa200ColAdp: 4508.07,
  tauxDosageFacteurXIII: 14912.66,
  hb: 29717.87,
  ht: 440.49,
  plaquettes: 27074,
  techniqueChromogenique: false,
  tauxTechniqueChromogenique: 14704.3,
  techniqueSolubiliteCaillot: true,
  tauxTechniqueSolubiliteCaillot: 31900.35,
  confirmationMoleculaire: 'NONFAITE',
  mutationPresence: true,
  mutationType: 'HOMOZYGOTE',
  epistaxis: false,
  frequenceEpistaxis: 6035,
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 14785,
  ecchymose: false,
  typeEcchymose: 'PROVOQUE',
  frequenceEcchymose: 24264,
  menorragie: false,
  frequenceMenorragie: 17385,
  hematemese: false,
  frequenceHematemese: 19955,
  rectorragie: false,
  frequenceRectorragie: 30946,
  hematurie: false,
  frequenceHematurie: 5716,
  hematomeSousCutane: false,
  typeHematomeSousCutane: 'PROVOQUE',
  frequenceHematomeSousCutane: 13961,
  hematomeMusculaire: true,
  siegeHematomeMusculaire: 'jusqu’à ce que un peu groin groin',
  typeHematomeMusculaire: 'SPONTANE',
  frequenceHematomeMusculaire: 14514,
  hemarthrose: true,
  typeHemarthrose: 'PROVOQUE',
  frequenceHemarthrose: 11927,
  saignementSNC: true,
  typeSaignementSNC: 'SPONTANE',
  frequenceSaignementSNC: 5969,
  ruptureKystesHemorragiques: true,
  hemorragiesPostChirurgicales: false,
  hemoperitone: true,
  accidentsThrombotiques: true,
  typeAccidentsThrombotiques: 'VEINEUX',
  hemorragieGrave: true,
  typeHemorragieGrave: 'PAR_LA_LOCALISATION',
  chirurgiePrepare: 'NON',
  suiteOperatoireHemorragique: 'NON',
  circoncisionPrepare: 'NP',
  suiteOperatoireCirconcision: 'NON',
  ageCirconcision: 2619,
  facteurVIIIRecombinant: 'NON',
  plasmaFraisCongele: 'NP',
  cryoprecipite: 'OUI',
  culotsPlaquettaires: 'NP',
  dicynone: 'NP',
  exacyl: 'NP',
  traitementMartial: 'NON',
  traitementOestroprogestatif: 'NP',
  transfusionCGR: 'OUI',
  inhibiteurs: 'OUI',
  inhibiteurNeutralisant: true,
  titreUB: 30796.8,
  inhibiteurNonNeutralisant: false,
  infectionsVirales: 'NP',
  thrombose: 'OUI',
  reactionAllergique: 'OUI',
  alloImmunisation: 'NON',
  adhesionTherapeutique: 'NON',
  causeNonAdhesion: 'aux environs de moins',
  vieSociale: 'PRESCOLARISE',
  mariage: 'OUI',
  enfants: 'NON',
  activitePhysique: 'NP',
  typeActivitePhysique: 'vouh membre de l’équipe pousser',
  sequelles: 'NP',
  typeSequelles: 'diplomate au cas où insolite',
  patientDecede: 'OUI',
  dateDeces: dayjs('2025-02-22'),
  ageDeces: 10710,
  hemorragieSnc: true,
  hemorragieAutreQueSnc: true,
  hiv: false,
  autreInfection: false,
  evenementThromboembolique: true,
  cancer: false,
  covid19: true,
  inconnue: true,
  autreEvenement: false,
  autreEvenementDetails: 'probablement envoyer psitt',
};

export const sampleWithNewData: NewFicheFacteurVIII = {
  etatCivil: 'DIVORCE',
  serviceClinique: 'HTO',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_COMBINE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
