import dayjs from 'dayjs/esm';

import { IFicheFacteurVIII, NewFicheFacteurVIII } from './fiche-facteur-viii.model';

export const sampleWithRequiredData: IFicheFacteurVIII = {
  id: 5335,
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'PUR',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_XI',
};

export const sampleWithPartialData: IFicheFacteurVIII = {
  id: 2603,
  dossierNumber: 'à condition que',
  ordreNumber: 'hormis collègue',
  etatCivil: 'MARIE',
  serviceClinique: 'PRIVE',
  autreServiceClinique: 'areu areu sitôt que',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-02-22'),
  adresse: 'durant',
  nomPrenomMere: 'tout alors que',
  medecinTraitant: 'pff',
  diagnostic: 'WILLEBRAND',
  autreDiagnostic: 'dévorer à côté de',
  anneeDiagnostic: 31159,
  consentementRegistre: 'NON',
  dateEnregistrementRegistre: dayjs('2025-02-22'),
  degreParenteConsanguins: 'LOINTAIN',
  nombreCas: 29511,
  lienParenteCas1: 'LOINTAIN',
  typeHemorragieCas1: 'dès que',
  cas2Numero: 20009,
  lienParenteCas2: 'COUSIN',
  lienParenteCas3: 'LOINTAIN',
  decesSyndromeHemorragique: 'NON',
  deces1Numero: 11588,
  causeDeces1: 'garantir',
  lienParenteDeces2: 'FRERE',
  causeDeces2: 'aussitôt que',
  causeDeces3: 'd’autant que tant',
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: true,
  datePremierSigneClinique: dayjs('2025-02-23'),
  ageDiagnosticAnnee: 11906,
  tpMT: 5703.38,
  fibrinogene: 3528.65,
  tsFait: 'NORMAL',
  toPfa: 'ALLONGE',
  toPfa200ColEpi: 16399.42,
  toPfa200ColAdp: 17418.85,
  tauxDosageFacteurXIII: 25697.29,
  hb: 19237.18,
  techniqueSolubiliteCaillot: true,
  tauxTechniqueSolubiliteCaillot: 5331.08,
  mutationPresence: false,
  mutationType: 'AUCUNE',
  frequenceEpistaxis: 22641,
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  ecchymose: true,
  typeEcchymose: 'PROVOQUE',
  frequenceMenorragie: 3337,
  hematemese: false,
  frequenceHematemese: 20943,
  rectorragie: true,
  frequenceRectorragie: 10442,
  hematurie: false,
  frequenceHematurie: 28557,
  typeHematomeSousCutane: 'PROVOQUE',
  hematomeMusculaire: true,
  hemarthrose: true,
  typeHemarthrose: 'SPONTANE',
  frequenceHemarthrose: 23904,
  saignementSNC: false,
  accidentsThrombotiques: false,
  typeAccidentsThrombotiques: 'VEINEUX',
  chirurgiePrepare: 'NON',
  circoncisionPrepare: 'NP',
  suiteOperatoireCirconcision: 'OUI',
  facteurVIIIRecombinant: 'OUI',
  exacyl: 'NON',
  traitementMartial: 'NP',
  inhibiteurs: 'NON',
  reactionAllergique: 'OUI',
  adhesionTherapeutique: 'NP',
  causeNonAdhesion: 'paf aussitôt que',
  mariage: 'NP',
  activitePhysique: 'OUI',
  typeActivitePhysique: 'à même vouh détacher',
  typeSequelles: 'athlète tant',
  patientDecede: 'OUI',
  ageDeces: 4751,
  cancer: true,
  covid19: false,
};

export const sampleWithFullData: IFicheFacteurVIII = {
  id: 10272,
  dossierNumber: 'de façon à ce que sauvage biathlète',
  ordreNumber: 'probablement encore',
  indexNumber: 'dévoiler contre feindre',
  prenom: 'instruire',
  nom: 'avant de drôlement',
  nomJeuneFille: 'diplomate rectorat',
  profession: 'signaler ha',
  etatCivil: 'DIVORCE',
  serviceClinique: 'AUTRE',
  autreServiceClinique: 'pschitt jamais',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-02-23'),
  ageActuel: 30874,
  origine: 'KAIRAOUANE',
  autreOrigine: 'à défaut de ',
  adresse: 'abriter',
  telephone: '0172411469',
  prenomPere: 'biathlète clientèle lente',
  professionPere: 'soupçonner',
  nomPrenomMere: 'premièrement toc-toc cadr',
  professionMere: 'hypocrite',
  medecinTraitant: 'dynamique bzzz autrefois',
  serviceOrigine: 'bof propre',
  biologisteResponsableDg: 'envers via',
  diagnostic: 'AUTRE',
  autreDiagnostic: 'étant donné que',
  anneeDiagnostic: 9169,
  consentementRegistre: 'NON',
  dateEnregistrementRegistre: dayjs('2025-02-23'),
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  casSimilaires: 'NON',
  nombreCas: 30827,
  cas1Numero: 1215,
  lienParenteCas1: 'COUSIN',
  degreParenteCas1: 'tant apte doucement',
  typeHemorragieCas1: 'sale de crainte que',
  cas2Numero: 13623,
  lienParenteCas2: 'FRERE',
  degreParenteCas2: 'prolonger jeune enfant',
  typeHemorragieCas2: 'vroum insipide bientôt',
  cas3Numero: 16069,
  lienParenteCas3: 'LOINTAIN',
  degreParenteCas3: 'recta exister à raison de',
  typeHemorragieCas3: 'spécialiste',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 17402,
  deces1Numero: 16473,
  lienParenteDeces1: 'LOINTAIN',
  causeDeces1: 'ronron malgré bof',
  deces2Numero: 18682,
  lienParenteDeces2: 'FRERE',
  causeDeces2: 'touriste',
  deces3Numero: 12234,
  lienParenteDeces3: 'FRERE',
  causeDeces3: 'permettre',
  enqueteFamiliale: 'NONFAITE',
  decouverteFortuite: false,
  enqueteFamilialeBool: false,
  explorationSyndromeHemorragique: false,
  typeExplorationSyndromeHemorragique: 'HEMORRAGIE_CEREBRALE_NN',
  datePremierSigneClinique: dayjs('2025-02-23'),
  ageDiagnosticJour: 24047,
  ageDiagnosticMois: 10636,
  ageDiagnosticAnnee: 31622,
  tp: 9117.33,
  tpMT: 7882.99,
  tca: 32197.06,
  tcaMT: 19478.87,
  fibrinogene: 3526.1,
  ts: 'FAITE',
  tsFait: 'ALLONGE',
  toPfa: 'ALLONGE',
  toPfa200ColEpi: 10778.74,
  toPfa200ColAdp: 1222.49,
  tauxDosageFacteurXIII: 27886.33,
  hb: 9417.12,
  ht: 13053.37,
  plaquettes: 21356,
  techniqueChromogenique: false,
  tauxTechniqueChromogenique: 23735.25,
  techniqueSolubiliteCaillot: true,
  tauxTechniqueSolubiliteCaillot: 10972.84,
  confirmationMoleculaire: 'NONFAITE',
  mutationPresence: false,
  mutationType: 'AUCUNE',
  epistaxis: true,
  frequenceEpistaxis: 10128,
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 31293,
  ecchymose: false,
  typeEcchymose: 'SPONTANE',
  frequenceEcchymose: 7116,
  menorragie: true,
  frequenceMenorragie: 18217,
  hematemese: true,
  frequenceHematemese: 32113,
  rectorragie: true,
  frequenceRectorragie: 13925,
  hematurie: true,
  frequenceHematurie: 12596,
  hematomeSousCutane: false,
  typeHematomeSousCutane: 'PROVOQUE',
  frequenceHematomeSousCutane: 1505,
  hematomeMusculaire: false,
  siegeHematomeMusculaire: 'à force de en guise de auparavant',
  typeHematomeMusculaire: 'SPONTANE',
  frequenceHematomeMusculaire: 21038,
  hemarthrose: true,
  typeHemarthrose: 'PROVOQUE',
  frequenceHemarthrose: 12051,
  saignementSNC: false,
  typeSaignementSNC: 'SPONTANE',
  frequenceSaignementSNC: 10772,
  ruptureKystesHemorragiques: false,
  hemorragiesPostChirurgicales: true,
  hemoperitone: true,
  accidentsThrombotiques: true,
  typeAccidentsThrombotiques: 'VEINEUX',
  hemorragieGrave: true,
  typeHemorragieGrave: 'PAR_LA_LOCALISATION',
  chirurgiePrepare: 'NP',
  suiteOperatoireHemorragique: 'NP',
  circoncisionPrepare: 'NON',
  suiteOperatoireCirconcision: 'NON',
  ageCirconcision: 20214,
  facteurVIIIRecombinant: 'NON',
  plasmaFraisCongele: 'OUI',
  cryoprecipite: 'OUI',
  culotsPlaquettaires: 'NP',
  dicynone: 'OUI',
  exacyl: 'OUI',
  traitementMartial: 'NP',
  traitementOestroprogestatif: 'OUI',
  transfusionCGR: 'NP',
  inhibiteurs: 'NP',
  inhibiteurNeutralisant: true,
  titreUB: 688.89,
  inhibiteurNonNeutralisant: true,
  infectionsVirales: 'NON',
  thrombose: 'OUI',
  reactionAllergique: 'OUI',
  alloImmunisation: 'OUI',
  adhesionTherapeutique: 'OUI',
  causeNonAdhesion: 'au-dedans de avant étant donné que',
  vieSociale: 'TRAVAILLE',
  mariage: 'NON',
  enfants: 'OUI',
  activitePhysique: 'NON',
  typeActivitePhysique: 'trop malade membre de l’équipe',
  sequelles: 'NP',
  typeSequelles: 'aïe',
  patientDecede: 'NP',
  dateDeces: dayjs('2025-02-23'),
  ageDeces: 17111,
  hemorragieSnc: true,
  hemorragieAutreQueSnc: false,
  hiv: true,
  autreInfection: true,
  evenementThromboembolique: true,
  cancer: true,
  covid19: true,
  inconnue: true,
  autreEvenement: false,
  autreEvenementDetails: 'innombrable',
};

export const sampleWithNewData: NewFicheFacteurVIII = {
  etatCivil: 'DIVORCE',
  serviceClinique: 'PEDIATRIE_A',
  couvertureSociale: 'INDIGENT',
  sexe: 'MASCULIN',
  diagnostic: 'AUTRE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
