import dayjs from 'dayjs/esm';

import { IFicheVonWillebrand, NewFicheVonWillebrand } from './fiche-von-willebrand.model';

export const sampleWithRequiredData: IFicheVonWillebrand = {
  id: 7155,
  etatCivil: 'NP',
  serviceClinique: 'GYNECO',
  couvertureSociale: 'NP',
  sexe: 'MASCULIN',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  typeMvW: 'TYPE1',
};

export const sampleWithPartialData: IFicheVonWillebrand = {
  id: 17143,
  dossierNumber: 'hors de',
  indexNumber: 'secours',
  prenom: 'administration sitôt que ',
  nomJeuneFille: 'à la faveur de',
  profession: 'psitt main-d’œuvre consei',
  etatCivil: 'MARIE',
  serviceClinique: 'PUR',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-05-08'),
  origine: 'SFAX',
  autreOrigine: 'assurément contre',
  adresse: 'de façon que ensuite',
  telephone: '0717830747',
  prenomPere: 'délectable passablement v',
  professionPere: 'police approfondir',
  biologisteResponsableDg: 'touriste',
  diagnostic: 'WILLEBRAND',
  consentementRegistre: 'OUI',
  degreParenteConsanguins: 'TROISIEME_DEGRE',
  casSimilaires: 'NP',
  nombreCas: 7616,
  lienParenteCas1: 'COUSIN',
  degreParenteCas1: 'plutôt bè hi',
  degreParenteCas2: 'tic-tac',
  typeHemorragieCas2: 'bang snif',
  cas3Numero: 18435,
  lienParenteCas3: 'LOINTAIN',
  degreParenteCas3: 'a',
  typeHemorragieCas3: 'équipe de recherche délégation pauvre',
  deces2Numero: 16628,
  causeDeces2: 'aïe tant',
  lienParenteDeces3: 'COUSIN',
  causeDeces3: 'personnel pendant que meuh',
  circonstancesDecouverte: 'SYNDROME_HEMORRAGIQUE',
  circonstancesDecouvertePrecision: 'ouah accélérer',
  jamaisSaigne: 'NP',
  agePremierSigneCliniqueAnnees: 29199,
  symptomeEpistaxis: 'NP',
  symptomeHemoptysie: 'OUI',
  symptomeHemorragiePostAmygdalectomie: 'OUI',
  symptomeAutreDescription: 'membre à vie',
  agePremiereConsultationMois: 18283,
  ageDiagnosticJours: 13158,
  ageDiagnosticMois: 6420,
  typeMvW: 'TYPE2',
  pathologiesAssociees: 'large',
  dateTestConfirmation: dayjs('2025-05-08'),
  hb: 3197.38,
  hte: 11382.54,
  tp: 32523.87,
  tcaMT: 6409.22,
  tcaMPlusT2H: 8704.94,
  tsResultat: 'ALLONGE',
  occlusionPlaquettaire: 'NORMAL',
  collageneEpinephrine: 19833.51,
  f8c: 3879.44,
  ripa: 'NONFAITE',
  ripaResultat: 'DIMINUE',
  multimereHPM: 'ABSENTS',
  liaisonFvwF8: 'FAITE',
  liaisonFvwF8Resultat: 'NORMAL',
  mutationPresente: true,
  mutationNom: 'toutefois afin que',
  ecchymoses: 'OUI',
  ecchymosesSpontanees: true,
  ecchymosesProvoquees: true,
  ecchymosesSiege: 'ouch cyan concevoir',
  hemorragieMuqueuses: 'OUI',
  epistaxis: 'NON',
  hemorragiesIntrabuccales: 'NON',
  hemorragiesIntrabuccalesFrequence: 1039,
  menoragieFrequence: 27540,
  scoreHighamFait: true,
  hematomeFrequence: 14344,
  hemarthroseProvoque: true,
  hemorragieAmygdalienneFrequence: 7583,
  avulsionDentaire: 'NP',
  avulsionPrepare: false,
  traumatisme: 'NON',
  traumatismeType: 'peser insolite',
  chirurgie: 'NON',
  chirurgiePrepare: 'NP',
  accouchement: 'NP',
  circoncision: 'OUI',
  hemorragieVisceresProvoque: true,
  autreHemorragieVisceres: 'en plus de hors de',
  explorationVisceres: false,
  hemorragieGrave: 'NP',
  graveDeglobulisation: true,
  graveEtatDeChoc: true,
  scoreISTHBAT: 7260,
  desmopressine: 'NON',
  traitementSubstitutifPrevention: 'NON',
  traitementPreparation: 'deçà offrir oh',
  pfc: 'OUI',
  concentreFVW: 'OUI',
  antifibrinolytiques: 'OUI',
  voieOrale: true,
  voieIV: false,
  voieLocale: true,
  corticotherapie: 'OUI',
  kinesitherapie: 'NP',
  culotsGlobulaires: 'NP',
  nombreCulotsGlobulaires: 6362,
  anemie: 'OUI',
  anemieSevere: false,
  tauxHb: 31990.95,
  anticorpsAntiFVW: 'NEGATIF',
  anticorpsAntiFVIII: 'NON_FAIT',
  hepatiteC: 'NEGATIF',
  thrombose: true,
  autreComplication: true,
  adherenceTherapeutique: 'NP',
  statutSocial: 'CHOMEUR',
  typeActivitePhysique: "à l'insu de pour que",
  sequelles: 'NON',
  patientDecede: 'NON',
};

export const sampleWithFullData: IFicheVonWillebrand = {
  id: 6717,
  dossierNumber: 'quasi au cas où',
  ordreNumber: 'en croâ clientèle',
  indexNumber: 'immense',
  prenom: 'avex lors assurément',
  nom: 'de peur de psitt',
  nomJeuneFille: 'corps enseignant vers',
  profession: 'toutefois',
  etatCivil: 'DIVORCE',
  serviceClinique: 'PEDIATRIE_B',
  autreServiceClinique: 'approuver à même',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-05-09'),
  ageActuel: 6357,
  origine: 'GAFSA',
  autreOrigine: 'oh',
  adresse: 'selon aussi',
  telephone: '0381996931',
  prenomPere: 'sitôt que vétuste',
  professionPere: 'dès que dring apte',
  nomPrenomMere: 'hi incalculable accompagn',
  professionMere: 'entamer',
  medecinTraitant: 'au cas où',
  serviceOrigine: 'membre de l’équipe entre-',
  biologisteResponsableDg: 'au point que efficace équ',
  diagnostic: 'DEFICIT_COMBINE',
  autreDiagnostic: 'ensemble toucher',
  anneeDiagnostic: 19147,
  dateEnregistrementRegistre: dayjs('2025-05-08'),
  consentementRegistre: 'OUI',
  parentsConsanguins: 'NP',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  casSimilaires: 'NP',
  nombreCas: 23996,
  cas1Numero: 21733,
  lienParenteCas1: 'COUSIN',
  degreParenteCas1: 'à la merci hypocrite',
  typeHemorragieCas1: "impromptu collègue à l'entour de",
  cas2Numero: 14335,
  lienParenteCas2: 'COUSIN',
  degreParenteCas2: 'hé de façon à ce que en g',
  typeHemorragieCas2: 'au-dehors vite',
  cas3Numero: 31656,
  lienParenteCas3: 'COUSIN',
  degreParenteCas3: 'au-dessous de antagoniste',
  typeHemorragieCas3: 'tsoin-tsoin fêter direction',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 22125,
  deces1Numero: 31709,
  lienParenteDeces1: 'LOINTAIN',
  causeDeces1: 'serviable chef arrière',
  deces2Numero: 31873,
  lienParenteDeces2: 'FRERE',
  causeDeces2: "à l'entour de",
  deces3Numero: 19708,
  lienParenteDeces3: 'LOINTAIN',
  causeDeces3: 'collègue bzzz',
  enqueteFamiliale: 'FAITE',
  circonstancesDecouverte: 'ENQUETE_FAMILIALE',
  circonstancesDecouvertePrecision: 'assurément camarade',
  jamaisSaigne: 'OUI',
  agePremierSigneCliniqueJours: 9333,
  agePremierSigneCliniqueMois: 15649,
  agePremierSigneCliniqueAnnees: 19342,
  symptomeEcchymose: 'NON',
  symptomeEpistaxis: 'NP',
  symptomeGingivorragies: 'NON',
  symptomeMetrorragies: 'NON',
  symptomeMelena: 'NON',
  symptomeHemoptysie: 'OUI',
  symptomeHemorragiePostAmygdalectomie: 'NON',
  symptomeHemorragiePostAvulsionDentaire: 'NP',
  symptomeHemorragieChuteCordon: 'NON',
  symptomeAutre: 'NP',
  symptomeAutreDescription: 'moderne avare',
  datePremiereConsultation: dayjs('2025-05-08'),
  agePremiereConsultationJours: 32175,
  agePremiereConsultationMois: 10116,
  agePremiereConsultationAnnees: 19813,
  ageDiagnosticJours: 30598,
  ageDiagnosticMois: 25579,
  ageDiagnosticAnnees: 25545,
  typeMvW: 'TYPE3',
  sousTypeMvW: 'TYPE2N',
  pathologiesAssociees: 'délectable',
  dateTestConfirmation: dayjs('2025-05-08'),
  gs: 'O',
  hb: 4426.55,
  hte: 21427.1,
  plaquettes: 19318,
  tp: 18754.04,
  tcaMT: 1262.09,
  tcaMPlusT: 19935.99,
  tcaMPlusT2H: 17990.08,
  fibrinogene: 27499.94,
  tsResultat: 'NORMAL',
  tsValeur: 7705.59,
  occlusionPlaquettaire: 'ALLONGE',
  collageneEpinephrine: 30955.19,
  collageneADP: 2193.13,
  fvwag: 10551.43,
  fvwact: 20739.52,
  f8c: 6212.1,
  ratioFvwactFvwag: 3683.26,
  ratioF8cFvwag: 14115.55,
  autresTestsSpecifiques: 'FAITE',
  vwfCB: 'FAITE',
  vwfCBResultat: 27131.09,
  ripa: 'FAITE',
  ripaResultat: 'PARADOXALE',
  multimereHPM: 'PRESENTS',
  liaisonFvwF8: 'FAITE',
  liaisonFvwF8Resultat: 'NORMAL',
  fvwpp: 'NONFAITE',
  fvwppResultat: 'NORMAL',
  mutationGenetique: 'FAITE',
  mutationPresente: false,
  mutationNom: 'fourbe ouch subito',
  mutationZygote: 'HETEROZYGOTE',
  ecchymoses: 'NON',
  ecchymosesSpontanees: false,
  ecchymosesProvoquees: true,
  ecchymosesSiege: 'à condition que du côté de',
  ecchymosesFrequence: 24543,
  hemorragieMuqueuses: 'NON',
  epistaxis: 'OUI',
  epistaxisFrequence: 19620,
  hemorragiesIntrabuccales: 'NON',
  hemorragiesIntrabuccalesFrequence: 27042,
  menoragie: 'NP',
  menoragieFrequence: 12606,
  scoreHighamFait: false,
  scoreHighamValeur: 5022,
  hematome: 'OUI',
  hematomeSpontane: true,
  hematomeProvoque: false,
  hematomeSousCutane: false,
  hematomeMusculaire: true,
  hematomeTissusMous: true,
  hematomeFrequence: 17833,
  hemarthrose: 'OUI',
  hemarthroseSpontane: true,
  hemarthroseProvoque: false,
  hemarthroseSiege: 'crac donner partenaire',
  hemarthroseFrequence: 22801,
  hemorragieAmygdalienne: 'NP',
  hemorragieAmygdalienneFrequence: 20870,
  avulsionDentaire: 'NON',
  avulsionPrepare: false,
  avulsionBienDeroule: 'NON',
  traumatisme: 'OUI',
  traumatismeType: 'pauvre extatique',
  chirurgie: 'OUI',
  chirurgieType: 'voter',
  chirurgiePrepare: 'NON',
  chirurgieBienDeroule: 'OUI',
  accouchement: 'OUI',
  hemorragiePostpartum: 'NON',
  circoncision: 'NP',
  ageCirconcision: 8866,
  circoncisionPrepare: 'NON',
  circoncisionBienDeroule: 'NON',
  hemorragieVisceres: 'OUI',
  hemorragieVisceresSpontane: true,
  hemorragieVisceresProvoque: true,
  hemorragieVisceresType: 'HEMATURIE',
  autreHemorragieVisceres: 'oups conseil d’administration drôlement',
  explorationVisceres: false,
  lesionSousJacente: 'entre',
  hemorragieGrave: 'OUI',
  graveDeglobulisation: true,
  graveEtatDeChoc: true,
  graveParLocalisation: true,
  siegeGraviteLocalisation: 'marier badaboum ainsi',
  nombreHospitalisations: 10226,
  nombreTransfusions: 6186,
  scoreISTHBAT: 30545,
  desmopressine: 'NP',
  traitementSubstitutifPrevention: 'OUI',
  traitementPreparation: 'afin de',
  traitementSubstitutifCuratif: 'NON',
  cryoprecipite: 'NON',
  pfc: 'NON',
  concentreFVIIIFVW: 'NP',
  concentreFVW: 'NP',
  concentreFVIII: 'NON',
  agentBypassant: 'NP',
  antifibrinolytiques: 'NON',
  voieOrale: true,
  voieIV: false,
  voieLocale: true,
  oestroprogestatifs: 'NP',
  traitementAntalgique: 'OUI',
  corticotherapie: 'NP',
  kinesitherapie: 'NP',
  traitementMartial: 'OUI',
  culotsGlobulaires: 'NP',
  nombreCulotsGlobulaires: 19298,
  immunosuppresseur: 'OUI',
  nomImmunosuppresseur: 'de crainte que donner',
  anemie: 'OUI',
  anemieSevere: true,
  tauxHb: 28293.52,
  anticorpsAntiFVW: 'NON_FAIT',
  anticorpsAntiFVIII: 'NON_FAIT',
  hepatiteB: 'NON_FAIT',
  hepatiteC: 'NON_FAIT',
  hiv: 'NEGATIF',
  thrombose: false,
  reactionAllergique: true,
  autreComplication: true,
  autreComplicationDescription: 'si bien que honorer sans que',
  adherenceTherapeutique: 'OUI',
  causeNonAdherence: 'terriblement aigre dring',
  statutSocial: 'TRAVAILLE',
  marie: 'NP',
  enfants: 'NON',
  activitePhysique: 'NP',
  typeActivitePhysique: 'oups',
  sequelles: 'NP',
  typeSequelles: 'dorénavant',
  patientDecede: 'NON',
  dateDeces: dayjs('2025-05-08'),
  ageDeces: 11383,
  causeDeces: 'CANCER',
};

export const sampleWithNewData: NewFicheVonWillebrand = {
  etatCivil: 'MARIE',
  serviceClinique: 'GYNECO',
  couvertureSociale: 'NP',
  sexe: 'MASCULIN',
  diagnostic: 'HEMOPHILIE',
  typeMvW: 'TYPE3',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
