import dayjs from 'dayjs/esm';
import { CivilStatus } from 'app/entities/enumerations/civil-status.model';
import { ServiceCliniqueType } from 'app/entities/enumerations/service-clinique-type.model';
import { CouvertureSociale } from 'app/entities/enumerations/couverture-sociale.model';
import { Gender } from 'app/entities/enumerations/gender.model';
import { Region } from 'app/entities/enumerations/region.model';
import { DiagnosticType } from 'app/entities/enumerations/diagnostic-type.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { DegreParente } from 'app/entities/enumerations/degre-parente.model';
import { LienParente } from 'app/entities/enumerations/lien-parente.model';
import { FaiteNonFaite } from 'app/entities/enumerations/faite-non-faite.model';
import { CirconstanceDecouverteMvW } from 'app/entities/enumerations/circonstance-decouverte-mv-w.model';
import { TypeMvW } from 'app/entities/enumerations/type-mv-w.model';
import { SousTypeMvW } from 'app/entities/enumerations/sous-type-mv-w.model';
import { GroupeSanguin } from 'app/entities/enumerations/groupe-sanguin.model';
import { TypeTS } from 'app/entities/enumerations/type-ts.model';
import { TypeOcclusion } from 'app/entities/enumerations/type-occlusion.model';
import { TypeRipaResultat } from 'app/entities/enumerations/type-ripa-resultat.model';
import { TypeMultimere } from 'app/entities/enumerations/type-multimere.model';
import { TypeResultatPatho } from 'app/entities/enumerations/type-resultat-patho.model';
import { TypeFvWppRatio } from 'app/entities/enumerations/type-fv-wpp-ratio.model';
import { TypeZygote } from 'app/entities/enumerations/type-zygote.model';
import { TypeHemorragieVisceres } from 'app/entities/enumerations/type-hemorragie-visceres.model';
import { ResultatSerologie } from 'app/entities/enumerations/resultat-serologie.model';
import { StatutSocial } from 'app/entities/enumerations/statut-social.model';
import { CauseDeces } from 'app/entities/enumerations/cause-deces.model';

export interface IFicheVonWillebrand {
  id: number;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  prenom?: string | null;
  nom?: string | null;
  nomJeuneFille?: string | null;
  profession?: string | null;
  etatCivil?: keyof typeof CivilStatus | null;
  serviceClinique?: keyof typeof ServiceCliniqueType | null;
  autreServiceClinique?: string | null;
  couvertureSociale?: keyof typeof CouvertureSociale | null;
  sexe?: keyof typeof Gender | null;
  dateNaissance?: dayjs.Dayjs | null;
  ageActuel?: number | null;
  origine?: keyof typeof Region | null;
  autreOrigine?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  prenomPere?: string | null;
  professionPere?: string | null;
  nomPrenomMere?: string | null;
  professionMere?: string | null;
  medecinTraitant?: string | null;
  serviceOrigine?: string | null;
  biologisteResponsableDg?: string | null;
  diagnostic?: keyof typeof DiagnosticType | null;
  autreDiagnostic?: string | null;
  anneeDiagnostic?: number | null;
  dateEnregistrementRegistre?: dayjs.Dayjs | null;
  consentementRegistre?: keyof typeof OuiNonNP | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: keyof typeof DegreParente | null;
  casSimilaires?: keyof typeof OuiNonNP | null;
  nombreCas?: number | null;
  cas1Numero?: number | null;
  lienParenteCas1?: keyof typeof LienParente | null;
  degreParenteCas1?: string | null;
  typeHemorragieCas1?: string | null;
  cas2Numero?: number | null;
  lienParenteCas2?: keyof typeof LienParente | null;
  degreParenteCas2?: string | null;
  typeHemorragieCas2?: string | null;
  cas3Numero?: number | null;
  lienParenteCas3?: keyof typeof LienParente | null;
  degreParenteCas3?: string | null;
  typeHemorragieCas3?: string | null;
  decesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nombreDeces?: number | null;
  deces1Numero?: number | null;
  lienParenteDeces1?: keyof typeof LienParente | null;
  causeDeces1?: string | null;
  deces2Numero?: number | null;
  lienParenteDeces2?: keyof typeof LienParente | null;
  causeDeces2?: string | null;
  deces3Numero?: number | null;
  lienParenteDeces3?: keyof typeof LienParente | null;
  causeDeces3?: string | null;
  enqueteFamiliale?: keyof typeof FaiteNonFaite | null;
  circonstancesDecouverte?: keyof typeof CirconstanceDecouverteMvW | null;
  circonstancesDecouvertePrecision?: string | null;
  jamaisSaigne?: keyof typeof OuiNonNP | null;
  agePremierSigneCliniqueJours?: number | null;
  agePremierSigneCliniqueMois?: number | null;
  agePremierSigneCliniqueAnnees?: number | null;
  symptomeEcchymose?: keyof typeof OuiNonNP | null;
  symptomeEpistaxis?: keyof typeof OuiNonNP | null;
  symptomeGingivorragies?: keyof typeof OuiNonNP | null;
  symptomeMetrorragies?: keyof typeof OuiNonNP | null;
  symptomeMelena?: keyof typeof OuiNonNP | null;
  symptomeHemoptysie?: keyof typeof OuiNonNP | null;
  symptomeHemorragiePostAmygdalectomie?: keyof typeof OuiNonNP | null;
  symptomeHemorragiePostAvulsionDentaire?: keyof typeof OuiNonNP | null;
  symptomeHemorragieChuteCordon?: keyof typeof OuiNonNP | null;
  symptomeAutre?: keyof typeof OuiNonNP | null;
  symptomeAutreDescription?: string | null;
  datePremiereConsultation?: dayjs.Dayjs | null;
  agePremiereConsultationJours?: number | null;
  agePremiereConsultationMois?: number | null;
  agePremiereConsultationAnnees?: number | null;
  ageDiagnosticJours?: number | null;
  ageDiagnosticMois?: number | null;
  ageDiagnosticAnnees?: number | null;
  typeMvW?: keyof typeof TypeMvW | null;
  sousTypeMvW?: keyof typeof SousTypeMvW | null;
  pathologiesAssociees?: string | null;
  dateTestConfirmation?: dayjs.Dayjs | null;
  gs?: keyof typeof GroupeSanguin | null;
  hb?: number | null;
  hte?: number | null;
  plaquettes?: number | null;
  tp?: number | null;
  tcaMT?: number | null;
  tcaMPlusT?: number | null;
  tcaMPlusT2H?: number | null;
  fibrinogene?: number | null;
  tsResultat?: keyof typeof TypeTS | null;
  tsValeur?: number | null;
  occlusionPlaquettaire?: keyof typeof TypeOcclusion | null;
  collageneEpinephrine?: number | null;
  collageneADP?: number | null;
  fvwag?: number | null;
  fvwact?: number | null;
  f8c?: number | null;
  ratioFvwactFvwag?: number | null;
  ratioF8cFvwag?: number | null;
  autresTestsSpecifiques?: keyof typeof FaiteNonFaite | null;
  vwfCB?: keyof typeof FaiteNonFaite | null;
  vwfCBResultat?: number | null;
  ripa?: keyof typeof FaiteNonFaite | null;
  ripaResultat?: keyof typeof TypeRipaResultat | null;
  multimereHPM?: keyof typeof TypeMultimere | null;
  liaisonFvwF8?: keyof typeof FaiteNonFaite | null;
  liaisonFvwF8Resultat?: keyof typeof TypeResultatPatho | null;
  fvwpp?: keyof typeof FaiteNonFaite | null;
  fvwppResultat?: keyof typeof TypeFvWppRatio | null;
  mutationGenetique?: keyof typeof FaiteNonFaite | null;
  mutationPresente?: boolean | null;
  mutationNom?: string | null;
  mutationZygote?: keyof typeof TypeZygote | null;
  ecchymoses?: keyof typeof OuiNonNP | null;
  ecchymosesSpontanees?: boolean | null;
  ecchymosesProvoquees?: boolean | null;
  ecchymosesSiege?: string | null;
  ecchymosesFrequence?: number | null;
  hemorragieMuqueuses?: keyof typeof OuiNonNP | null;
  epistaxis?: keyof typeof OuiNonNP | null;
  epistaxisFrequence?: number | null;
  hemorragiesIntrabuccales?: keyof typeof OuiNonNP | null;
  hemorragiesIntrabuccalesFrequence?: number | null;
  menoragie?: keyof typeof OuiNonNP | null;
  menoragieFrequence?: number | null;
  scoreHighamFait?: boolean | null;
  scoreHighamValeur?: number | null;
  hematome?: keyof typeof OuiNonNP | null;
  hematomeSpontane?: boolean | null;
  hematomeProvoque?: boolean | null;
  hematomeSousCutane?: boolean | null;
  hematomeMusculaire?: boolean | null;
  hematomeTissusMous?: boolean | null;
  hematomeFrequence?: number | null;
  hemarthrose?: keyof typeof OuiNonNP | null;
  hemarthroseSpontane?: boolean | null;
  hemarthroseProvoque?: boolean | null;
  hemarthroseSiege?: string | null;
  hemarthroseFrequence?: number | null;
  hemorragieAmygdalienne?: keyof typeof OuiNonNP | null;
  hemorragieAmygdalienneFrequence?: number | null;
  avulsionDentaire?: keyof typeof OuiNonNP | null;
  avulsionPrepare?: boolean | null;
  avulsionBienDeroule?: keyof typeof OuiNonNP | null;
  traumatisme?: keyof typeof OuiNonNP | null;
  traumatismeType?: string | null;
  chirurgie?: keyof typeof OuiNonNP | null;
  chirurgieType?: string | null;
  chirurgiePrepare?: keyof typeof OuiNonNP | null;
  chirurgieBienDeroule?: keyof typeof OuiNonNP | null;
  accouchement?: keyof typeof OuiNonNP | null;
  hemorragiePostpartum?: keyof typeof OuiNonNP | null;
  circoncision?: keyof typeof OuiNonNP | null;
  ageCirconcision?: number | null;
  circoncisionPrepare?: keyof typeof OuiNonNP | null;
  circoncisionBienDeroule?: keyof typeof OuiNonNP | null;
  hemorragieVisceres?: keyof typeof OuiNonNP | null;
  hemorragieVisceresSpontane?: boolean | null;
  hemorragieVisceresProvoque?: boolean | null;
  hemorragieVisceresType?: keyof typeof TypeHemorragieVisceres | null;
  autreHemorragieVisceres?: string | null;
  explorationVisceres?: boolean | null;
  lesionSousJacente?: string | null;
  hemorragieGrave?: keyof typeof OuiNonNP | null;
  graveDeglobulisation?: boolean | null;
  graveEtatDeChoc?: boolean | null;
  graveParLocalisation?: boolean | null;
  siegeGraviteLocalisation?: string | null;
  nombreHospitalisations?: number | null;
  nombreTransfusions?: number | null;
  scoreISTHBAT?: number | null;
  desmopressine?: keyof typeof OuiNonNP | null;
  traitementSubstitutifPrevention?: keyof typeof OuiNonNP | null;
  traitementPreparation?: string | null;
  traitementSubstitutifCuratif?: keyof typeof OuiNonNP | null;
  cryoprecipite?: keyof typeof OuiNonNP | null;
  pfc?: keyof typeof OuiNonNP | null;
  concentreFVIIIFVW?: keyof typeof OuiNonNP | null;
  concentreFVW?: keyof typeof OuiNonNP | null;
  concentreFVIII?: keyof typeof OuiNonNP | null;
  agentBypassant?: keyof typeof OuiNonNP | null;
  antifibrinolytiques?: keyof typeof OuiNonNP | null;
  voieOrale?: boolean | null;
  voieIV?: boolean | null;
  voieLocale?: boolean | null;
  oestroprogestatifs?: keyof typeof OuiNonNP | null;
  traitementAntalgique?: keyof typeof OuiNonNP | null;
  corticotherapie?: keyof typeof OuiNonNP | null;
  kinesitherapie?: keyof typeof OuiNonNP | null;
  traitementMartial?: keyof typeof OuiNonNP | null;
  culotsGlobulaires?: keyof typeof OuiNonNP | null;
  nombreCulotsGlobulaires?: number | null;
  immunosuppresseur?: keyof typeof OuiNonNP | null;
  nomImmunosuppresseur?: string | null;
  anemie?: keyof typeof OuiNonNP | null;
  anemieSevere?: boolean | null;
  tauxHb?: number | null;
  anticorpsAntiFVW?: keyof typeof ResultatSerologie | null;
  anticorpsAntiFVIII?: keyof typeof ResultatSerologie | null;
  hepatiteB?: keyof typeof ResultatSerologie | null;
  hepatiteC?: keyof typeof ResultatSerologie | null;
  hiv?: keyof typeof ResultatSerologie | null;
  thrombose?: boolean | null;
  reactionAllergique?: boolean | null;
  autreComplication?: boolean | null;
  autreComplicationDescription?: string | null;
  adherenceTherapeutique?: keyof typeof OuiNonNP | null;
  causeNonAdherence?: string | null;
  statutSocial?: keyof typeof StatutSocial | null;
  marie?: keyof typeof OuiNonNP | null;
  enfants?: keyof typeof OuiNonNP | null;
  activitePhysique?: keyof typeof OuiNonNP | null;
  typeActivitePhysique?: string | null;
  sequelles?: keyof typeof OuiNonNP | null;
  typeSequelles?: string | null;
  patientDecede?: keyof typeof OuiNonNP | null;
  dateDeces?: dayjs.Dayjs | null;
  ageDeces?: number | null;
  causeDeces?: keyof typeof CauseDeces | null;
}

export type NewFicheVonWillebrand = Omit<IFicheVonWillebrand, 'id'> & { id: null };
