import { TestBed } from '@angular/core/testing';

import { sampleWithNewData, sampleWithRequiredData } from '../fiche-facteur-xi.test-samples';

import { FicheFacteurXIFormService } from './fiche-facteur-xi-form.service';

describe('FicheFacteurXI Form Service', () => {
  let service: FicheFacteurXIFormService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(FicheFacteurXIFormService);
  });

  describe('Service methods', () => {
    describe('createFicheFacteurXIFormGroup', () => {
      it('should create a new form with FormControl', () => {
        const formGroup = service.createFicheFacteurXIFormGroup();

        expect(formGroup.controls).toEqual(
          expect.objectContaining({
            id: expect.any(Object),
            dossierNumber: expect.any(Object),
            ordreNumber: expect.any(Object),
            indexNumber: expect.any(Object),
            prenom: expect.any(Object),
            nom: expect.any(Object),
            nomJeuneFille: expect.any(Object),
            profession: expect.any(Object),
            etatCivil: expect.any(Object),
            serviceClinique: expect.any(Object),
            autreServiceClinique: expect.any(Object),
            couvertureSociale: expect.any(Object),
            sexe: expect.any(Object),
            dateNaissance: expect.any(Object),
            ageActuel: expect.any(Object),
            origine: expect.any(Object),
            autreOrigine: expect.any(Object),
            adresse: expect.any(Object),
            telephone: expect.any(Object),
            prenomPere: expect.any(Object),
            professionPere: expect.any(Object),
            nomPrenomMere: expect.any(Object),
            professionMere: expect.any(Object),
            medecinTraitant: expect.any(Object),
            serviceOrigine: expect.any(Object),
            biologisteResponsableDg: expect.any(Object),
            diagnostic: expect.any(Object),
            autreDiagnostic: expect.any(Object),
            anneeDiagnostic: expect.any(Object),
            consentementRegistre: expect.any(Object),
            dateEnregistrementRegistre: expect.any(Object),
            parentsConsanguins: expect.any(Object),
            degreParenteConsanguins: expect.any(Object),
            casSimilaires: expect.any(Object),
            nombreCas: expect.any(Object),
            cas1Numero: expect.any(Object),
            lienParenteCas1: expect.any(Object),
            degreParenteCas1: expect.any(Object),
            typeHemorragieCas1: expect.any(Object),
            cas2Numero: expect.any(Object),
            lienParenteCas2: expect.any(Object),
            degreParenteCas2: expect.any(Object),
            typeHemorragieCas2: expect.any(Object),
            cas3Numero: expect.any(Object),
            lienParenteCas3: expect.any(Object),
            degreParenteCas3: expect.any(Object),
            typeHemorragieCas3: expect.any(Object),
            decesSyndromeHemorragique: expect.any(Object),
            nombreDeces: expect.any(Object),
            deces1Numero: expect.any(Object),
            lienParenteDeces1: expect.any(Object),
            causeDeces1: expect.any(Object),
            deces2Numero: expect.any(Object),
            lienParenteDeces2: expect.any(Object),
            causeDeces2: expect.any(Object),
            deces3Numero: expect.any(Object),
            lienParenteDeces3: expect.any(Object),
            causeDeces3: expect.any(Object),
            enqueteFamiliale: expect.any(Object),
            syndromeHemorragique: expect.any(Object),
            precisionSyndromeHemorragique: expect.any(Object),
            decouverteFortuite: expect.any(Object),
            precisionDecouverteFortuite: expect.any(Object),
            jamaisSaigne: expect.any(Object),
            agePremierSigneCliniqueJours: expect.any(Object),
            agePremierSigneCliniqueMois: expect.any(Object),
            agePremierSigneCliniqueAnnees: expect.any(Object),
            symptomeEcchymose: expect.any(Object),
            symptomeEpistaxis: expect.any(Object),
            symptomeGingivorragies: expect.any(Object),
            symptomeMetrorragies: expect.any(Object),
            symptomeMelena: expect.any(Object),
            symptomeHemoptysie: expect.any(Object),
            symptomeHemorragiePostAmygdalectomie: expect.any(Object),
            symptomeHemorragiePostAvulsionDentaire: expect.any(Object),
            symptomeHemorragieChuteCordon: expect.any(Object),
            symptomeAutre: expect.any(Object),
            symptomeAutreDescription: expect.any(Object),
            datePremiereConsultation: expect.any(Object),
            agePremiereConsultationJours: expect.any(Object),
            agePremiereConsultationMois: expect.any(Object),
            agePremiereConsultationAnnees: expect.any(Object),
            ageDiagnosticJours: expect.any(Object),
            ageDiagnosticMois: expect.any(Object),
            ageDiagnosticAnnees: expect.any(Object),
            hb: expect.any(Object),
            hte: expect.any(Object),
            plaquettes: expect.any(Object),
            pfaColEpi: expect.any(Object),
            pfaColADP: expect.any(Object),
            tp: expect.any(Object),
            tpMPlusT: expect.any(Object),
            fibrinogene: expect.any(Object),
            tcaMT: expect.any(Object),
            tcaMPlusT: expect.any(Object),
            tcaTemoin: expect.any(Object),
            facteurXI: expect.any(Object),
            autresFacteursDosageDescription: expect.any(Object),
            autresFacteursTaux1: expect.any(Object),
            autresFacteursTaux2: expect.any(Object),
            autresFacteursTaux3: expect.any(Object),
            confirmationMoleculaire: expect.any(Object),
            mutationPresente: expect.any(Object),
            mutationNom: expect.any(Object),
            mutationZygote: expect.any(Object),
            mutation2Nom: expect.any(Object),
            serologieVHB: expect.any(Object),
            serologieVHC: expect.any(Object),
            serologieVIH: expect.any(Object),
            epistaxis: expect.any(Object),
            frequenceEpistaxis: expect.any(Object),
            gingivorragies: expect.any(Object),
            typeGingivorragies: expect.any(Object),
            frequenceGingivorragies: expect.any(Object),
            ecchymose: expect.any(Object),
            typeEcchymose: expect.any(Object),
            frequenceEcchymose: expect.any(Object),
            menorragie: expect.any(Object),
            frequenceMenorragie: expect.any(Object),
            hematemese: expect.any(Object),
            frequenceHematemese: expect.any(Object),
            rectorragie: expect.any(Object),
            frequenceRectorragie: expect.any(Object),
            hematurie: expect.any(Object),
            frequenceHematurie: expect.any(Object),
            hemorragiePostTraumatique: expect.any(Object),
            frequenceHemorragiePostTraumatique: expect.any(Object),
            hematomeSousCutane: expect.any(Object),
            typeHematomeSousCutane: expect.any(Object),
            frequenceHematomeSousCutane: expect.any(Object),
            hematomeMusculaire: expect.any(Object),
            typeHematomeMusculaire: expect.any(Object),
            frequenceHematomeMusculaire: expect.any(Object),
            hematomeTissusMousProfonds: expect.any(Object),
            typeHematomeTissusMousProfonds: expect.any(Object),
            frequenceHematomeTissusMousProfonds: expect.any(Object),
            hemarthrose: expect.any(Object),
            typeHemarthrose: expect.any(Object),
            frequenceHemarthrose: expect.any(Object),
            saignementSNC: expect.any(Object),
            typeSaignementSNC: expect.any(Object),
            frequenceSaignementSNC: expect.any(Object),
            saignementChuteCordon: expect.any(Object),
            frequenceSaignementChuteCordon: expect.any(Object),
            retardCicatrisationPlaies: expect.any(Object),
            frequenceRetardCicatrisationPlaies: expect.any(Object),
            autresManifestations: expect.any(Object),
            faussesCouchesSpontaneesRecurrence: expect.any(Object),
            frequenceFaussesCouches: expect.any(Object),
            accidentsThrombotiques: expect.any(Object),
            thromboseVeineuse: expect.any(Object),
            thromboseArterielle: expect.any(Object),
            frequenceAccidentsThrombotiques: expect.any(Object),
            hemoperitoine: expect.any(Object),
            frequenceHemoperitoine: expect.any(Object),
            ruptureKystesHemorragiques: expect.any(Object),
            frequenceRuptureKystes: expect.any(Object),
            hemorragieGrave: expect.any(Object),
            frequenceHemorragieGrave: expect.any(Object),
            graviteDeglobulisation: expect.any(Object),
            graviteEtatDeChoc: expect.any(Object),
            graviteParLocalisation: expect.any(Object),
            siegeGraviteLocalisation: expect.any(Object),
            chirurgiePrepare: expect.any(Object),
            chirurgieSuiteHemorragique: expect.any(Object),
            circoncisionPrepare: expect.any(Object),
            circoncisionSuiteHemorragique: expect.any(Object),
            ageCirconcision: expect.any(Object),
            traitementPFC: expect.any(Object),
            traitementCryoprecipite: expect.any(Object),
            traitementConcentreFacteurXI: expect.any(Object),
            traitementCulotsPlaquettaires: expect.any(Object),
            traitementDicynone: expect.any(Object),
            traitementExacyl: expect.any(Object),
            traitementMartial: expect.any(Object),
            traitementOestroprogestatif: expect.any(Object),
            transfusionCGR: expect.any(Object),
            alloImmunisation: expect.any(Object),
            inhibiteurNeutralisant: expect.any(Object),
            titreInhibiteurUB: expect.any(Object),
            inhibiteurNonNeutralisant: expect.any(Object),
            infectionVIH: expect.any(Object),
            infectionVHC: expect.any(Object),
            infectionVHB: expect.any(Object),
            thrombose: expect.any(Object),
            reactionAllergique: expect.any(Object),
            autresComplications: expect.any(Object),
            adherenceTherapeutique: expect.any(Object),
            causeNonAdherence: expect.any(Object),
            statutSocial: expect.any(Object),
            marie: expect.any(Object),
            enfants: expect.any(Object),
            activitePhysique: expect.any(Object),
            typeActivitePhysique: expect.any(Object),
            sequelles: expect.any(Object),
            typeSequelles: expect.any(Object),
            patientDecede: expect.any(Object),
            dateDeces: expect.any(Object),
            ageDeces: expect.any(Object),
            causeDeces: expect.any(Object),
          }),
        );
      });

      it('passing IFicheFacteurXI should create a new form with FormGroup', () => {
        const formGroup = service.createFicheFacteurXIFormGroup(sampleWithRequiredData);

        expect(formGroup.controls).toEqual(
          expect.objectContaining({
            id: expect.any(Object),
            dossierNumber: expect.any(Object),
            ordreNumber: expect.any(Object),
            indexNumber: expect.any(Object),
            prenom: expect.any(Object),
            nom: expect.any(Object),
            nomJeuneFille: expect.any(Object),
            profession: expect.any(Object),
            etatCivil: expect.any(Object),
            serviceClinique: expect.any(Object),
            autreServiceClinique: expect.any(Object),
            couvertureSociale: expect.any(Object),
            sexe: expect.any(Object),
            dateNaissance: expect.any(Object),
            ageActuel: expect.any(Object),
            origine: expect.any(Object),
            autreOrigine: expect.any(Object),
            adresse: expect.any(Object),
            telephone: expect.any(Object),
            prenomPere: expect.any(Object),
            professionPere: expect.any(Object),
            nomPrenomMere: expect.any(Object),
            professionMere: expect.any(Object),
            medecinTraitant: expect.any(Object),
            serviceOrigine: expect.any(Object),
            biologisteResponsableDg: expect.any(Object),
            diagnostic: expect.any(Object),
            autreDiagnostic: expect.any(Object),
            anneeDiagnostic: expect.any(Object),
            consentementRegistre: expect.any(Object),
            dateEnregistrementRegistre: expect.any(Object),
            parentsConsanguins: expect.any(Object),
            degreParenteConsanguins: expect.any(Object),
            casSimilaires: expect.any(Object),
            nombreCas: expect.any(Object),
            cas1Numero: expect.any(Object),
            lienParenteCas1: expect.any(Object),
            degreParenteCas1: expect.any(Object),
            typeHemorragieCas1: expect.any(Object),
            cas2Numero: expect.any(Object),
            lienParenteCas2: expect.any(Object),
            degreParenteCas2: expect.any(Object),
            typeHemorragieCas2: expect.any(Object),
            cas3Numero: expect.any(Object),
            lienParenteCas3: expect.any(Object),
            degreParenteCas3: expect.any(Object),
            typeHemorragieCas3: expect.any(Object),
            decesSyndromeHemorragique: expect.any(Object),
            nombreDeces: expect.any(Object),
            deces1Numero: expect.any(Object),
            lienParenteDeces1: expect.any(Object),
            causeDeces1: expect.any(Object),
            deces2Numero: expect.any(Object),
            lienParenteDeces2: expect.any(Object),
            causeDeces2: expect.any(Object),
            deces3Numero: expect.any(Object),
            lienParenteDeces3: expect.any(Object),
            causeDeces3: expect.any(Object),
            enqueteFamiliale: expect.any(Object),
            syndromeHemorragique: expect.any(Object),
            precisionSyndromeHemorragique: expect.any(Object),
            decouverteFortuite: expect.any(Object),
            precisionDecouverteFortuite: expect.any(Object),
            jamaisSaigne: expect.any(Object),
            agePremierSigneCliniqueJours: expect.any(Object),
            agePremierSigneCliniqueMois: expect.any(Object),
            agePremierSigneCliniqueAnnees: expect.any(Object),
            symptomeEcchymose: expect.any(Object),
            symptomeEpistaxis: expect.any(Object),
            symptomeGingivorragies: expect.any(Object),
            symptomeMetrorragies: expect.any(Object),
            symptomeMelena: expect.any(Object),
            symptomeHemoptysie: expect.any(Object),
            symptomeHemorragiePostAmygdalectomie: expect.any(Object),
            symptomeHemorragiePostAvulsionDentaire: expect.any(Object),
            symptomeHemorragieChuteCordon: expect.any(Object),
            symptomeAutre: expect.any(Object),
            symptomeAutreDescription: expect.any(Object),
            datePremiereConsultation: expect.any(Object),
            agePremiereConsultationJours: expect.any(Object),
            agePremiereConsultationMois: expect.any(Object),
            agePremiereConsultationAnnees: expect.any(Object),
            ageDiagnosticJours: expect.any(Object),
            ageDiagnosticMois: expect.any(Object),
            ageDiagnosticAnnees: expect.any(Object),
            hb: expect.any(Object),
            hte: expect.any(Object),
            plaquettes: expect.any(Object),
            pfaColEpi: expect.any(Object),
            pfaColADP: expect.any(Object),
            tp: expect.any(Object),
            tpMPlusT: expect.any(Object),
            fibrinogene: expect.any(Object),
            tcaMT: expect.any(Object),
            tcaMPlusT: expect.any(Object),
            tcaTemoin: expect.any(Object),
            facteurXI: expect.any(Object),
            autresFacteursDosageDescription: expect.any(Object),
            autresFacteursTaux1: expect.any(Object),
            autresFacteursTaux2: expect.any(Object),
            autresFacteursTaux3: expect.any(Object),
            confirmationMoleculaire: expect.any(Object),
            mutationPresente: expect.any(Object),
            mutationNom: expect.any(Object),
            mutationZygote: expect.any(Object),
            mutation2Nom: expect.any(Object),
            serologieVHB: expect.any(Object),
            serologieVHC: expect.any(Object),
            serologieVIH: expect.any(Object),
            epistaxis: expect.any(Object),
            frequenceEpistaxis: expect.any(Object),
            gingivorragies: expect.any(Object),
            typeGingivorragies: expect.any(Object),
            frequenceGingivorragies: expect.any(Object),
            ecchymose: expect.any(Object),
            typeEcchymose: expect.any(Object),
            frequenceEcchymose: expect.any(Object),
            menorragie: expect.any(Object),
            frequenceMenorragie: expect.any(Object),
            hematemese: expect.any(Object),
            frequenceHematemese: expect.any(Object),
            rectorragie: expect.any(Object),
            frequenceRectorragie: expect.any(Object),
            hematurie: expect.any(Object),
            frequenceHematurie: expect.any(Object),
            hemorragiePostTraumatique: expect.any(Object),
            frequenceHemorragiePostTraumatique: expect.any(Object),
            hematomeSousCutane: expect.any(Object),
            typeHematomeSousCutane: expect.any(Object),
            frequenceHematomeSousCutane: expect.any(Object),
            hematomeMusculaire: expect.any(Object),
            typeHematomeMusculaire: expect.any(Object),
            frequenceHematomeMusculaire: expect.any(Object),
            hematomeTissusMousProfonds: expect.any(Object),
            typeHematomeTissusMousProfonds: expect.any(Object),
            frequenceHematomeTissusMousProfonds: expect.any(Object),
            hemarthrose: expect.any(Object),
            typeHemarthrose: expect.any(Object),
            frequenceHemarthrose: expect.any(Object),
            saignementSNC: expect.any(Object),
            typeSaignementSNC: expect.any(Object),
            frequenceSaignementSNC: expect.any(Object),
            saignementChuteCordon: expect.any(Object),
            frequenceSaignementChuteCordon: expect.any(Object),
            retardCicatrisationPlaies: expect.any(Object),
            frequenceRetardCicatrisationPlaies: expect.any(Object),
            autresManifestations: expect.any(Object),
            faussesCouchesSpontaneesRecurrence: expect.any(Object),
            frequenceFaussesCouches: expect.any(Object),
            accidentsThrombotiques: expect.any(Object),
            thromboseVeineuse: expect.any(Object),
            thromboseArterielle: expect.any(Object),
            frequenceAccidentsThrombotiques: expect.any(Object),
            hemoperitoine: expect.any(Object),
            frequenceHemoperitoine: expect.any(Object),
            ruptureKystesHemorragiques: expect.any(Object),
            frequenceRuptureKystes: expect.any(Object),
            hemorragieGrave: expect.any(Object),
            frequenceHemorragieGrave: expect.any(Object),
            graviteDeglobulisation: expect.any(Object),
            graviteEtatDeChoc: expect.any(Object),
            graviteParLocalisation: expect.any(Object),
            siegeGraviteLocalisation: expect.any(Object),
            chirurgiePrepare: expect.any(Object),
            chirurgieSuiteHemorragique: expect.any(Object),
            circoncisionPrepare: expect.any(Object),
            circoncisionSuiteHemorragique: expect.any(Object),
            ageCirconcision: expect.any(Object),
            traitementPFC: expect.any(Object),
            traitementCryoprecipite: expect.any(Object),
            traitementConcentreFacteurXI: expect.any(Object),
            traitementCulotsPlaquettaires: expect.any(Object),
            traitementDicynone: expect.any(Object),
            traitementExacyl: expect.any(Object),
            traitementMartial: expect.any(Object),
            traitementOestroprogestatif: expect.any(Object),
            transfusionCGR: expect.any(Object),
            alloImmunisation: expect.any(Object),
            inhibiteurNeutralisant: expect.any(Object),
            titreInhibiteurUB: expect.any(Object),
            inhibiteurNonNeutralisant: expect.any(Object),
            infectionVIH: expect.any(Object),
            infectionVHC: expect.any(Object),
            infectionVHB: expect.any(Object),
            thrombose: expect.any(Object),
            reactionAllergique: expect.any(Object),
            autresComplications: expect.any(Object),
            adherenceTherapeutique: expect.any(Object),
            causeNonAdherence: expect.any(Object),
            statutSocial: expect.any(Object),
            marie: expect.any(Object),
            enfants: expect.any(Object),
            activitePhysique: expect.any(Object),
            typeActivitePhysique: expect.any(Object),
            sequelles: expect.any(Object),
            typeSequelles: expect.any(Object),
            patientDecede: expect.any(Object),
            dateDeces: expect.any(Object),
            ageDeces: expect.any(Object),
            causeDeces: expect.any(Object),
          }),
        );
      });
    });

    describe('getFicheFacteurXI', () => {
      it('should return NewFicheFacteurXI for default FicheFacteurXI initial value', () => {
        const formGroup = service.createFicheFacteurXIFormGroup(sampleWithNewData);

        const ficheFacteurXI = service.getFicheFacteurXI(formGroup) as any;

        expect(ficheFacteurXI).toMatchObject(sampleWithNewData);
      });

      it('should return NewFicheFacteurXI for empty FicheFacteurXI initial value', () => {
        const formGroup = service.createFicheFacteurXIFormGroup();

        const ficheFacteurXI = service.getFicheFacteurXI(formGroup) as any;

        expect(ficheFacteurXI).toMatchObject({});
      });

      it('should return IFicheFacteurXI', () => {
        const formGroup = service.createFicheFacteurXIFormGroup(sampleWithRequiredData);

        const ficheFacteurXI = service.getFicheFacteurXI(formGroup) as any;

        expect(ficheFacteurXI).toMatchObject(sampleWithRequiredData);
      });
    });

    describe('resetForm', () => {
      it('passing IFicheFacteurXI should not enable id FormControl', () => {
        const formGroup = service.createFicheFacteurXIFormGroup();
        expect(formGroup.controls.id.disabled).toBe(true);

        service.resetForm(formGroup, sampleWithRequiredData);

        expect(formGroup.controls.id.disabled).toBe(true);
      });

      it('passing NewFicheFacteurXI should disable id FormControl', () => {
        const formGroup = service.createFicheFacteurXIFormGroup(sampleWithRequiredData);
        expect(formGroup.controls.id.disabled).toBe(true);

        service.resetForm(formGroup, { id: null });

        expect(formGroup.controls.id.disabled).toBe(true);
      });
    });
  });
});
