import dayjs from 'dayjs/esm';

import { IFicheThrombopathie, NewFicheThrombopathie } from './fiche-thrombopathie.model';

export const sampleWithRequiredData: IFicheThrombopathie = {
  id: 24045,
  etatCivil: 'NP',
  serviceClinique: 'PRIVE',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_XI',
};

export const sampleWithPartialData: IFicheThrombopathie = {
  id: 23115,
  ordreNumber: "aujourd'hui magenta éparg",
  prenom: 'blablabla',
  nom: 'sur',
  nomJeuneFille: 'diplomate depuis',
  etatCivil: 'MARIE',
  serviceClinique: 'GYNECO',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  origine: 'SFAX',
  adresse: 'moyennant aussitôt que ba',
  telephone: '+33 520523508',
  professionPere: 'tsoin-tsoin',
  nomPrenomMere: 'en outre de quelquefois',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  autreDiagnostic: 'gigantesque ressentir en ',
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-16'),
  degreParenteConsanguins: 'personnel professionnel d',
  nombreCas: 5626,
  nombreDeces: 16237,
  typeHemorragie: 'derrière',
  antecedentsMedicaux: 'pacifique chef de cuisine',
  antecedentsChirurgicaux: 'OUI',
  typeChirurgie: 'contre',
  typeSyndromeHemorragique: 'ha ha prout',
  ageDiagnostic: 2113,
  decouverteFortuite: true,
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: true,
  syndromeDysmorphique: 'NON',
  albinisme: 'NON',
  arthrogrypose: 'NON',
  gb: 386,
  tcmh: 13586.11,
  plaquettes: 8617,
  toPfa100ColEpi: 7395.47,
  tp: 12874.03,
  cmf: 'NON',
  resultatCmf: 'au cas où bien que',
  etudeGenetique: 'NON',
  resultatEtudeGenetique: 'afin que coller',
  maladieBernardSoulier: true,
  ecchymose: 'OUI',
  typeGingivorragies: 'PROVOQUE',
  epistaxis: 'NON',
  typeEpistaxis: 'PROVOQUE',
  typeHematome: 'SPONTANE',
  frequenceMenoMetrorragies: 24504,
  severiteMenoMetrorragies: 'que siffler derrière',
  typeLesionSousJacente: 'dès que super propre',
  hemorragieVisceres: 'NP',
  hemorragieDigestiveBasse: true,
  explorationHemorragieVisceres: 'NON',
  interventionChirurgicale: 'NON',
  hematomesCerebrales: true,
  edcHemorragique: false,
  transfusionCps: 'OUI',
  dicynone: 'NP',
  transfusionCgr: 'NON',
  traitementMartial: 'NP',
  thrombose: 'NON',
  alloImmunisationHLA: 'NON',
};

export const sampleWithFullData: IFicheThrombopathie = {
  id: 14688,
  dossierNumber: 'mairie jusqu’à ce que si',
  ordreNumber: 'zzzz délectable surveille',
  indexNumber: 'cyan',
  prenom: 'souvent',
  nom: 'autour de user',
  nomJeuneFille: 'bè',
  profession: 'grrr arrière jeune',
  etatCivil: 'DIVORCE',
  serviceClinique: 'PEDIATRIE_A',
  autreServiceClinique: 'afin que gens ouin',
  couvertureSociale: 'NP',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-15'),
  ageActuel: 25971,
  origine: 'TATAOUINE',
  autreOrigine: 'extatique parmi',
  adresse: 'diriger',
  telephone: '+33 470816459',
  prenomPere: 'rectorat',
  professionPere: 'hebdomadaire extrêmement',
  nomPrenomMere: 'pourvu que',
  professionMere: 'plus délectable hors',
  medecinTraitant: 'souvent en outre de',
  serviceOrigine: 'actionnaire pourvu que co',
  biologisteResponsableDg: 'infime fonctionnaire',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  autreDiagnostic: 'à moins de bientôt',
  anneeDiagnostic: 13574,
  consentementRegistre: 'NON',
  dateEnregistrementRegistre: dayjs('2025-02-15'),
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'quant à peser séculaire',
  casSimilaires: 'OUI',
  nombreCas: 18676,
  degreParenteCasSimilaires: 'oups oh',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 26467,
  typeHemorragie: 'conserver ah reprocher',
  lienParenteDeces: 'renouveler hé égoïste',
  enqueteFamiliale: 'NONFAITE',
  antecedentsMedicaux: 'via',
  antecedentsChirurgicaux: 'OUI',
  typeChirurgie: 'joliment',
  complicationHemorragique: 'NON',
  agePremierSigneHemorragique: 15728,
  typeSyndromeHemorragique: 'devant remplir',
  ageDiagnostic: 2951,
  decouverteFortuite: false,
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: false,
  typeCirconstanceDiagnostic: 'substituer',
  eczema: 'NON',
  syndromeDysmorphique: 'OUI',
  albinisme: 'NON',
  arthrogrypose: 'NON',
  gb: 1204,
  hb: 14309.79,
  vgm: 26449.34,
  tcmh: 6870.4,
  plaquettes: 16391,
  frottisSanguin: 'ha délégation',
  ts: 999.41,
  toPfa: 13455.98,
  toPfa100ColEpi: 2391.92,
  toPfa100ColAdp: 1234.04,
  tp: 25254.39,
  tca: 2890.67,
  aggregometriePlaquettaire: 'OUI',
  resultatAgregometrie: 'altruiste sus de façon que',
  cmf: 'NP',
  resultatCmf: 'altruiste aussitôt que responsable',
  dosageFvwAg: 15074.94,
  dosageFvwRco: 21460.53,
  etudeGenetique: 'NP',
  resultatEtudeGenetique: 'reconstituer',
  thrombasthenieGlanzmann: true,
  maladieBernardSoulier: false,
  autreThrombopathie: true,
  autreThrombopathieDetails: 'avant pourvu que',
  ecchymose: 'NP',
  typeEcchymose: 'SPONTANE',
  gingivorragies: 'NP',
  typeGingivorragies: 'SPONTANE',
  epistaxis: 'NON',
  typeEpistaxis: 'SPONTANE',
  hematome: 'OUI',
  typeHematome: 'SPONTANE',
  siegelHematome: 'relier',
  menoMetrorragies: 'OUI',
  frequenceMenoMetrorragies: 1230,
  severiteMenoMetrorragies: 'marron membre du personnel athlète',
  explorationMenoMetrorragies: 'OUI',
  typeLesionSousJacente: 'pff drôlement',
  hemorragieVisceres: 'NON',
  hemorragieDigestiveHaute: false,
  hemorragieDigestiveBasse: true,
  hematurie: false,
  explorationHemorragieVisceres: 'NON',
  lesionSousJacenteVisceres: 'paf',
  interventionChirurgicale: 'NON',
  typeInterventionChirurgicale: 'déjà auprès de',
  hematomesCerebrales: false,
  edcHemorragique: false,
  transfusionCps: 'NON',
  facteurVIIRecombinant: 'NON',
  dicynone: 'NP',
  exacyl: 'NP',
  traitementOestroprogestatif: 'NP',
  mechage: 'OUI',
  transfusionCgr: 'OUI',
  traitementMartial: 'NON',
  thrombose: 'NP',
  alloImmunisationHLA: 'OUI',
};

export const sampleWithNewData: NewFicheThrombopathie = {
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'PEDIATRIE_B',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  diagnostic: 'HEMOPHILIE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
