import dayjs from 'dayjs/esm';

import { IFicheThrombopathie, NewFicheThrombopathie } from './fiche-thrombopathie.model';

export const sampleWithRequiredData: IFicheThrombopathie = {
  id: 6349,
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'PUR',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
};

export const sampleWithPartialData: IFicheThrombopathie = {
  id: 4557,
  ordreNumber: 'smack euh',
  indexNumber: 'communauté étudiante',
  prenom: 'avant de paraître',
  nom: 'comme via hystérique',
  nomJeuneFille: 'camarade',
  etatCivil: 'MARIE',
  serviceClinique: 'PEDIATRIE_B',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-15'),
  telephone: '+33 771074330',
  prenomPere: 'électorat consulter',
  professionPere: 'lors lorsque',
  professionMere: 'comme grrr conseil munici',
  diagnostic: 'THROMBOPATHIE',
  autreDiagnostic: 'athlète de peur que',
  anneeDiagnostic: 11785,
  parentsConsanguins: 'NP',
  degreParenteConsanguins: 'insolite hôte',
  nombreCas: 3119,
  degreParenteCasSimilaires: 'contre oui',
  decesSyndromeHemorragique: 'NP',
  nombreDeces: 192,
  typeHemorragie: 'défendre',
  lienParenteDeces: 'antagoniste interroger',
  antecedentsChirurgicaux: 'NP',
  typeChirurgie: 'en face de',
  agePremierSigneHemorragique: 17388,
  typeSyndromeHemorragique: 'au cas où pauvre psitt',
  ageDiagnostic: 1715,
  syndromeDysmorphique: 'OUI',
  hb: 15092.04,
  vgm: 8447.43,
  plaquettes: 12412,
  frottisSanguin: 'suivant',
  ts: 23356.99,
  toPfa: 12721.5,
  toPfa100ColEpi: 19444.26,
  tp: 31265.13,
  aggregometriePlaquettaire: 'NP',
  resultatAgregometrie: "à l'instar de",
  resultatCmf: 'de par',
  dosageFvwRco: 11116.37,
  etudeGenetique: 'NON',
  thrombasthenieGlanzmann: true,
  typeEcchymose: 'SPONTANE',
  gingivorragies: 'NP',
  epistaxis: 'NP',
  typeEpistaxis: 'PROVOQUE',
  hematome: 'NON',
  typeHematome: 'PROVOQUE',
  menoMetrorragies: 'NON',
  frequenceMenoMetrorragies: 14937,
  severiteMenoMetrorragies: 'partager',
  typeLesionSousJacente: 'touriste boum personnel',
  hemorragieVisceres: 'OUI',
  lesionSousJacenteVisceres: 'dring guère habile',
  typeInterventionChirurgicale: 'lectorat loufoque',
  dicynone: 'NON',
  exacyl: 'OUI',
  traitementOestroprogestatif: 'NP',
  mechage: 'NON',
  transfusionCgr: 'OUI',
  traitementMartial: 'OUI',
};

export const sampleWithFullData: IFicheThrombopathie = {
  id: 12137,
  dossierNumber: 'foule rédaction',
  ordreNumber: 'timide',
  indexNumber: 'au-dehors terne dedans',
  prenom: 'parfois spécialiste',
  nom: 'fonctionnaire',
  nomJeuneFille: 'certes',
  profession: 'soudain triangulaire ouch',
  etatCivil: 'NP',
  serviceClinique: 'PUR',
  autreServiceClinique: 'nonobstant vu que cot cot',
  couvertureSociale: 'INDIGENT',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-16'),
  ageActuel: 15993,
  origine: 'TOZEUR',
  autreOrigine: 'rectorat entre svelte',
  adresse: 'si bien que aimable moyen',
  telephone: '+33 311894217',
  prenomPere: 'jeune dorénavant',
  professionPere: 'antique gestionnaire de',
  nomPrenomMere: 'conseil d’administration ',
  professionMere: 'sincère communauté étudia',
  medecinTraitant: 'sitôt que guère',
  serviceOrigine: 'auprès de secouriste si b',
  biologisteResponsableDg: 'concurrence',
  diagnostic: 'AUTRE',
  autreDiagnostic: "à l'insu de soit sitôt qu",
  anneeDiagnostic: 2299,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-16'),
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'espiègle',
  casSimilaires: 'NP',
  nombreCas: 9852,
  degreParenteCasSimilaires: "à l'encontre de",
  decesSyndromeHemorragique: 'NP',
  nombreDeces: 14369,
  typeHemorragie: 'patientèle avant que blablabla',
  lienParenteDeces: 'dans en dehors de',
  enqueteFamiliale: 'FAITE',
  antecedentsMedicaux: 'peut-être',
  antecedentsChirurgicaux: 'NP',
  typeChirurgie: 'jamais',
  complicationHemorragique: 'NP',
  agePremierSigneHemorragique: 19087,
  typeSyndromeHemorragique: 'secouriste snif biathlète',
  ageDiagnostic: 30740,
  decouverteFortuite: true,
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: false,
  typeCirconstanceDiagnostic: 'bè étant donné que',
  eczema: 'NON',
  syndromeDysmorphique: 'NP',
  albinisme: 'NON',
  arthrogrypose: 'NON',
  gb: 26299,
  hb: 18970.29,
  vgm: 28597.17,
  tcmh: 28369.66,
  plaquettes: 26865,
  frottisSanguin: 'rembourser',
  ts: 28593.85,
  toPfa: 11755.15,
  toPfa100ColEpi: 29286.82,
  toPfa100ColAdp: 31329.58,
  tp: 3808.92,
  tca: 19798.1,
  aggregometriePlaquettaire: 'NON',
  resultatAgregometrie: 'à peine souvent',
  cmf: 'OUI',
  resultatCmf: 'membre titulaire',
  dosageFvwAg: 7899.33,
  dosageFvwRco: 5381.14,
  etudeGenetique: 'NP',
  resultatEtudeGenetique: 'terriblement',
  thrombasthenieGlanzmann: true,
  maladieBernardSoulier: false,
  autreThrombopathie: false,
  autreThrombopathieDetails: "de crainte que d'entre ha ha",
  ecchymose: 'NON',
  typeEcchymose: 'SPONTANE',
  gingivorragies: 'NON',
  typeGingivorragies: 'PROVOQUE',
  epistaxis: 'OUI',
  typeEpistaxis: 'PROVOQUE',
  hematome: 'NON',
  typeHematome: 'PROVOQUE',
  siegelHematome: 'auprès de',
  menoMetrorragies: 'OUI',
  frequenceMenoMetrorragies: 28159,
  severiteMenoMetrorragies: 'spécialiste distribuer broum',
  explorationMenoMetrorragies: 'NON',
  typeLesionSousJacente: 'là-haut chef de cuisine si',
  hemorragieVisceres: 'NP',
  hemorragieDigestiveHaute: true,
  hemorragieDigestiveBasse: true,
  hematurie: false,
  explorationHemorragieVisceres: 'OUI',
  lesionSousJacenteVisceres: 'combien commis de cuisine ah',
  interventionChirurgicale: 'OUI',
  typeInterventionChirurgicale: 'avant que',
  hematomesCerebrales: true,
  edcHemorragique: false,
  transfusionCps: 'NON',
  facteurVIIRecombinant: 'OUI',
  dicynone: 'OUI',
  exacyl: 'NP',
  traitementOestroprogestatif: 'OUI',
  mechage: 'NON',
  transfusionCgr: 'NON',
  traitementMartial: 'NON',
  thrombose: 'NP',
  alloImmunisationHLA: 'OUI',
};

export const sampleWithNewData: NewFicheThrombopathie = {
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'PUR',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  diagnostic: 'THROMBOPATHIE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
