import dayjs from 'dayjs/esm';

import { IFicheThrombopathie, NewFicheThrombopathie } from './fiche-thrombopathie.model';

export const sampleWithRequiredData: IFicheThrombopathie = {
  id: 25957,
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'HTO',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  diagnostic: 'THROMBOPATHIE',
};

export const sampleWithPartialData: IFicheThrombopathie = {
  id: 13817,
  ordreNumber: 'égoïste',
  indexNumber: 'penser attendrir',
  nom: 'paf',
  profession: 'du fait que bientôt par',
  etatCivil: 'DIVORCE',
  serviceClinique: 'PEDIATRIE_B',
  autreServiceClinique: 'mêler',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  origine: 'SBZ',
  autreOrigine: 'actionnaire incognito',
  adresse: 'touchant lors continuer',
  telephone: '0368824426',
  prenomPere: 'actionnaire calculer',
  professionPere: 'retarder',
  nomPrenomMere: 'devant',
  professionMere: 'vaste du fait que candide',
  biologisteResponsableDg: 'incorporer volontiers',
  diagnostic: 'WILLEBRAND',
  anneeDiagnostic: 28753,
  parentsConsanguins: 'NON',
  nombreCas: 12200,
  decesSyndromeHemorragique: 'NP',
  typeHemorragie: 'administration',
  complicationHemorragique: 'OUI',
  ageDiagnostic: 24401,
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: true,
  eczema: 'NON',
  syndromeDysmorphique: 'NP',
  albinisme: 'OUI',
  gb: 10734,
  hb: 18482.58,
  tcmh: 8978.78,
  ts: 31070.53,
  toPfa100ColEpi: 10439.91,
  toPfa100ColAdp: 26742.33,
  aggregometriePlaquettaire: 'NP',
  resultatAgregometrie: 'admirablement',
  cmf: 'OUI',
  dosageFvwRco: 28965.34,
  thrombasthenieGlanzmann: true,
  maladieBernardSoulier: true,
  autreThrombopathieDetails: 'solitaire remédier mélancolique',
  ecchymose: 'NON',
  typeGingivorragies: 'SPONTANE',
  epistaxis: 'NP',
  typeEpistaxis: 'PROVOQUE',
  siegelHematome: 'au dépens de',
  frequenceMenoMetrorragies: 23027,
  severiteMenoMetrorragies: 'à peu près auparavant',
  explorationMenoMetrorragies: 'OUI',
  hemorragieVisceres: 'NON',
  hemorragieDigestiveHaute: false,
  hemorragieDigestiveBasse: false,
  explorationHemorragieVisceres: 'NON',
  hematomesCerebrales: false,
  edcHemorragique: true,
  facteurVIIRecombinant: 'OUI',
  dicynone: 'NON',
  exacyl: 'OUI',
  traitementOestroprogestatif: 'NP',
  transfusionCgr: 'OUI',
  traitementMartial: 'NP',
  alloImmunisationHLA: 'OUI',
};

export const sampleWithFullData: IFicheThrombopathie = {
  id: 1755,
  dossierNumber: 'fidèle très quelque',
  ordreNumber: 'adorable',
  indexNumber: 'de crainte que',
  prenom: 'spécialiste grrr',
  nom: 'ouin snif',
  nomJeuneFille: 'dense',
  profession: 'avant-hier',
  etatCivil: 'MARIE',
  serviceClinique: 'PEDIATRIE_B',
  autreServiceClinique: 'voter',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-02-16'),
  ageActuel: 2520,
  origine: 'KAIRAOUANE',
  autreOrigine: 'pour que de façon à ce qu',
  adresse: 'sauf ensuite',
  telephone: '+33 698538168',
  prenomPere: 'malade préférer',
  professionPere: 'trop communauté étudiante',
  nomPrenomMere: "tant que craindre à l'ent",
  professionMere: 'triste cuicui soulever',
  medecinTraitant: 'sauf à',
  serviceOrigine: 'vroum hôte',
  biologisteResponsableDg: 'afin que',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  autreDiagnostic: 'appeler',
  anneeDiagnostic: 10340,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-15'),
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'entre-temps rectangulaire',
  casSimilaires: 'OUI',
  nombreCas: 17826,
  degreParenteCasSimilaires: 'vouh',
  decesSyndromeHemorragique: 'NP',
  nombreDeces: 5252,
  typeHemorragie: 'sitôt que',
  lienParenteDeces: 'planquer avex',
  enqueteFamiliale: 'NONFAITE',
  antecedentsMedicaux: 'équipe',
  antecedentsChirurgicaux: 'NON',
  typeChirurgie: 'à raison de énorme sombre',
  complicationHemorragique: 'NON',
  agePremierSigneHemorragique: 19688,
  typeSyndromeHemorragique: 'hors de si alors que',
  ageDiagnostic: 13935,
  decouverteFortuite: false,
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: false,
  typeCirconstanceDiagnostic: 'population du Québec grrr',
  eczema: 'NON',
  syndromeDysmorphique: 'NON',
  albinisme: 'NP',
  arthrogrypose: 'NP',
  gb: 6998,
  hb: 12769.67,
  vgm: 5527.82,
  tcmh: 392.39,
  plaquettes: 4026,
  frottisSanguin: 'délégation au cas où secouriste',
  ts: 32401.69,
  toPfa: 7011.37,
  toPfa100ColEpi: 15585.98,
  toPfa100ColAdp: 12865.35,
  tp: 6931.66,
  tca: 21463.3,
  aggregometriePlaquettaire: 'NON',
  resultatAgregometrie: "à l'exception de",
  cmf: 'NP',
  resultatCmf: 'comme habile de façon à',
  dosageFvwAg: 13022.05,
  dosageFvwRco: 6205.33,
  etudeGenetique: 'NP',
  resultatEtudeGenetique: 'plier',
  thrombasthenieGlanzmann: true,
  maladieBernardSoulier: true,
  autreThrombopathie: false,
  autreThrombopathieDetails: 'gestionnaire chef de cuisine insolite',
  ecchymose: 'NON',
  typeEcchymose: 'PROVOQUE',
  gingivorragies: 'NON',
  typeGingivorragies: 'PROVOQUE',
  epistaxis: 'NON',
  typeEpistaxis: 'SPONTANE',
  hematome: 'OUI',
  typeHematome: 'PROVOQUE',
  siegelHematome: 'innombrable chut',
  menoMetrorragies: 'OUI',
  frequenceMenoMetrorragies: 25419,
  severiteMenoMetrorragies: 'coller combien',
  explorationMenoMetrorragies: 'OUI',
  typeLesionSousJacente: 'blablabla électorat si bien que',
  hemorragieVisceres: 'OUI',
  hemorragieDigestiveHaute: true,
  hemorragieDigestiveBasse: false,
  hematurie: false,
  explorationHemorragieVisceres: 'OUI',
  lesionSousJacenteVisceres: 'personnel serviable',
  interventionChirurgicale: 'NP',
  typeInterventionChirurgicale: 'vis-à-vie de pis',
  hematomesCerebrales: false,
  edcHemorragique: false,
  transfusionCps: 'OUI',
  facteurVIIRecombinant: 'OUI',
  dicynone: 'NP',
  exacyl: 'NON',
  traitementOestroprogestatif: 'OUI',
  mechage: 'NP',
  transfusionCgr: 'NP',
  traitementMartial: 'OUI',
  thrombose: 'NON',
  alloImmunisationHLA: 'NON',
};

export const sampleWithNewData: NewFicheThrombopathie = {
  etatCivil: 'NP',
  serviceClinique: 'PEDIATRIE_A',
  couvertureSociale: 'NP',
  sexe: 'MASCULIN',
  diagnostic: 'DEFICIT_FACTEUR_XI',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
