import dayjs from 'dayjs/esm';
import { CivilStatus } from 'app/entities/enumerations/civil-status.model';
import { ServiceCliniqueType } from 'app/entities/enumerations/service-clinique-type.model';
import { CouvertureSociale } from 'app/entities/enumerations/couverture-sociale.model';
import { Gender } from 'app/entities/enumerations/gender.model';
import { Region } from 'app/entities/enumerations/region.model';
import { DiagnosticType } from 'app/entities/enumerations/diagnostic-type.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { FaiteNonFaite } from 'app/entities/enumerations/faite-non-faite.model';
import { TypeManifestation } from 'app/entities/enumerations/type-manifestation.model';

export interface IFicheThrombopathie {
  id: number;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  prenom?: string | null;
  nom?: string | null;
  nomJeuneFille?: string | null;
  profession?: string | null;
  etatCivil?: keyof typeof CivilStatus | null;
  serviceClinique?: keyof typeof ServiceCliniqueType | null;
  autreServiceClinique?: string | null;
  couvertureSociale?: keyof typeof CouvertureSociale | null;
  sexe?: keyof typeof Gender | null;
  dateNaissance?: dayjs.Dayjs | null;
  ageActuel?: number | null;
  origine?: keyof typeof Region | null;
  autreOrigine?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  prenomPere?: string | null;
  professionPere?: string | null;
  nomPrenomMere?: string | null;
  professionMere?: string | null;
  medecinTraitant?: string | null;
  serviceOrigine?: string | null;
  biologisteResponsableDg?: string | null;
  diagnostic?: keyof typeof DiagnosticType | null;
  autreDiagnostic?: string | null;
  anneeDiagnostic?: number | null;
  consentementRegistre?: keyof typeof OuiNonNP | null;
  dateEnregistrementRegistre?: dayjs.Dayjs | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: string | null;
  casSimilaires?: keyof typeof OuiNonNP | null;
  nombreCas?: number | null;
  degreParenteCasSimilaires?: string | null;
  decesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nombreDeces?: number | null;
  typeHemorragie?: string | null;
  lienParenteDeces?: string | null;
  enqueteFamiliale?: keyof typeof FaiteNonFaite | null;
  antecedentsMedicaux?: string | null;
  antecedentsChirurgicaux?: keyof typeof OuiNonNP | null;
  typeChirurgie?: string | null;
  complicationHemorragique?: keyof typeof OuiNonNP | null;
  agePremierSigneHemorragique?: number | null;
  typeSyndromeHemorragique?: string | null;
  ageDiagnostic?: number | null;
  decouverteFortuite?: boolean | null;
  enqueteFamilialeBool?: boolean | null;
  explorationSyndromeHemorragique?: boolean | null;
  typeCirconstanceDiagnostic?: string | null;
  eczema?: keyof typeof OuiNonNP | null;
  syndromeDysmorphique?: keyof typeof OuiNonNP | null;
  albinisme?: keyof typeof OuiNonNP | null;
  arthrogrypose?: keyof typeof OuiNonNP | null;
  gb?: number | null;
  hb?: number | null;
  vgm?: number | null;
  tcmh?: number | null;
  plaquettes?: number | null;
  frottisSanguin?: string | null;
  ts?: number | null;
  toPfa?: number | null;
  toPfa100ColEpi?: number | null;
  toPfa100ColAdp?: number | null;
  tp?: number | null;
  tca?: number | null;
  aggregometriePlaquettaire?: keyof typeof OuiNonNP | null;
  resultatAgregometrie?: string | null;
  cmf?: keyof typeof OuiNonNP | null;
  resultatCmf?: string | null;
  dosageFvwAg?: number | null;
  dosageFvwRco?: number | null;
  etudeGenetique?: keyof typeof OuiNonNP | null;
  resultatEtudeGenetique?: string | null;
  thrombasthenieGlanzmann?: boolean | null;
  maladieBernardSoulier?: boolean | null;
  autreThrombopathie?: boolean | null;
  autreThrombopathieDetails?: string | null;
  ecchymose?: keyof typeof OuiNonNP | null;
  typeEcchymose?: keyof typeof TypeManifestation | null;
  gingivorragies?: keyof typeof OuiNonNP | null;
  typeGingivorragies?: keyof typeof TypeManifestation | null;
  epistaxis?: keyof typeof OuiNonNP | null;
  typeEpistaxis?: keyof typeof TypeManifestation | null;
  hematome?: keyof typeof OuiNonNP | null;
  typeHematome?: keyof typeof TypeManifestation | null;
  siegelHematome?: string | null;
  menoMetrorragies?: keyof typeof OuiNonNP | null;
  frequenceMenoMetrorragies?: number | null;
  severiteMenoMetrorragies?: string | null;
  explorationMenoMetrorragies?: keyof typeof OuiNonNP | null;
  typeLesionSousJacente?: string | null;
  hemorragieVisceres?: keyof typeof OuiNonNP | null;
  hemorragieDigestiveHaute?: boolean | null;
  hemorragieDigestiveBasse?: boolean | null;
  hematurie?: boolean | null;
  explorationHemorragieVisceres?: keyof typeof OuiNonNP | null;
  lesionSousJacenteVisceres?: string | null;
  interventionChirurgicale?: keyof typeof OuiNonNP | null;
  typeInterventionChirurgicale?: string | null;
  hematomesCerebrales?: boolean | null;
  edcHemorragique?: boolean | null;
  transfusionCps?: keyof typeof OuiNonNP | null;
  facteurVIIRecombinant?: keyof typeof OuiNonNP | null;
  dicynone?: keyof typeof OuiNonNP | null;
  exacyl?: keyof typeof OuiNonNP | null;
  traitementOestroprogestatif?: keyof typeof OuiNonNP | null;
  mechage?: keyof typeof OuiNonNP | null;
  transfusionCgr?: keyof typeof OuiNonNP | null;
  traitementMartial?: keyof typeof OuiNonNP | null;
  thrombose?: keyof typeof OuiNonNP | null;
  alloImmunisationHLA?: keyof typeof OuiNonNP | null;
}

export type NewFicheThrombopathie = Omit<IFicheThrombopathie, 'id'> & { id: null };
