package tn.adhes.hemostase.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FicheFacteurXVIIIAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurXVIIIAllPropertiesEquals(FicheFacteurXVIII expected, FicheFacteurXVIII actual) {
        assertFicheFacteurXVIIIAutoGeneratedPropertiesEquals(expected, actual);
        assertFicheFacteurXVIIIAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurXVIIIAllUpdatablePropertiesEquals(FicheFacteurXVIII expected, FicheFacteurXVIII actual) {
        assertFicheFacteurXVIIIUpdatableFieldsEquals(expected, actual);
        assertFicheFacteurXVIIIUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurXVIIIAutoGeneratedPropertiesEquals(FicheFacteurXVIII expected, FicheFacteurXVIII actual) {
        assertThat(expected)
            .as("Verify FicheFacteurXVIII auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurXVIIIUpdatableFieldsEquals(FicheFacteurXVIII expected, FicheFacteurXVIII actual) {
        assertThat(expected)
            .as("Verify FicheFacteurXVIII relevant properties")
            .satisfies(e -> assertThat(e.getDossierNumber()).as("check dossierNumber").isEqualTo(actual.getDossierNumber()))
            .satisfies(e -> assertThat(e.getOrdreNumber()).as("check ordreNumber").isEqualTo(actual.getOrdreNumber()))
            .satisfies(e -> assertThat(e.getIndexNumber()).as("check indexNumber").isEqualTo(actual.getIndexNumber()))
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getNomJeuneFille()).as("check nomJeuneFille").isEqualTo(actual.getNomJeuneFille()))
            .satisfies(e -> assertThat(e.getProfession()).as("check profession").isEqualTo(actual.getProfession()))
            .satisfies(e -> assertThat(e.getEtatCivil()).as("check etatCivil").isEqualTo(actual.getEtatCivil()))
            .satisfies(e -> assertThat(e.getServiceClinique()).as("check serviceClinique").isEqualTo(actual.getServiceClinique()))
            .satisfies(e ->
                assertThat(e.getAutreServiceClinique()).as("check autreServiceClinique").isEqualTo(actual.getAutreServiceClinique())
            )
            .satisfies(e -> assertThat(e.getCouvertureSociale()).as("check couvertureSociale").isEqualTo(actual.getCouvertureSociale()))
            .satisfies(e -> assertThat(e.getSexe()).as("check sexe").isEqualTo(actual.getSexe()))
            .satisfies(e -> assertThat(e.getDateNaissance()).as("check dateNaissance").isEqualTo(actual.getDateNaissance()))
            .satisfies(e -> assertThat(e.getAgeActuel()).as("check ageActuel").isEqualTo(actual.getAgeActuel()))
            .satisfies(e -> assertThat(e.getOrigine()).as("check origine").isEqualTo(actual.getOrigine()))
            .satisfies(e -> assertThat(e.getAutreOrigine()).as("check autreOrigine").isEqualTo(actual.getAutreOrigine()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getPrenomPere()).as("check prenomPere").isEqualTo(actual.getPrenomPere()))
            .satisfies(e -> assertThat(e.getProfessionPere()).as("check professionPere").isEqualTo(actual.getProfessionPere()))
            .satisfies(e -> assertThat(e.getNomPrenomMere()).as("check nomPrenomMere").isEqualTo(actual.getNomPrenomMere()))
            .satisfies(e -> assertThat(e.getProfessionMere()).as("check professionMere").isEqualTo(actual.getProfessionMere()))
            .satisfies(e -> assertThat(e.getMedecinTraitant()).as("check medecinTraitant").isEqualTo(actual.getMedecinTraitant()))
            .satisfies(e -> assertThat(e.getServiceOrigine()).as("check serviceOrigine").isEqualTo(actual.getServiceOrigine()))
            .satisfies(e ->
                assertThat(e.getBiologisteResponsableDg())
                    .as("check biologisteResponsableDg")
                    .isEqualTo(actual.getBiologisteResponsableDg())
            )
            .satisfies(e -> assertThat(e.getDiagnostic()).as("check diagnostic").isEqualTo(actual.getDiagnostic()))
            .satisfies(e -> assertThat(e.getAutreDiagnostic()).as("check autreDiagnostic").isEqualTo(actual.getAutreDiagnostic()))
            .satisfies(e -> assertThat(e.getAnneeDiagnostic()).as("check anneeDiagnostic").isEqualTo(actual.getAnneeDiagnostic()))
            .satisfies(e ->
                assertThat(e.getConsentementRegistre()).as("check consentementRegistre").isEqualTo(actual.getConsentementRegistre())
            )
            .satisfies(e ->
                assertThat(e.getDateEnregistrementRegistre())
                    .as("check dateEnregistrementRegistre")
                    .isEqualTo(actual.getDateEnregistrementRegistre())
            )
            .satisfies(e -> assertThat(e.getParentsConsanguins()).as("check parentsConsanguins").isEqualTo(actual.getParentsConsanguins()))
            .satisfies(e ->
                assertThat(e.getDegreParenteConsanguins())
                    .as("check degreParenteConsanguins")
                    .isEqualTo(actual.getDegreParenteConsanguins())
            )
            .satisfies(e -> assertThat(e.getCasSimilaires()).as("check casSimilaires").isEqualTo(actual.getCasSimilaires()))
            .satisfies(e -> assertThat(e.getNombreCas()).as("check nombreCas").isEqualTo(actual.getNombreCas()))
            .satisfies(e -> assertThat(e.getCas1Numero()).as("check cas1Numero").isEqualTo(actual.getCas1Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas1()).as("check lienParenteCas1").isEqualTo(actual.getLienParenteCas1()))
            .satisfies(e -> assertThat(e.getDegreParenteCas1()).as("check degreParenteCas1").isEqualTo(actual.getDegreParenteCas1()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas1()).as("check typeHemorragieCas1").isEqualTo(actual.getTypeHemorragieCas1()))
            .satisfies(e -> assertThat(e.getCas2Numero()).as("check cas2Numero").isEqualTo(actual.getCas2Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas2()).as("check lienParenteCas2").isEqualTo(actual.getLienParenteCas2()))
            .satisfies(e -> assertThat(e.getDegreParenteCas2()).as("check degreParenteCas2").isEqualTo(actual.getDegreParenteCas2()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas2()).as("check typeHemorragieCas2").isEqualTo(actual.getTypeHemorragieCas2()))
            .satisfies(e -> assertThat(e.getCas3Numero()).as("check cas3Numero").isEqualTo(actual.getCas3Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas3()).as("check lienParenteCas3").isEqualTo(actual.getLienParenteCas3()))
            .satisfies(e -> assertThat(e.getDegreParenteCas3()).as("check degreParenteCas3").isEqualTo(actual.getDegreParenteCas3()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas3()).as("check typeHemorragieCas3").isEqualTo(actual.getTypeHemorragieCas3()))
            .satisfies(e ->
                assertThat(e.getDecesSyndromeHemorragique())
                    .as("check decesSyndromeHemorragique")
                    .isEqualTo(actual.getDecesSyndromeHemorragique())
            )
            .satisfies(e -> assertThat(e.getNombreDeces()).as("check nombreDeces").isEqualTo(actual.getNombreDeces()))
            .satisfies(e -> assertThat(e.getDeces1Numero()).as("check deces1Numero").isEqualTo(actual.getDeces1Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces1()).as("check lienParenteDeces1").isEqualTo(actual.getLienParenteDeces1()))
            .satisfies(e -> assertThat(e.getCauseDeces1()).as("check causeDeces1").isEqualTo(actual.getCauseDeces1()))
            .satisfies(e -> assertThat(e.getDeces2Numero()).as("check deces2Numero").isEqualTo(actual.getDeces2Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces2()).as("check lienParenteDeces2").isEqualTo(actual.getLienParenteDeces2()))
            .satisfies(e -> assertThat(e.getCauseDeces2()).as("check causeDeces2").isEqualTo(actual.getCauseDeces2()))
            .satisfies(e -> assertThat(e.getDeces3Numero()).as("check deces3Numero").isEqualTo(actual.getDeces3Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces3()).as("check lienParenteDeces3").isEqualTo(actual.getLienParenteDeces3()))
            .satisfies(e -> assertThat(e.getCauseDeces3()).as("check causeDeces3").isEqualTo(actual.getCauseDeces3()))
            .satisfies(e -> assertThat(e.getEnqueteFamiliale()).as("check enqueteFamiliale").isEqualTo(actual.getEnqueteFamiliale()))
            .satisfies(e -> assertThat(e.getCircHemorragique()).as("check circHemorragique").isEqualTo(actual.getCircHemorragique()))
            .satisfies(e ->
                assertThat(e.getPrecisionsCircHemorragique())
                    .as("check precisionsCircHemorragique")
                    .isEqualTo(actual.getPrecisionsCircHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getDecouverteFortuitePreop())
                    .as("check decouverteFortuitePreop")
                    .isEqualTo(actual.getDecouverteFortuitePreop())
            )
            .satisfies(e ->
                assertThat(e.getPrecisionsDecouverteFortuite())
                    .as("check precisionsDecouverteFortuite")
                    .isEqualTo(actual.getPrecisionsDecouverteFortuite())
            )
            .satisfies(e -> assertThat(e.getJamaisSaignement()).as("check jamaisSaignement").isEqualTo(actual.getJamaisSaignement()))
            .satisfies(e ->
                assertThat(e.getAgePremierSigneJours()).as("check agePremierSigneJours").isEqualTo(actual.getAgePremierSigneJours())
            )
            .satisfies(e ->
                assertThat(e.getAgePremierSigneMois()).as("check agePremierSigneMois").isEqualTo(actual.getAgePremierSigneMois())
            )
            .satisfies(e ->
                assertThat(e.getAgePremierSigneAnnees()).as("check agePremierSigneAnnees").isEqualTo(actual.getAgePremierSigneAnnees())
            )
            .satisfies(e -> assertThat(e.getSymptomeEcchymose()).as("check symptomeEcchymose").isEqualTo(actual.getSymptomeEcchymose()))
            .satisfies(e -> assertThat(e.getSymptomeEpistaxis()).as("check symptomeEpistaxis").isEqualTo(actual.getSymptomeEpistaxis()))
            .satisfies(e ->
                assertThat(e.getSymptomeGingivorragies()).as("check symptomeGingivorragies").isEqualTo(actual.getSymptomeGingivorragies())
            )
            .satisfies(e ->
                assertThat(e.getSymptomeMetrorragies()).as("check symptomeMetrorragies").isEqualTo(actual.getSymptomeMetrorragies())
            )
            .satisfies(e -> assertThat(e.getSymptomeMelena()).as("check symptomeMelena").isEqualTo(actual.getSymptomeMelena()))
            .satisfies(e -> assertThat(e.getSymptomeHemoptysie()).as("check symptomeHemoptysie").isEqualTo(actual.getSymptomeHemoptysie()))
            .satisfies(e ->
                assertThat(e.getSymptomePostAmygdalectomie())
                    .as("check symptomePostAmygdalectomie")
                    .isEqualTo(actual.getSymptomePostAmygdalectomie())
            )
            .satisfies(e ->
                assertThat(e.getSymptomePostAvulsionDentaire())
                    .as("check symptomePostAvulsionDentaire")
                    .isEqualTo(actual.getSymptomePostAvulsionDentaire())
            )
            .satisfies(e ->
                assertThat(e.getSymptomeChuteCordon()).as("check symptomeChuteCordon").isEqualTo(actual.getSymptomeChuteCordon())
            )
            .satisfies(e -> assertThat(e.getSymptomeAutre()).as("check symptomeAutre").isEqualTo(actual.getSymptomeAutre()))
            .satisfies(e ->
                assertThat(e.getSymptomeAutreDescription())
                    .as("check symptomeAutreDescription")
                    .isEqualTo(actual.getSymptomeAutreDescription())
            )
            .satisfies(e ->
                assertThat(e.getDatePremiereConsultation())
                    .as("check datePremiereConsultation")
                    .isEqualTo(actual.getDatePremiereConsultation())
            )
            .satisfies(e ->
                assertThat(e.getAgePremiereConsultationJours())
                    .as("check agePremiereConsultationJours")
                    .isEqualTo(actual.getAgePremiereConsultationJours())
            )
            .satisfies(e ->
                assertThat(e.getAgePremiereConsultationMois())
                    .as("check agePremiereConsultationMois")
                    .isEqualTo(actual.getAgePremiereConsultationMois())
            )
            .satisfies(e ->
                assertThat(e.getAgePremiereConsultationAnnees())
                    .as("check agePremiereConsultationAnnees")
                    .isEqualTo(actual.getAgePremiereConsultationAnnees())
            )
            .satisfies(e -> assertThat(e.getAgeDiagnosticJours()).as("check ageDiagnosticJours").isEqualTo(actual.getAgeDiagnosticJours()))
            .satisfies(e -> assertThat(e.getAgeDiagnosticMois()).as("check ageDiagnosticMois").isEqualTo(actual.getAgeDiagnosticMois()))
            .satisfies(e ->
                assertThat(e.getAgeDiagnosticAnnees()).as("check ageDiagnosticAnnees").isEqualTo(actual.getAgeDiagnosticAnnees())
            )
            .satisfies(e -> assertThat(e.getHb()).as("check hb").isEqualTo(actual.getHb()))
            .satisfies(e -> assertThat(e.getHt()).as("check ht").isEqualTo(actual.getHt()))
            .satisfies(e -> assertThat(e.getPlaquettes()).as("check plaquettes").isEqualTo(actual.getPlaquettes()))
            .satisfies(e -> assertThat(e.getColEpi()).as("check colEpi").isEqualTo(actual.getColEpi()))
            .satisfies(e -> assertThat(e.getColAdp()).as("check colAdp").isEqualTo(actual.getColAdp()))
            .satisfies(e -> assertThat(e.getTp()).as("check tp").isEqualTo(actual.getTp()))
            .satisfies(e -> assertThat(e.getTpMPlusT()).as("check tpMPlusT").isEqualTo(actual.getTpMPlusT()))
            .satisfies(e -> assertThat(e.getFibrinogene()).as("check fibrinogene").isEqualTo(actual.getFibrinogene()))
            .satisfies(e -> assertThat(e.getTcaMT()).as("check tcaMT").isEqualTo(actual.getTcaMT()))
            .satisfies(e -> assertThat(e.getTcaMPlusT()).as("check tcaMPlusT").isEqualTo(actual.getTcaMPlusT()))
            .satisfies(e -> assertThat(e.getTcaTemoin()).as("check tcaTemoin").isEqualTo(actual.getTcaTemoin()))
            .satisfies(e ->
                assertThat(e.getFacteurDeficitaireAutre())
                    .as("check facteurDeficitaireAutre")
                    .isEqualTo(actual.getFacteurDeficitaireAutre())
            )
            .satisfies(e ->
                assertThat(e.getTauxFacteurDeficitaireAutre())
                    .as("check tauxFacteurDeficitaireAutre")
                    .isEqualTo(actual.getTauxFacteurDeficitaireAutre())
            )
            .satisfies(e ->
                assertThat(e.getFacteurSupplementaire1()).as("check facteurSupplementaire1").isEqualTo(actual.getFacteurSupplementaire1())
            )
            .satisfies(e ->
                assertThat(e.getTauxSupplementaire1()).as("check tauxSupplementaire1").isEqualTo(actual.getTauxSupplementaire1())
            )
            .satisfies(e ->
                assertThat(e.getFacteurSupplementaire2()).as("check facteurSupplementaire2").isEqualTo(actual.getFacteurSupplementaire2())
            )
            .satisfies(e ->
                assertThat(e.getTauxSupplementaire2()).as("check tauxSupplementaire2").isEqualTo(actual.getTauxSupplementaire2())
            )
            .satisfies(e ->
                assertThat(e.getFacteurSupplementaire3()).as("check facteurSupplementaire3").isEqualTo(actual.getFacteurSupplementaire3())
            )
            .satisfies(e ->
                assertThat(e.getTauxSupplementaire3()).as("check tauxSupplementaire3").isEqualTo(actual.getTauxSupplementaire3())
            )
            .satisfies(e ->
                assertThat(e.getConfirmationMoleculaire())
                    .as("check confirmationMoleculaire")
                    .isEqualTo(actual.getConfirmationMoleculaire())
            )
            .satisfies(e -> assertThat(e.getMutationPresente()).as("check mutationPresente").isEqualTo(actual.getMutationPresente()))
            .satisfies(e -> assertThat(e.getMutationNom()).as("check mutationNom").isEqualTo(actual.getMutationNom()))
            .satisfies(e -> assertThat(e.getMutationType()).as("check mutationType").isEqualTo(actual.getMutationType()))
            .satisfies(e -> assertThat(e.getMutation2Nom()).as("check mutation2Nom").isEqualTo(actual.getMutation2Nom()))
            .satisfies(e -> assertThat(e.getSerologieVHB()).as("check serologieVHB").isEqualTo(actual.getSerologieVHB()))
            .satisfies(e -> assertThat(e.getSerologieVHC()).as("check serologieVHC").isEqualTo(actual.getSerologieVHC()))
            .satisfies(e -> assertThat(e.getSerologieVIH()).as("check serologieVIH").isEqualTo(actual.getSerologieVIH()))
            .satisfies(e -> assertThat(e.getEpistaxis()).as("check epistaxis").isEqualTo(actual.getEpistaxis()))
            .satisfies(e -> assertThat(e.getFrequenceEpistaxis()).as("check frequenceEpistaxis").isEqualTo(actual.getFrequenceEpistaxis()))
            .satisfies(e -> assertThat(e.getGingivorragies()).as("check gingivorragies").isEqualTo(actual.getGingivorragies()))
            .satisfies(e -> assertThat(e.getTypeGingivorragies()).as("check typeGingivorragies").isEqualTo(actual.getTypeGingivorragies()))
            .satisfies(e ->
                assertThat(e.getFrequenceGingivorragies())
                    .as("check frequenceGingivorragies")
                    .isEqualTo(actual.getFrequenceGingivorragies())
            )
            .satisfies(e -> assertThat(e.getEcchymose()).as("check ecchymose").isEqualTo(actual.getEcchymose()))
            .satisfies(e -> assertThat(e.getTypeEcchymose()).as("check typeEcchymose").isEqualTo(actual.getTypeEcchymose()))
            .satisfies(e -> assertThat(e.getFrequenceEcchymose()).as("check frequenceEcchymose").isEqualTo(actual.getFrequenceEcchymose()))
            .satisfies(e -> assertThat(e.getMenorragie()).as("check menorragie").isEqualTo(actual.getMenorragie()))
            .satisfies(e ->
                assertThat(e.getFrequenceMenorragie()).as("check frequenceMenorragie").isEqualTo(actual.getFrequenceMenorragie())
            )
            .satisfies(e -> assertThat(e.getHematemese()).as("check hematemese").isEqualTo(actual.getHematemese()))
            .satisfies(e ->
                assertThat(e.getFrequenceHematemese()).as("check frequenceHematemese").isEqualTo(actual.getFrequenceHematemese())
            )
            .satisfies(e -> assertThat(e.getRectorragie()).as("check rectorragie").isEqualTo(actual.getRectorragie()))
            .satisfies(e ->
                assertThat(e.getFrequenceRectorragie()).as("check frequenceRectorragie").isEqualTo(actual.getFrequenceRectorragie())
            )
            .satisfies(e -> assertThat(e.getHematurie()).as("check hematurie").isEqualTo(actual.getHematurie()))
            .satisfies(e -> assertThat(e.getFrequenceHematurie()).as("check frequenceHematurie").isEqualTo(actual.getFrequenceHematurie()))
            .satisfies(e -> assertThat(e.getHematomeSousCutane()).as("check hematomeSousCutane").isEqualTo(actual.getHematomeSousCutane()))
            .satisfies(e ->
                assertThat(e.getTypeHematomeSousCutane()).as("check typeHematomeSousCutane").isEqualTo(actual.getTypeHematomeSousCutane())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceHematomeSousCutane())
                    .as("check frequenceHematomeSousCutane")
                    .isEqualTo(actual.getFrequenceHematomeSousCutane())
            )
            .satisfies(e -> assertThat(e.getHematomeMusculaire()).as("check hematomeMusculaire").isEqualTo(actual.getHematomeMusculaire()))
            .satisfies(e ->
                assertThat(e.getSiegeHematomeMusculaire())
                    .as("check siegeHematomeMusculaire")
                    .isEqualTo(actual.getSiegeHematomeMusculaire())
            )
            .satisfies(e ->
                assertThat(e.getTypeHematomeMusculaire()).as("check typeHematomeMusculaire").isEqualTo(actual.getTypeHematomeMusculaire())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceHematomeMusculaire())
                    .as("check frequenceHematomeMusculaire")
                    .isEqualTo(actual.getFrequenceHematomeMusculaire())
            )
            .satisfies(e -> assertThat(e.getHemarthrose()).as("check hemarthrose").isEqualTo(actual.getHemarthrose()))
            .satisfies(e -> assertThat(e.getTypeHemarthrose()).as("check typeHemarthrose").isEqualTo(actual.getTypeHemarthrose()))
            .satisfies(e ->
                assertThat(e.getFrequenceHemarthrose()).as("check frequenceHemarthrose").isEqualTo(actual.getFrequenceHemarthrose())
            )
            .satisfies(e -> assertThat(e.getSaignementSNC()).as("check saignementSNC").isEqualTo(actual.getSaignementSNC()))
            .satisfies(e -> assertThat(e.getTypeSaignementSNC()).as("check typeSaignementSNC").isEqualTo(actual.getTypeSaignementSNC()))
            .satisfies(e ->
                assertThat(e.getFrequenceSaignementSNC()).as("check frequenceSaignementSNC").isEqualTo(actual.getFrequenceSaignementSNC())
            )
            .satisfies(e ->
                assertThat(e.getSaignementChuteCordon()).as("check saignementChuteCordon").isEqualTo(actual.getSaignementChuteCordon())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceSaignementChuteCordon())
                    .as("check frequenceSaignementChuteCordon")
                    .isEqualTo(actual.getFrequenceSaignementChuteCordon())
            )
            .satisfies(e ->
                assertThat(e.getRetardCicatrisationPlaies())
                    .as("check retardCicatrisationPlaies")
                    .isEqualTo(actual.getRetardCicatrisationPlaies())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceRetardCicatrisationPlaies())
                    .as("check frequenceRetardCicatrisationPlaies")
                    .isEqualTo(actual.getFrequenceRetardCicatrisationPlaies())
            )
            .satisfies(e ->
                assertThat(e.getAutresManifestations()).as("check autresManifestations").isEqualTo(actual.getAutresManifestations())
            )
            .satisfies(e ->
                assertThat(e.getFaussesCouchesSpontaneesRecurrence())
                    .as("check faussesCouchesSpontaneesRecurrence")
                    .isEqualTo(actual.getFaussesCouchesSpontaneesRecurrence())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceFaussesCouches())
                    .as("check frequenceFaussesCouches")
                    .isEqualTo(actual.getFrequenceFaussesCouches())
            )
            .satisfies(e ->
                assertThat(e.getAccidentsThrombotiques()).as("check accidentsThrombotiques").isEqualTo(actual.getAccidentsThrombotiques())
            )
            .satisfies(e -> assertThat(e.getThromboseVeineuse()).as("check thromboseVeineuse").isEqualTo(actual.getThromboseVeineuse()))
            .satisfies(e ->
                assertThat(e.getThromboseArterielle()).as("check thromboseArterielle").isEqualTo(actual.getThromboseArterielle())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceAccidentsThrombotiques())
                    .as("check frequenceAccidentsThrombotiques")
                    .isEqualTo(actual.getFrequenceAccidentsThrombotiques())
            )
            .satisfies(e -> assertThat(e.getHemoperitoine()).as("check hemoperitoine").isEqualTo(actual.getHemoperitoine()))
            .satisfies(e ->
                assertThat(e.getFrequenceHemoperitoine()).as("check frequenceHemoperitoine").isEqualTo(actual.getFrequenceHemoperitoine())
            )
            .satisfies(e ->
                assertThat(e.getRuptureKystesHemorragiques())
                    .as("check ruptureKystesHemorragiques")
                    .isEqualTo(actual.getRuptureKystesHemorragiques())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceRuptureKystes()).as("check frequenceRuptureKystes").isEqualTo(actual.getFrequenceRuptureKystes())
            )
            .satisfies(e -> assertThat(e.getHemorragieGrave()).as("check hemorragieGrave").isEqualTo(actual.getHemorragieGrave()))
            .satisfies(e ->
                assertThat(e.getFrequenceHemorragieGrave())
                    .as("check frequenceHemorragieGrave")
                    .isEqualTo(actual.getFrequenceHemorragieGrave())
            )
            .satisfies(e ->
                assertThat(e.getGraviteDeglobulisation()).as("check graviteDeglobulisation").isEqualTo(actual.getGraviteDeglobulisation())
            )
            .satisfies(e -> assertThat(e.getGraviteEtatDeChoc()).as("check graviteEtatDeChoc").isEqualTo(actual.getGraviteEtatDeChoc()))
            .satisfies(e ->
                assertThat(e.getGraviteParLocalisation()).as("check graviteParLocalisation").isEqualTo(actual.getGraviteParLocalisation())
            )
            .satisfies(e ->
                assertThat(e.getSiegeGraviteLocalisation())
                    .as("check siegeGraviteLocalisation")
                    .isEqualTo(actual.getSiegeGraviteLocalisation())
            )
            .satisfies(e -> assertThat(e.getChirurgiePrepare()).as("check chirurgiePrepare").isEqualTo(actual.getChirurgiePrepare()))
            .satisfies(e ->
                assertThat(e.getChirurgieSuiteHemorragique())
                    .as("check chirurgieSuiteHemorragique")
                    .isEqualTo(actual.getChirurgieSuiteHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getCirconcisionPrepare()).as("check circoncisionPrepare").isEqualTo(actual.getCirconcisionPrepare())
            )
            .satisfies(e ->
                assertThat(e.getCirconcisionSuiteHemorragique())
                    .as("check circoncisionSuiteHemorragique")
                    .isEqualTo(actual.getCirconcisionSuiteHemorragique())
            )
            .satisfies(e -> assertThat(e.getAgeCirconcision()).as("check ageCirconcision").isEqualTo(actual.getAgeCirconcision()))
            .satisfies(e -> assertThat(e.getTraitementPFC()).as("check traitementPFC").isEqualTo(actual.getTraitementPFC()))
            .satisfies(e ->
                assertThat(e.getTraitementCryoprecipite())
                    .as("check traitementCryoprecipite")
                    .isEqualTo(actual.getTraitementCryoprecipite())
            )
            .satisfies(e ->
                assertThat(e.getTraitementConcentreFacteurXI())
                    .as("check traitementConcentreFacteurXI")
                    .isEqualTo(actual.getTraitementConcentreFacteurXI())
            )
            .satisfies(e ->
                assertThat(e.getTraitementCulotsPlaquettaires())
                    .as("check traitementCulotsPlaquettaires")
                    .isEqualTo(actual.getTraitementCulotsPlaquettaires())
            )
            .satisfies(e -> assertThat(e.getTraitementDicynone()).as("check traitementDicynone").isEqualTo(actual.getTraitementDicynone()))
            .satisfies(e -> assertThat(e.getTraitementExacyl()).as("check traitementExacyl").isEqualTo(actual.getTraitementExacyl()))
            .satisfies(e -> assertThat(e.getTraitementMartial()).as("check traitementMartial").isEqualTo(actual.getTraitementMartial()))
            .satisfies(e ->
                assertThat(e.getTraitementOestroprogestatif())
                    .as("check traitementOestroprogestatif")
                    .isEqualTo(actual.getTraitementOestroprogestatif())
            )
            .satisfies(e -> assertThat(e.getTransfusionCGR()).as("check transfusionCGR").isEqualTo(actual.getTransfusionCGR()))
            .satisfies(e -> assertThat(e.getAlloImmunisation()).as("check alloImmunisation").isEqualTo(actual.getAlloImmunisation()))
            .satisfies(e ->
                assertThat(e.getInhibiteurNeutralisant()).as("check inhibiteurNeutralisant").isEqualTo(actual.getInhibiteurNeutralisant())
            )
            .satisfies(e -> assertThat(e.getTitreInhibiteurUB()).as("check titreInhibiteurUB").isEqualTo(actual.getTitreInhibiteurUB()))
            .satisfies(e ->
                assertThat(e.getInhibiteurNonNeutralisant())
                    .as("check inhibiteurNonNeutralisant")
                    .isEqualTo(actual.getInhibiteurNonNeutralisant())
            )
            .satisfies(e -> assertThat(e.getInfectionVIH()).as("check infectionVIH").isEqualTo(actual.getInfectionVIH()))
            .satisfies(e -> assertThat(e.getInfectionVHC()).as("check infectionVHC").isEqualTo(actual.getInfectionVHC()))
            .satisfies(e -> assertThat(e.getInfectionVHB()).as("check infectionVHB").isEqualTo(actual.getInfectionVHB()))
            .satisfies(e -> assertThat(e.getThrombose()).as("check thrombose").isEqualTo(actual.getThrombose()))
            .satisfies(e -> assertThat(e.getReactionAllergique()).as("check reactionAllergique").isEqualTo(actual.getReactionAllergique()))
            .satisfies(e ->
                assertThat(e.getAutresComplications()).as("check autresComplications").isEqualTo(actual.getAutresComplications())
            )
            .satisfies(e ->
                assertThat(e.getAdherenceTherapeutique()).as("check adherenceTherapeutique").isEqualTo(actual.getAdherenceTherapeutique())
            )
            .satisfies(e -> assertThat(e.getCauseNonAdherence()).as("check causeNonAdherence").isEqualTo(actual.getCauseNonAdherence()))
            .satisfies(e -> assertThat(e.getStatutSocial()).as("check statutSocial").isEqualTo(actual.getStatutSocial()))
            .satisfies(e -> assertThat(e.getMarie()).as("check marie").isEqualTo(actual.getMarie()))
            .satisfies(e -> assertThat(e.getEnfants()).as("check enfants").isEqualTo(actual.getEnfants()))
            .satisfies(e -> assertThat(e.getActivitePhysique()).as("check activitePhysique").isEqualTo(actual.getActivitePhysique()))
            .satisfies(e ->
                assertThat(e.getTypeActivitePhysique()).as("check typeActivitePhysique").isEqualTo(actual.getTypeActivitePhysique())
            )
            .satisfies(e -> assertThat(e.getSequelles()).as("check sequelles").isEqualTo(actual.getSequelles()))
            .satisfies(e -> assertThat(e.getTypeSequelles()).as("check typeSequelles").isEqualTo(actual.getTypeSequelles()))
            .satisfies(e -> assertThat(e.getPatientDecede()).as("check patientDecede").isEqualTo(actual.getPatientDecede()))
            .satisfies(e -> assertThat(e.getDateDeces()).as("check dateDeces").isEqualTo(actual.getDateDeces()))
            .satisfies(e -> assertThat(e.getAgeDeces()).as("check ageDeces").isEqualTo(actual.getAgeDeces()))
            .satisfies(e -> assertThat(e.getCauseDeces()).as("check causeDeces").isEqualTo(actual.getCauseDeces()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurXVIIIUpdatableRelationshipsEquals(FicheFacteurXVIII expected, FicheFacteurXVIII actual) {
        // empty method
    }
}
