package tn.adhes.hemostase.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FicheFacteurVIIIAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurVIIIAllPropertiesEquals(FicheFacteurVIII expected, FicheFacteurVIII actual) {
        assertFicheFacteurVIIIAutoGeneratedPropertiesEquals(expected, actual);
        assertFicheFacteurVIIIAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurVIIIAllUpdatablePropertiesEquals(FicheFacteurVIII expected, FicheFacteurVIII actual) {
        assertFicheFacteurVIIIUpdatableFieldsEquals(expected, actual);
        assertFicheFacteurVIIIUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurVIIIAutoGeneratedPropertiesEquals(FicheFacteurVIII expected, FicheFacteurVIII actual) {
        assertThat(expected)
            .as("Verify FicheFacteurVIII auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurVIIIUpdatableFieldsEquals(FicheFacteurVIII expected, FicheFacteurVIII actual) {
        assertThat(expected)
            .as("Verify FicheFacteurVIII relevant properties")
            .satisfies(e -> assertThat(e.getDossierNumber()).as("check dossierNumber").isEqualTo(actual.getDossierNumber()))
            .satisfies(e -> assertThat(e.getOrdreNumber()).as("check ordreNumber").isEqualTo(actual.getOrdreNumber()))
            .satisfies(e -> assertThat(e.getIndexNumber()).as("check indexNumber").isEqualTo(actual.getIndexNumber()))
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getNomJeuneFille()).as("check nomJeuneFille").isEqualTo(actual.getNomJeuneFille()))
            .satisfies(e -> assertThat(e.getProfession()).as("check profession").isEqualTo(actual.getProfession()))
            .satisfies(e -> assertThat(e.getEtatCivil()).as("check etatCivil").isEqualTo(actual.getEtatCivil()))
            .satisfies(e -> assertThat(e.getServiceClinique()).as("check serviceClinique").isEqualTo(actual.getServiceClinique()))
            .satisfies(e ->
                assertThat(e.getAutreServiceClinique()).as("check autreServiceClinique").isEqualTo(actual.getAutreServiceClinique())
            )
            .satisfies(e -> assertThat(e.getCouvertureSociale()).as("check couvertureSociale").isEqualTo(actual.getCouvertureSociale()))
            .satisfies(e -> assertThat(e.getSexe()).as("check sexe").isEqualTo(actual.getSexe()))
            .satisfies(e -> assertThat(e.getDateNaissance()).as("check dateNaissance").isEqualTo(actual.getDateNaissance()))
            .satisfies(e -> assertThat(e.getAgeActuel()).as("check ageActuel").isEqualTo(actual.getAgeActuel()))
            .satisfies(e -> assertThat(e.getOrigine()).as("check origine").isEqualTo(actual.getOrigine()))
            .satisfies(e -> assertThat(e.getAutreOrigine()).as("check autreOrigine").isEqualTo(actual.getAutreOrigine()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getPrenomPere()).as("check prenomPere").isEqualTo(actual.getPrenomPere()))
            .satisfies(e -> assertThat(e.getProfessionPere()).as("check professionPere").isEqualTo(actual.getProfessionPere()))
            .satisfies(e -> assertThat(e.getNomPrenomMere()).as("check nomPrenomMere").isEqualTo(actual.getNomPrenomMere()))
            .satisfies(e -> assertThat(e.getProfessionMere()).as("check professionMere").isEqualTo(actual.getProfessionMere()))
            .satisfies(e -> assertThat(e.getMedecinTraitant()).as("check medecinTraitant").isEqualTo(actual.getMedecinTraitant()))
            .satisfies(e -> assertThat(e.getServiceOrigine()).as("check serviceOrigine").isEqualTo(actual.getServiceOrigine()))
            .satisfies(e ->
                assertThat(e.getBiologisteResponsableDg())
                    .as("check biologisteResponsableDg")
                    .isEqualTo(actual.getBiologisteResponsableDg())
            )
            .satisfies(e -> assertThat(e.getDiagnostic()).as("check diagnostic").isEqualTo(actual.getDiagnostic()))
            .satisfies(e -> assertThat(e.getAutreDiagnostic()).as("check autreDiagnostic").isEqualTo(actual.getAutreDiagnostic()))
            .satisfies(e -> assertThat(e.getAnneeDiagnostic()).as("check anneeDiagnostic").isEqualTo(actual.getAnneeDiagnostic()))
            .satisfies(e ->
                assertThat(e.getConsentementRegistre()).as("check consentementRegistre").isEqualTo(actual.getConsentementRegistre())
            )
            .satisfies(e ->
                assertThat(e.getDateEnregistrementRegistre())
                    .as("check dateEnregistrementRegistre")
                    .isEqualTo(actual.getDateEnregistrementRegistre())
            )
            .satisfies(e -> assertThat(e.getParentsConsanguins()).as("check parentsConsanguins").isEqualTo(actual.getParentsConsanguins()))
            .satisfies(e ->
                assertThat(e.getDegreParenteConsanguins())
                    .as("check degreParenteConsanguins")
                    .isEqualTo(actual.getDegreParenteConsanguins())
            )
            .satisfies(e -> assertThat(e.getCasSimilaires()).as("check casSimilaires").isEqualTo(actual.getCasSimilaires()))
            .satisfies(e -> assertThat(e.getNombreCas()).as("check nombreCas").isEqualTo(actual.getNombreCas()))
            .satisfies(e -> assertThat(e.getCas1Numero()).as("check cas1Numero").isEqualTo(actual.getCas1Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas1()).as("check lienParenteCas1").isEqualTo(actual.getLienParenteCas1()))
            .satisfies(e -> assertThat(e.getDegreParenteCas1()).as("check degreParenteCas1").isEqualTo(actual.getDegreParenteCas1()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas1()).as("check typeHemorragieCas1").isEqualTo(actual.getTypeHemorragieCas1()))
            .satisfies(e -> assertThat(e.getCas2Numero()).as("check cas2Numero").isEqualTo(actual.getCas2Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas2()).as("check lienParenteCas2").isEqualTo(actual.getLienParenteCas2()))
            .satisfies(e -> assertThat(e.getDegreParenteCas2()).as("check degreParenteCas2").isEqualTo(actual.getDegreParenteCas2()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas2()).as("check typeHemorragieCas2").isEqualTo(actual.getTypeHemorragieCas2()))
            .satisfies(e -> assertThat(e.getCas3Numero()).as("check cas3Numero").isEqualTo(actual.getCas3Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas3()).as("check lienParenteCas3").isEqualTo(actual.getLienParenteCas3()))
            .satisfies(e -> assertThat(e.getDegreParenteCas3()).as("check degreParenteCas3").isEqualTo(actual.getDegreParenteCas3()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas3()).as("check typeHemorragieCas3").isEqualTo(actual.getTypeHemorragieCas3()))
            .satisfies(e ->
                assertThat(e.getDecesSyndromeHemorragique())
                    .as("check decesSyndromeHemorragique")
                    .isEqualTo(actual.getDecesSyndromeHemorragique())
            )
            .satisfies(e -> assertThat(e.getNombreDeces()).as("check nombreDeces").isEqualTo(actual.getNombreDeces()))
            .satisfies(e -> assertThat(e.getDeces1Numero()).as("check deces1Numero").isEqualTo(actual.getDeces1Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces1()).as("check lienParenteDeces1").isEqualTo(actual.getLienParenteDeces1()))
            .satisfies(e -> assertThat(e.getCauseDeces1()).as("check causeDeces1").isEqualTo(actual.getCauseDeces1()))
            .satisfies(e -> assertThat(e.getDeces2Numero()).as("check deces2Numero").isEqualTo(actual.getDeces2Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces2()).as("check lienParenteDeces2").isEqualTo(actual.getLienParenteDeces2()))
            .satisfies(e -> assertThat(e.getCauseDeces2()).as("check causeDeces2").isEqualTo(actual.getCauseDeces2()))
            .satisfies(e -> assertThat(e.getDeces3Numero()).as("check deces3Numero").isEqualTo(actual.getDeces3Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces3()).as("check lienParenteDeces3").isEqualTo(actual.getLienParenteDeces3()))
            .satisfies(e -> assertThat(e.getCauseDeces3()).as("check causeDeces3").isEqualTo(actual.getCauseDeces3()))
            .satisfies(e -> assertThat(e.getEnqueteFamiliale()).as("check enqueteFamiliale").isEqualTo(actual.getEnqueteFamiliale()))
            .satisfies(e -> assertThat(e.getDecouverteFortuite()).as("check decouverteFortuite").isEqualTo(actual.getDecouverteFortuite()))
            .satisfies(e ->
                assertThat(e.getEnqueteFamilialeBool()).as("check enqueteFamilialeBool").isEqualTo(actual.getEnqueteFamilialeBool())
            )
            .satisfies(e ->
                assertThat(e.getExplorationSyndromeHemorragique())
                    .as("check explorationSyndromeHemorragique")
                    .isEqualTo(actual.getExplorationSyndromeHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getTypeExplorationSyndromeHemorragique())
                    .as("check typeExplorationSyndromeHemorragique")
                    .isEqualTo(actual.getTypeExplorationSyndromeHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getDatePremierSigneClinique())
                    .as("check datePremierSigneClinique")
                    .isEqualTo(actual.getDatePremierSigneClinique())
            )
            .satisfies(e -> assertThat(e.getAgeDiagnosticJour()).as("check ageDiagnosticJour").isEqualTo(actual.getAgeDiagnosticJour()))
            .satisfies(e -> assertThat(e.getAgeDiagnosticMois()).as("check ageDiagnosticMois").isEqualTo(actual.getAgeDiagnosticMois()))
            .satisfies(e -> assertThat(e.getAgeDiagnosticAnnee()).as("check ageDiagnosticAnnee").isEqualTo(actual.getAgeDiagnosticAnnee()))
            .satisfies(e -> assertThat(e.getTp()).as("check tp").isEqualTo(actual.getTp()))
            .satisfies(e -> assertThat(e.getTpMT()).as("check tpMT").isEqualTo(actual.getTpMT()))
            .satisfies(e -> assertThat(e.getTca()).as("check tca").isEqualTo(actual.getTca()))
            .satisfies(e -> assertThat(e.getTcaMT()).as("check tcaMT").isEqualTo(actual.getTcaMT()))
            .satisfies(e -> assertThat(e.getFibrinogene()).as("check fibrinogene").isEqualTo(actual.getFibrinogene()))
            .satisfies(e -> assertThat(e.getTs()).as("check ts").isEqualTo(actual.getTs()))
            .satisfies(e -> assertThat(e.getTsFait()).as("check tsFait").isEqualTo(actual.getTsFait()))
            .satisfies(e -> assertThat(e.getToPfa()).as("check toPfa").isEqualTo(actual.getToPfa()))
            .satisfies(e -> assertThat(e.getToPfa200ColEpi()).as("check toPfa200ColEpi").isEqualTo(actual.getToPfa200ColEpi()))
            .satisfies(e -> assertThat(e.getToPfa200ColAdp()).as("check toPfa200ColAdp").isEqualTo(actual.getToPfa200ColAdp()))
            .satisfies(e ->
                assertThat(e.getTauxDosageFacteurXIII()).as("check tauxDosageFacteurXIII").isEqualTo(actual.getTauxDosageFacteurXIII())
            )
            .satisfies(e -> assertThat(e.getHb()).as("check hb").isEqualTo(actual.getHb()))
            .satisfies(e -> assertThat(e.getHt()).as("check ht").isEqualTo(actual.getHt()))
            .satisfies(e -> assertThat(e.getPlaquettes()).as("check plaquettes").isEqualTo(actual.getPlaquettes()))
            .satisfies(e ->
                assertThat(e.getTechniqueChromogenique()).as("check techniqueChromogenique").isEqualTo(actual.getTechniqueChromogenique())
            )
            .satisfies(e ->
                assertThat(e.getTauxTechniqueChromogenique())
                    .as("check tauxTechniqueChromogenique")
                    .isEqualTo(actual.getTauxTechniqueChromogenique())
            )
            .satisfies(e ->
                assertThat(e.getTechniqueSolubiliteCaillot())
                    .as("check techniqueSolubiliteCaillot")
                    .isEqualTo(actual.getTechniqueSolubiliteCaillot())
            )
            .satisfies(e ->
                assertThat(e.getTauxTechniqueSolubiliteCaillot())
                    .as("check tauxTechniqueSolubiliteCaillot")
                    .isEqualTo(actual.getTauxTechniqueSolubiliteCaillot())
            )
            .satisfies(e ->
                assertThat(e.getConfirmationMoleculaire())
                    .as("check confirmationMoleculaire")
                    .isEqualTo(actual.getConfirmationMoleculaire())
            )
            .satisfies(e -> assertThat(e.getMutationPresence()).as("check mutationPresence").isEqualTo(actual.getMutationPresence()))
            .satisfies(e -> assertThat(e.getMutationType()).as("check mutationType").isEqualTo(actual.getMutationType()))
            .satisfies(e -> assertThat(e.getEpistaxis()).as("check epistaxis").isEqualTo(actual.getEpistaxis()))
            .satisfies(e -> assertThat(e.getFrequenceEpistaxis()).as("check frequenceEpistaxis").isEqualTo(actual.getFrequenceEpistaxis()))
            .satisfies(e -> assertThat(e.getGingivorragies()).as("check gingivorragies").isEqualTo(actual.getGingivorragies()))
            .satisfies(e -> assertThat(e.getTypeGingivorragies()).as("check typeGingivorragies").isEqualTo(actual.getTypeGingivorragies()))
            .satisfies(e ->
                assertThat(e.getFrequenceGingivorragies())
                    .as("check frequenceGingivorragies")
                    .isEqualTo(actual.getFrequenceGingivorragies())
            )
            .satisfies(e -> assertThat(e.getEcchymose()).as("check ecchymose").isEqualTo(actual.getEcchymose()))
            .satisfies(e -> assertThat(e.getTypeEcchymose()).as("check typeEcchymose").isEqualTo(actual.getTypeEcchymose()))
            .satisfies(e -> assertThat(e.getFrequenceEcchymose()).as("check frequenceEcchymose").isEqualTo(actual.getFrequenceEcchymose()))
            .satisfies(e -> assertThat(e.getMenorragie()).as("check menorragie").isEqualTo(actual.getMenorragie()))
            .satisfies(e ->
                assertThat(e.getFrequenceMenorragie()).as("check frequenceMenorragie").isEqualTo(actual.getFrequenceMenorragie())
            )
            .satisfies(e -> assertThat(e.getHematemese()).as("check hematemese").isEqualTo(actual.getHematemese()))
            .satisfies(e ->
                assertThat(e.getFrequenceHematemese()).as("check frequenceHematemese").isEqualTo(actual.getFrequenceHematemese())
            )
            .satisfies(e -> assertThat(e.getRectorragie()).as("check rectorragie").isEqualTo(actual.getRectorragie()))
            .satisfies(e ->
                assertThat(e.getFrequenceRectorragie()).as("check frequenceRectorragie").isEqualTo(actual.getFrequenceRectorragie())
            )
            .satisfies(e -> assertThat(e.getHematurie()).as("check hematurie").isEqualTo(actual.getHematurie()))
            .satisfies(e -> assertThat(e.getFrequenceHematurie()).as("check frequenceHematurie").isEqualTo(actual.getFrequenceHematurie()))
            .satisfies(e -> assertThat(e.getHematomeSousCutane()).as("check hematomeSousCutane").isEqualTo(actual.getHematomeSousCutane()))
            .satisfies(e ->
                assertThat(e.getTypeHematomeSousCutane()).as("check typeHematomeSousCutane").isEqualTo(actual.getTypeHematomeSousCutane())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceHematomeSousCutane())
                    .as("check frequenceHematomeSousCutane")
                    .isEqualTo(actual.getFrequenceHematomeSousCutane())
            )
            .satisfies(e -> assertThat(e.getHematomeMusculaire()).as("check hematomeMusculaire").isEqualTo(actual.getHematomeMusculaire()))
            .satisfies(e ->
                assertThat(e.getSiegeHematomeMusculaire())
                    .as("check siegeHematomeMusculaire")
                    .isEqualTo(actual.getSiegeHematomeMusculaire())
            )
            .satisfies(e ->
                assertThat(e.getTypeHematomeMusculaire()).as("check typeHematomeMusculaire").isEqualTo(actual.getTypeHematomeMusculaire())
            )
            .satisfies(e ->
                assertThat(e.getFrequenceHematomeMusculaire())
                    .as("check frequenceHematomeMusculaire")
                    .isEqualTo(actual.getFrequenceHematomeMusculaire())
            )
            .satisfies(e -> assertThat(e.getHemarthrose()).as("check hemarthrose").isEqualTo(actual.getHemarthrose()))
            .satisfies(e -> assertThat(e.getTypeHemarthrose()).as("check typeHemarthrose").isEqualTo(actual.getTypeHemarthrose()))
            .satisfies(e ->
                assertThat(e.getFrequenceHemarthrose()).as("check frequenceHemarthrose").isEqualTo(actual.getFrequenceHemarthrose())
            )
            .satisfies(e -> assertThat(e.getSaignementSNC()).as("check saignementSNC").isEqualTo(actual.getSaignementSNC()))
            .satisfies(e -> assertThat(e.getTypeSaignementSNC()).as("check typeSaignementSNC").isEqualTo(actual.getTypeSaignementSNC()))
            .satisfies(e ->
                assertThat(e.getFrequenceSaignementSNC()).as("check frequenceSaignementSNC").isEqualTo(actual.getFrequenceSaignementSNC())
            )
            .satisfies(e ->
                assertThat(e.getRuptureKystesHemorragiques())
                    .as("check ruptureKystesHemorragiques")
                    .isEqualTo(actual.getRuptureKystesHemorragiques())
            )
            .satisfies(e ->
                assertThat(e.getHemorragiesPostChirurgicales())
                    .as("check hemorragiesPostChirurgicales")
                    .isEqualTo(actual.getHemorragiesPostChirurgicales())
            )
            .satisfies(e -> assertThat(e.getHemoperitone()).as("check hemoperitone").isEqualTo(actual.getHemoperitone()))
            .satisfies(e ->
                assertThat(e.getAccidentsThrombotiques()).as("check accidentsThrombotiques").isEqualTo(actual.getAccidentsThrombotiques())
            )
            .satisfies(e ->
                assertThat(e.getTypeAccidentsThrombotiques())
                    .as("check typeAccidentsThrombotiques")
                    .isEqualTo(actual.getTypeAccidentsThrombotiques())
            )
            .satisfies(e -> assertThat(e.getHemorragieGrave()).as("check hemorragieGrave").isEqualTo(actual.getHemorragieGrave()))
            .satisfies(e ->
                assertThat(e.getTypeHemorragieGrave()).as("check typeHemorragieGrave").isEqualTo(actual.getTypeHemorragieGrave())
            )
            .satisfies(e -> assertThat(e.getChirurgiePrepare()).as("check chirurgiePrepare").isEqualTo(actual.getChirurgiePrepare()))
            .satisfies(e ->
                assertThat(e.getSuiteOperatoireHemorragique())
                    .as("check suiteOperatoireHemorragique")
                    .isEqualTo(actual.getSuiteOperatoireHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getCirconcisionPrepare()).as("check circoncisionPrepare").isEqualTo(actual.getCirconcisionPrepare())
            )
            .satisfies(e ->
                assertThat(e.getSuiteOperatoireCirconcision())
                    .as("check suiteOperatoireCirconcision")
                    .isEqualTo(actual.getSuiteOperatoireCirconcision())
            )
            .satisfies(e -> assertThat(e.getAgeCirconcision()).as("check ageCirconcision").isEqualTo(actual.getAgeCirconcision()))
            .satisfies(e ->
                assertThat(e.getFacteurVIIIRecombinant()).as("check facteurVIIIRecombinant").isEqualTo(actual.getFacteurVIIIRecombinant())
            )
            .satisfies(e -> assertThat(e.getPlasmaFraisCongele()).as("check plasmaFraisCongele").isEqualTo(actual.getPlasmaFraisCongele()))
            .satisfies(e -> assertThat(e.getCryoprecipite()).as("check cryoprecipite").isEqualTo(actual.getCryoprecipite()))
            .satisfies(e ->
                assertThat(e.getCulotsPlaquettaires()).as("check culotsPlaquettaires").isEqualTo(actual.getCulotsPlaquettaires())
            )
            .satisfies(e -> assertThat(e.getDicynone()).as("check dicynone").isEqualTo(actual.getDicynone()))
            .satisfies(e -> assertThat(e.getExacyl()).as("check exacyl").isEqualTo(actual.getExacyl()))
            .satisfies(e -> assertThat(e.getTraitementMartial()).as("check traitementMartial").isEqualTo(actual.getTraitementMartial()))
            .satisfies(e ->
                assertThat(e.getTraitementOestroprogestatif())
                    .as("check traitementOestroprogestatif")
                    .isEqualTo(actual.getTraitementOestroprogestatif())
            )
            .satisfies(e -> assertThat(e.getTransfusionCGR()).as("check transfusionCGR").isEqualTo(actual.getTransfusionCGR()))
            .satisfies(e -> assertThat(e.getInhibiteurs()).as("check inhibiteurs").isEqualTo(actual.getInhibiteurs()))
            .satisfies(e ->
                assertThat(e.getInhibiteurNeutralisant()).as("check inhibiteurNeutralisant").isEqualTo(actual.getInhibiteurNeutralisant())
            )
            .satisfies(e -> assertThat(e.getTitreUB()).as("check titreUB").isEqualTo(actual.getTitreUB()))
            .satisfies(e ->
                assertThat(e.getInhibiteurNonNeutralisant())
                    .as("check inhibiteurNonNeutralisant")
                    .isEqualTo(actual.getInhibiteurNonNeutralisant())
            )
            .satisfies(e -> assertThat(e.getInfectionsVirales()).as("check infectionsVirales").isEqualTo(actual.getInfectionsVirales()))
            .satisfies(e -> assertThat(e.getThrombose()).as("check thrombose").isEqualTo(actual.getThrombose()))
            .satisfies(e -> assertThat(e.getReactionAllergique()).as("check reactionAllergique").isEqualTo(actual.getReactionAllergique()))
            .satisfies(e -> assertThat(e.getAlloImmunisation()).as("check alloImmunisation").isEqualTo(actual.getAlloImmunisation()))
            .satisfies(e ->
                assertThat(e.getAdhesionTherapeutique()).as("check adhesionTherapeutique").isEqualTo(actual.getAdhesionTherapeutique())
            )
            .satisfies(e -> assertThat(e.getCauseNonAdhesion()).as("check causeNonAdhesion").isEqualTo(actual.getCauseNonAdhesion()))
            .satisfies(e -> assertThat(e.getVieSociale()).as("check vieSociale").isEqualTo(actual.getVieSociale()))
            .satisfies(e -> assertThat(e.getMariage()).as("check mariage").isEqualTo(actual.getMariage()))
            .satisfies(e -> assertThat(e.getEnfants()).as("check enfants").isEqualTo(actual.getEnfants()))
            .satisfies(e -> assertThat(e.getActivitePhysique()).as("check activitePhysique").isEqualTo(actual.getActivitePhysique()))
            .satisfies(e ->
                assertThat(e.getTypeActivitePhysique()).as("check typeActivitePhysique").isEqualTo(actual.getTypeActivitePhysique())
            )
            .satisfies(e -> assertThat(e.getSequelles()).as("check sequelles").isEqualTo(actual.getSequelles()))
            .satisfies(e -> assertThat(e.getTypeSequelles()).as("check typeSequelles").isEqualTo(actual.getTypeSequelles()))
            .satisfies(e -> assertThat(e.getPatientDecede()).as("check patientDecede").isEqualTo(actual.getPatientDecede()))
            .satisfies(e -> assertThat(e.getDateDeces()).as("check dateDeces").isEqualTo(actual.getDateDeces()))
            .satisfies(e -> assertThat(e.getAgeDeces()).as("check ageDeces").isEqualTo(actual.getAgeDeces()))
            .satisfies(e -> assertThat(e.getHemorragieSnc()).as("check hemorragieSnc").isEqualTo(actual.getHemorragieSnc()))
            .satisfies(e ->
                assertThat(e.getHemorragieAutreQueSnc()).as("check hemorragieAutreQueSnc").isEqualTo(actual.getHemorragieAutreQueSnc())
            )
            .satisfies(e -> assertThat(e.getHiv()).as("check hiv").isEqualTo(actual.getHiv()))
            .satisfies(e -> assertThat(e.getAutreInfection()).as("check autreInfection").isEqualTo(actual.getAutreInfection()))
            .satisfies(e ->
                assertThat(e.getEvenementThromboembolique())
                    .as("check evenementThromboembolique")
                    .isEqualTo(actual.getEvenementThromboembolique())
            )
            .satisfies(e -> assertThat(e.getCancer()).as("check cancer").isEqualTo(actual.getCancer()))
            .satisfies(e -> assertThat(e.getCovid19()).as("check covid19").isEqualTo(actual.getCovid19()))
            .satisfies(e -> assertThat(e.getInconnue()).as("check inconnue").isEqualTo(actual.getInconnue()))
            .satisfies(e -> assertThat(e.getAutreEvenement()).as("check autreEvenement").isEqualTo(actual.getAutreEvenement()))
            .satisfies(e ->
                assertThat(e.getAutreEvenementDetails()).as("check autreEvenementDetails").isEqualTo(actual.getAutreEvenementDetails())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheFacteurVIIIUpdatableRelationshipsEquals(FicheFacteurVIII expected, FicheFacteurVIII actual) {
        // empty method
    }
}
