package tn.adhes.hemostase.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FicheThrombopathieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheThrombopathieAllPropertiesEquals(FicheThrombopathie expected, FicheThrombopathie actual) {
        assertFicheThrombopathieAutoGeneratedPropertiesEquals(expected, actual);
        assertFicheThrombopathieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheThrombopathieAllUpdatablePropertiesEquals(FicheThrombopathie expected, FicheThrombopathie actual) {
        assertFicheThrombopathieUpdatableFieldsEquals(expected, actual);
        assertFicheThrombopathieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheThrombopathieAutoGeneratedPropertiesEquals(FicheThrombopathie expected, FicheThrombopathie actual) {
        assertThat(expected)
            .as("Verify FicheThrombopathie auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheThrombopathieUpdatableFieldsEquals(FicheThrombopathie expected, FicheThrombopathie actual) {
        assertThat(expected)
            .as("Verify FicheThrombopathie relevant properties")
            .satisfies(e -> assertThat(e.getDossierNumber()).as("check dossierNumber").isEqualTo(actual.getDossierNumber()))
            .satisfies(e -> assertThat(e.getOrdreNumber()).as("check ordreNumber").isEqualTo(actual.getOrdreNumber()))
            .satisfies(e -> assertThat(e.getIndexNumber()).as("check indexNumber").isEqualTo(actual.getIndexNumber()))
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getNomJeuneFille()).as("check nomJeuneFille").isEqualTo(actual.getNomJeuneFille()))
            .satisfies(e -> assertThat(e.getProfession()).as("check profession").isEqualTo(actual.getProfession()))
            .satisfies(e -> assertThat(e.getEtatCivil()).as("check etatCivil").isEqualTo(actual.getEtatCivil()))
            .satisfies(e -> assertThat(e.getServiceClinique()).as("check serviceClinique").isEqualTo(actual.getServiceClinique()))
            .satisfies(e ->
                assertThat(e.getAutreServiceClinique()).as("check autreServiceClinique").isEqualTo(actual.getAutreServiceClinique())
            )
            .satisfies(e -> assertThat(e.getCouvertureSociale()).as("check couvertureSociale").isEqualTo(actual.getCouvertureSociale()))
            .satisfies(e -> assertThat(e.getSexe()).as("check sexe").isEqualTo(actual.getSexe()))
            .satisfies(e -> assertThat(e.getDateNaissance()).as("check dateNaissance").isEqualTo(actual.getDateNaissance()))
            .satisfies(e -> assertThat(e.getAgeActuel()).as("check ageActuel").isEqualTo(actual.getAgeActuel()))
            .satisfies(e -> assertThat(e.getOrigine()).as("check origine").isEqualTo(actual.getOrigine()))
            .satisfies(e -> assertThat(e.getAutreOrigine()).as("check autreOrigine").isEqualTo(actual.getAutreOrigine()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getPrenomPere()).as("check prenomPere").isEqualTo(actual.getPrenomPere()))
            .satisfies(e -> assertThat(e.getProfessionPere()).as("check professionPere").isEqualTo(actual.getProfessionPere()))
            .satisfies(e -> assertThat(e.getNomPrenomMere()).as("check nomPrenomMere").isEqualTo(actual.getNomPrenomMere()))
            .satisfies(e -> assertThat(e.getProfessionMere()).as("check professionMere").isEqualTo(actual.getProfessionMere()))
            .satisfies(e -> assertThat(e.getMedecinTraitant()).as("check medecinTraitant").isEqualTo(actual.getMedecinTraitant()))
            .satisfies(e -> assertThat(e.getServiceOrigine()).as("check serviceOrigine").isEqualTo(actual.getServiceOrigine()))
            .satisfies(e ->
                assertThat(e.getBiologisteResponsableDg())
                    .as("check biologisteResponsableDg")
                    .isEqualTo(actual.getBiologisteResponsableDg())
            )
            .satisfies(e -> assertThat(e.getDiagnostic()).as("check diagnostic").isEqualTo(actual.getDiagnostic()))
            .satisfies(e -> assertThat(e.getAutreDiagnostic()).as("check autreDiagnostic").isEqualTo(actual.getAutreDiagnostic()))
            .satisfies(e -> assertThat(e.getAnneeDiagnostic()).as("check anneeDiagnostic").isEqualTo(actual.getAnneeDiagnostic()))
            .satisfies(e ->
                assertThat(e.getConsentementRegistre()).as("check consentementRegistre").isEqualTo(actual.getConsentementRegistre())
            )
            .satisfies(e ->
                assertThat(e.getDateEnregistrementRegistre())
                    .as("check dateEnregistrementRegistre")
                    .isEqualTo(actual.getDateEnregistrementRegistre())
            )
            .satisfies(e -> assertThat(e.getParentsConsanguins()).as("check parentsConsanguins").isEqualTo(actual.getParentsConsanguins()))
            .satisfies(e ->
                assertThat(e.getDegreParenteConsanguins())
                    .as("check degreParenteConsanguins")
                    .isEqualTo(actual.getDegreParenteConsanguins())
            )
            .satisfies(e -> assertThat(e.getCasSimilaires()).as("check casSimilaires").isEqualTo(actual.getCasSimilaires()))
            .satisfies(e -> assertThat(e.getNombreCas()).as("check nombreCas").isEqualTo(actual.getNombreCas()))
            .satisfies(e ->
                assertThat(e.getDegreParenteCasSimilaires())
                    .as("check degreParenteCasSimilaires")
                    .isEqualTo(actual.getDegreParenteCasSimilaires())
            )
            .satisfies(e ->
                assertThat(e.getDecesSyndromeHemorragique())
                    .as("check decesSyndromeHemorragique")
                    .isEqualTo(actual.getDecesSyndromeHemorragique())
            )
            .satisfies(e -> assertThat(e.getNombreDeces()).as("check nombreDeces").isEqualTo(actual.getNombreDeces()))
            .satisfies(e -> assertThat(e.getTypeHemorragie()).as("check typeHemorragie").isEqualTo(actual.getTypeHemorragie()))
            .satisfies(e -> assertThat(e.getLienParenteDeces()).as("check lienParenteDeces").isEqualTo(actual.getLienParenteDeces()))
            .satisfies(e -> assertThat(e.getEnqueteFamiliale()).as("check enqueteFamiliale").isEqualTo(actual.getEnqueteFamiliale()))
            .satisfies(e ->
                assertThat(e.getAntecedentsMedicaux()).as("check antecedentsMedicaux").isEqualTo(actual.getAntecedentsMedicaux())
            )
            .satisfies(e ->
                assertThat(e.getAntecedentsChirurgicaux())
                    .as("check antecedentsChirurgicaux")
                    .isEqualTo(actual.getAntecedentsChirurgicaux())
            )
            .satisfies(e -> assertThat(e.getTypeChirurgie()).as("check typeChirurgie").isEqualTo(actual.getTypeChirurgie()))
            .satisfies(e ->
                assertThat(e.getComplicationHemorragique())
                    .as("check complicationHemorragique")
                    .isEqualTo(actual.getComplicationHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getAgePremierSigneHemorragique())
                    .as("check agePremierSigneHemorragique")
                    .isEqualTo(actual.getAgePremierSigneHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getTypeSyndromeHemorragique())
                    .as("check typeSyndromeHemorragique")
                    .isEqualTo(actual.getTypeSyndromeHemorragique())
            )
            .satisfies(e -> assertThat(e.getAgeDiagnostic()).as("check ageDiagnostic").isEqualTo(actual.getAgeDiagnostic()))
            .satisfies(e -> assertThat(e.getDecouverteFortuite()).as("check decouverteFortuite").isEqualTo(actual.getDecouverteFortuite()))
            .satisfies(e ->
                assertThat(e.getEnqueteFamilialeBool()).as("check enqueteFamilialeBool").isEqualTo(actual.getEnqueteFamilialeBool())
            )
            .satisfies(e ->
                assertThat(e.getExplorationSyndromeHemorragique())
                    .as("check explorationSyndromeHemorragique")
                    .isEqualTo(actual.getExplorationSyndromeHemorragique())
            )
            .satisfies(e ->
                assertThat(e.getTypeCirconstanceDiagnostic())
                    .as("check typeCirconstanceDiagnostic")
                    .isEqualTo(actual.getTypeCirconstanceDiagnostic())
            )
            .satisfies(e -> assertThat(e.getEczema()).as("check eczema").isEqualTo(actual.getEczema()))
            .satisfies(e ->
                assertThat(e.getSyndromeDysmorphique()).as("check syndromeDysmorphique").isEqualTo(actual.getSyndromeDysmorphique())
            )
            .satisfies(e -> assertThat(e.getAlbinisme()).as("check albinisme").isEqualTo(actual.getAlbinisme()))
            .satisfies(e -> assertThat(e.getArthrogrypose()).as("check arthrogrypose").isEqualTo(actual.getArthrogrypose()))
            .satisfies(e -> assertThat(e.getGb()).as("check gb").isEqualTo(actual.getGb()))
            .satisfies(e -> assertThat(e.getHb()).as("check hb").isEqualTo(actual.getHb()))
            .satisfies(e -> assertThat(e.getVgm()).as("check vgm").isEqualTo(actual.getVgm()))
            .satisfies(e -> assertThat(e.getTcmh()).as("check tcmh").isEqualTo(actual.getTcmh()))
            .satisfies(e -> assertThat(e.getPlaquettes()).as("check plaquettes").isEqualTo(actual.getPlaquettes()))
            .satisfies(e -> assertThat(e.getFrottisSanguin()).as("check frottisSanguin").isEqualTo(actual.getFrottisSanguin()))
            .satisfies(e -> assertThat(e.getTs()).as("check ts").isEqualTo(actual.getTs()))
            .satisfies(e -> assertThat(e.getToPfa()).as("check toPfa").isEqualTo(actual.getToPfa()))
            .satisfies(e -> assertThat(e.getToPfa100ColEpi()).as("check toPfa100ColEpi").isEqualTo(actual.getToPfa100ColEpi()))
            .satisfies(e -> assertThat(e.getToPfa100ColAdp()).as("check toPfa100ColAdp").isEqualTo(actual.getToPfa100ColAdp()))
            .satisfies(e -> assertThat(e.getTp()).as("check tp").isEqualTo(actual.getTp()))
            .satisfies(e -> assertThat(e.getTca()).as("check tca").isEqualTo(actual.getTca()))
            .satisfies(e ->
                assertThat(e.getAggregometriePlaquettaire())
                    .as("check aggregometriePlaquettaire")
                    .isEqualTo(actual.getAggregometriePlaquettaire())
            )
            .satisfies(e ->
                assertThat(e.getResultatAgregometrie()).as("check resultatAgregometrie").isEqualTo(actual.getResultatAgregometrie())
            )
            .satisfies(e -> assertThat(e.getCmf()).as("check cmf").isEqualTo(actual.getCmf()))
            .satisfies(e -> assertThat(e.getResultatCmf()).as("check resultatCmf").isEqualTo(actual.getResultatCmf()))
            .satisfies(e -> assertThat(e.getDosageFvwAg()).as("check dosageFvwAg").isEqualTo(actual.getDosageFvwAg()))
            .satisfies(e -> assertThat(e.getDosageFvwRco()).as("check dosageFvwRco").isEqualTo(actual.getDosageFvwRco()))
            .satisfies(e -> assertThat(e.getEtudeGenetique()).as("check etudeGenetique").isEqualTo(actual.getEtudeGenetique()))
            .satisfies(e ->
                assertThat(e.getResultatEtudeGenetique()).as("check resultatEtudeGenetique").isEqualTo(actual.getResultatEtudeGenetique())
            )
            .satisfies(e ->
                assertThat(e.getThrombasthenieGlanzmann())
                    .as("check thrombasthenieGlanzmann")
                    .isEqualTo(actual.getThrombasthenieGlanzmann())
            )
            .satisfies(e ->
                assertThat(e.getMaladieBernardSoulier()).as("check maladieBernardSoulier").isEqualTo(actual.getMaladieBernardSoulier())
            )
            .satisfies(e -> assertThat(e.getAutreThrombopathie()).as("check autreThrombopathie").isEqualTo(actual.getAutreThrombopathie()))
            .satisfies(e ->
                assertThat(e.getAutreThrombopathieDetails())
                    .as("check autreThrombopathieDetails")
                    .isEqualTo(actual.getAutreThrombopathieDetails())
            )
            .satisfies(e -> assertThat(e.getEcchymose()).as("check ecchymose").isEqualTo(actual.getEcchymose()))
            .satisfies(e -> assertThat(e.getTypeEcchymose()).as("check typeEcchymose").isEqualTo(actual.getTypeEcchymose()))
            .satisfies(e -> assertThat(e.getGingivorragies()).as("check gingivorragies").isEqualTo(actual.getGingivorragies()))
            .satisfies(e -> assertThat(e.getTypeGingivorragies()).as("check typeGingivorragies").isEqualTo(actual.getTypeGingivorragies()))
            .satisfies(e -> assertThat(e.getEpistaxis()).as("check epistaxis").isEqualTo(actual.getEpistaxis()))
            .satisfies(e -> assertThat(e.getTypeEpistaxis()).as("check typeEpistaxis").isEqualTo(actual.getTypeEpistaxis()))
            .satisfies(e -> assertThat(e.getHematome()).as("check hematome").isEqualTo(actual.getHematome()))
            .satisfies(e -> assertThat(e.getTypeHematome()).as("check typeHematome").isEqualTo(actual.getTypeHematome()))
            .satisfies(e -> assertThat(e.getSiegelHematome()).as("check siegelHematome").isEqualTo(actual.getSiegelHematome()))
            .satisfies(e -> assertThat(e.getMenoMetrorragies()).as("check menoMetrorragies").isEqualTo(actual.getMenoMetrorragies()))
            .satisfies(e ->
                assertThat(e.getFrequenceMenoMetrorragies())
                    .as("check frequenceMenoMetrorragies")
                    .isEqualTo(actual.getFrequenceMenoMetrorragies())
            )
            .satisfies(e ->
                assertThat(e.getSeveriteMenoMetrorragies())
                    .as("check severiteMenoMetrorragies")
                    .isEqualTo(actual.getSeveriteMenoMetrorragies())
            )
            .satisfies(e ->
                assertThat(e.getExplorationMenoMetrorragies())
                    .as("check explorationMenoMetrorragies")
                    .isEqualTo(actual.getExplorationMenoMetrorragies())
            )
            .satisfies(e ->
                assertThat(e.getTypeLesionSousJacente()).as("check typeLesionSousJacente").isEqualTo(actual.getTypeLesionSousJacente())
            )
            .satisfies(e -> assertThat(e.getHemorragieVisceres()).as("check hemorragieVisceres").isEqualTo(actual.getHemorragieVisceres()))
            .satisfies(e ->
                assertThat(e.getHemorragieDigestiveHaute())
                    .as("check hemorragieDigestiveHaute")
                    .isEqualTo(actual.getHemorragieDigestiveHaute())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieDigestiveBasse())
                    .as("check hemorragieDigestiveBasse")
                    .isEqualTo(actual.getHemorragieDigestiveBasse())
            )
            .satisfies(e -> assertThat(e.getHematurie()).as("check hematurie").isEqualTo(actual.getHematurie()))
            .satisfies(e ->
                assertThat(e.getExplorationHemorragieVisceres())
                    .as("check explorationHemorragieVisceres")
                    .isEqualTo(actual.getExplorationHemorragieVisceres())
            )
            .satisfies(e ->
                assertThat(e.getLesionSousJacenteVisceres())
                    .as("check lesionSousJacenteVisceres")
                    .isEqualTo(actual.getLesionSousJacenteVisceres())
            )
            .satisfies(e ->
                assertThat(e.getInterventionChirurgicale())
                    .as("check interventionChirurgicale")
                    .isEqualTo(actual.getInterventionChirurgicale())
            )
            .satisfies(e ->
                assertThat(e.getTypeInterventionChirurgicale())
                    .as("check typeInterventionChirurgicale")
                    .isEqualTo(actual.getTypeInterventionChirurgicale())
            )
            .satisfies(e ->
                assertThat(e.getHematomesCerebrales()).as("check hematomesCerebrales").isEqualTo(actual.getHematomesCerebrales())
            )
            .satisfies(e -> assertThat(e.getEdcHemorragique()).as("check edcHemorragique").isEqualTo(actual.getEdcHemorragique()))
            .satisfies(e -> assertThat(e.getTransfusionCps()).as("check transfusionCps").isEqualTo(actual.getTransfusionCps()))
            .satisfies(e ->
                assertThat(e.getFacteurVIIRecombinant()).as("check facteurVIIRecombinant").isEqualTo(actual.getFacteurVIIRecombinant())
            )
            .satisfies(e -> assertThat(e.getDicynone()).as("check dicynone").isEqualTo(actual.getDicynone()))
            .satisfies(e -> assertThat(e.getExacyl()).as("check exacyl").isEqualTo(actual.getExacyl()))
            .satisfies(e ->
                assertThat(e.getTraitementOestroprogestatif())
                    .as("check traitementOestroprogestatif")
                    .isEqualTo(actual.getTraitementOestroprogestatif())
            )
            .satisfies(e -> assertThat(e.getMechage()).as("check mechage").isEqualTo(actual.getMechage()))
            .satisfies(e -> assertThat(e.getTransfusionCgr()).as("check transfusionCgr").isEqualTo(actual.getTransfusionCgr()))
            .satisfies(e -> assertThat(e.getTraitementMartial()).as("check traitementMartial").isEqualTo(actual.getTraitementMartial()))
            .satisfies(e -> assertThat(e.getThrombose()).as("check thrombose").isEqualTo(actual.getThrombose()))
            .satisfies(e ->
                assertThat(e.getAlloImmunisationHLA()).as("check alloImmunisationHLA").isEqualTo(actual.getAlloImmunisationHLA())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheThrombopathieUpdatableRelationshipsEquals(FicheThrombopathie expected, FicheThrombopathie actual) {
        // empty method
    }
}
