package tn.adhes.hemostase.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class FicheHemophilieTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));
    private static final AtomicInteger intCount = new AtomicInteger(random.nextInt() + (2 * Short.MAX_VALUE));

    public static FicheHemophilie getFicheHemophilieSample1() {
        return new FicheHemophilie()
            .id(1L)
            .dossierNumber("dossierNumber1")
            .ordreNumber("ordreNumber1")
            .indexNumber("indexNumber1")
            .prenom("prenom1")
            .nom("nom1")
            .nomJeuneFille("nomJeuneFille1")
            .profession("profession1")
            .autreServiceClinique("autreServiceClinique1")
            .ageActuel(1)
            .autreOrigine("autreOrigine1")
            .adresse("adresse1")
            .telephone("telephone1")
            .prenomPere("prenomPere1")
            .professionPere("professionPere1")
            .nomPrenomMere("nomPrenomMere1")
            .professionMere("professionMere1")
            .medecinTraitant("medecinTraitant1")
            .serviceOrigine("serviceOrigine1")
            .biologisteResponsableDg("biologisteResponsableDg1")
            .autreDiagnostic("autreDiagnostic1")
            .anneeDiagnostic(1)
            .degreParenteConsanguins("degreParenteConsanguins1")
            .nombreCas(1)
            .nombreDeces(1)
            .fratrieNbFreres(1)
            .fratrieNbSoeurs(1)
            .ageDiagnosticJours(1)
            .ageDiagnosticMois(1)
            .ageDiagnosticAnnees(1)
            .plaquettes(1)
            .autreExplorationMoleculaire("autreExplorationMoleculaire1")
            .hemarthroseSiege("hemarthroseSiege1")
            .hemarthroseFrequenceAn(1)
            .hematomeSuperficielSiege("hematomeSuperficielSiege1")
            .hemorragiesCutaneoMuqueusesFrequenceAn(1)
            .hemorragieVisceresExamen("hemorragieVisceresExamen1")
            .circoncisionAge(1)
            .interventionChirurgicaleType("interventionChirurgicaleType1")
            .causePriseEnCharge("causePriseEnCharge1")
            .prophylaxieDoseFrequence("prophylaxieDoseFrequence1")
            .typeTraitementSubstitutif("typeTraitementSubstitutif1")
            .agePremiereSubstitution(1)
            .posologieITI("posologieITI1")
            .dureeITI("dureeITI1")
            .causeNonObservance("causeNonObservance1")
            .efficaciteHemlibra(1)
            .chargeViraleVHC("chargeViraleVHC1")
            .typeHandicap("typeHandicap1")
            .typeActiviteSportive("typeActiviteSportive1")
            .causeDeces("causeDeces1");
    }

    public static FicheHemophilie getFicheHemophilieSample2() {
        return new FicheHemophilie()
            .id(2L)
            .dossierNumber("dossierNumber2")
            .ordreNumber("ordreNumber2")
            .indexNumber("indexNumber2")
            .prenom("prenom2")
            .nom("nom2")
            .nomJeuneFille("nomJeuneFille2")
            .profession("profession2")
            .autreServiceClinique("autreServiceClinique2")
            .ageActuel(2)
            .autreOrigine("autreOrigine2")
            .adresse("adresse2")
            .telephone("telephone2")
            .prenomPere("prenomPere2")
            .professionPere("professionPere2")
            .nomPrenomMere("nomPrenomMere2")
            .professionMere("professionMere2")
            .medecinTraitant("medecinTraitant2")
            .serviceOrigine("serviceOrigine2")
            .biologisteResponsableDg("biologisteResponsableDg2")
            .autreDiagnostic("autreDiagnostic2")
            .anneeDiagnostic(2)
            .degreParenteConsanguins("degreParenteConsanguins2")
            .nombreCas(2)
            .nombreDeces(2)
            .fratrieNbFreres(2)
            .fratrieNbSoeurs(2)
            .ageDiagnosticJours(2)
            .ageDiagnosticMois(2)
            .ageDiagnosticAnnees(2)
            .plaquettes(2)
            .autreExplorationMoleculaire("autreExplorationMoleculaire2")
            .hemarthroseSiege("hemarthroseSiege2")
            .hemarthroseFrequenceAn(2)
            .hematomeSuperficielSiege("hematomeSuperficielSiege2")
            .hemorragiesCutaneoMuqueusesFrequenceAn(2)
            .hemorragieVisceresExamen("hemorragieVisceresExamen2")
            .circoncisionAge(2)
            .interventionChirurgicaleType("interventionChirurgicaleType2")
            .causePriseEnCharge("causePriseEnCharge2")
            .prophylaxieDoseFrequence("prophylaxieDoseFrequence2")
            .typeTraitementSubstitutif("typeTraitementSubstitutif2")
            .agePremiereSubstitution(2)
            .posologieITI("posologieITI2")
            .dureeITI("dureeITI2")
            .causeNonObservance("causeNonObservance2")
            .efficaciteHemlibra(2)
            .chargeViraleVHC("chargeViraleVHC2")
            .typeHandicap("typeHandicap2")
            .typeActiviteSportive("typeActiviteSportive2")
            .causeDeces("causeDeces2");
    }

    public static FicheHemophilie getFicheHemophilieRandomSampleGenerator() {
        return new FicheHemophilie()
            .id(longCount.incrementAndGet())
            .dossierNumber(UUID.randomUUID().toString())
            .ordreNumber(UUID.randomUUID().toString())
            .indexNumber(UUID.randomUUID().toString())
            .prenom(UUID.randomUUID().toString())
            .nom(UUID.randomUUID().toString())
            .nomJeuneFille(UUID.randomUUID().toString())
            .profession(UUID.randomUUID().toString())
            .autreServiceClinique(UUID.randomUUID().toString())
            .ageActuel(intCount.incrementAndGet())
            .autreOrigine(UUID.randomUUID().toString())
            .adresse(UUID.randomUUID().toString())
            .telephone(UUID.randomUUID().toString())
            .prenomPere(UUID.randomUUID().toString())
            .professionPere(UUID.randomUUID().toString())
            .nomPrenomMere(UUID.randomUUID().toString())
            .professionMere(UUID.randomUUID().toString())
            .medecinTraitant(UUID.randomUUID().toString())
            .serviceOrigine(UUID.randomUUID().toString())
            .biologisteResponsableDg(UUID.randomUUID().toString())
            .autreDiagnostic(UUID.randomUUID().toString())
            .anneeDiagnostic(intCount.incrementAndGet())
            .degreParenteConsanguins(UUID.randomUUID().toString())
            .nombreCas(intCount.incrementAndGet())
            .nombreDeces(intCount.incrementAndGet())
            .fratrieNbFreres(intCount.incrementAndGet())
            .fratrieNbSoeurs(intCount.incrementAndGet())
            .ageDiagnosticJours(intCount.incrementAndGet())
            .ageDiagnosticMois(intCount.incrementAndGet())
            .ageDiagnosticAnnees(intCount.incrementAndGet())
            .plaquettes(intCount.incrementAndGet())
            .autreExplorationMoleculaire(UUID.randomUUID().toString())
            .hemarthroseSiege(UUID.randomUUID().toString())
            .hemarthroseFrequenceAn(intCount.incrementAndGet())
            .hematomeSuperficielSiege(UUID.randomUUID().toString())
            .hemorragiesCutaneoMuqueusesFrequenceAn(intCount.incrementAndGet())
            .hemorragieVisceresExamen(UUID.randomUUID().toString())
            .circoncisionAge(intCount.incrementAndGet())
            .interventionChirurgicaleType(UUID.randomUUID().toString())
            .causePriseEnCharge(UUID.randomUUID().toString())
            .prophylaxieDoseFrequence(UUID.randomUUID().toString())
            .typeTraitementSubstitutif(UUID.randomUUID().toString())
            .agePremiereSubstitution(intCount.incrementAndGet())
            .posologieITI(UUID.randomUUID().toString())
            .dureeITI(UUID.randomUUID().toString())
            .causeNonObservance(UUID.randomUUID().toString())
            .efficaciteHemlibra(intCount.incrementAndGet())
            .chargeViraleVHC(UUID.randomUUID().toString())
            .typeHandicap(UUID.randomUUID().toString())
            .typeActiviteSportive(UUID.randomUUID().toString())
            .causeDeces(UUID.randomUUID().toString());
    }
}
