package tn.adhes.hemostase.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class FicheThrombopathieTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));
    private static final AtomicInteger intCount = new AtomicInteger(random.nextInt() + (2 * Short.MAX_VALUE));

    public static FicheThrombopathie getFicheThrombopathieSample1() {
        return new FicheThrombopathie()
            .id(1L)
            .dossierNumber("dossierNumber1")
            .ordreNumber("ordreNumber1")
            .indexNumber("indexNumber1")
            .prenom("prenom1")
            .nom("nom1")
            .nomJeuneFille("nomJeuneFille1")
            .profession("profession1")
            .autreServiceClinique("autreServiceClinique1")
            .ageActuel(1)
            .autreOrigine("autreOrigine1")
            .adresse("adresse1")
            .telephone("telephone1")
            .prenomPere("prenomPere1")
            .professionPere("professionPere1")
            .nomPrenomMere("nomPrenomMere1")
            .professionMere("professionMere1")
            .medecinTraitant("medecinTraitant1")
            .serviceOrigine("serviceOrigine1")
            .biologisteResponsableDg("biologisteResponsableDg1")
            .autreDiagnostic("autreDiagnostic1")
            .anneeDiagnostic(1)
            .degreParenteConsanguins("degreParenteConsanguins1")
            .nombreCas(1)
            .degreParenteCasSimilaires("degreParenteCasSimilaires1")
            .nombreDeces(1)
            .typeHemorragie("typeHemorragie1")
            .lienParenteDeces("lienParenteDeces1")
            .antecedentsMedicaux("antecedentsMedicaux1")
            .typeChirurgie("typeChirurgie1")
            .agePremierSigneHemorragique(1)
            .typeSyndromeHemorragique("typeSyndromeHemorragique1")
            .ageDiagnostic(1)
            .typeCirconstanceDiagnostic("typeCirconstanceDiagnostic1")
            .gb(1)
            .plaquettes(1)
            .frottisSanguin("frottisSanguin1")
            .resultatAgregometrie("resultatAgregometrie1")
            .resultatCmf("resultatCmf1")
            .resultatEtudeGenetique("resultatEtudeGenetique1")
            .autreThrombopathieDetails("autreThrombopathieDetails1")
            .siegelHematome("siegelHematome1")
            .frequenceMenoMetrorragies(1)
            .severiteMenoMetrorragies("severiteMenoMetrorragies1")
            .typeLesionSousJacente("typeLesionSousJacente1")
            .lesionSousJacenteVisceres("lesionSousJacenteVisceres1")
            .typeInterventionChirurgicale("typeInterventionChirurgicale1");
    }

    public static FicheThrombopathie getFicheThrombopathieSample2() {
        return new FicheThrombopathie()
            .id(2L)
            .dossierNumber("dossierNumber2")
            .ordreNumber("ordreNumber2")
            .indexNumber("indexNumber2")
            .prenom("prenom2")
            .nom("nom2")
            .nomJeuneFille("nomJeuneFille2")
            .profession("profession2")
            .autreServiceClinique("autreServiceClinique2")
            .ageActuel(2)
            .autreOrigine("autreOrigine2")
            .adresse("adresse2")
            .telephone("telephone2")
            .prenomPere("prenomPere2")
            .professionPere("professionPere2")
            .nomPrenomMere("nomPrenomMere2")
            .professionMere("professionMere2")
            .medecinTraitant("medecinTraitant2")
            .serviceOrigine("serviceOrigine2")
            .biologisteResponsableDg("biologisteResponsableDg2")
            .autreDiagnostic("autreDiagnostic2")
            .anneeDiagnostic(2)
            .degreParenteConsanguins("degreParenteConsanguins2")
            .nombreCas(2)
            .degreParenteCasSimilaires("degreParenteCasSimilaires2")
            .nombreDeces(2)
            .typeHemorragie("typeHemorragie2")
            .lienParenteDeces("lienParenteDeces2")
            .antecedentsMedicaux("antecedentsMedicaux2")
            .typeChirurgie("typeChirurgie2")
            .agePremierSigneHemorragique(2)
            .typeSyndromeHemorragique("typeSyndromeHemorragique2")
            .ageDiagnostic(2)
            .typeCirconstanceDiagnostic("typeCirconstanceDiagnostic2")
            .gb(2)
            .plaquettes(2)
            .frottisSanguin("frottisSanguin2")
            .resultatAgregometrie("resultatAgregometrie2")
            .resultatCmf("resultatCmf2")
            .resultatEtudeGenetique("resultatEtudeGenetique2")
            .autreThrombopathieDetails("autreThrombopathieDetails2")
            .siegelHematome("siegelHematome2")
            .frequenceMenoMetrorragies(2)
            .severiteMenoMetrorragies("severiteMenoMetrorragies2")
            .typeLesionSousJacente("typeLesionSousJacente2")
            .lesionSousJacenteVisceres("lesionSousJacenteVisceres2")
            .typeInterventionChirurgicale("typeInterventionChirurgicale2");
    }

    public static FicheThrombopathie getFicheThrombopathieRandomSampleGenerator() {
        return new FicheThrombopathie()
            .id(longCount.incrementAndGet())
            .dossierNumber(UUID.randomUUID().toString())
            .ordreNumber(UUID.randomUUID().toString())
            .indexNumber(UUID.randomUUID().toString())
            .prenom(UUID.randomUUID().toString())
            .nom(UUID.randomUUID().toString())
            .nomJeuneFille(UUID.randomUUID().toString())
            .profession(UUID.randomUUID().toString())
            .autreServiceClinique(UUID.randomUUID().toString())
            .ageActuel(intCount.incrementAndGet())
            .autreOrigine(UUID.randomUUID().toString())
            .adresse(UUID.randomUUID().toString())
            .telephone(UUID.randomUUID().toString())
            .prenomPere(UUID.randomUUID().toString())
            .professionPere(UUID.randomUUID().toString())
            .nomPrenomMere(UUID.randomUUID().toString())
            .professionMere(UUID.randomUUID().toString())
            .medecinTraitant(UUID.randomUUID().toString())
            .serviceOrigine(UUID.randomUUID().toString())
            .biologisteResponsableDg(UUID.randomUUID().toString())
            .autreDiagnostic(UUID.randomUUID().toString())
            .anneeDiagnostic(intCount.incrementAndGet())
            .degreParenteConsanguins(UUID.randomUUID().toString())
            .nombreCas(intCount.incrementAndGet())
            .degreParenteCasSimilaires(UUID.randomUUID().toString())
            .nombreDeces(intCount.incrementAndGet())
            .typeHemorragie(UUID.randomUUID().toString())
            .lienParenteDeces(UUID.randomUUID().toString())
            .antecedentsMedicaux(UUID.randomUUID().toString())
            .typeChirurgie(UUID.randomUUID().toString())
            .agePremierSigneHemorragique(intCount.incrementAndGet())
            .typeSyndromeHemorragique(UUID.randomUUID().toString())
            .ageDiagnostic(intCount.incrementAndGet())
            .typeCirconstanceDiagnostic(UUID.randomUUID().toString())
            .gb(intCount.incrementAndGet())
            .plaquettes(intCount.incrementAndGet())
            .frottisSanguin(UUID.randomUUID().toString())
            .resultatAgregometrie(UUID.randomUUID().toString())
            .resultatCmf(UUID.randomUUID().toString())
            .resultatEtudeGenetique(UUID.randomUUID().toString())
            .autreThrombopathieDetails(UUID.randomUUID().toString())
            .siegelHematome(UUID.randomUUID().toString())
            .frequenceMenoMetrorragies(intCount.incrementAndGet())
            .severiteMenoMetrorragies(UUID.randomUUID().toString())
            .typeLesionSousJacente(UUID.randomUUID().toString())
            .lesionSousJacenteVisceres(UUID.randomUUID().toString())
            .typeInterventionChirurgicale(UUID.randomUUID().toString());
    }
}
