package tn.adhes.hemostase.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FicheVonWillebrandAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheVonWillebrandAllPropertiesEquals(FicheVonWillebrand expected, FicheVonWillebrand actual) {
        assertFicheVonWillebrandAutoGeneratedPropertiesEquals(expected, actual);
        assertFicheVonWillebrandAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheVonWillebrandAllUpdatablePropertiesEquals(FicheVonWillebrand expected, FicheVonWillebrand actual) {
        assertFicheVonWillebrandUpdatableFieldsEquals(expected, actual);
        assertFicheVonWillebrandUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheVonWillebrandAutoGeneratedPropertiesEquals(FicheVonWillebrand expected, FicheVonWillebrand actual) {
        assertThat(expected)
            .as("Verify FicheVonWillebrand auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheVonWillebrandUpdatableFieldsEquals(FicheVonWillebrand expected, FicheVonWillebrand actual) {
        assertThat(expected)
            .as("Verify FicheVonWillebrand relevant properties")
            .satisfies(e -> assertThat(e.getDossierNumber()).as("check dossierNumber").isEqualTo(actual.getDossierNumber()))
            .satisfies(e -> assertThat(e.getOrdreNumber()).as("check ordreNumber").isEqualTo(actual.getOrdreNumber()))
            .satisfies(e -> assertThat(e.getIndexNumber()).as("check indexNumber").isEqualTo(actual.getIndexNumber()))
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getNomJeuneFille()).as("check nomJeuneFille").isEqualTo(actual.getNomJeuneFille()))
            .satisfies(e -> assertThat(e.getProfession()).as("check profession").isEqualTo(actual.getProfession()))
            .satisfies(e -> assertThat(e.getEtatCivil()).as("check etatCivil").isEqualTo(actual.getEtatCivil()))
            .satisfies(e -> assertThat(e.getServiceClinique()).as("check serviceClinique").isEqualTo(actual.getServiceClinique()))
            .satisfies(e ->
                assertThat(e.getAutreServiceClinique()).as("check autreServiceClinique").isEqualTo(actual.getAutreServiceClinique())
            )
            .satisfies(e -> assertThat(e.getCouvertureSociale()).as("check couvertureSociale").isEqualTo(actual.getCouvertureSociale()))
            .satisfies(e -> assertThat(e.getSexe()).as("check sexe").isEqualTo(actual.getSexe()))
            .satisfies(e -> assertThat(e.getDateNaissance()).as("check dateNaissance").isEqualTo(actual.getDateNaissance()))
            .satisfies(e -> assertThat(e.getAgeActuel()).as("check ageActuel").isEqualTo(actual.getAgeActuel()))
            .satisfies(e -> assertThat(e.getOrigine()).as("check origine").isEqualTo(actual.getOrigine()))
            .satisfies(e -> assertThat(e.getAutreOrigine()).as("check autreOrigine").isEqualTo(actual.getAutreOrigine()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getPrenomPere()).as("check prenomPere").isEqualTo(actual.getPrenomPere()))
            .satisfies(e -> assertThat(e.getProfessionPere()).as("check professionPere").isEqualTo(actual.getProfessionPere()))
            .satisfies(e -> assertThat(e.getNomPrenomMere()).as("check nomPrenomMere").isEqualTo(actual.getNomPrenomMere()))
            .satisfies(e -> assertThat(e.getProfessionMere()).as("check professionMere").isEqualTo(actual.getProfessionMere()))
            .satisfies(e -> assertThat(e.getMedecinTraitant()).as("check medecinTraitant").isEqualTo(actual.getMedecinTraitant()))
            .satisfies(e -> assertThat(e.getServiceOrigine()).as("check serviceOrigine").isEqualTo(actual.getServiceOrigine()))
            .satisfies(e ->
                assertThat(e.getBiologisteResponsableDg())
                    .as("check biologisteResponsableDg")
                    .isEqualTo(actual.getBiologisteResponsableDg())
            )
            .satisfies(e -> assertThat(e.getDiagnostic()).as("check diagnostic").isEqualTo(actual.getDiagnostic()))
            .satisfies(e -> assertThat(e.getAutreDiagnostic()).as("check autreDiagnostic").isEqualTo(actual.getAutreDiagnostic()))
            .satisfies(e -> assertThat(e.getAnneeDiagnostic()).as("check anneeDiagnostic").isEqualTo(actual.getAnneeDiagnostic()))
            .satisfies(e ->
                assertThat(e.getDateEnregistrementRegistre())
                    .as("check dateEnregistrementRegistre")
                    .isEqualTo(actual.getDateEnregistrementRegistre())
            )
            .satisfies(e ->
                assertThat(e.getConsentementRegistre()).as("check consentementRegistre").isEqualTo(actual.getConsentementRegistre())
            )
            .satisfies(e -> assertThat(e.getParentsConsanguins()).as("check parentsConsanguins").isEqualTo(actual.getParentsConsanguins()))
            .satisfies(e ->
                assertThat(e.getDegreParenteConsanguins())
                    .as("check degreParenteConsanguins")
                    .isEqualTo(actual.getDegreParenteConsanguins())
            )
            .satisfies(e -> assertThat(e.getCasSimilaires()).as("check casSimilaires").isEqualTo(actual.getCasSimilaires()))
            .satisfies(e -> assertThat(e.getNombreCas()).as("check nombreCas").isEqualTo(actual.getNombreCas()))
            .satisfies(e -> assertThat(e.getCas1Numero()).as("check cas1Numero").isEqualTo(actual.getCas1Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas1()).as("check lienParenteCas1").isEqualTo(actual.getLienParenteCas1()))
            .satisfies(e -> assertThat(e.getDegreParenteCas1()).as("check degreParenteCas1").isEqualTo(actual.getDegreParenteCas1()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas1()).as("check typeHemorragieCas1").isEqualTo(actual.getTypeHemorragieCas1()))
            .satisfies(e -> assertThat(e.getCas2Numero()).as("check cas2Numero").isEqualTo(actual.getCas2Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas2()).as("check lienParenteCas2").isEqualTo(actual.getLienParenteCas2()))
            .satisfies(e -> assertThat(e.getDegreParenteCas2()).as("check degreParenteCas2").isEqualTo(actual.getDegreParenteCas2()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas2()).as("check typeHemorragieCas2").isEqualTo(actual.getTypeHemorragieCas2()))
            .satisfies(e -> assertThat(e.getCas3Numero()).as("check cas3Numero").isEqualTo(actual.getCas3Numero()))
            .satisfies(e -> assertThat(e.getLienParenteCas3()).as("check lienParenteCas3").isEqualTo(actual.getLienParenteCas3()))
            .satisfies(e -> assertThat(e.getDegreParenteCas3()).as("check degreParenteCas3").isEqualTo(actual.getDegreParenteCas3()))
            .satisfies(e -> assertThat(e.getTypeHemorragieCas3()).as("check typeHemorragieCas3").isEqualTo(actual.getTypeHemorragieCas3()))
            .satisfies(e ->
                assertThat(e.getDecesSyndromeHemorragique())
                    .as("check decesSyndromeHemorragique")
                    .isEqualTo(actual.getDecesSyndromeHemorragique())
            )
            .satisfies(e -> assertThat(e.getNombreDeces()).as("check nombreDeces").isEqualTo(actual.getNombreDeces()))
            .satisfies(e -> assertThat(e.getDeces1Numero()).as("check deces1Numero").isEqualTo(actual.getDeces1Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces1()).as("check lienParenteDeces1").isEqualTo(actual.getLienParenteDeces1()))
            .satisfies(e -> assertThat(e.getCauseDeces1()).as("check causeDeces1").isEqualTo(actual.getCauseDeces1()))
            .satisfies(e -> assertThat(e.getDeces2Numero()).as("check deces2Numero").isEqualTo(actual.getDeces2Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces2()).as("check lienParenteDeces2").isEqualTo(actual.getLienParenteDeces2()))
            .satisfies(e -> assertThat(e.getCauseDeces2()).as("check causeDeces2").isEqualTo(actual.getCauseDeces2()))
            .satisfies(e -> assertThat(e.getDeces3Numero()).as("check deces3Numero").isEqualTo(actual.getDeces3Numero()))
            .satisfies(e -> assertThat(e.getLienParenteDeces3()).as("check lienParenteDeces3").isEqualTo(actual.getLienParenteDeces3()))
            .satisfies(e -> assertThat(e.getCauseDeces3()).as("check causeDeces3").isEqualTo(actual.getCauseDeces3()))
            .satisfies(e -> assertThat(e.getEnqueteFamiliale()).as("check enqueteFamiliale").isEqualTo(actual.getEnqueteFamiliale()))
            .satisfies(e ->
                assertThat(e.getCirconstancesDecouverte())
                    .as("check circonstancesDecouverte")
                    .isEqualTo(actual.getCirconstancesDecouverte())
            )
            .satisfies(e ->
                assertThat(e.getCirconstancesDecouvertePrecision())
                    .as("check circonstancesDecouvertePrecision")
                    .isEqualTo(actual.getCirconstancesDecouvertePrecision())
            )
            .satisfies(e -> assertThat(e.getJamaisSaigne()).as("check jamaisSaigne").isEqualTo(actual.getJamaisSaigne()))
            .satisfies(e ->
                assertThat(e.getAgePremierSigneCliniqueJours())
                    .as("check agePremierSigneCliniqueJours")
                    .isEqualTo(actual.getAgePremierSigneCliniqueJours())
            )
            .satisfies(e ->
                assertThat(e.getAgePremierSigneCliniqueMois())
                    .as("check agePremierSigneCliniqueMois")
                    .isEqualTo(actual.getAgePremierSigneCliniqueMois())
            )
            .satisfies(e ->
                assertThat(e.getAgePremierSigneCliniqueAnnees())
                    .as("check agePremierSigneCliniqueAnnees")
                    .isEqualTo(actual.getAgePremierSigneCliniqueAnnees())
            )
            .satisfies(e -> assertThat(e.getSymptomeEcchymose()).as("check symptomeEcchymose").isEqualTo(actual.getSymptomeEcchymose()))
            .satisfies(e -> assertThat(e.getSymptomeEpistaxis()).as("check symptomeEpistaxis").isEqualTo(actual.getSymptomeEpistaxis()))
            .satisfies(e ->
                assertThat(e.getSymptomeGingivorragies()).as("check symptomeGingivorragies").isEqualTo(actual.getSymptomeGingivorragies())
            )
            .satisfies(e ->
                assertThat(e.getSymptomeMetrorragies()).as("check symptomeMetrorragies").isEqualTo(actual.getSymptomeMetrorragies())
            )
            .satisfies(e -> assertThat(e.getSymptomeMelena()).as("check symptomeMelena").isEqualTo(actual.getSymptomeMelena()))
            .satisfies(e -> assertThat(e.getSymptomeHemoptysie()).as("check symptomeHemoptysie").isEqualTo(actual.getSymptomeHemoptysie()))
            .satisfies(e ->
                assertThat(e.getSymptomeHemorragiePostAmygdalectomie())
                    .as("check symptomeHemorragiePostAmygdalectomie")
                    .isEqualTo(actual.getSymptomeHemorragiePostAmygdalectomie())
            )
            .satisfies(e ->
                assertThat(e.getSymptomeHemorragiePostAvulsionDentaire())
                    .as("check symptomeHemorragiePostAvulsionDentaire")
                    .isEqualTo(actual.getSymptomeHemorragiePostAvulsionDentaire())
            )
            .satisfies(e ->
                assertThat(e.getSymptomeHemorragieChuteCordon())
                    .as("check symptomeHemorragieChuteCordon")
                    .isEqualTo(actual.getSymptomeHemorragieChuteCordon())
            )
            .satisfies(e -> assertThat(e.getSymptomeAutre()).as("check symptomeAutre").isEqualTo(actual.getSymptomeAutre()))
            .satisfies(e ->
                assertThat(e.getSymptomeAutreDescription())
                    .as("check symptomeAutreDescription")
                    .isEqualTo(actual.getSymptomeAutreDescription())
            )
            .satisfies(e ->
                assertThat(e.getDatePremiereConsultation())
                    .as("check datePremiereConsultation")
                    .isEqualTo(actual.getDatePremiereConsultation())
            )
            .satisfies(e ->
                assertThat(e.getAgePremiereConsultationJours())
                    .as("check agePremiereConsultationJours")
                    .isEqualTo(actual.getAgePremiereConsultationJours())
            )
            .satisfies(e ->
                assertThat(e.getAgePremiereConsultationMois())
                    .as("check agePremiereConsultationMois")
                    .isEqualTo(actual.getAgePremiereConsultationMois())
            )
            .satisfies(e ->
                assertThat(e.getAgePremiereConsultationAnnees())
                    .as("check agePremiereConsultationAnnees")
                    .isEqualTo(actual.getAgePremiereConsultationAnnees())
            )
            .satisfies(e -> assertThat(e.getAgeDiagnosticJours()).as("check ageDiagnosticJours").isEqualTo(actual.getAgeDiagnosticJours()))
            .satisfies(e -> assertThat(e.getAgeDiagnosticMois()).as("check ageDiagnosticMois").isEqualTo(actual.getAgeDiagnosticMois()))
            .satisfies(e ->
                assertThat(e.getAgeDiagnosticAnnees()).as("check ageDiagnosticAnnees").isEqualTo(actual.getAgeDiagnosticAnnees())
            )
            .satisfies(e -> assertThat(e.getTypeMvW()).as("check typeMvW").isEqualTo(actual.getTypeMvW()))
            .satisfies(e -> assertThat(e.getSousTypeMvW()).as("check sousTypeMvW").isEqualTo(actual.getSousTypeMvW()))
            .satisfies(e ->
                assertThat(e.getPathologiesAssociees()).as("check pathologiesAssociees").isEqualTo(actual.getPathologiesAssociees())
            )
            .satisfies(e ->
                assertThat(e.getDateTestConfirmation()).as("check dateTestConfirmation").isEqualTo(actual.getDateTestConfirmation())
            )
            .satisfies(e -> assertThat(e.getGs()).as("check gs").isEqualTo(actual.getGs()))
            .satisfies(e -> assertThat(e.getHb()).as("check hb").isEqualTo(actual.getHb()))
            .satisfies(e -> assertThat(e.getHte()).as("check hte").isEqualTo(actual.getHte()))
            .satisfies(e -> assertThat(e.getPlaquettes()).as("check plaquettes").isEqualTo(actual.getPlaquettes()))
            .satisfies(e -> assertThat(e.getTp()).as("check tp").isEqualTo(actual.getTp()))
            .satisfies(e -> assertThat(e.getTcaMT()).as("check tcaMT").isEqualTo(actual.getTcaMT()))
            .satisfies(e -> assertThat(e.getTcaMPlusT()).as("check tcaMPlusT").isEqualTo(actual.getTcaMPlusT()))
            .satisfies(e -> assertThat(e.getTcaMPlusT2H()).as("check tcaMPlusT2H").isEqualTo(actual.getTcaMPlusT2H()))
            .satisfies(e -> assertThat(e.getFibrinogene()).as("check fibrinogene").isEqualTo(actual.getFibrinogene()))
            .satisfies(e -> assertThat(e.getTsResultat()).as("check tsResultat").isEqualTo(actual.getTsResultat()))
            .satisfies(e -> assertThat(e.getTsValeur()).as("check tsValeur").isEqualTo(actual.getTsValeur()))
            .satisfies(e ->
                assertThat(e.getOcclusionPlaquettaire()).as("check occlusionPlaquettaire").isEqualTo(actual.getOcclusionPlaquettaire())
            )
            .satisfies(e ->
                assertThat(e.getCollageneEpinephrine()).as("check collageneEpinephrine").isEqualTo(actual.getCollageneEpinephrine())
            )
            .satisfies(e -> assertThat(e.getCollageneADP()).as("check collageneADP").isEqualTo(actual.getCollageneADP()))
            .satisfies(e -> assertThat(e.getFvwag()).as("check fvwag").isEqualTo(actual.getFvwag()))
            .satisfies(e -> assertThat(e.getFvwact()).as("check fvwact").isEqualTo(actual.getFvwact()))
            .satisfies(e -> assertThat(e.getf8c()).as("check f8c").isEqualTo(actual.getf8c()))
            .satisfies(e -> assertThat(e.getRatioFvwactFvwag()).as("check ratioFvwactFvwag").isEqualTo(actual.getRatioFvwactFvwag()))
            .satisfies(e -> assertThat(e.getRatioF8cFvwag()).as("check ratioF8cFvwag").isEqualTo(actual.getRatioF8cFvwag()))
            .satisfies(e ->
                assertThat(e.getAutresTestsSpecifiques()).as("check autresTestsSpecifiques").isEqualTo(actual.getAutresTestsSpecifiques())
            )
            .satisfies(e -> assertThat(e.getVwfCB()).as("check vwfCB").isEqualTo(actual.getVwfCB()))
            .satisfies(e -> assertThat(e.getVwfCBResultat()).as("check vwfCBResultat").isEqualTo(actual.getVwfCBResultat()))
            .satisfies(e -> assertThat(e.getRipa()).as("check ripa").isEqualTo(actual.getRipa()))
            .satisfies(e -> assertThat(e.getRipaResultat()).as("check ripaResultat").isEqualTo(actual.getRipaResultat()))
            .satisfies(e -> assertThat(e.getMultimereHPM()).as("check multimereHPM").isEqualTo(actual.getMultimereHPM()))
            .satisfies(e -> assertThat(e.getLiaisonFvwF8()).as("check liaisonFvwF8").isEqualTo(actual.getLiaisonFvwF8()))
            .satisfies(e ->
                assertThat(e.getLiaisonFvwF8Resultat()).as("check liaisonFvwF8Resultat").isEqualTo(actual.getLiaisonFvwF8Resultat())
            )
            .satisfies(e -> assertThat(e.getFvwpp()).as("check fvwpp").isEqualTo(actual.getFvwpp()))
            .satisfies(e -> assertThat(e.getFvwppResultat()).as("check fvwppResultat").isEqualTo(actual.getFvwppResultat()))
            .satisfies(e -> assertThat(e.getMutationGenetique()).as("check mutationGenetique").isEqualTo(actual.getMutationGenetique()))
            .satisfies(e -> assertThat(e.getMutationPresente()).as("check mutationPresente").isEqualTo(actual.getMutationPresente()))
            .satisfies(e -> assertThat(e.getMutationNom()).as("check mutationNom").isEqualTo(actual.getMutationNom()))
            .satisfies(e -> assertThat(e.getMutationZygote()).as("check mutationZygote").isEqualTo(actual.getMutationZygote()))
            .satisfies(e -> assertThat(e.getEcchymoses()).as("check ecchymoses").isEqualTo(actual.getEcchymoses()))
            .satisfies(e ->
                assertThat(e.getEcchymosesSpontanees()).as("check ecchymosesSpontanees").isEqualTo(actual.getEcchymosesSpontanees())
            )
            .satisfies(e ->
                assertThat(e.getEcchymosesProvoquees()).as("check ecchymosesProvoquees").isEqualTo(actual.getEcchymosesProvoquees())
            )
            .satisfies(e -> assertThat(e.getEcchymosesSiege()).as("check ecchymosesSiege").isEqualTo(actual.getEcchymosesSiege()))
            .satisfies(e ->
                assertThat(e.getEcchymosesFrequence()).as("check ecchymosesFrequence").isEqualTo(actual.getEcchymosesFrequence())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieMuqueuses()).as("check hemorragieMuqueuses").isEqualTo(actual.getHemorragieMuqueuses())
            )
            .satisfies(e -> assertThat(e.getEpistaxis()).as("check epistaxis").isEqualTo(actual.getEpistaxis()))
            .satisfies(e -> assertThat(e.getEpistaxisFrequence()).as("check epistaxisFrequence").isEqualTo(actual.getEpistaxisFrequence()))
            .satisfies(e ->
                assertThat(e.getHemorragiesIntrabuccales())
                    .as("check hemorragiesIntrabuccales")
                    .isEqualTo(actual.getHemorragiesIntrabuccales())
            )
            .satisfies(e ->
                assertThat(e.getHemorragiesIntrabuccalesFrequence())
                    .as("check hemorragiesIntrabuccalesFrequence")
                    .isEqualTo(actual.getHemorragiesIntrabuccalesFrequence())
            )
            .satisfies(e -> assertThat(e.getMenoragie()).as("check menoragie").isEqualTo(actual.getMenoragie()))
            .satisfies(e -> assertThat(e.getMenoragieFrequence()).as("check menoragieFrequence").isEqualTo(actual.getMenoragieFrequence()))
            .satisfies(e -> assertThat(e.getScoreHighamFait()).as("check scoreHighamFait").isEqualTo(actual.getScoreHighamFait()))
            .satisfies(e -> assertThat(e.getScoreHighamValeur()).as("check scoreHighamValeur").isEqualTo(actual.getScoreHighamValeur()))
            .satisfies(e -> assertThat(e.getHematome()).as("check hematome").isEqualTo(actual.getHematome()))
            .satisfies(e -> assertThat(e.getHematomeSpontane()).as("check hematomeSpontane").isEqualTo(actual.getHematomeSpontane()))
            .satisfies(e -> assertThat(e.getHematomeProvoque()).as("check hematomeProvoque").isEqualTo(actual.getHematomeProvoque()))
            .satisfies(e -> assertThat(e.getHematomeSousCutane()).as("check hematomeSousCutane").isEqualTo(actual.getHematomeSousCutane()))
            .satisfies(e -> assertThat(e.getHematomeMusculaire()).as("check hematomeMusculaire").isEqualTo(actual.getHematomeMusculaire()))
            .satisfies(e -> assertThat(e.getHematomeTissusMous()).as("check hematomeTissusMous").isEqualTo(actual.getHematomeTissusMous()))
            .satisfies(e -> assertThat(e.getHematomeFrequence()).as("check hematomeFrequence").isEqualTo(actual.getHematomeFrequence()))
            .satisfies(e -> assertThat(e.getHemarthrose()).as("check hemarthrose").isEqualTo(actual.getHemarthrose()))
            .satisfies(e ->
                assertThat(e.getHemarthroseSpontane()).as("check hemarthroseSpontane").isEqualTo(actual.getHemarthroseSpontane())
            )
            .satisfies(e ->
                assertThat(e.getHemarthroseProvoque()).as("check hemarthroseProvoque").isEqualTo(actual.getHemarthroseProvoque())
            )
            .satisfies(e -> assertThat(e.getHemarthroseSiege()).as("check hemarthroseSiege").isEqualTo(actual.getHemarthroseSiege()))
            .satisfies(e ->
                assertThat(e.getHemarthroseFrequence()).as("check hemarthroseFrequence").isEqualTo(actual.getHemarthroseFrequence())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieAmygdalienne()).as("check hemorragieAmygdalienne").isEqualTo(actual.getHemorragieAmygdalienne())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieAmygdalienneFrequence())
                    .as("check hemorragieAmygdalienneFrequence")
                    .isEqualTo(actual.getHemorragieAmygdalienneFrequence())
            )
            .satisfies(e -> assertThat(e.getAvulsionDentaire()).as("check avulsionDentaire").isEqualTo(actual.getAvulsionDentaire()))
            .satisfies(e -> assertThat(e.getAvulsionPrepare()).as("check avulsionPrepare").isEqualTo(actual.getAvulsionPrepare()))
            .satisfies(e ->
                assertThat(e.getAvulsionBienDeroule()).as("check avulsionBienDeroule").isEqualTo(actual.getAvulsionBienDeroule())
            )
            .satisfies(e -> assertThat(e.getTraumatisme()).as("check traumatisme").isEqualTo(actual.getTraumatisme()))
            .satisfies(e -> assertThat(e.getTraumatismeType()).as("check traumatismeType").isEqualTo(actual.getTraumatismeType()))
            .satisfies(e -> assertThat(e.getChirurgie()).as("check chirurgie").isEqualTo(actual.getChirurgie()))
            .satisfies(e -> assertThat(e.getChirurgieType()).as("check chirurgieType").isEqualTo(actual.getChirurgieType()))
            .satisfies(e -> assertThat(e.getChirurgiePrepare()).as("check chirurgiePrepare").isEqualTo(actual.getChirurgiePrepare()))
            .satisfies(e ->
                assertThat(e.getChirurgieBienDeroule()).as("check chirurgieBienDeroule").isEqualTo(actual.getChirurgieBienDeroule())
            )
            .satisfies(e -> assertThat(e.getAccouchement()).as("check accouchement").isEqualTo(actual.getAccouchement()))
            .satisfies(e ->
                assertThat(e.getHemorragiePostpartum()).as("check hemorragiePostpartum").isEqualTo(actual.getHemorragiePostpartum())
            )
            .satisfies(e -> assertThat(e.getCirconcision()).as("check circoncision").isEqualTo(actual.getCirconcision()))
            .satisfies(e -> assertThat(e.getAgeCirconcision()).as("check ageCirconcision").isEqualTo(actual.getAgeCirconcision()))
            .satisfies(e ->
                assertThat(e.getCirconcisionPrepare()).as("check circoncisionPrepare").isEqualTo(actual.getCirconcisionPrepare())
            )
            .satisfies(e ->
                assertThat(e.getCirconcisionBienDeroule())
                    .as("check circoncisionBienDeroule")
                    .isEqualTo(actual.getCirconcisionBienDeroule())
            )
            .satisfies(e -> assertThat(e.getHemorragieVisceres()).as("check hemorragieVisceres").isEqualTo(actual.getHemorragieVisceres()))
            .satisfies(e ->
                assertThat(e.getHemorragieVisceresSpontane())
                    .as("check hemorragieVisceresSpontane")
                    .isEqualTo(actual.getHemorragieVisceresSpontane())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieVisceresProvoque())
                    .as("check hemorragieVisceresProvoque")
                    .isEqualTo(actual.getHemorragieVisceresProvoque())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieVisceresType()).as("check hemorragieVisceresType").isEqualTo(actual.getHemorragieVisceresType())
            )
            .satisfies(e ->
                assertThat(e.getAutreHemorragieVisceres())
                    .as("check autreHemorragieVisceres")
                    .isEqualTo(actual.getAutreHemorragieVisceres())
            )
            .satisfies(e ->
                assertThat(e.getExplorationVisceres()).as("check explorationVisceres").isEqualTo(actual.getExplorationVisceres())
            )
            .satisfies(e -> assertThat(e.getLesionSousJacente()).as("check lesionSousJacente").isEqualTo(actual.getLesionSousJacente()))
            .satisfies(e -> assertThat(e.getHemorragieGrave()).as("check hemorragieGrave").isEqualTo(actual.getHemorragieGrave()))
            .satisfies(e ->
                assertThat(e.getGraveDeglobulisation()).as("check graveDeglobulisation").isEqualTo(actual.getGraveDeglobulisation())
            )
            .satisfies(e -> assertThat(e.getGraveEtatDeChoc()).as("check graveEtatDeChoc").isEqualTo(actual.getGraveEtatDeChoc()))
            .satisfies(e ->
                assertThat(e.getGraveParLocalisation()).as("check graveParLocalisation").isEqualTo(actual.getGraveParLocalisation())
            )
            .satisfies(e ->
                assertThat(e.getSiegeGraviteLocalisation())
                    .as("check siegeGraviteLocalisation")
                    .isEqualTo(actual.getSiegeGraviteLocalisation())
            )
            .satisfies(e ->
                assertThat(e.getNombreHospitalisations()).as("check nombreHospitalisations").isEqualTo(actual.getNombreHospitalisations())
            )
            .satisfies(e -> assertThat(e.getNombreTransfusions()).as("check nombreTransfusions").isEqualTo(actual.getNombreTransfusions()))
            .satisfies(e -> assertThat(e.getScoreISTHBAT()).as("check scoreISTHBAT").isEqualTo(actual.getScoreISTHBAT()))
            .satisfies(e -> assertThat(e.getDesmopressine()).as("check desmopressine").isEqualTo(actual.getDesmopressine()))
            .satisfies(e ->
                assertThat(e.getTraitementSubstitutifPrevention())
                    .as("check traitementSubstitutifPrevention")
                    .isEqualTo(actual.getTraitementSubstitutifPrevention())
            )
            .satisfies(e ->
                assertThat(e.getTraitementPreparation()).as("check traitementPreparation").isEqualTo(actual.getTraitementPreparation())
            )
            .satisfies(e ->
                assertThat(e.getTraitementSubstitutifCuratif())
                    .as("check traitementSubstitutifCuratif")
                    .isEqualTo(actual.getTraitementSubstitutifCuratif())
            )
            .satisfies(e -> assertThat(e.getCryoprecipite()).as("check cryoprecipite").isEqualTo(actual.getCryoprecipite()))
            .satisfies(e -> assertThat(e.getPfc()).as("check pfc").isEqualTo(actual.getPfc()))
            .satisfies(e -> assertThat(e.getConcentreFVIIIFVW()).as("check concentreFVIIIFVW").isEqualTo(actual.getConcentreFVIIIFVW()))
            .satisfies(e -> assertThat(e.getConcentreFVW()).as("check concentreFVW").isEqualTo(actual.getConcentreFVW()))
            .satisfies(e -> assertThat(e.getConcentreFVIII()).as("check concentreFVIII").isEqualTo(actual.getConcentreFVIII()))
            .satisfies(e -> assertThat(e.getAgentBypassant()).as("check agentBypassant").isEqualTo(actual.getAgentBypassant()))
            .satisfies(e ->
                assertThat(e.getAntifibrinolytiques()).as("check antifibrinolytiques").isEqualTo(actual.getAntifibrinolytiques())
            )
            .satisfies(e -> assertThat(e.getVoieOrale()).as("check voieOrale").isEqualTo(actual.getVoieOrale()))
            .satisfies(e -> assertThat(e.getVoieIV()).as("check voieIV").isEqualTo(actual.getVoieIV()))
            .satisfies(e -> assertThat(e.getVoieLocale()).as("check voieLocale").isEqualTo(actual.getVoieLocale()))
            .satisfies(e -> assertThat(e.getOestroprogestatifs()).as("check oestroprogestatifs").isEqualTo(actual.getOestroprogestatifs()))
            .satisfies(e ->
                assertThat(e.getTraitementAntalgique()).as("check traitementAntalgique").isEqualTo(actual.getTraitementAntalgique())
            )
            .satisfies(e -> assertThat(e.getCorticotherapie()).as("check corticotherapie").isEqualTo(actual.getCorticotherapie()))
            .satisfies(e -> assertThat(e.getKinesitherapie()).as("check kinesitherapie").isEqualTo(actual.getKinesitherapie()))
            .satisfies(e -> assertThat(e.getTraitementMartial()).as("check traitementMartial").isEqualTo(actual.getTraitementMartial()))
            .satisfies(e -> assertThat(e.getCulotsGlobulaires()).as("check culotsGlobulaires").isEqualTo(actual.getCulotsGlobulaires()))
            .satisfies(e ->
                assertThat(e.getNombreCulotsGlobulaires())
                    .as("check nombreCulotsGlobulaires")
                    .isEqualTo(actual.getNombreCulotsGlobulaires())
            )
            .satisfies(e -> assertThat(e.getImmunosuppresseur()).as("check immunosuppresseur").isEqualTo(actual.getImmunosuppresseur()))
            .satisfies(e ->
                assertThat(e.getNomImmunosuppresseur()).as("check nomImmunosuppresseur").isEqualTo(actual.getNomImmunosuppresseur())
            )
            .satisfies(e -> assertThat(e.getAnemie()).as("check anemie").isEqualTo(actual.getAnemie()))
            .satisfies(e -> assertThat(e.getAnemieSevere()).as("check anemieSevere").isEqualTo(actual.getAnemieSevere()))
            .satisfies(e -> assertThat(e.getTauxHb()).as("check tauxHb").isEqualTo(actual.getTauxHb()))
            .satisfies(e -> assertThat(e.getAnticorpsAntiFVW()).as("check anticorpsAntiFVW").isEqualTo(actual.getAnticorpsAntiFVW()))
            .satisfies(e -> assertThat(e.getAnticorpsAntiFVIII()).as("check anticorpsAntiFVIII").isEqualTo(actual.getAnticorpsAntiFVIII()))
            .satisfies(e -> assertThat(e.getHepatiteB()).as("check hepatiteB").isEqualTo(actual.getHepatiteB()))
            .satisfies(e -> assertThat(e.getHepatiteC()).as("check hepatiteC").isEqualTo(actual.getHepatiteC()))
            .satisfies(e -> assertThat(e.getHiv()).as("check hiv").isEqualTo(actual.getHiv()))
            .satisfies(e -> assertThat(e.getThrombose()).as("check thrombose").isEqualTo(actual.getThrombose()))
            .satisfies(e -> assertThat(e.getReactionAllergique()).as("check reactionAllergique").isEqualTo(actual.getReactionAllergique()))
            .satisfies(e -> assertThat(e.getAutreComplication()).as("check autreComplication").isEqualTo(actual.getAutreComplication()))
            .satisfies(e ->
                assertThat(e.getAutreComplicationDescription())
                    .as("check autreComplicationDescription")
                    .isEqualTo(actual.getAutreComplicationDescription())
            )
            .satisfies(e ->
                assertThat(e.getAdherenceTherapeutique()).as("check adherenceTherapeutique").isEqualTo(actual.getAdherenceTherapeutique())
            )
            .satisfies(e -> assertThat(e.getCauseNonAdherence()).as("check causeNonAdherence").isEqualTo(actual.getCauseNonAdherence()))
            .satisfies(e -> assertThat(e.getStatutSocial()).as("check statutSocial").isEqualTo(actual.getStatutSocial()))
            .satisfies(e -> assertThat(e.getMarie()).as("check marie").isEqualTo(actual.getMarie()))
            .satisfies(e -> assertThat(e.getEnfants()).as("check enfants").isEqualTo(actual.getEnfants()))
            .satisfies(e -> assertThat(e.getActivitePhysique()).as("check activitePhysique").isEqualTo(actual.getActivitePhysique()))
            .satisfies(e ->
                assertThat(e.getTypeActivitePhysique()).as("check typeActivitePhysique").isEqualTo(actual.getTypeActivitePhysique())
            )
            .satisfies(e -> assertThat(e.getSequelles()).as("check sequelles").isEqualTo(actual.getSequelles()))
            .satisfies(e -> assertThat(e.getTypeSequelles()).as("check typeSequelles").isEqualTo(actual.getTypeSequelles()))
            .satisfies(e -> assertThat(e.getPatientDecede()).as("check patientDecede").isEqualTo(actual.getPatientDecede()))
            .satisfies(e -> assertThat(e.getDateDeces()).as("check dateDeces").isEqualTo(actual.getDateDeces()))
            .satisfies(e -> assertThat(e.getAgeDeces()).as("check ageDeces").isEqualTo(actual.getAgeDeces()))
            .satisfies(e -> assertThat(e.getCauseDeces()).as("check causeDeces").isEqualTo(actual.getCauseDeces()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheVonWillebrandUpdatableRelationshipsEquals(FicheVonWillebrand expected, FicheVonWillebrand actual) {
        // empty method
    }
}
