package tn.adhes.hemostase.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class FicheFacteurVIIITestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));
    private static final AtomicInteger intCount = new AtomicInteger(random.nextInt() + (2 * Short.MAX_VALUE));

    public static FicheFacteurVIII getFicheFacteurVIIISample1() {
        return new FicheFacteurVIII()
            .id(1L)
            .dossierNumber("dossierNumber1")
            .ordreNumber("ordreNumber1")
            .indexNumber("indexNumber1")
            .prenom("prenom1")
            .nom("nom1")
            .nomJeuneFille("nomJeuneFille1")
            .profession("profession1")
            .autreServiceClinique("autreServiceClinique1")
            .ageActuel(1)
            .autreOrigine("autreOrigine1")
            .adresse("adresse1")
            .telephone("telephone1")
            .prenomPere("prenomPere1")
            .professionPere("professionPere1")
            .nomPrenomMere("nomPrenomMere1")
            .professionMere("professionMere1")
            .medecinTraitant("medecinTraitant1")
            .serviceOrigine("serviceOrigine1")
            .biologisteResponsableDg("biologisteResponsableDg1")
            .autreDiagnostic("autreDiagnostic1")
            .anneeDiagnostic(1)
            .nombreCas(1)
            .cas1Numero(1)
            .degreParenteCas1("degreParenteCas11")
            .typeHemorragieCas1("typeHemorragieCas11")
            .cas2Numero(1)
            .degreParenteCas2("degreParenteCas21")
            .typeHemorragieCas2("typeHemorragieCas21")
            .cas3Numero(1)
            .degreParenteCas3("degreParenteCas31")
            .typeHemorragieCas3("typeHemorragieCas31")
            .nombreDeces(1)
            .deces1Numero(1)
            .causeDeces1("causeDeces11")
            .deces2Numero(1)
            .causeDeces2("causeDeces21")
            .deces3Numero(1)
            .causeDeces3("causeDeces31")
            .ageDiagnosticJour(1)
            .ageDiagnosticMois(1)
            .ageDiagnosticAnnee(1)
            .plaquettes(1)
            .frequenceEpistaxis(1)
            .frequenceGingivorragies(1)
            .frequenceEcchymose(1)
            .frequenceMenorragie(1)
            .frequenceHematemese(1)
            .frequenceRectorragie(1)
            .frequenceHematurie(1)
            .frequenceHematomeSousCutane(1)
            .siegeHematomeMusculaire("siegeHematomeMusculaire1")
            .frequenceHematomeMusculaire(1)
            .frequenceHemarthrose(1)
            .frequenceSaignementSNC(1)
            .ageCirconcision(1)
            .causeNonAdhesion("causeNonAdhesion1")
            .typeActivitePhysique("typeActivitePhysique1")
            .typeSequelles("typeSequelles1")
            .ageDeces(1)
            .autreEvenementDetails("autreEvenementDetails1");
    }

    public static FicheFacteurVIII getFicheFacteurVIIISample2() {
        return new FicheFacteurVIII()
            .id(2L)
            .dossierNumber("dossierNumber2")
            .ordreNumber("ordreNumber2")
            .indexNumber("indexNumber2")
            .prenom("prenom2")
            .nom("nom2")
            .nomJeuneFille("nomJeuneFille2")
            .profession("profession2")
            .autreServiceClinique("autreServiceClinique2")
            .ageActuel(2)
            .autreOrigine("autreOrigine2")
            .adresse("adresse2")
            .telephone("telephone2")
            .prenomPere("prenomPere2")
            .professionPere("professionPere2")
            .nomPrenomMere("nomPrenomMere2")
            .professionMere("professionMere2")
            .medecinTraitant("medecinTraitant2")
            .serviceOrigine("serviceOrigine2")
            .biologisteResponsableDg("biologisteResponsableDg2")
            .autreDiagnostic("autreDiagnostic2")
            .anneeDiagnostic(2)
            .nombreCas(2)
            .cas1Numero(2)
            .degreParenteCas1("degreParenteCas12")
            .typeHemorragieCas1("typeHemorragieCas12")
            .cas2Numero(2)
            .degreParenteCas2("degreParenteCas22")
            .typeHemorragieCas2("typeHemorragieCas22")
            .cas3Numero(2)
            .degreParenteCas3("degreParenteCas32")
            .typeHemorragieCas3("typeHemorragieCas32")
            .nombreDeces(2)
            .deces1Numero(2)
            .causeDeces1("causeDeces12")
            .deces2Numero(2)
            .causeDeces2("causeDeces22")
            .deces3Numero(2)
            .causeDeces3("causeDeces32")
            .ageDiagnosticJour(2)
            .ageDiagnosticMois(2)
            .ageDiagnosticAnnee(2)
            .plaquettes(2)
            .frequenceEpistaxis(2)
            .frequenceGingivorragies(2)
            .frequenceEcchymose(2)
            .frequenceMenorragie(2)
            .frequenceHematemese(2)
            .frequenceRectorragie(2)
            .frequenceHematurie(2)
            .frequenceHematomeSousCutane(2)
            .siegeHematomeMusculaire("siegeHematomeMusculaire2")
            .frequenceHematomeMusculaire(2)
            .frequenceHemarthrose(2)
            .frequenceSaignementSNC(2)
            .ageCirconcision(2)
            .causeNonAdhesion("causeNonAdhesion2")
            .typeActivitePhysique("typeActivitePhysique2")
            .typeSequelles("typeSequelles2")
            .ageDeces(2)
            .autreEvenementDetails("autreEvenementDetails2");
    }

    public static FicheFacteurVIII getFicheFacteurVIIIRandomSampleGenerator() {
        return new FicheFacteurVIII()
            .id(longCount.incrementAndGet())
            .dossierNumber(UUID.randomUUID().toString())
            .ordreNumber(UUID.randomUUID().toString())
            .indexNumber(UUID.randomUUID().toString())
            .prenom(UUID.randomUUID().toString())
            .nom(UUID.randomUUID().toString())
            .nomJeuneFille(UUID.randomUUID().toString())
            .profession(UUID.randomUUID().toString())
            .autreServiceClinique(UUID.randomUUID().toString())
            .ageActuel(intCount.incrementAndGet())
            .autreOrigine(UUID.randomUUID().toString())
            .adresse(UUID.randomUUID().toString())
            .telephone(UUID.randomUUID().toString())
            .prenomPere(UUID.randomUUID().toString())
            .professionPere(UUID.randomUUID().toString())
            .nomPrenomMere(UUID.randomUUID().toString())
            .professionMere(UUID.randomUUID().toString())
            .medecinTraitant(UUID.randomUUID().toString())
            .serviceOrigine(UUID.randomUUID().toString())
            .biologisteResponsableDg(UUID.randomUUID().toString())
            .autreDiagnostic(UUID.randomUUID().toString())
            .anneeDiagnostic(intCount.incrementAndGet())
            .nombreCas(intCount.incrementAndGet())
            .cas1Numero(intCount.incrementAndGet())
            .degreParenteCas1(UUID.randomUUID().toString())
            .typeHemorragieCas1(UUID.randomUUID().toString())
            .cas2Numero(intCount.incrementAndGet())
            .degreParenteCas2(UUID.randomUUID().toString())
            .typeHemorragieCas2(UUID.randomUUID().toString())
            .cas3Numero(intCount.incrementAndGet())
            .degreParenteCas3(UUID.randomUUID().toString())
            .typeHemorragieCas3(UUID.randomUUID().toString())
            .nombreDeces(intCount.incrementAndGet())
            .deces1Numero(intCount.incrementAndGet())
            .causeDeces1(UUID.randomUUID().toString())
            .deces2Numero(intCount.incrementAndGet())
            .causeDeces2(UUID.randomUUID().toString())
            .deces3Numero(intCount.incrementAndGet())
            .causeDeces3(UUID.randomUUID().toString())
            .ageDiagnosticJour(intCount.incrementAndGet())
            .ageDiagnosticMois(intCount.incrementAndGet())
            .ageDiagnosticAnnee(intCount.incrementAndGet())
            .plaquettes(intCount.incrementAndGet())
            .frequenceEpistaxis(intCount.incrementAndGet())
            .frequenceGingivorragies(intCount.incrementAndGet())
            .frequenceEcchymose(intCount.incrementAndGet())
            .frequenceMenorragie(intCount.incrementAndGet())
            .frequenceHematemese(intCount.incrementAndGet())
            .frequenceRectorragie(intCount.incrementAndGet())
            .frequenceHematurie(intCount.incrementAndGet())
            .frequenceHematomeSousCutane(intCount.incrementAndGet())
            .siegeHematomeMusculaire(UUID.randomUUID().toString())
            .frequenceHematomeMusculaire(intCount.incrementAndGet())
            .frequenceHemarthrose(intCount.incrementAndGet())
            .frequenceSaignementSNC(intCount.incrementAndGet())
            .ageCirconcision(intCount.incrementAndGet())
            .causeNonAdhesion(UUID.randomUUID().toString())
            .typeActivitePhysique(UUID.randomUUID().toString())
            .typeSequelles(UUID.randomUUID().toString())
            .ageDeces(intCount.incrementAndGet())
            .autreEvenementDetails(UUID.randomUUID().toString());
    }
}
