import dayjs from 'dayjs/esm';

import { IFicheFacteurVII, NewFicheFacteurVII } from './fiche-facteur-vii.model';

export const sampleWithRequiredData: IFicheFacteurVII = {
  id: 19090,
  etatCivil: 'MARIE',
  serviceClinique: 'PEDIATRIE_B',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  diagnostic: 'DEFICIT_FACTEUR_VII',
};

export const sampleWithPartialData: IFicheFacteurVII = {
  id: 8963,
  dossierNumber: 'de peur que horrible',
  nom: 'intégrer',
  nomJeuneFille: 'conformer',
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'GYNECO',
  autreServiceClinique: 'tant',
  couvertureSociale: 'NP',
  sexe: 'MASCULIN',
  origine: 'KAIRAOUANE',
  autreOrigine: 'croître d’autant que équi',
  professionPere: 'extra plouf habile',
  nomPrenomMere: 'du fait que',
  medecinTraitant: 'de crainte que accroître',
  diagnostic: 'DEFICIT_FACTEUR_XI',
  parentsConsanguins: 'NP',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  casSimilaires: 'OUI',
  cas1Numero: 3426,
  degreParenteCas1: 'à la faveur de',
  typeHemorragieCas1: 'cot cot',
  cas2Numero: 10703,
  lienParenteCas3: 'FRERE',
  degreParenteCas3: 'préoccuper',
  typeHemorragieCas3: 'membre de l’équipe',
  causeDeces1: 'miam',
  lienParenteDeces2: 'FRERE',
  decouverteFortuite: true,
  enqueteFamilialeBool: false,
  explorationSyndromeHemorragique: true,
  ageDiagnosticMois: 32365,
  ageDiagnosticAnnee: 26001,
  hb: 11226.17,
  toPfa200ColAdp: 2098.65,
  tpMT: 10730.14,
  tcaMT: 26960.27,
  facteurVII: 11421.19,
  confirmationMoleculaire: 'FAITE',
  mutationType: 'AUCUNE',
  epistaxis: false,
  frequenceEpistaxis: 27640,
  gingivorragies: true,
  typeGingivorragies: 'SPONTANE',
  ecchymose: false,
  frequenceEcchymose: 30774,
  frequenceHematemese: 29922,
  rectorragie: false,
  frequenceRectorragie: 8995,
  hematurie: false,
  typeHematomeSousCutane: 'SPONTANE',
  frequenceHematomeSousCutane: 1344,
  siegeHematomeMusculaire: 'du fait que',
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 16814,
  hemarthrose: true,
  typeSaignementSNC: 'SPONTANE',
  typeAccidentsThrombotiques: 'ARTERIEL',
  hemorragieGrave: false,
  typeHemorragieGrave: 'PAR_LA_LOCALISATION',
  chirurgiePrepare: 'NP',
  circoncisionPrepare: 'NP',
  ageCirconcision: 22756,
  facteurVIIRecombinant: 'NP',
  culotsPlaquettaires: 'NP',
  dicynone: 'OUI',
  exacyl: 'OUI',
  traitementMartial: 'OUI',
  transfusionCGR: 'NON',
  titreUB: 5690.04,
  inhibiteurNonNeutralisant: true,
  alloImmunisation: 'OUI',
  adhesionTherapeutique: 'OUI',
  causeNonAdhesion: 'à bas de',
  activitePhysique: 'OUI',
  sequelles: 'NP',
  typeSequelles: 'actionnaire',
  patientDecede: 'OUI',
  dateDeces: dayjs('2025-02-16'),
  hemorragieSnc: true,
  hiv: false,
  evenementThromboembolique: true,
  cancer: false,
  inconnue: false,
};

export const sampleWithFullData: IFicheFacteurVII = {
  id: 3246,
  dossierNumber: 'triste selon',
  ordreNumber: 'sauf par rapport à',
  indexNumber: 'malgré',
  prenom: 'vouh de crainte que commi',
  nom: 'à moins de miam hormis',
  nomJeuneFille: 'chez ressortir',
  profession: 'vu que horrible athlète',
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'GYNECO',
  autreServiceClinique: 'sous couleur de jusqu’à ce que',
  couvertureSociale: 'NP',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-15'),
  ageActuel: 30579,
  origine: 'SBZ',
  autreOrigine: 'miaou athlète',
  adresse: 'assez alors',
  telephone: '+33 525785803',
  prenomPere: 'psitt égoïste',
  professionPere: 'patientèle de sorte que r',
  nomPrenomMere: 'sombre',
  professionMere: 'sur',
  medecinTraitant: 'orange affronter',
  serviceOrigine: 'permettre',
  biologisteResponsableDg: 'plutôt à côté de',
  diagnostic: 'DEFICIT_FACTEUR_XI',
  autreDiagnostic: 'assez émérite tout',
  anneeDiagnostic: 31005,
  consentementRegistre: 'NON',
  dateEnregistrementRegistre: dayjs('2025-02-16'),
  parentsConsanguins: 'NON',
  degreParenteConsanguins: 'LOINTAIN',
  casSimilaires: 'NP',
  nombreCas: 15580,
  cas1Numero: 25458,
  lienParenteCas1: 'FRERE',
  degreParenteCas1: 'biathlète tsoin-tsoin',
  typeHemorragieCas1: 'tôt',
  cas2Numero: 3177,
  lienParenteCas2: 'FRERE',
  degreParenteCas2: 'dans la mesure où avant q',
  typeHemorragieCas2: 'voler',
  cas3Numero: 20978,
  lienParenteCas3: 'LOINTAIN',
  degreParenteCas3: 'à force de membre du pers',
  typeHemorragieCas3: 'groin groin',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 31602,
  deces1Numero: 24227,
  lienParenteDeces1: 'COUSIN',
  causeDeces1: 'prout',
  deces2Numero: 27745,
  lienParenteDeces2: 'LOINTAIN',
  causeDeces2: 'accomplir ouille édifier',
  deces3Numero: 3110,
  lienParenteDeces3: 'COUSIN',
  causeDeces3: 'à raison de devant',
  enqueteFamiliale: 'NONFAITE',
  decouverteFortuite: false,
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: false,
  typeExplorationSyndromeHemorragique: 'CUTANEO_MUQUEUX',
  datePremierSigneClinique: dayjs('2025-02-16'),
  ageDiagnosticJour: 18403,
  ageDiagnosticMois: 27835,
  ageDiagnosticAnnee: 28399,
  hb: 8296.77,
  ht: 28517.16,
  plaquettes: 32552,
  toPfa200ColEpi: 10764,
  toPfa200ColAdp: 24711.12,
  tp: 987.8,
  tpMT: 24491.94,
  fibrinogene: 21949.76,
  tcaMT: 13794.92,
  facteurVII: 12230.36,
  dosageAutresFacteurs: 'quoique',
  confirmationMoleculaire: 'FAITE',
  mutationPresence: false,
  mutationType: 'AUCUNE',
  epistaxis: true,
  frequenceEpistaxis: 11769,
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 582,
  ecchymose: true,
  typeEcchymose: 'SPONTANE',
  frequenceEcchymose: 27054,
  menorragie: false,
  frequenceMenorragie: 135,
  hematemese: false,
  frequenceHematemese: 25417,
  rectorragie: true,
  frequenceRectorragie: 26204,
  hematurie: false,
  frequenceHematurie: 2569,
  hematomeSousCutane: true,
  typeHematomeSousCutane: 'SPONTANE',
  frequenceHematomeSousCutane: 18425,
  hematomeMusculaire: false,
  siegeHematomeMusculaire: 'contre',
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 16697,
  hemarthrose: true,
  typeHemarthrose: 'SPONTANE',
  frequenceHemarthrose: 237,
  saignementSNC: false,
  typeSaignementSNC: 'SPONTANE',
  frequenceSaignementSNC: 30069,
  ruptureKystesHemorragiques: false,
  hemorragiesPostChirurgicales: true,
  hemoperitone: false,
  accidentsThrombotiques: false,
  typeAccidentsThrombotiques: 'ARTERIEL',
  hemorragieGrave: false,
  typeHemorragieGrave: 'PAR_LA_LOCALISATION',
  chirurgiePrepare: 'NP',
  suiteOperatoireHemorragique: 'NP',
  circoncisionPrepare: 'NON',
  suiteOperatoireCirconcision: 'OUI',
  ageCirconcision: 1196,
  facteurVIIRecombinant: 'OUI',
  plasmaFraisCongele: 'NP',
  cryoprecipite: 'OUI',
  culotsPlaquettaires: 'NP',
  dicynone: 'NP',
  exacyl: 'NON',
  traitementMartial: 'NP',
  traitementOestroprogestatif: 'OUI',
  transfusionCGR: 'OUI',
  inhibiteurs: 'NP',
  inhibiteurNeutralisant: true,
  titreUB: 20783.77,
  inhibiteurNonNeutralisant: true,
  infectionsVirales: 'NON',
  thrombose: 'NP',
  reactionAllergique: 'OUI',
  alloImmunisation: 'NON',
  adhesionTherapeutique: 'NP',
  causeNonAdhesion: 'toc-toc envers',
  vieSociale: 'SCOLARISE',
  mariage: 'NP',
  enfants: 'NON',
  activitePhysique: 'OUI',
  typeActivitePhysique: 'exagérer',
  sequelles: 'NP',
  typeSequelles: 'miaou',
  patientDecede: 'NON',
  dateDeces: dayjs('2025-02-15'),
  ageDeces: 6072,
  hemorragieSnc: true,
  hemorragieAutreQueSnc: true,
  hiv: false,
  autreInfection: true,
  evenementThromboembolique: true,
  cancer: false,
  covid19: false,
  inconnue: false,
  autreEvenement: true,
  autreEvenementDetails: 'instruire jusque renvoyer',
};

export const sampleWithNewData: NewFicheFacteurVII = {
  etatCivil: 'NP',
  serviceClinique: 'PEDIATRIE_A',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
