import dayjs from 'dayjs/esm';

import { IFicheFacteurVII, NewFicheFacteurVII } from './fiche-facteur-vii.model';

export const sampleWithRequiredData: IFicheFacteurVII = {
  id: 29096,
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'AUTRE',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
};

export const sampleWithPartialData: IFicheFacteurVII = {
  id: 25459,
  ordreNumber: 'de sorte que magenta',
  indexNumber: 'devant en outre de ha ha',
  profession: 'tellement',
  etatCivil: 'NP',
  serviceClinique: 'PUR',
  autreServiceClinique: 'à condition que membre titulaire au cas où',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-02-16'),
  ageActuel: 15386,
  professionPere: 'porte-parole extrêmement',
  professionMere: 'complètement',
  medecinTraitant: 'guide',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  autreDiagnostic: 'boum snob',
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-15'),
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  nombreCas: 17836,
  cas1Numero: 28579,
  typeHemorragieCas1: 'cyan',
  lienParenteCas2: 'COUSIN',
  cas3Numero: 15433,
  lienParenteCas3: 'COUSIN',
  degreParenteCas3: 'pour',
  typeHemorragieCas3: 'mélancolique déjà procurer',
  decesSyndromeHemorragique: 'NON',
  lienParenteDeces1: 'COUSIN',
  causeDeces1: 'magenta diététiste en faveur de',
  causeDeces2: 'précisément',
  lienParenteDeces3: 'LOINTAIN',
  enqueteFamiliale: 'NONFAITE',
  decouverteFortuite: true,
  enqueteFamilialeBool: false,
  ht: 31912.57,
  plaquettes: 20249,
  toPfa200ColEpi: 15669.29,
  toPfa200ColAdp: 26843,
  tpMT: 24543.45,
  dosageAutresFacteurs: 'présidence paf quelquefois',
  mutationPresence: true,
  mutationType: 'HETEROZYGOTE',
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  ecchymose: true,
  hematemese: false,
  frequenceHematemese: 23401,
  hematurie: false,
  frequenceHematurie: 26788,
  hematomeSousCutane: true,
  hematomeMusculaire: false,
  siegeHematomeMusculaire: 'jamais ici loin',
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 28670,
  frequenceHemarthrose: 4093,
  saignementSNC: true,
  typeSaignementSNC: 'PROVOQUE',
  frequenceSaignementSNC: 5824,
  hemorragiesPostChirurgicales: false,
  typeAccidentsThrombotiques: 'ARTERIEL',
  hemorragieGrave: true,
  typeHemorragieGrave: 'DEGLOBULISATION',
  chirurgiePrepare: 'NON',
  suiteOperatoireHemorragique: 'NP',
  circoncisionPrepare: 'NON',
  plasmaFraisCongele: 'OUI',
  dicynone: 'NON',
  traitementMartial: 'OUI',
  inhibiteurs: 'OUI',
  infectionsVirales: 'NON',
  reactionAllergique: 'NON',
  adhesionTherapeutique: 'NP',
  activitePhysique: 'NP',
  sequelles: 'NP',
  typeSequelles: 'membre à vie',
  ageDeces: 26247,
  hemorragieAutreQueSnc: false,
  autreInfection: false,
  evenementThromboembolique: true,
  covid19: false,
  inconnue: false,
  autreEvenement: false,
  autreEvenementDetails: 'en',
};

export const sampleWithFullData: IFicheFacteurVII = {
  id: 3846,
  dossierNumber: 'aussitôt que',
  ordreNumber: 'corps enseignant depuis p',
  indexNumber: 'bè',
  prenom: 'gigantesque corps enseign',
  nom: 'grrr',
  nomJeuneFille: 'oh',
  profession: 'commissionnaire',
  etatCivil: 'NP',
  serviceClinique: 'PEDIATRIE_B',
  autreServiceClinique: 'coïncider ci hebdomadaire',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-16'),
  ageActuel: 29504,
  origine: 'KASSERINE',
  autreOrigine: 'également habile',
  adresse: 'badaboum juger amorphe',
  telephone: '+33 786845432',
  prenomPere: 'extrêmement garder',
  professionPere: 'arrière épouser',
  nomPrenomMere: 'de façon que snif parfois',
  professionMere: 'tant que',
  medecinTraitant: 'lorsque ouille',
  serviceOrigine: 'coin-coin',
  biologisteResponsableDg: 'classer au prix de',
  diagnostic: 'DEFICIT_FACTEUR_XI',
  autreDiagnostic: 'patientèle sage tchou tch',
  anneeDiagnostic: 21835,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-15'),
  parentsConsanguins: 'NP',
  degreParenteConsanguins: 'TROISIEME_DEGRE',
  casSimilaires: 'OUI',
  nombreCas: 3047,
  cas1Numero: 29859,
  lienParenteCas1: 'COUSIN',
  degreParenteCas1: 'dedans amorphe minuscule',
  typeHemorragieCas1: 'extra concernant',
  cas2Numero: 19616,
  lienParenteCas2: 'FRERE',
  degreParenteCas2: 'fêter administration',
  typeHemorragieCas2: 'charitable suffisamment',
  cas3Numero: 20472,
  lienParenteCas3: 'COUSIN',
  degreParenteCas3: 'personnel expliquer',
  typeHemorragieCas3: 'paf via snif',
  decesSyndromeHemorragique: 'NP',
  nombreDeces: 20687,
  deces1Numero: 8975,
  lienParenteDeces1: 'LOINTAIN',
  causeDeces1: 'loin de secours',
  deces2Numero: 18129,
  lienParenteDeces2: 'LOINTAIN',
  causeDeces2: 'ha ha mairie alors',
  deces3Numero: 29627,
  lienParenteDeces3: 'COUSIN',
  causeDeces3: 'même si',
  enqueteFamiliale: 'NONFAITE',
  decouverteFortuite: true,
  enqueteFamilialeBool: true,
  explorationSyndromeHemorragique: true,
  typeExplorationSyndromeHemorragique: 'HEMORRAGIE_POSTPARTUM',
  datePremierSigneClinique: dayjs('2025-02-16'),
  ageDiagnosticJour: 21352,
  ageDiagnosticMois: 29326,
  ageDiagnosticAnnee: 22250,
  hb: 1332.8,
  ht: 32477.7,
  plaquettes: 6957,
  toPfa200ColEpi: 2720.05,
  toPfa200ColAdp: 29429.8,
  tp: 12052.48,
  tpMT: 6048.37,
  fibrinogene: 6802.67,
  tcaMT: 29676.35,
  facteurVII: 24767.67,
  dosageAutresFacteurs: 'y',
  confirmationMoleculaire: 'FAITE',
  mutationPresence: false,
  mutationType: 'HOMOZYGOTE',
  epistaxis: false,
  frequenceEpistaxis: 13884,
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 2391,
  ecchymose: false,
  typeEcchymose: 'PROVOQUE',
  frequenceEcchymose: 23607,
  menorragie: false,
  frequenceMenorragie: 5720,
  hematemese: true,
  frequenceHematemese: 1616,
  rectorragie: false,
  frequenceRectorragie: 32636,
  hematurie: false,
  frequenceHematurie: 26712,
  hematomeSousCutane: true,
  typeHematomeSousCutane: 'SPONTANE',
  frequenceHematomeSousCutane: 20023,
  hematomeMusculaire: false,
  siegeHematomeMusculaire: 'triste tant bzzz',
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 24418,
  hemarthrose: true,
  typeHemarthrose: 'SPONTANE',
  frequenceHemarthrose: 13388,
  saignementSNC: false,
  typeSaignementSNC: 'PROVOQUE',
  frequenceSaignementSNC: 15578,
  ruptureKystesHemorragiques: false,
  hemorragiesPostChirurgicales: true,
  hemoperitone: true,
  accidentsThrombotiques: false,
  typeAccidentsThrombotiques: 'VEINEUX',
  hemorragieGrave: true,
  typeHemorragieGrave: 'DEGLOBULISATION',
  chirurgiePrepare: 'NON',
  suiteOperatoireHemorragique: 'NON',
  circoncisionPrepare: 'NON',
  suiteOperatoireCirconcision: 'NON',
  ageCirconcision: 24272,
  facteurVIIRecombinant: 'OUI',
  plasmaFraisCongele: 'OUI',
  cryoprecipite: 'NON',
  culotsPlaquettaires: 'NON',
  dicynone: 'OUI',
  exacyl: 'NON',
  traitementMartial: 'OUI',
  traitementOestroprogestatif: 'NP',
  transfusionCGR: 'NON',
  inhibiteurs: 'OUI',
  inhibiteurNeutralisant: false,
  titreUB: 1527.02,
  inhibiteurNonNeutralisant: true,
  infectionsVirales: 'NP',
  thrombose: 'NP',
  reactionAllergique: 'NP',
  alloImmunisation: 'NP',
  adhesionTherapeutique: 'NP',
  causeNonAdhesion: 'proche à travers inspecter',
  vieSociale: 'TRAVAILLE',
  mariage: 'OUI',
  enfants: 'NON',
  activitePhysique: 'NON',
  typeActivitePhysique: 'si',
  sequelles: 'OUI',
  typeSequelles: 'parlementaire chef de cuisine falloir',
  patientDecede: 'NON',
  dateDeces: dayjs('2025-02-15'),
  ageDeces: 7868,
  hemorragieSnc: false,
  hemorragieAutreQueSnc: false,
  hiv: true,
  autreInfection: false,
  evenementThromboembolique: true,
  cancer: true,
  covid19: true,
  inconnue: true,
  autreEvenement: true,
  autreEvenementDetails: 'franco',
};

export const sampleWithNewData: NewFicheFacteurVII = {
  etatCivil: 'NP',
  serviceClinique: 'GYNECO',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
