package org.adhes.hemostase.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FicheHemophilieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieAllPropertiesEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertFicheHemophilieAutoGeneratedPropertiesEquals(expected, actual);
        assertFicheHemophilieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieAllUpdatablePropertiesEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertFicheHemophilieUpdatableFieldsEquals(expected, actual);
        assertFicheHemophilieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieAutoGeneratedPropertiesEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertThat(expected)
            .as("Verify FicheHemophilie auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieUpdatableFieldsEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertThat(expected)
            .as("Verify FicheHemophilie relevant properties")
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getNomJeuneFille()).as("check nomJeuneFille").isEqualTo(actual.getNomJeuneFille()))
            .satisfies(e -> assertThat(e.getProfession()).as("check profession").isEqualTo(actual.getProfession()))
            .satisfies(e -> assertThat(e.getSexe()).as("check sexe").isEqualTo(actual.getSexe()))
            .satisfies(e -> assertThat(e.getDateNaissance()).as("check dateNaissance").isEqualTo(actual.getDateNaissance()))
            .satisfies(e -> assertThat(e.getAgeActuel()).as("check ageActuel").isEqualTo(actual.getAgeActuel()))
            .satisfies(e -> assertThat(e.getOrigine()).as("check origine").isEqualTo(actual.getOrigine()))
            .satisfies(e -> assertThat(e.getAutreOrigine()).as("check autreOrigine").isEqualTo(actual.getAutreOrigine()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getEtatCivil()).as("check etatCivil").isEqualTo(actual.getEtatCivil()))
            .satisfies(e -> assertThat(e.getCouvertureSociale()).as("check couvertureSociale").isEqualTo(actual.getCouvertureSociale()))
            .satisfies(e -> assertThat(e.getPrenomPere()).as("check prenomPere").isEqualTo(actual.getPrenomPere()))
            .satisfies(e -> assertThat(e.getProfessionPere()).as("check professionPere").isEqualTo(actual.getProfessionPere()))
            .satisfies(e -> assertThat(e.getNomPrenomMere()).as("check nomPrenomMere").isEqualTo(actual.getNomPrenomMere()))
            .satisfies(e -> assertThat(e.getProfessionMere()).as("check professionMere").isEqualTo(actual.getProfessionMere()))
            .satisfies(e -> assertThat(e.getMedecinTraitant()).as("check medecinTraitant").isEqualTo(actual.getMedecinTraitant()))
            .satisfies(e -> assertThat(e.getServiceOrigine()).as("check serviceOrigine").isEqualTo(actual.getServiceOrigine()))
            .satisfies(e ->
                assertThat(e.getBiologisteResponsableDg())
                    .as("check biologisteResponsableDg")
                    .isEqualTo(actual.getBiologisteResponsableDg())
            )
            .satisfies(e -> assertThat(e.getDiagnostic()).as("check diagnostic").isEqualTo(actual.getDiagnostic()))
            .satisfies(e -> assertThat(e.getAutreDiagnostic()).as("check autreDiagnostic").isEqualTo(actual.getAutreDiagnostic()))
            .satisfies(e -> assertThat(e.getAnneeDiagnostic()).as("check anneeDiagnostic").isEqualTo(actual.getAnneeDiagnostic()))
            .satisfies(e ->
                assertThat(e.getConsentementRegistre()).as("check consentementRegistre").isEqualTo(actual.getConsentementRegistre())
            )
            .satisfies(e ->
                assertThat(e.getDateEnregistrementRegistre())
                    .as("check dateEnregistrementRegistre")
                    .isEqualTo(actual.getDateEnregistrementRegistre())
            )
            .satisfies(e -> assertThat(e.getDossierNumber()).as("check dossierNumber").isEqualTo(actual.getDossierNumber()))
            .satisfies(e -> assertThat(e.getOrdreNumber()).as("check ordreNumber").isEqualTo(actual.getOrdreNumber()))
            .satisfies(e -> assertThat(e.getIndexNumber()).as("check indexNumber").isEqualTo(actual.getIndexNumber()))
            .satisfies(e ->
                assertThat(e.getDegreParenteConsanguins())
                    .as("check degreParenteConsanguins")
                    .isEqualTo(actual.getDegreParenteConsanguins())
            )
            .satisfies(e ->
                assertThat(e.getDegreParenteCasSimilaires())
                    .as("check degreParenteCasSimilaires")
                    .isEqualTo(actual.getDegreParenteCasSimilaires())
            )
            .satisfies(e ->
                assertThat(e.getTypeHemorragiesCutaneoMuqueuses())
                    .as("check typeHemorragiesCutaneoMuqueuses")
                    .isEqualTo(actual.getTypeHemorragiesCutaneoMuqueuses())
            )
            .satisfies(e ->
                assertThat(e.getCirconstanceHematomeSuperficiel())
                    .as("check circonstanceHematomeSuperficiel")
                    .isEqualTo(actual.getCirconstanceHematomeSuperficiel())
            )
            .satisfies(e ->
                assertThat(e.getSiegeHematomeSuperficiel())
                    .as("check siegeHematomeSuperficiel")
                    .isEqualTo(actual.getSiegeHematomeSuperficiel())
            )
            .satisfies(e ->
                assertThat(e.getCirconstanceHematomePsoas())
                    .as("check circonstanceHematomePsoas")
                    .isEqualTo(actual.getCirconstanceHematomePsoas())
            )
            .satisfies(e ->
                assertThat(e.getCirconstanceAccidentsHemorragiquesGraves())
                    .as("check circonstanceAccidentsHemorragiquesGraves")
                    .isEqualTo(actual.getCirconstanceAccidentsHemorragiquesGraves())
            )
            .satisfies(e ->
                assertThat(e.getTypeInterventionChirurgicale())
                    .as("check typeInterventionChirurgicale")
                    .isEqualTo(actual.getTypeInterventionChirurgicale())
            )
            .satisfies(e -> assertThat(e.getCausePriseEnCharge()).as("check causePriseEnCharge").isEqualTo(actual.getCausePriseEnCharge()))
            .satisfies(e -> assertThat(e.getPosologieITI()).as("check posologieITI").isEqualTo(actual.getPosologieITI()))
            .satisfies(e -> assertThat(e.getDureeITI()).as("check dureeITI").isEqualTo(actual.getDureeITI()))
            .satisfies(e ->
                assertThat(e.getCauseNonObservanceITI()).as("check causeNonObservanceITI").isEqualTo(actual.getCauseNonObservanceITI())
            )
            .satisfies(e -> assertThat(e.getTypeHandicap()).as("check typeHandicap").isEqualTo(actual.getTypeHandicap()))
            .satisfies(e ->
                assertThat(e.getTypeActiviteSportive()).as("check typeActiviteSportive").isEqualTo(actual.getTypeActiviteSportive())
            )
            .satisfies(e -> assertThat(e.getCauseDateDeces()).as("check causeDateDeces").isEqualTo(actual.getCauseDateDeces()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieUpdatableRelationshipsEquals(FicheHemophilie expected, FicheHemophilie actual) {
        // empty method
    }
}
