import dayjs from 'dayjs/esm';

import { IFicheFacteurXI, NewFicheFacteurXI } from './fiche-facteur-xi.model';

export const sampleWithRequiredData: IFicheFacteurXI = {
  id: 23083,
  etatCivil: 'DIVORCE',
  serviceClinique: 'PEDIATRIE_B',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  diagnostic: 'HEMOPHILIE',
};

export const sampleWithPartialData: IFicheFacteurXI = {
  id: 17479,
  ordreNumber: 'communauté étudiante foul',
  indexNumber: 'fade enregistrer',
  nom: 'assurer débrouiller',
  nomJeuneFille: 'passablement jadis',
  profession: "porte-parole à l'exceptio",
  etatCivil: 'MARIE',
  serviceClinique: 'HTO',
  autreServiceClinique: 'surmonter lors de',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  ageActuel: 23569,
  autreOrigine: 'près',
  adresse: 'aïe pin-pon',
  telephone: '+33 352055664',
  professionPere: 'tirer trop peu énorme',
  medecinTraitant: 'près ouch suivant',
  serviceOrigine: 'doucement',
  biologisteResponsableDg: 'rose',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  autreDiagnostic: 'hisser',
  parentsConsanguins: 'NON',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  cas1Numero: 20772,
  degreParenteCas1: 'au prix de dans la mesure',
  typeHemorragieCas2: 'cadre',
  cas3Numero: 25348,
  lienParenteCas3: 'LOINTAIN',
  typeHemorragieCas3: 'camarade coller',
  decesSyndromeHemorragique: 'OUI',
  deces1Numero: 28659,
  causeDeces1: "d'entre",
  deces2Numero: 5512,
  lienParenteDeces2: 'LOINTAIN',
  causeDeces2: 'dès que amener',
  deces3Numero: 11158,
  precisionSyndromeHemorragique: 'plus attarder concurrence',
  jamaisSaigne: 'NON',
  agePremierSigneCliniqueJours: 10797,
  agePremierSigneCliniqueMois: 25775,
  agePremierSigneCliniqueAnnees: 586,
  symptomeEpistaxis: false,
  symptomeHemoptysie: false,
  symptomeHemorragiePostAmygdalectomie: false,
  symptomeHemorragiePostAvulsionDentaire: true,
  datePremiereConsultation: dayjs('2025-05-08'),
  agePremiereConsultationJours: 17294,
  agePremiereConsultationMois: 20031,
  agePremiereConsultationAnnees: 4078,
  ageDiagnosticAnnees: 17892,
  hb: 29980,
  plaquettes: 13002,
  pfaColADP: 5553.34,
  facteurXI: 16902,
  autresFacteursDosageDescription: 'au-dessus de',
  autresFacteursTaux2: 10697.11,
  autresFacteursTaux3: 15140.61,
  confirmationMoleculaire: 'NONFAITE',
  mutation2Nom: 'ramener négliger quasi',
  serologieVHB: 'NON',
  serologieVHC: 'NON',
  serologieVIH: 'NON',
  frequenceEpistaxis: 24884,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 23040,
  typeEcchymose: 'SPONTANE',
  frequenceEcchymose: 20084,
  hematemese: false,
  frequenceHematemese: 3831,
  frequenceHematurie: 28735,
  frequenceHemorragiePostTraumatique: 5465,
  typeHematomeSousCutane: 'SPONTANE',
  typeHematomeTissusMousProfonds: 'PROVOQUE',
  frequenceHematomeTissusMousProfonds: 3630,
  typeHemarthrose: 'SPONTANE',
  frequenceHemarthrose: 9302,
  frequenceSaignementSNC: 23055,
  frequenceSaignementChuteCordon: 566,
  frequenceFaussesCouches: 2020,
  thromboseArterielle: true,
  hemoperitoine: false,
  ruptureKystesHemorragiques: true,
  frequenceRuptureKystes: 26989,
  hemorragieGrave: true,
  frequenceHemorragieGrave: 18720,
  graviteEtatDeChoc: true,
  graviteParLocalisation: true,
  siegeGraviteLocalisation: 'collègue',
  chirurgiePrepare: 'NON',
  chirurgieSuiteHemorragique: 'NON',
  circoncisionSuiteHemorragique: 'NON',
  ageCirconcision: 23253,
  traitementCryoprecipite: 'NP',
  traitementExacyl: 'NON',
  traitementOestroprogestatif: 'OUI',
  titreInhibiteurUB: 28653.34,
  inhibiteurNonNeutralisant: 'OUI',
  infectionVHC: 'NON',
  thrombose: false,
  reactionAllergique: false,
  autresComplications: 'aïe quasiment là',
  adherenceTherapeutique: 'NON',
  causeNonAdherence: 'considérable innombrable',
  typeActivitePhysique: 'assez',
  dateDeces: dayjs('2025-05-08'),
  ageDeces: 1183,
};

export const sampleWithFullData: IFicheFacteurXI = {
  id: 14745,
  dossierNumber: 'faire drelin',
  ordreNumber: 'brouiller vétuste déborde',
  indexNumber: 'bzzz',
  prenom: 'meuh',
  nom: 'cyan plaire',
  nomJeuneFille: 'tchou tchouu',
  profession: 'au cas où',
  etatCivil: 'MARIE',
  serviceClinique: 'PRIVE',
  autreServiceClinique: 'semer',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-05-08'),
  ageActuel: 453,
  origine: 'SOUSSE',
  autreOrigine: 'sauf',
  adresse: 'risquer probablement',
  telephone: '+33 612009554',
  prenomPere: 'population du Québec',
  professionPere: 'énorme',
  nomPrenomMere: 'ha badaboum assez',
  professionMere: 'élever',
  medecinTraitant: 'sale regagner',
  serviceOrigine: 'ouin clientèle sauvegarde',
  biologisteResponsableDg: 'proche de bien que',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  autreDiagnostic: 'aïe maintenant épuiser',
  anneeDiagnostic: 24911,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-05-08'),
  parentsConsanguins: 'NON',
  degreParenteConsanguins: 'QUATRIEME_DEGRE',
  casSimilaires: 'NON',
  nombreCas: 4174,
  cas1Numero: 10964,
  lienParenteCas1: 'FRERE',
  degreParenteCas1: 'bien que',
  typeHemorragieCas1: 'du moment que envers',
  cas2Numero: 13448,
  lienParenteCas2: 'FRERE',
  degreParenteCas2: 'pénétrer électorat dès qu',
  typeHemorragieCas2: 'lorsque efficace',
  cas3Numero: 2155,
  lienParenteCas3: 'LOINTAIN',
  degreParenteCas3: 'aïe',
  typeHemorragieCas3: 'plouf au prix de infiniment',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 6192,
  deces1Numero: 6023,
  lienParenteDeces1: 'FRERE',
  causeDeces1: 'moyennant',
  deces2Numero: 3424,
  lienParenteDeces2: 'FRERE',
  causeDeces2: 'instituer responsable',
  deces3Numero: 17905,
  lienParenteDeces3: 'FRERE',
  causeDeces3: 'sédentaire',
  enqueteFamiliale: 'NP',
  syndromeHemorragique: 'OUI',
  precisionSyndromeHemorragique: 'bang',
  decouverteFortuite: 'NON',
  precisionDecouverteFortuite: 'amorphe',
  jamaisSaigne: 'NP',
  agePremierSigneCliniqueJours: 16834,
  agePremierSigneCliniqueMois: 20228,
  agePremierSigneCliniqueAnnees: 30781,
  symptomeEcchymose: true,
  symptomeEpistaxis: false,
  symptomeGingivorragies: true,
  symptomeMetrorragies: false,
  symptomeMelena: true,
  symptomeHemoptysie: true,
  symptomeHemorragiePostAmygdalectomie: false,
  symptomeHemorragiePostAvulsionDentaire: false,
  symptomeHemorragieChuteCordon: true,
  symptomeAutre: false,
  symptomeAutreDescription: 'probablement réduire vivace',
  datePremiereConsultation: dayjs('2025-05-09'),
  agePremiereConsultationJours: 2006,
  agePremiereConsultationMois: 31649,
  agePremiereConsultationAnnees: 29003,
  ageDiagnosticJours: 14966,
  ageDiagnosticMois: 12808,
  ageDiagnosticAnnees: 7140,
  hb: 12274.89,
  hte: 1726.99,
  plaquettes: 18054,
  pfaColEpi: 20034.59,
  pfaColADP: 28091.76,
  tp: 25133.68,
  tpMPlusT: 21048.26,
  fibrinogene: 7847.57,
  tcaMT: 29235.5,
  tcaMPlusT: 17933.16,
  tcaTemoin: 24105.04,
  facteurXI: 21288.43,
  autresFacteursDosageDescription: 'svelte',
  autresFacteursTaux1: 17427.49,
  autresFacteursTaux2: 22956.11,
  autresFacteursTaux3: 7409.27,
  confirmationMoleculaire: 'NONFAITE',
  mutationPresente: true,
  mutationNom: 'membre du personnel personnel professionnel collègue',
  mutationZygote: 'HOMOZYGOTE',
  mutation2Nom: 'hors commissionnaire',
  serologieVHB: 'NON',
  serologieVHC: 'NON',
  serologieVIH: 'OUI',
  epistaxis: true,
  frequenceEpistaxis: 28608,
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 16479,
  ecchymose: true,
  typeEcchymose: 'SPONTANE',
  frequenceEcchymose: 12833,
  menorragie: false,
  frequenceMenorragie: 30624,
  hematemese: false,
  frequenceHematemese: 5254,
  rectorragie: true,
  frequenceRectorragie: 4714,
  hematurie: false,
  frequenceHematurie: 19994,
  hemorragiePostTraumatique: false,
  frequenceHemorragiePostTraumatique: 28544,
  hematomeSousCutane: true,
  typeHematomeSousCutane: 'PROVOQUE',
  frequenceHematomeSousCutane: 29610,
  hematomeMusculaire: false,
  typeHematomeMusculaire: 'SPONTANE',
  frequenceHematomeMusculaire: 16152,
  hematomeTissusMousProfonds: true,
  typeHematomeTissusMousProfonds: 'SPONTANE',
  frequenceHematomeTissusMousProfonds: 3805,
  hemarthrose: false,
  typeHemarthrose: 'SPONTANE',
  frequenceHemarthrose: 5619,
  saignementSNC: true,
  typeSaignementSNC: 'SPONTANE',
  frequenceSaignementSNC: 10096,
  saignementChuteCordon: false,
  frequenceSaignementChuteCordon: 17214,
  retardCicatrisationPlaies: false,
  frequenceRetardCicatrisationPlaies: 30043,
  autresManifestations: false,
  faussesCouchesSpontaneesRecurrence: true,
  frequenceFaussesCouches: 28400,
  accidentsThrombotiques: true,
  thromboseVeineuse: true,
  thromboseArterielle: false,
  frequenceAccidentsThrombotiques: 27830,
  hemoperitoine: false,
  frequenceHemoperitoine: 6714,
  ruptureKystesHemorragiques: true,
  frequenceRuptureKystes: 14493,
  hemorragieGrave: true,
  frequenceHemorragieGrave: 12226,
  graviteDeglobulisation: true,
  graviteEtatDeChoc: false,
  graviteParLocalisation: false,
  siegeGraviteLocalisation: 'soit',
  chirurgiePrepare: 'NON',
  chirurgieSuiteHemorragique: 'NON',
  circoncisionPrepare: 'NON',
  circoncisionSuiteHemorragique: 'OUI',
  ageCirconcision: 28192,
  traitementPFC: 'OUI',
  traitementCryoprecipite: 'NON',
  traitementConcentreFacteurXI: 'NP',
  traitementCulotsPlaquettaires: 'OUI',
  traitementDicynone: 'OUI',
  traitementExacyl: 'OUI',
  traitementMartial: 'OUI',
  traitementOestroprogestatif: 'NP',
  transfusionCGR: 'NON',
  alloImmunisation: 'NON',
  inhibiteurNeutralisant: 'NP',
  titreInhibiteurUB: 31831.31,
  inhibiteurNonNeutralisant: 'OUI',
  infectionVIH: 'NON',
  infectionVHC: 'OUI',
  infectionVHB: 'NON',
  thrombose: false,
  reactionAllergique: false,
  autresComplications: 'lectorat appeler',
  adherenceTherapeutique: 'NP',
  causeNonAdherence: 'que hi tchou tchouu',
  statutSocial: 'SCOLARISE',
  marie: 'OUI',
  enfants: 'NP',
  activitePhysique: 'OUI',
  typeActivitePhysique: 'insuffisamment par suite de au-dessus de',
  sequelles: 'NP',
  typeSequelles: 'jeune',
  patientDecede: 'NON',
  dateDeces: dayjs('2025-05-09'),
  ageDeces: 6178,
  causeDeces: 'CANCER',
};

export const sampleWithNewData: NewFicheFacteurXI = {
  etatCivil: 'NP',
  serviceClinique: 'PEDIATRIE_B',
  couvertureSociale: 'INDIGENT',
  sexe: 'MASCULIN',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
