import dayjs from 'dayjs/esm';
import { CivilStatus } from 'app/entities/enumerations/civil-status.model';
import { ServiceCliniqueType } from 'app/entities/enumerations/service-clinique-type.model';
import { CouvertureSociale } from 'app/entities/enumerations/couverture-sociale.model';
import { Gender } from 'app/entities/enumerations/gender.model';
import { Region } from 'app/entities/enumerations/region.model';
import { DiagnosticType } from 'app/entities/enumerations/diagnostic-type.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { DegreParente } from 'app/entities/enumerations/degre-parente.model';
import { LienParente } from 'app/entities/enumerations/lien-parente.model';
import { FaiteNonFaite } from 'app/entities/enumerations/faite-non-faite.model';
import { TypeZygote } from 'app/entities/enumerations/type-zygote.model';
import { TypeManifestation } from 'app/entities/enumerations/type-manifestation.model';
import { StatutSocial } from 'app/entities/enumerations/statut-social.model';
import { CauseDeces } from 'app/entities/enumerations/cause-deces.model';

export interface IFicheFacteurXI {
  id: number;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  prenom?: string | null;
  nom?: string | null;
  nomJeuneFille?: string | null;
  profession?: string | null;
  etatCivil?: keyof typeof CivilStatus | null;
  serviceClinique?: keyof typeof ServiceCliniqueType | null;
  autreServiceClinique?: string | null;
  couvertureSociale?: keyof typeof CouvertureSociale | null;
  sexe?: keyof typeof Gender | null;
  dateNaissance?: dayjs.Dayjs | null;
  ageActuel?: number | null;
  origine?: keyof typeof Region | null;
  autreOrigine?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  prenomPere?: string | null;
  professionPere?: string | null;
  nomPrenomMere?: string | null;
  professionMere?: string | null;
  medecinTraitant?: string | null;
  serviceOrigine?: string | null;
  biologisteResponsableDg?: string | null;
  diagnostic?: keyof typeof DiagnosticType | null;
  autreDiagnostic?: string | null;
  anneeDiagnostic?: number | null;
  consentementRegistre?: keyof typeof OuiNonNP | null;
  dateEnregistrementRegistre?: dayjs.Dayjs | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: keyof typeof DegreParente | null;
  casSimilaires?: keyof typeof OuiNonNP | null;
  nombreCas?: number | null;
  cas1Numero?: number | null;
  lienParenteCas1?: keyof typeof LienParente | null;
  degreParenteCas1?: string | null;
  typeHemorragieCas1?: string | null;
  cas2Numero?: number | null;
  lienParenteCas2?: keyof typeof LienParente | null;
  degreParenteCas2?: string | null;
  typeHemorragieCas2?: string | null;
  cas3Numero?: number | null;
  lienParenteCas3?: keyof typeof LienParente | null;
  degreParenteCas3?: string | null;
  typeHemorragieCas3?: string | null;
  decesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nombreDeces?: number | null;
  deces1Numero?: number | null;
  lienParenteDeces1?: keyof typeof LienParente | null;
  causeDeces1?: string | null;
  deces2Numero?: number | null;
  lienParenteDeces2?: keyof typeof LienParente | null;
  causeDeces2?: string | null;
  deces3Numero?: number | null;
  lienParenteDeces3?: keyof typeof LienParente | null;
  causeDeces3?: string | null;
  enqueteFamiliale?: keyof typeof OuiNonNP | null;
  syndromeHemorragique?: keyof typeof OuiNonNP | null;
  precisionSyndromeHemorragique?: string | null;
  decouverteFortuite?: keyof typeof OuiNonNP | null;
  precisionDecouverteFortuite?: string | null;
  jamaisSaigne?: keyof typeof OuiNonNP | null;
  agePremierSigneCliniqueJours?: number | null;
  agePremierSigneCliniqueMois?: number | null;
  agePremierSigneCliniqueAnnees?: number | null;
  symptomeEcchymose?: boolean | null;
  symptomeEpistaxis?: boolean | null;
  symptomeGingivorragies?: boolean | null;
  symptomeMetrorragies?: boolean | null;
  symptomeMelena?: boolean | null;
  symptomeHemoptysie?: boolean | null;
  symptomeHemorragiePostAmygdalectomie?: boolean | null;
  symptomeHemorragiePostAvulsionDentaire?: boolean | null;
  symptomeHemorragieChuteCordon?: boolean | null;
  symptomeAutre?: boolean | null;
  symptomeAutreDescription?: string | null;
  datePremiereConsultation?: dayjs.Dayjs | null;
  agePremiereConsultationJours?: number | null;
  agePremiereConsultationMois?: number | null;
  agePremiereConsultationAnnees?: number | null;
  ageDiagnosticJours?: number | null;
  ageDiagnosticMois?: number | null;
  ageDiagnosticAnnees?: number | null;
  hb?: number | null;
  hte?: number | null;
  plaquettes?: number | null;
  pfaColEpi?: number | null;
  pfaColADP?: number | null;
  tp?: number | null;
  tpMPlusT?: number | null;
  fibrinogene?: number | null;
  tcaMT?: number | null;
  tcaMPlusT?: number | null;
  tcaTemoin?: number | null;
  facteurXI?: number | null;
  autresFacteursDosageDescription?: string | null;
  autresFacteursTaux1?: number | null;
  autresFacteursTaux2?: number | null;
  autresFacteursTaux3?: number | null;
  confirmationMoleculaire?: keyof typeof FaiteNonFaite | null;
  mutationPresente?: boolean | null;
  mutationNom?: string | null;
  mutationZygote?: keyof typeof TypeZygote | null;
  mutation2Nom?: string | null;
  serologieVHB?: keyof typeof OuiNonNP | null;
  serologieVHC?: keyof typeof OuiNonNP | null;
  serologieVIH?: keyof typeof OuiNonNP | null;
  epistaxis?: boolean | null;
  frequenceEpistaxis?: number | null;
  gingivorragies?: boolean | null;
  typeGingivorragies?: keyof typeof TypeManifestation | null;
  frequenceGingivorragies?: number | null;
  ecchymose?: boolean | null;
  typeEcchymose?: keyof typeof TypeManifestation | null;
  frequenceEcchymose?: number | null;
  menorragie?: boolean | null;
  frequenceMenorragie?: number | null;
  hematemese?: boolean | null;
  frequenceHematemese?: number | null;
  rectorragie?: boolean | null;
  frequenceRectorragie?: number | null;
  hematurie?: boolean | null;
  frequenceHematurie?: number | null;
  hemorragiePostTraumatique?: boolean | null;
  frequenceHemorragiePostTraumatique?: number | null;
  hematomeSousCutane?: boolean | null;
  typeHematomeSousCutane?: keyof typeof TypeManifestation | null;
  frequenceHematomeSousCutane?: number | null;
  hematomeMusculaire?: boolean | null;
  typeHematomeMusculaire?: keyof typeof TypeManifestation | null;
  frequenceHematomeMusculaire?: number | null;
  hematomeTissusMousProfonds?: boolean | null;
  typeHematomeTissusMousProfonds?: keyof typeof TypeManifestation | null;
  frequenceHematomeTissusMousProfonds?: number | null;
  hemarthrose?: boolean | null;
  typeHemarthrose?: keyof typeof TypeManifestation | null;
  frequenceHemarthrose?: number | null;
  saignementSNC?: boolean | null;
  typeSaignementSNC?: keyof typeof TypeManifestation | null;
  frequenceSaignementSNC?: number | null;
  saignementChuteCordon?: boolean | null;
  frequenceSaignementChuteCordon?: number | null;
  retardCicatrisationPlaies?: boolean | null;
  frequenceRetardCicatrisationPlaies?: number | null;
  autresManifestations?: boolean | null;
  faussesCouchesSpontaneesRecurrence?: boolean | null;
  frequenceFaussesCouches?: number | null;
  accidentsThrombotiques?: boolean | null;
  thromboseVeineuse?: boolean | null;
  thromboseArterielle?: boolean | null;
  frequenceAccidentsThrombotiques?: number | null;
  hemoperitoine?: boolean | null;
  frequenceHemoperitoine?: number | null;
  ruptureKystesHemorragiques?: boolean | null;
  frequenceRuptureKystes?: number | null;
  hemorragieGrave?: boolean | null;
  frequenceHemorragieGrave?: number | null;
  graviteDeglobulisation?: boolean | null;
  graviteEtatDeChoc?: boolean | null;
  graviteParLocalisation?: boolean | null;
  siegeGraviteLocalisation?: string | null;
  chirurgiePrepare?: keyof typeof OuiNonNP | null;
  chirurgieSuiteHemorragique?: keyof typeof OuiNonNP | null;
  circoncisionPrepare?: keyof typeof OuiNonNP | null;
  circoncisionSuiteHemorragique?: keyof typeof OuiNonNP | null;
  ageCirconcision?: number | null;
  traitementPFC?: keyof typeof OuiNonNP | null;
  traitementCryoprecipite?: keyof typeof OuiNonNP | null;
  traitementConcentreFacteurXI?: keyof typeof OuiNonNP | null;
  traitementCulotsPlaquettaires?: keyof typeof OuiNonNP | null;
  traitementDicynone?: keyof typeof OuiNonNP | null;
  traitementExacyl?: keyof typeof OuiNonNP | null;
  traitementMartial?: keyof typeof OuiNonNP | null;
  traitementOestroprogestatif?: keyof typeof OuiNonNP | null;
  transfusionCGR?: keyof typeof OuiNonNP | null;
  alloImmunisation?: keyof typeof OuiNonNP | null;
  inhibiteurNeutralisant?: keyof typeof OuiNonNP | null;
  titreInhibiteurUB?: number | null;
  inhibiteurNonNeutralisant?: keyof typeof OuiNonNP | null;
  infectionVIH?: keyof typeof OuiNonNP | null;
  infectionVHC?: keyof typeof OuiNonNP | null;
  infectionVHB?: keyof typeof OuiNonNP | null;
  thrombose?: boolean | null;
  reactionAllergique?: boolean | null;
  autresComplications?: string | null;
  adherenceTherapeutique?: keyof typeof OuiNonNP | null;
  causeNonAdherence?: string | null;
  statutSocial?: keyof typeof StatutSocial | null;
  marie?: keyof typeof OuiNonNP | null;
  enfants?: keyof typeof OuiNonNP | null;
  activitePhysique?: keyof typeof OuiNonNP | null;
  typeActivitePhysique?: string | null;
  sequelles?: keyof typeof OuiNonNP | null;
  typeSequelles?: string | null;
  patientDecede?: keyof typeof OuiNonNP | null;
  dateDeces?: dayjs.Dayjs | null;
  ageDeces?: number | null;
  causeDeces?: keyof typeof CauseDeces | null;
}

export type NewFicheFacteurXI = Omit<IFicheFacteurXI, 'id'> & { id: null };
