import dayjs from 'dayjs/esm';

import { IFicheHemophilie, NewFicheHemophilie } from './fiche-hemophilie.model';

export const sampleWithRequiredData: IFicheHemophilie = {
  id: 16379,
  sexe: 'MASCULIN',
  etatCivil: 'NP',
  couvertureSociale: 'CNAM',
  diagnostic: 'DEFICIT_FACTEUR_XIII',
  circonstancesDecouverte: 'SYNDROME_HEMORRAGIQUE',
  formeClinique: 'A',
  severite: 'SEVERE',
};

export const sampleWithPartialData: IFicheHemophilie = {
  id: 31462,
  prenom: 'quelquefois au prix de vr',
  nom: 'spécialiste hors via',
  nomJeuneFille: 'badaboum sage',
  profession: 'efficace suffisamment du ',
  sexe: 'FEMININ',
  dateNaissance: dayjs('2025-02-15'),
  adresse: 'atchoum',
  etatCivil: 'NP',
  couvertureSociale: 'NP',
  serviceOrigine: 'pardonner devant',
  biologisteResponsableDg: 'oui croâ',
  diagnostic: 'HEMOPHILIE',
  autreDiagnostic: 'chef de cuisine de craint',
  ordreNumber: 'membre à vie lunatique re',
  indexNumber: 'amorphe devant aussi',
  degreParenteConsanguins: 'entre spécialiste',
  casSimilaires: 'OUI',
  decesSyndromeHemorragique: 'NON',
  nombreDeces: 22295,
  fratrieNbFreres: 12877,
  circonstancesDecouverte: 'FAMILIALE',
  plaiePostTraumatique: false,
  hemorragieCerebrale: true,
  ageDiagnosticJours: 8510,
  ageDiagnosticMois: 16406,
  hb: 10317.46,
  ht: 8397.08,
  plaquettes: 8829,
  tp: 11175.37,
  fibrinogene: 22346.93,
  tcaTemoin2h: 1868.86,
  ts: 'NON_FAIT',
  pfa: 'ALLONGE',
  dosageFacteurIX: 11432.15,
  formeClinique: 'A',
  severite: 'MODEREE',
  explorationMoleculaire: 'NP',
  inversionIntron22: false,
  hemarthroseSiege: 'de la part de broum équip',
  hemarthroseType: 'PROVOQUE',
  hemarthroseFrequenceAn: 1741,
  hematomeSuperficiel: 'NON',
  hematomeSuperficielSiege: 'enrichir autour vraisembl',
  hematomePsoas: 'OUI',
  hematomePsoasType: 'PLAIE_LANGUE',
  hematomePsoasRecidive: 'OUI',
  hemorragiesCutaneoMuqueusesTypes: 'CHUTE_DENTAIRE',
  hemorragiesCutaneoMuqueusesFrequenceAn: 22384,
  hemorragieVisceres: 'OUI',
  hemorragieVisceresType: 'RECTORRAGIE',
  hemorragieVisceresExploration: 'OUI',
  saignementSNC: 'NP',
  saignementSNCEvolution: 'DECES',
  circoncision: 'NP',
  circoncisionPreparation: 'OUI',
  accidentsHemorragiquesGraves: 'NON',
  accidentsHemorragiquesGravesTypes: 'EDC_HEMORRAGIQUE',
  priseEnChargeTherapeutique: 'PROPHYLAXIE',
  prophylaxieDoseFrequence: 'sans que ouille',
  dateDebutProphylaxie: dayjs('2025-02-14'),
  injectionType: 'INJECTION_HOPITAL',
  agePremiereSubstitution: 13739,
  genouDroit: true,
  chevilleDroite: true,
  chevilleGauche: false,
  epauleDroite: false,
  epauleGauche: false,
  poignetGauche: false,
  hancheGauche: false,
  pecTherapeutique: 'RAS',
  tauxInhibiteur: 'NP',
  testRecuperationFAH: true,
  augmenterDoseFacteur: false,
  feiba: true,
  corticotherapie: true,
  immurel: false,
  posologieITI: 'personnel',
  dureeITI: 'en dépit de envisager aim',
  causeNonObservance: 'grrr',
  prophylaxieHemlibra: true,
  schemaTherapeutique: 'MENSUEL',
  serologieHBC: 'POSITIVE',
  serologieHVC: 'NEGATIVE',
  dateDecouverteVHC: dayjs('2025-02-14'),
  evolutionVHC: 'PERSISTANCE',
  vieSociale: 'PRESCOLAIRE',
  typeHandicap: 'sauf à',
  activiteSportive: true,
  decede: true,
};

export const sampleWithFullData: IFicheHemophilie = {
  id: 1049,
  prenom: 'pour que',
  nom: 'parce que broum',
  nomJeuneFille: 'ouf',
  profession: 'rose de peur que croâ',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-14'),
  ageActuel: 13224,
  origine: 'GAFSA',
  autreOrigine: 'police près insipide',
  adresse: "d'après insolite",
  telephone: '+33 106654487',
  etatCivil: 'DIVORCE',
  couvertureSociale: 'NP',
  prenomPere: "d'entre mêler",
  professionPere: 'là-haut boum',
  nomPrenomMere: 'glouglou en outre de brou',
  professionMere: 'ha ha',
  medecinTraitant: 'sage raccrocher',
  serviceOrigine: 'à même tremper savoir',
  biologisteResponsableDg: 'sympathique',
  diagnostic: 'DEFICIT_COMBINE',
  autreDiagnostic: 'toc',
  anneeDiagnostic: 6367,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-14'),
  dossierNumber: 'ouin bzzz bien que',
  ordreNumber: 'porte-parole gens porte-p',
  indexNumber: 'jeune',
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'magenta de par',
  casSimilaires: 'OUI',
  nombreCas: 15187,
  degreParenteCasSimilaires: 'LOINTAIN',
  decesSyndromeHemorragique: 'NON',
  nombreDeces: 2579,
  formeHemophilie: 'NP',
  fratrieNbFreres: 10858,
  fratrieNbSoeurs: 5067,
  circonstancesDecouverte: 'SYNDROME_HEMORRAGIQUE',
  cutaneoMuqueux: true,
  hemarthrose: 'NP',
  hematomePostTraumatique: true,
  plaiePostTraumatique: true,
  hemorragiePostCirconcision: true,
  hemorragiePostChirurgie: false,
  hemorragieCerebrale: true,
  hemorragieDigestive: true,
  datePremierSigneClinique: dayjs('2025-02-15'),
  ageDiagnosticJours: 26094,
  ageDiagnosticMois: 2644,
  ageDiagnosticAnnees: 31059,
  dateTestConfirmation: dayjs('2025-02-15'),
  hb: 90.66,
  ht: 32614.05,
  plaquettes: 10153,
  tp: 25004.45,
  fibrinogene: 10427.83,
  tcaMT: 21269.59,
  tcaMTTotal: 11156.81,
  tcaMT2h: 14744.44,
  tcaTemoin2h: 30142.47,
  ts: 'FAIT',
  pfa: 'FAIT',
  dosageFacteurVIII: 24234.26,
  dosageFacteurIX: 31323.37,
  dosageFacteurVWActivite: 3956.68,
  dosageFacteurVWAntigene: 356.52,
  formeClinique: 'A',
  severite: 'MODEREE',
  explorationMoleculaire: 'NP',
  inversionIntron22: false,
  autreExplorationMoleculaire: 'patientèle',
  hemarthroseSiege: 'boum atchoum ficher',
  hemarthroseType: 'PROVOQUE',
  hemarthroseFrequenceAn: 15625,
  hematomeSuperficiel: 'OUI',
  hematomeSuperficielType: 'SPONTANE',
  hematomeSuperficielSiege: 'clac près',
  hematomePsoas: 'NON',
  hematomePsoasType: 'GINGIVORRAGIES',
  hematomePsoasRecidive: 'NON',
  hemorragiesCutaneoMuqueuses: 'NP',
  hemorragiesCutaneoMuqueusesTypes: 'EPISTAXIS',
  hemorragiesCutaneoMuqueusesFrequenceAn: 179,
  hemorragieVisceres: 'NP',
  hemorragieVisceresType: 'RECTORRAGIE',
  hemorragieVisceresExploration: 'NON',
  hemorragieVisceresExamen: 'population du Québec tran',
  saignementSNC: 'OUI',
  saignementSNCEvolution: 'REGRESSION',
  circoncision: 'NP',
  circoncisionPreparation: 'NON',
  circoncisionSuiteOperatoire: 'NP',
  circoncisionAge: 30893,
  avulsionDentaire: 'OUI',
  avulsionDentairePreparation: 'NP',
  interventionChirurgicale: 'NP',
  interventionChirurgicaleType: 'rectorat terminer',
  accidentsHemorragiquesGraves: 'OUI',
  accidentsHemorragiquesGravesTypes: 'HEMATOMES_CEREBRALES',
  priseEnChargeTherapeutique: 'A_LA_DEMANDE',
  causePriseEnCharge: 'orange dense',
  prophylaxieDoseFrequence: 'drelin',
  dateDebutProphylaxie: dayjs('2025-02-15'),
  injectionType: 'INJECTION_HOPITAL',
  modaliteTraitement: 'RECOMBINANT',
  typeTraitementSubstitutif: 'tant',
  agePremiereSubstitution: 16708,
  antecedentsTraitementPSL: 'NP',
  plasmaFraisCongele: 'NON',
  cryoprecipite: 'NP',
  orthopediques: 'NON',
  synovite: false,
  arthropathieHemophiliqueChronique: false,
  pseudotumeurs: false,
  fractures: false,
  coudeDroit: true,
  coudeGauche: false,
  genouDroit: true,
  genouGauche: true,
  chevilleDroite: false,
  chevilleGauche: true,
  epauleDroite: true,
  epauleGauche: true,
  poignetDroit: false,
  poignetGauche: false,
  hancheDroite: false,
  hancheGauche: true,
  pecTherapeutique: 'RAS',
  inhibiteurs: 'OUI',
  tauxInhibiteur: 'FAIBLE_REPONDEUR',
  testRecuperationFAH: true,
  dateTestRecuperation: dayjs('2025-02-14'),
  tauxRecuperation: 'DIMINUE',
  antiFAHNonNeutralisant: false,
  antiFAHNegatif: true,
  rechercheACC: 'NEGATIVE',
  augmenterDoseFacteur: true,
  novoseven: true,
  feiba: false,
  corticotherapie: true,
  immurel: true,
  iti: true,
  posologieITI: 'communauté étudiante jete',
  dureeITI: 'tandis que téméraire tsoi',
  observanceITI: 'NON',
  causeNonObservance: 'jeune enfant',
  evolutionInhibiteur: 'DISPARITION',
  prophylaxieHemlibra: true,
  dateDebutHemlibra: dayjs('2025-02-15'),
  schemaTherapeutique: 'HEBDOMADAIRE',
  efficaciteHemlibra: 29869,
  serologieHBC: 'NP',
  serologieHVC: 'POSITIVE',
  dateDecouverteVHC: dayjs('2025-02-14'),
  chargeViraleVHC: 'pendant que',
  traitementVHC: 'OUI',
  evolutionVHC: 'DISPARITION',
  serologieHIV: 'NEGATIVE',
  vieSociale: 'TRAVAILLE',
  marie: 'OUI',
  enfants: 'NON',
  handicap: 'OUI',
  typeHandicap: 'soit à condition que',
  activiteSportive: true,
  typeActiviteSportive: 'écraser engloutir',
  decede: true,
  causeDeces: 'aïe instruire présidence',
  dateDeces: dayjs('2025-02-15'),
};

export const sampleWithNewData: NewFicheHemophilie = {
  sexe: 'MASCULIN',
  etatCivil: 'MARIE',
  couvertureSociale: 'CNAM',
  diagnostic: 'THROMBOPATHIE',
  circonstancesDecouverte: 'FORTUITE',
  formeClinique: 'A',
  severite: 'SEVERE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
