import dayjs from 'dayjs/esm';
import { Gender } from 'app/entities/enumerations/gender.model';
import { Region } from 'app/entities/enumerations/region.model';
import { CivilStatus } from 'app/entities/enumerations/civil-status.model';
import { CouvertureSociale } from 'app/entities/enumerations/couverture-sociale.model';
import { DiagnosticType } from 'app/entities/enumerations/diagnostic-type.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { DegreeParente } from 'app/entities/enumerations/degree-parente.model';
import { FormeHemophilie } from 'app/entities/enumerations/forme-hemophilie.model';
import { CircumstanceDecouverte } from 'app/entities/enumerations/circumstance-decouverte.model';
import { TestStatus } from 'app/entities/enumerations/test-status.model';
import { FormeClinique } from 'app/entities/enumerations/forme-clinique.model';
import { Severite } from 'app/entities/enumerations/severite.model';
import { TypeManifestation } from 'app/entities/enumerations/type-manifestation.model';
import { TypeHemorragie } from 'app/entities/enumerations/type-hemorragie.model';
import { TypeHemorragieCutaneoMuqueuse } from 'app/entities/enumerations/type-hemorragie-cutaneo-muqueuse.model';
import { TypeHemorragieViscere } from 'app/entities/enumerations/type-hemorragie-viscere.model';
import { EvolutionSNC } from 'app/entities/enumerations/evolution-snc.model';
import { SuiteOperatoire } from 'app/entities/enumerations/suite-operatoire.model';
import { TypeAccidentHemorragiqueGrave } from 'app/entities/enumerations/type-accident-hemorragique-grave.model';
import { TypePriseEnCharge } from 'app/entities/enumerations/type-prise-en-charge.model';
import { InjectionType } from 'app/entities/enumerations/injection-type.model';
import { ModaliteTraitement } from 'app/entities/enumerations/modalite-traitement.model';
import { PECTherapeutique } from 'app/entities/enumerations/pec-therapeutique.model';
import { TauxInhibiteur } from 'app/entities/enumerations/taux-inhibiteur.model';
import { TauxRecuperation } from 'app/entities/enumerations/taux-recuperation.model';
import { RechercheACC } from 'app/entities/enumerations/recherche-acc.model';
import { EvolutionInhibiteur } from 'app/entities/enumerations/evolution-inhibiteur.model';
import { SchemaTherapeutique } from 'app/entities/enumerations/schema-therapeutique.model';
import { Serologie } from 'app/entities/enumerations/serologie.model';
import { EvolutionVHC } from 'app/entities/enumerations/evolution-vhc.model';
import { VieSociale } from 'app/entities/enumerations/vie-sociale.model';

export interface IFicheHemophilie {
  id: number;
  prenom?: string | null;
  nom?: string | null;
  nomJeuneFille?: string | null;
  profession?: string | null;
  sexe?: keyof typeof Gender | null;
  dateNaissance?: dayjs.Dayjs | null;
  ageActuel?: number | null;
  origine?: keyof typeof Region | null;
  autreOrigine?: string | null;
  adresse?: string | null;
  telephone?: string | null;
  etatCivil?: keyof typeof CivilStatus | null;
  couvertureSociale?: keyof typeof CouvertureSociale | null;
  prenomPere?: string | null;
  professionPere?: string | null;
  nomPrenomMere?: string | null;
  professionMere?: string | null;
  medecinTraitant?: string | null;
  serviceOrigine?: string | null;
  biologisteResponsableDg?: string | null;
  diagnostic?: keyof typeof DiagnosticType | null;
  autreDiagnostic?: string | null;
  anneeDiagnostic?: number | null;
  consentementRegistre?: keyof typeof OuiNonNP | null;
  dateEnregistrementRegistre?: dayjs.Dayjs | null;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: string | null;
  casSimilaires?: keyof typeof OuiNonNP | null;
  nombreCas?: number | null;
  degreParenteCasSimilaires?: keyof typeof DegreeParente | null;
  decesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nombreDeces?: number | null;
  formeHemophilie?: keyof typeof FormeHemophilie | null;
  fratrieNbFreres?: number | null;
  fratrieNbSoeurs?: number | null;
  circonstancesDecouverte?: keyof typeof CircumstanceDecouverte | null;
  cutaneoMuqueux?: boolean | null;
  hemarthrose?: keyof typeof OuiNonNP | null;
  hematomePostTraumatique?: boolean | null;
  plaiePostTraumatique?: boolean | null;
  hemorragiePostCirconcision?: boolean | null;
  hemorragiePostChirurgie?: boolean | null;
  hemorragieCerebrale?: boolean | null;
  hemorragieDigestive?: boolean | null;
  datePremierSigneClinique?: dayjs.Dayjs | null;
  ageDiagnosticJours?: number | null;
  ageDiagnosticMois?: number | null;
  ageDiagnosticAnnees?: number | null;
  dateTestConfirmation?: dayjs.Dayjs | null;
  hb?: number | null;
  ht?: number | null;
  plaquettes?: number | null;
  tp?: number | null;
  fibrinogene?: number | null;
  tcaMT?: number | null;
  tcaMTTotal?: number | null;
  tcaMT2h?: number | null;
  tcaTemoin2h?: number | null;
  ts?: keyof typeof TestStatus | null;
  pfa?: keyof typeof TestStatus | null;
  dosageFacteurVIII?: number | null;
  dosageFacteurIX?: number | null;
  dosageFacteurVWActivite?: number | null;
  dosageFacteurVWAntigene?: number | null;
  formeClinique?: keyof typeof FormeClinique | null;
  severite?: keyof typeof Severite | null;
  explorationMoleculaire?: keyof typeof OuiNonNP | null;
  inversionIntron22?: boolean | null;
  autreExplorationMoleculaire?: string | null;
  hemarthroseSiege?: string | null;
  hemarthroseType?: keyof typeof TypeManifestation | null;
  hemarthroseFrequenceAn?: number | null;
  hematomeSuperficiel?: keyof typeof OuiNonNP | null;
  hematomeSuperficielType?: keyof typeof TypeManifestation | null;
  hematomeSuperficielSiege?: string | null;
  hematomePsoas?: keyof typeof OuiNonNP | null;
  hematomePsoasType?: keyof typeof TypeHemorragie | null;
  hematomePsoasRecidive?: keyof typeof OuiNonNP | null;
  hemorragiesCutaneoMuqueuses?: keyof typeof OuiNonNP | null;
  hemorragiesCutaneoMuqueusesTypes?: keyof typeof TypeHemorragieCutaneoMuqueuse | null;
  hemorragiesCutaneoMuqueusesFrequenceAn?: number | null;
  hemorragieVisceres?: keyof typeof OuiNonNP | null;
  hemorragieVisceresType?: keyof typeof TypeHemorragieViscere | null;
  hemorragieVisceresExploration?: keyof typeof OuiNonNP | null;
  hemorragieVisceresExamen?: string | null;
  saignementSNC?: keyof typeof OuiNonNP | null;
  saignementSNCEvolution?: keyof typeof EvolutionSNC | null;
  circoncision?: keyof typeof OuiNonNP | null;
  circoncisionPreparation?: keyof typeof OuiNonNP | null;
  circoncisionSuiteOperatoire?: keyof typeof SuiteOperatoire | null;
  circoncisionAge?: number | null;
  avulsionDentaire?: keyof typeof OuiNonNP | null;
  avulsionDentairePreparation?: keyof typeof OuiNonNP | null;
  interventionChirurgicale?: keyof typeof OuiNonNP | null;
  interventionChirurgicaleType?: string | null;
  accidentsHemorragiquesGraves?: keyof typeof OuiNonNP | null;
  accidentsHemorragiquesGravesTypes?: keyof typeof TypeAccidentHemorragiqueGrave | null;
  priseEnChargeTherapeutique?: keyof typeof TypePriseEnCharge | null;
  causePriseEnCharge?: string | null;
  prophylaxieDoseFrequence?: string | null;
  dateDebutProphylaxie?: dayjs.Dayjs | null;
  injectionType?: keyof typeof InjectionType | null;
  modaliteTraitement?: keyof typeof ModaliteTraitement | null;
  typeTraitementSubstitutif?: string | null;
  agePremiereSubstitution?: number | null;
  antecedentsTraitementPSL?: keyof typeof OuiNonNP | null;
  plasmaFraisCongele?: keyof typeof OuiNonNP | null;
  cryoprecipite?: keyof typeof OuiNonNP | null;
  orthopediques?: keyof typeof OuiNonNP | null;
  synovite?: boolean | null;
  arthropathieHemophiliqueChronique?: boolean | null;
  pseudotumeurs?: boolean | null;
  fractures?: boolean | null;
  coudeDroit?: boolean | null;
  coudeGauche?: boolean | null;
  genouDroit?: boolean | null;
  genouGauche?: boolean | null;
  chevilleDroite?: boolean | null;
  chevilleGauche?: boolean | null;
  epauleDroite?: boolean | null;
  epauleGauche?: boolean | null;
  poignetDroit?: boolean | null;
  poignetGauche?: boolean | null;
  hancheDroite?: boolean | null;
  hancheGauche?: boolean | null;
  pecTherapeutique?: keyof typeof PECTherapeutique | null;
  inhibiteurs?: keyof typeof OuiNonNP | null;
  tauxInhibiteur?: keyof typeof TauxInhibiteur | null;
  testRecuperationFAH?: boolean | null;
  dateTestRecuperation?: dayjs.Dayjs | null;
  tauxRecuperation?: keyof typeof TauxRecuperation | null;
  antiFAHNonNeutralisant?: boolean | null;
  antiFAHNegatif?: boolean | null;
  rechercheACC?: keyof typeof RechercheACC | null;
  augmenterDoseFacteur?: boolean | null;
  novoseven?: boolean | null;
  feiba?: boolean | null;
  corticotherapie?: boolean | null;
  immurel?: boolean | null;
  iti?: boolean | null;
  posologieITI?: string | null;
  dureeITI?: string | null;
  observanceITI?: keyof typeof OuiNonNP | null;
  causeNonObservance?: string | null;
  evolutionInhibiteur?: keyof typeof EvolutionInhibiteur | null;
  prophylaxieHemlibra?: boolean | null;
  dateDebutHemlibra?: dayjs.Dayjs | null;
  schemaTherapeutique?: keyof typeof SchemaTherapeutique | null;
  efficaciteHemlibra?: number | null;
  serologieHBC?: keyof typeof Serologie | null;
  serologieHVC?: keyof typeof Serologie | null;
  dateDecouverteVHC?: dayjs.Dayjs | null;
  chargeViraleVHC?: string | null;
  traitementVHC?: keyof typeof OuiNonNP | null;
  evolutionVHC?: keyof typeof EvolutionVHC | null;
  serologieHIV?: keyof typeof Serologie | null;
  vieSociale?: keyof typeof VieSociale | null;
  marie?: keyof typeof OuiNonNP | null;
  enfants?: keyof typeof OuiNonNP | null;
  handicap?: keyof typeof OuiNonNP | null;
  typeHandicap?: string | null;
  activiteSportive?: boolean | null;
  typeActiviteSportive?: string | null;
  decede?: boolean | null;
  causeDeces?: string | null;
  dateDeces?: dayjs.Dayjs | null;
}

export type NewFicheHemophilie = Omit<IFicheHemophilie, 'id'> & { id: null };
