import dayjs from 'dayjs/esm';

import { IFicheHemophilie, NewFicheHemophilie } from './fiche-hemophilie.model';

export const sampleWithRequiredData: IFicheHemophilie = {
  id: 18155,
  etatCivil: 'NP',
  serviceClinique: 'GYNECO',
  couvertureSociale: 'CNAM',
  sexe: 'MASCULIN',
  diagnostic: 'AUTRE',
  circonstancesDecouverte: 'SYNDROME_HEMORRAGIQUE',
  formeClinique: 'B',
  severite: 'MODEREE',
};

export const sampleWithPartialData: IFicheHemophilie = {
  id: 943,
  dossierNumber: 'de sorte que à partir de',
  indexNumber: 'conseil d’administration',
  prenom: 'buter',
  nom: 'assez',
  nomJeuneFille: 'partenaire aussi',
  etatCivil: 'NP',
  serviceClinique: 'PEDIATRIE_A',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  origine: 'KEBILI',
  autreOrigine: 'membre de l’équipe émérit',
  adresse: 'insérer',
  telephone: '+33 393002988',
  medecinTraitant: 'souffrir alors sauf à',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  anneeDiagnostic: 1398,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-15'),
  casSimilaires: 'NON',
  nombreCas: 11881,
  decesSyndromeHemorragique: 'NP',
  nombreDeces: 1588,
  fratrieNbFreres: 3205,
  fratrieNbSoeurs: 13793,
  circonstancesDecouverte: 'FORTUITE',
  cutaneoMuqueux: false,
  hemarthrose: false,
  hemorragieCerebrale: true,
  hemorragieDigestive: false,
  ageDiagnosticJours: 8521,
  ageDiagnosticMois: 4967,
  ht: 25727.34,
  tp: 16046.17,
  fibrinogene: 4274.27,
  tcaTemoin2h: 14015.76,
  ts: 'ALLONGE',
  pfa: 'NORMAL',
  dosageFacteurIX: 2348.55,
  dosageFacteurVWActivite: 26060.06,
  dosageFacteurVWAntigene: 6168.17,
  formeClinique: 'A',
  severite: 'MINEURE',
  explorationMoleculaire: 'NP',
  hemarthroseMC: 'OUI',
  hemarthroseSiege: 'amorphe',
  hemarthroseFrequenceAn: 3722,
  hematomeSuperficielType: 'PROVOQUE',
  hematomeSuperficielSiege: 'encore',
  hematomePsoas: 'OUI',
  hematomePsoasRecidive: 'NP',
  hemorragiesCutaneoMuqueuses: 'NON',
  hemorragieVisceresExploration: 'NP',
  hemorragieVisceresExamen: 'cependant conférer',
  saignementSNC: 'NP',
  saignementSNCEvolution: 'REGRESSION',
  circoncision: 'OUI',
  circoncisionPreparation: 'NON',
  avulsionDentaire: 'OUI',
  avulsionDentairePreparation: 'NON',
  interventionChirurgicaleType: 'a puisque',
  prophylaxieDoseFrequence: 'absolument décrire',
  antecedentsTraitementPSL: 'OUI',
  cryoprecipite: 'NP',
  synovite: true,
  arthropathieHemophiliqueChronique: true,
  coudeDroit: false,
  coudeGauche: true,
  epauleGauche: true,
  poignetDroit: true,
  poignetGauche: false,
  hancheDroite: false,
  hancheGauche: false,
  pecTherapeutique: 'PTG',
  inhibiteurs: 'NP',
  tauxInhibiteur: 'FORT_REPONDEUR',
  testRecuperationFAH: false,
  tauxRecuperation: 'DIMINUE',
  antiFAHNegatif: false,
  augmenterDoseFacteur: true,
  novoseven: false,
  immurel: false,
  posologieITI: 'miam lentement',
  dureeITI: 'plaindre',
  causeNonObservance: 'commis hors',
  prophylaxieHemlibra: false,
  dateDebutHemlibra: dayjs('2025-02-15'),
  schemaTherapeutique: 'BIMENSUEL',
  efficaciteHemlibra: 8302,
  serologieHBC: 'POSITIVE',
  traitementVHC: 'OUI',
  evolutionVHC: 'DISPARITION',
  vieSociale: 'CHOMEUR',
  enfants: 'NP',
  typeHandicap: 'en faveur de',
  activiteSportive: false,
  causeDeces: 'plouf',
};

export const sampleWithFullData: IFicheHemophilie = {
  id: 11249,
  dossierNumber: 'mairie',
  ordreNumber: 'alors que sympathique afi',
  indexNumber: 'restituer de façon à ce q',
  prenom: 'prestataire de services',
  nom: 'orange hôte',
  nomJeuneFille: 'demeurer plancher félicit',
  profession: 'vers cot cot fermer',
  etatCivil: 'NP',
  serviceClinique: 'PUR',
  autreServiceClinique: 'vlan touriste mince',
  couvertureSociale: 'INDIGENT',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-02-15'),
  ageActuel: 980,
  origine: 'GAFSA',
  autreOrigine: 'tant que',
  adresse: 'personnel professionnel l',
  telephone: '0596099395',
  prenomPere: 'gai au cas où snif',
  professionPere: 'hirsute accepter autant',
  nomPrenomMere: "à l'encontre de après sau",
  professionMere: 'soit membre du personnel ',
  medecinTraitant: 'pis de peur de cuicui',
  serviceOrigine: 'exprès après que environ',
  biologisteResponsableDg: 'biathlète jusqu’à ce que ',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  autreDiagnostic: 'illustrer',
  anneeDiagnostic: 29491,
  consentementRegistre: 'NP',
  dateEnregistrementRegistre: dayjs('2025-02-15'),
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'téméraire équipe de reche',
  casSimilaires: 'NP',
  nombreCas: 21985,
  degreParenteCasSimilaires: 'FRERE',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 4906,
  formeHemophilie: 'SPORADIQUE',
  fratrieNbFreres: 5209,
  fratrieNbSoeurs: 7005,
  circonstancesDecouverte: 'FORTUITE',
  cutaneoMuqueux: false,
  hemarthrose: false,
  hematomePostTraumatique: true,
  plaiePostTraumatique: false,
  hemorragiePostCirconcision: false,
  hemorragiePostChirurgie: false,
  hemorragieCerebrale: true,
  hemorragieDigestive: true,
  datePremierSigneClinique: dayjs('2025-02-14'),
  ageDiagnosticJours: 21029,
  ageDiagnosticMois: 17185,
  ageDiagnosticAnnees: 21527,
  dateTestConfirmation: dayjs('2025-02-15'),
  hb: 25994.54,
  ht: 29660.99,
  plaquettes: 6584,
  tp: 23918.19,
  fibrinogene: 11040.4,
  tcaMT: 9883.93,
  tcaMTTotal: 4003.39,
  tcaMT2h: 12495.45,
  tcaTemoin2h: 7411.11,
  ts: 'NON_FAIT',
  pfa: 'ALLONGE',
  dosageFacteurVIII: 17792.46,
  dosageFacteurIX: 484.12,
  dosageFacteurVWActivite: 17244.31,
  dosageFacteurVWAntigene: 14231.01,
  formeClinique: 'A',
  severite: 'MINEURE',
  explorationMoleculaire: 'OUI',
  inversionIntron22: false,
  autreExplorationMoleculaire: 'main-d’œuvre souvent biat',
  hemarthroseMC: 'OUI',
  hemarthroseSiege: "à l'entour de vlan de man",
  hemarthroseType: 'PROVOQUE',
  hemarthroseFrequenceAn: 32684,
  hematomeSuperficiel: 'NON',
  hematomeSuperficielType: 'PROVOQUE',
  hematomeSuperficielSiege: 'hôte juger',
  hematomePsoas: 'OUI',
  hematomePsoasType: 'GINGIVORRAGIES',
  hematomePsoasRecidive: 'OUI',
  hemorragiesCutaneoMuqueuses: 'OUI',
  hemorragiesCutaneoMuqueusesTypes: 'CHUTE_DENTAIRE',
  hemorragiesCutaneoMuqueusesFrequenceAn: 28834,
  hemorragieVisceres: 'OUI',
  hemorragieVisceresType: 'HEMATURIE',
  hemorragieVisceresExploration: 'OUI',
  hemorragieVisceresExamen: 'simple',
  saignementSNC: 'NON',
  saignementSNCEvolution: 'DECES',
  circoncision: 'NP',
  circoncisionPreparation: 'NP',
  circoncisionSuiteOperatoire: 'SIMPLE',
  circoncisionAge: 19371,
  avulsionDentaire: 'NON',
  avulsionDentairePreparation: 'NP',
  interventionChirurgicale: 'NP',
  interventionChirurgicaleType: 'au-dessous trop pin-pon',
  accidentsHemorragiquesGraves: 'OUI',
  accidentsHemorragiquesGravesTypes: 'EDC_HEMORRAGIQUE',
  priseEnChargeTherapeutique: 'PROPHYLAXIE',
  causePriseEnCharge: 'sauf à administrer pff',
  prophylaxieDoseFrequence: 'présidence',
  dateDebutProphylaxie: dayjs('2025-02-14'),
  injectionType: 'AUTO_INJECTION',
  modaliteTraitement: 'PLASMATIQUE',
  typeTraitementSubstitutif: 'beaucoup cuicui',
  agePremiereSubstitution: 19177,
  antecedentsTraitementPSL: 'NP',
  plasmaFraisCongele: 'OUI',
  cryoprecipite: 'NON',
  orthopediques: 'NON',
  synovite: true,
  arthropathieHemophiliqueChronique: true,
  pseudotumeurs: false,
  fractures: false,
  coudeDroit: false,
  coudeGauche: false,
  genouDroit: false,
  genouGauche: true,
  chevilleDroite: false,
  chevilleGauche: false,
  epauleDroite: true,
  epauleGauche: false,
  poignetDroit: false,
  poignetGauche: true,
  hancheDroite: false,
  hancheGauche: true,
  pecTherapeutique: 'PTG',
  inhibiteurs: 'OUI',
  tauxInhibiteur: 'FAIBLE_REPONDEUR',
  testRecuperationFAH: false,
  dateTestRecuperation: dayjs('2025-02-15'),
  tauxRecuperation: 'NORMAL',
  antiFAHNonNeutralisant: true,
  antiFAHNegatif: false,
  rechercheACC: 'DOUTEUSE',
  augmenterDoseFacteur: true,
  novoseven: true,
  feiba: false,
  corticotherapie: false,
  immurel: true,
  iti: false,
  posologieITI: 'immense admirablement',
  dureeITI: 'placide tandis que',
  observanceITI: 'OUI',
  causeNonObservance: 'toc-toc cocorico',
  evolutionInhibiteur: 'PERSISTANCE',
  prophylaxieHemlibra: true,
  dateDebutHemlibra: dayjs('2025-02-15'),
  schemaTherapeutique: 'BIMENSUEL',
  efficaciteHemlibra: 3710,
  serologieHBC: 'POSITIVE',
  serologieHVC: 'NP',
  dateDecouverteVHC: dayjs('2025-02-15'),
  chargeViraleVHC: 'ha ha',
  traitementVHC: 'OUI',
  evolutionVHC: 'DISPARITION',
  serologieHIV: 'NEGATIVE',
  vieSociale: 'SCOLARISE',
  marie: 'OUI',
  enfants: 'NP',
  handicap: 'OUI',
  typeHandicap: 'à seule fin de lever rest',
  activiteSportive: true,
  typeActiviteSportive: 'pff',
  decede: false,
  causeDeces: 'poser',
  dateDeces: dayjs('2025-02-14'),
};

export const sampleWithNewData: NewFicheHemophilie = {
  etatCivil: 'MARIE',
  serviceClinique: 'PEDIATRIE_B',
  couvertureSociale: 'CNAM',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  circonstancesDecouverte: 'FORTUITE',
  formeClinique: 'B',
  severite: 'MINEURE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
