import dayjs from 'dayjs/esm';

import { IFicheHemophilie, NewFicheHemophilie } from './fiche-hemophilie.model';

export const sampleWithRequiredData: IFicheHemophilie = {
  id: 25235,
  dossierNumber: "d'après",
  priseEnCharge: 'PROPHYLAXIE',
};

export const sampleWithPartialData: IFicheHemophilie = {
  id: 15283,
  dossierNumber: 'hors de',
  casSimilairesFamille: 'NP',
  nbreCasDeces: 17863,
  formeHemophilie: 'NP',
  nbreFreres: 125,
  hemogrammeHt: 12610.98,
  tp: 25281.67,
  tcaTemoin2h: 20634.16,
  ts: 'NON_FAIT',
  frequenceHemarthrose: 602,
  hematomeSuperficiel: 'NP',
  circonstanceHematomeSuperficiel: 'SPONTANE',
  hematomePsoas: 'OUI',
  typeHemorragiesCutaneoMuqueuses: 'GINGIVORRAGIES',
  hemorragieVisceres: 'NON',
  explorationHemorragieVisceres: 'NON',
  evolutionSNC: 'REGRESSION',
  circoncision: 'NP',
  avulsionDentaire: 'NP',
  interventionChirurgicale: 'OUI',
  circonstanceAccidentsHemorragiquesGraves: 'HEMATOMES_CEREBRALES',
  priseEnCharge: 'A_LA_DEMANDE',
  causePriseEnCharge: 'spécialiste',
  doseProphylaxie: 'si bien que vlan obé',
  debutProphylaxie: dayjs('2024-11-08'),
  cryoprecipite: 'NON',
  typeComplicationsOrthopediques: 'PSEUDOTUMEURS',
  articulationCible: 'CHEVILLE_GAUCHE',
  complicationsInhibiteurs: 'OUI',
  dateRecuperationFAH: dayjs('2024-11-09'),
  tauxRecuperation: 'DIMINUE',
  antiFAHNonNeutralisant: 'OUI',
  rechercheACC: 'NON_FAITE',
  catTherapeutique: 'NOVOSEVEN',
  iti: 'NON',
  posologieITI: 'toujours minuscule',
  evolutionInhibiteur: 'DISPARITION',
  prophylaxieHemlibra: 'NON',
  dateDebutHemlibra: dayjs('2024-11-09'),
  schemaTherapeutique: 'MENSUEL',
  serologieHBC: 'NP',
  serologieHVC: 'POSITIVE',
  chargeViraleVHC: 'pin-pon sédentaire',
};

export const sampleWithFullData: IFicheHemophilie = {
  id: 27113,
  dossierNumber: 'cyan ha ha',
  ordreNumber: 'davantage à défaut de ',
  indexNumber: 'tandis que plic',
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'cot cot',
  casSimilairesFamille: 'OUI',
  nbreCasSimilaires: 28961,
  degreParenteCasSimilaires: 'touchant communiquer',
  casDecesSyndromeHemorragique: 'NON',
  nbreCasDeces: 8592,
  formeHemophilie: 'HEREDITAIRE',
  nbreFreres: 12293,
  nbreSoeurs: 9619,
  dateTestConfirmation: dayjs('2024-11-08'),
  hemogrammeHb: 18431.74,
  hemogrammeHt: 32271.47,
  plaquettes: 15734,
  tp: 9760.88,
  fibrinogene: 11977.28,
  tcaMT: 3893.8,
  tcaMT2h: 8024.7,
  tcaTemoin2h: 4509.58,
  ts: 'NON_FAIT',
  hemarthrose: 'OUI',
  siegeHemarthrose: 'CHEVILLE_DROITE',
  circonstanceHemarthrose: 'PROVOQUE',
  frequenceHemarthrose: 25443,
  hematomeSuperficiel: 'OUI',
  circonstanceHematomeSuperficiel: 'PROVOQUE',
  siegeHematomeSuperficiel: 'gigantesque hypocrite quitte à',
  hematomePsoas: 'NON',
  circonstanceHematomePsoas: 'SPONTANE',
  recidiveHematomePsoas: 'OUI',
  hemorragiesCutaneoMuqueuses: 'NON',
  typeHemorragiesCutaneoMuqueuses: 'ECHYMOSES',
  frequenceHemorragiesCutaneoMuqueuses: 20211,
  hemorragieVisceres: 'NON',
  typeHemorragieVisceres: 'HEMATURIE',
  explorationHemorragieVisceres: 'OUI',
  examenLesionHemorragieVisceres: 'baigner hirsute',
  saignementSNC: 'NP',
  evolutionSNC: 'DECES',
  circoncision: 'NON',
  typePreparationCirconcision: 'NP',
  suiteOperatoireCirconcision: 'SIMPLE',
  ageCirconcision: 30254,
  avulsionDentaire: 'NP',
  typePreparationAvulsionDentaire: 'NON_PREPAREE',
  interventionChirurgicale: 'OUI',
  typeInterventionChirurgicale: 'à la faveur de prou',
  accidentsHemorragiquesGraves: 'OUI',
  circonstanceAccidentsHemorragiquesGraves: 'HEMOTHORAX',
  priseEnCharge: 'A_LA_DEMANDE',
  causePriseEnCharge: 'dedans que',
  doseProphylaxie: 'sous couleur de au l',
  frequenceProphylaxie: 25067,
  debutProphylaxie: dayjs('2024-11-08'),
  modaliteInjection: 'INJECTION_PARENT',
  typeTraitementSubstitutif: 'PLASMATIQUE',
  age1ereSubstitution: 10148,
  antecedentsPSL: 'OUI',
  plasmaFraisCongele: 'OUI',
  cryoprecipite: 'OUI',
  complicationsOrthopediques: 'OUI',
  typeComplicationsOrthopediques: 'SYNOVITE',
  articulationCible: 'GENOU_GAUCHE',
  pecTherapeutique: 'SYNOVIORTHESE',
  complicationsInhibiteurs: 'NP',
  tauxInhibiteur: 'NP',
  testRecuperationFAH: 'NON_FAIT',
  dateRecuperationFAH: dayjs('2024-11-08'),
  tauxRecuperation: 'DIMINUE',
  antiFAHNonNeutralisant: 'NP',
  rechercheACC: 'NON_FAITE',
  catTherapeutique: 'IMMUREL',
  iti: 'NP',
  posologieITI: 'brusque pauvre',
  dureeITI: 'blablabla svelte',
  observanceITI: 'OUI',
  causeNonObservanceITI: 'secouriste foule',
  evolutionInhibiteur: 'PERSISTANCE',
  prophylaxieHemlibra: 'NON',
  dateDebutHemlibra: dayjs('2024-11-09'),
  schemaTherapeutique: 'MENSUEL',
  efficaciteHemlibra: 2186,
  serologieHBC: 'NEGATIVE',
  serologieHVC: 'NEGATIVE',
  dateDecouverteVHC: dayjs('2024-11-09'),
  chargeViraleVHC: 'entre-temps',
  traitementVHC: 'NON',
  evolutionVHC: 'PERSISTANCE',
  serologieHIV: 'NEGATIVE',
};

export const sampleWithNewData: NewFicheHemophilie = {
  dossierNumber: 'dedans',
  priseEnCharge: 'A_LA_DEMANDE',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
