import dayjs from 'dayjs/esm';
import { IPatient } from 'app/entities/patient/patient.model';
import { OuiNonNP } from 'app/entities/enumerations/oui-non-np.model';
import { FormeHemophilie } from 'app/entities/enumerations/forme-hemophilie.model';
import { TestStatus } from 'app/entities/enumerations/test-status.model';
import { ArticulationCible } from 'app/entities/enumerations/articulation-cible.model';
import { TypeManifestation } from 'app/entities/enumerations/type-manifestation.model';
import { TypeHemorragie } from 'app/entities/enumerations/type-hemorragie.model';
import { TypeHemorragieVisceres } from 'app/entities/enumerations/type-hemorragie-visceres.model';
import { EvolutionSNC } from 'app/entities/enumerations/evolution-snc.model';
import { TypePreparation } from 'app/entities/enumerations/type-preparation.model';
import { SuiteOperatoire } from 'app/entities/enumerations/suite-operatoire.model';
import { AccidentsGravesType } from 'app/entities/enumerations/accidents-graves-type.model';
import { PriseEnChargeType } from 'app/entities/enumerations/prise-en-charge-type.model';
import { InjectionType } from 'app/entities/enumerations/injection-type.model';
import { TraitementType } from 'app/entities/enumerations/traitement-type.model';
import { TypeComplicationsOrthopediques } from 'app/entities/enumerations/type-complications-orthopediques.model';
import { PECTherapeutique } from 'app/entities/enumerations/pec-therapeutique.model';
import { TauxInhibiteur } from 'app/entities/enumerations/taux-inhibiteur.model';
import { TauxRecuperation } from 'app/entities/enumerations/taux-recuperation.model';
import { RechercheACC } from 'app/entities/enumerations/recherche-acc.model';
import { CATTherapeutique } from 'app/entities/enumerations/cat-therapeutique.model';
import { Observance } from 'app/entities/enumerations/observance.model';
import { EvolutionInhibiteur } from 'app/entities/enumerations/evolution-inhibiteur.model';
import { SchemaTherapeutique } from 'app/entities/enumerations/schema-therapeutique.model';
import { Serologie } from 'app/entities/enumerations/serologie.model';
import { EvolutionVHC } from 'app/entities/enumerations/evolution-vhc.model';
import { CircumstanceDecouverte } from 'app/entities/enumerations/circumstance-decouverte.model';

export interface IFicheHemophilie {
  id: number;
  dossierNumber?: string | null;
  ordreNumber?: string | null;
  indexNumber?: string | null;
  parentsConsanguins?: keyof typeof OuiNonNP | null;
  degreParenteConsanguins?: string | null;
  casSimilairesFamille?: keyof typeof OuiNonNP | null;
  nbreCasSimilaires?: number | null;
  degreParenteCasSimilaires?: string | null;
  casDecesSyndromeHemorragique?: keyof typeof OuiNonNP | null;
  nbreCasDeces?: number | null;
  formeHemophilie?: keyof typeof FormeHemophilie | null;
  nbreFreres?: number | null;
  nbreSoeurs?: number | null;
  dateTestConfirmation?: dayjs.Dayjs | null;
  hemogrammeHb?: number | null;
  hemogrammeHt?: number | null;
  plaquettes?: number | null;
  tp?: number | null;
  fibrinogene?: number | null;
  tcaMT?: number | null;
  tcaMT2h?: number | null;
  tcaTemoin2h?: number | null;
  ts?: keyof typeof TestStatus | null;
  hemarthrose?: keyof typeof OuiNonNP | null;
  siegeHemarthrose?: keyof typeof ArticulationCible | null;
  circonstanceHemarthrose?: keyof typeof TypeManifestation | null;
  frequenceHemarthrose?: number | null;
  hematomeSuperficiel?: keyof typeof OuiNonNP | null;
  circonstanceHematomeSuperficiel?: keyof typeof TypeManifestation | null;
  siegeHematomeSuperficiel?: string | null;
  hematomePsoas?: keyof typeof OuiNonNP | null;
  circonstanceHematomePsoas?: keyof typeof TypeManifestation | null;
  recidiveHematomePsoas?: keyof typeof OuiNonNP | null;
  hemorragiesCutaneoMuqueuses?: keyof typeof OuiNonNP | null;
  typeHemorragiesCutaneoMuqueuses?: keyof typeof TypeHemorragie | null;
  frequenceHemorragiesCutaneoMuqueuses?: number | null;
  hemorragieVisceres?: keyof typeof OuiNonNP | null;
  typeHemorragieVisceres?: keyof typeof TypeHemorragieVisceres | null;
  explorationHemorragieVisceres?: keyof typeof OuiNonNP | null;
  examenLesionHemorragieVisceres?: string | null;
  saignementSNC?: keyof typeof OuiNonNP | null;
  evolutionSNC?: keyof typeof EvolutionSNC | null;
  circoncision?: keyof typeof OuiNonNP | null;
  typePreparationCirconcision?: keyof typeof TypePreparation | null;
  suiteOperatoireCirconcision?: keyof typeof SuiteOperatoire | null;
  ageCirconcision?: number | null;
  avulsionDentaire?: keyof typeof OuiNonNP | null;
  typePreparationAvulsionDentaire?: keyof typeof TypePreparation | null;
  interventionChirurgicale?: keyof typeof OuiNonNP | null;
  typeInterventionChirurgicale?: string | null;
  accidentsHemorragiquesGraves?: keyof typeof OuiNonNP | null;
  circonstanceAccidentsHemorragiquesGraves?: keyof typeof AccidentsGravesType | null;
  priseEnCharge?: keyof typeof PriseEnChargeType | null;
  causePriseEnCharge?: string | null;
  doseProphylaxie?: string | null;
  frequenceProphylaxie?: number | null;
  debutProphylaxie?: dayjs.Dayjs | null;
  modaliteInjection?: keyof typeof InjectionType | null;
  typeTraitementSubstitutif?: keyof typeof TraitementType | null;
  age1ereSubstitution?: number | null;
  antecedentsPSL?: keyof typeof OuiNonNP | null;
  plasmaFraisCongele?: keyof typeof OuiNonNP | null;
  cryoprecipite?: keyof typeof OuiNonNP | null;
  complicationsOrthopediques?: keyof typeof OuiNonNP | null;
  typeComplicationsOrthopediques?: keyof typeof TypeComplicationsOrthopediques | null;
  articulationCible?: keyof typeof ArticulationCible | null;
  pecTherapeutique?: keyof typeof PECTherapeutique | null;
  complicationsInhibiteurs?: keyof typeof OuiNonNP | null;
  tauxInhibiteur?: keyof typeof TauxInhibiteur | null;
  testRecuperationFAH?: keyof typeof TestStatus | null;
  dateRecuperationFAH?: dayjs.Dayjs | null;
  tauxRecuperation?: keyof typeof TauxRecuperation | null;
  antiFAHNonNeutralisant?: keyof typeof OuiNonNP | null;
  rechercheACC?: keyof typeof RechercheACC | null;
  catTherapeutique?: keyof typeof CATTherapeutique | null;
  iti?: keyof typeof OuiNonNP | null;
  posologieITI?: string | null;
  dureeITI?: string | null;
  observanceITI?: keyof typeof Observance | null;
  causeNonObservanceITI?: string | null;
  evolutionInhibiteur?: keyof typeof EvolutionInhibiteur | null;
  prophylaxieHemlibra?: keyof typeof OuiNonNP | null;
  dateDebutHemlibra?: dayjs.Dayjs | null;
  schemaTherapeutique?: keyof typeof SchemaTherapeutique | null;
  efficaciteHemlibra?: number | null;
  serologieHBC?: keyof typeof Serologie | null;
  serologieHVC?: keyof typeof Serologie | null;
  dateDecouverteVHC?: dayjs.Dayjs | null;
  chargeViraleVHC?: string | null;
  traitementVHC?: keyof typeof OuiNonNP | null;
  evolutionVHC?: keyof typeof EvolutionVHC | null;
  serologieHIV?: keyof typeof Serologie | null;
  patient?: Pick<IPatient, 'id'> | null;
  circumstanceDecouverte?: keyof typeof CircumstanceDecouverte | null;
}

export type NewFicheHemophilie = Omit<IFicheHemophilie, 'id'> & { id: null };
