import { TestBed } from '@angular/core/testing';

import { sampleWithNewData, sampleWithRequiredData } from '../fiche-hemophilie.test-samples';

import { FicheHemophilieFormService } from './fiche-hemophilie-form.service';

describe('FicheHemophilie Form Service', () => {
  let service: FicheHemophilieFormService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(FicheHemophilieFormService);
  });

  describe('Service methods', () => {
    describe('createFicheHemophilieFormGroup', () => {
      it('should create a new form with FormControl', () => {
        const formGroup = service.createFicheHemophilieFormGroup();

        expect(formGroup.controls).toEqual(
          expect.objectContaining({
            id: expect.any(Object),
            prenom: expect.any(Object),
            nom: expect.any(Object),
            nomJeuneFille: expect.any(Object),
            profession: expect.any(Object),
            sexe: expect.any(Object),
            dateNaissance: expect.any(Object),
            ageActuel: expect.any(Object),
            origine: expect.any(Object),
            autreOrigine: expect.any(Object),
            adresse: expect.any(Object),
            telephone: expect.any(Object),
            etatCivil: expect.any(Object),
            couvertureSociale: expect.any(Object),
            prenomPere: expect.any(Object),
            professionPere: expect.any(Object),
            nomPrenomMere: expect.any(Object),
            professionMere: expect.any(Object),
            medecinTraitant: expect.any(Object),
            serviceOrigine: expect.any(Object),
            biologisteResponsableDg: expect.any(Object),
            diagnostic: expect.any(Object),
            autreDiagnostic: expect.any(Object),
            anneeDiagnostic: expect.any(Object),
            consentementRegistre: expect.any(Object),
            dateEnregistrementRegistre: expect.any(Object),
            dossierNumber: expect.any(Object),
            ordreNumber: expect.any(Object),
            indexNumber: expect.any(Object),
            parentsConsanguins: expect.any(Object),
            degreParenteConsanguins: expect.any(Object),
            casSimilaires: expect.any(Object),
            nombreCas: expect.any(Object),
            degreParenteCasSimilaires: expect.any(Object),
            decesSyndromeHemorragique: expect.any(Object),
            nombreDeces: expect.any(Object),
            formeHemophilie: expect.any(Object),
            fratrieNbFreres: expect.any(Object),
            fratrieNbSoeurs: expect.any(Object),
            circonstancesDecouverte: expect.any(Object),
            cutaneoMuqueux: expect.any(Object),
            hemarthrose: expect.any(Object),
            hematomePostTraumatique: expect.any(Object),
            plaiePostTraumatique: expect.any(Object),
            hemorragiePostCirconcision: expect.any(Object),
            hemorragiePostChirurgie: expect.any(Object),
            hemorragieCerebrale: expect.any(Object),
            hemorragieDigestive: expect.any(Object),
            datePremierSigneClinique: expect.any(Object),
            ageDiagnosticJours: expect.any(Object),
            ageDiagnosticMois: expect.any(Object),
            ageDiagnosticAnnees: expect.any(Object),
            dateTestConfirmation: expect.any(Object),
            hb: expect.any(Object),
            ht: expect.any(Object),
            plaquettes: expect.any(Object),
            tp: expect.any(Object),
            fibrinogene: expect.any(Object),
            tcaMT: expect.any(Object),
            tcaMTTotal: expect.any(Object),
            tcaMT2h: expect.any(Object),
            tcaTemoin2h: expect.any(Object),
            ts: expect.any(Object),
            pfa: expect.any(Object),
            dosageFacteurVIII: expect.any(Object),
            dosageFacteurIX: expect.any(Object),
            dosageFacteurVWActivite: expect.any(Object),
            dosageFacteurVWAntigene: expect.any(Object),
            formeClinique: expect.any(Object),
            severite: expect.any(Object),
            explorationMoleculaire: expect.any(Object),
            inversionIntron22: expect.any(Object),
            autreExplorationMoleculaire: expect.any(Object),
            hemarthroseSiege: expect.any(Object),
            hemarthroseType: expect.any(Object),
            hemarthroseFrequenceAn: expect.any(Object),
            hematomeSuperficiel: expect.any(Object),
            hematomeSuperficielType: expect.any(Object),
            hematomeSuperficielSiege: expect.any(Object),
            hematomePsoas: expect.any(Object),
            hematomePsoasType: expect.any(Object),
            hematomePsoasRecidive: expect.any(Object),
            hemorragiesCutaneoMuqueuses: expect.any(Object),
            hemorragiesCutaneoMuqueusesTypes: expect.any(Object),
            hemorragiesCutaneoMuqueusesFrequenceAn: expect.any(Object),
            hemorragieVisceres: expect.any(Object),
            hemorragieVisceresType: expect.any(Object),
            hemorragieVisceresExploration: expect.any(Object),
            hemorragieVisceresExamen: expect.any(Object),
            saignementSNC: expect.any(Object),
            saignementSNCEvolution: expect.any(Object),
            circoncision: expect.any(Object),
            circoncisionPreparation: expect.any(Object),
            circoncisionSuiteOperatoire: expect.any(Object),
            circoncisionAge: expect.any(Object),
            avulsionDentaire: expect.any(Object),
            avulsionDentairePreparation: expect.any(Object),
            interventionChirurgicale: expect.any(Object),
            interventionChirurgicaleType: expect.any(Object),
            accidentsHemorragiquesGraves: expect.any(Object),
            accidentsHemorragiquesGravesTypes: expect.any(Object),
            priseEnChargeTherapeutique: expect.any(Object),
            causePriseEnCharge: expect.any(Object),
            prophylaxieDoseFrequence: expect.any(Object),
            dateDebutProphylaxie: expect.any(Object),
            injectionType: expect.any(Object),
            modaliteTraitement: expect.any(Object),
            typeTraitementSubstitutif: expect.any(Object),
            agePremiereSubstitution: expect.any(Object),
            antecedentsTraitementPSL: expect.any(Object),
            plasmaFraisCongele: expect.any(Object),
            cryoprecipite: expect.any(Object),
            orthopediques: expect.any(Object),
            synovite: expect.any(Object),
            arthropathieHemophiliqueChronique: expect.any(Object),
            pseudotumeurs: expect.any(Object),
            fractures: expect.any(Object),
            coudeDroit: expect.any(Object),
            coudeGauche: expect.any(Object),
            genouDroit: expect.any(Object),
            genouGauche: expect.any(Object),
            chevilleDroite: expect.any(Object),
            chevilleGauche: expect.any(Object),
            epauleDroite: expect.any(Object),
            epauleGauche: expect.any(Object),
            poignetDroit: expect.any(Object),
            poignetGauche: expect.any(Object),
            hancheDroite: expect.any(Object),
            hancheGauche: expect.any(Object),
            pecTherapeutique: expect.any(Object),
            inhibiteurs: expect.any(Object),
            tauxInhibiteur: expect.any(Object),
            testRecuperationFAH: expect.any(Object),
            dateTestRecuperation: expect.any(Object),
            tauxRecuperation: expect.any(Object),
            antiFAHNonNeutralisant: expect.any(Object),
            antiFAHNegatif: expect.any(Object),
            rechercheACC: expect.any(Object),
            augmenterDoseFacteur: expect.any(Object),
            novoseven: expect.any(Object),
            feiba: expect.any(Object),
            corticotherapie: expect.any(Object),
            immurel: expect.any(Object),
            iti: expect.any(Object),
            posologieITI: expect.any(Object),
            dureeITI: expect.any(Object),
            observanceITI: expect.any(Object),
            causeNonObservance: expect.any(Object),
            evolutionInhibiteur: expect.any(Object),
            prophylaxieHemlibra: expect.any(Object),
            dateDebutHemlibra: expect.any(Object),
            schemaTherapeutique: expect.any(Object),
            efficaciteHemlibra: expect.any(Object),
            serologieHBC: expect.any(Object),
            serologieHVC: expect.any(Object),
            dateDecouverteVHC: expect.any(Object),
            chargeViraleVHC: expect.any(Object),
            traitementVHC: expect.any(Object),
            evolutionVHC: expect.any(Object),
            serologieHIV: expect.any(Object),
            vieSociale: expect.any(Object),
            marie: expect.any(Object),
            enfants: expect.any(Object),
            handicap: expect.any(Object),
            typeHandicap: expect.any(Object),
            activiteSportive: expect.any(Object),
            typeActiviteSportive: expect.any(Object),
            decede: expect.any(Object),
            causeDeces: expect.any(Object),
            dateDeces: expect.any(Object),
          }),
        );
      });

      it('passing IFicheHemophilie should create a new form with FormGroup', () => {
        const formGroup = service.createFicheHemophilieFormGroup(sampleWithRequiredData);

        expect(formGroup.controls).toEqual(
          expect.objectContaining({
            id: expect.any(Object),
            prenom: expect.any(Object),
            nom: expect.any(Object),
            nomJeuneFille: expect.any(Object),
            profession: expect.any(Object),
            sexe: expect.any(Object),
            dateNaissance: expect.any(Object),
            ageActuel: expect.any(Object),
            origine: expect.any(Object),
            autreOrigine: expect.any(Object),
            adresse: expect.any(Object),
            telephone: expect.any(Object),
            etatCivil: expect.any(Object),
            couvertureSociale: expect.any(Object),
            prenomPere: expect.any(Object),
            professionPere: expect.any(Object),
            nomPrenomMere: expect.any(Object),
            professionMere: expect.any(Object),
            medecinTraitant: expect.any(Object),
            serviceOrigine: expect.any(Object),
            biologisteResponsableDg: expect.any(Object),
            diagnostic: expect.any(Object),
            autreDiagnostic: expect.any(Object),
            anneeDiagnostic: expect.any(Object),
            consentementRegistre: expect.any(Object),
            dateEnregistrementRegistre: expect.any(Object),
            dossierNumber: expect.any(Object),
            ordreNumber: expect.any(Object),
            indexNumber: expect.any(Object),
            parentsConsanguins: expect.any(Object),
            degreParenteConsanguins: expect.any(Object),
            casSimilaires: expect.any(Object),
            nombreCas: expect.any(Object),
            degreParenteCasSimilaires: expect.any(Object),
            decesSyndromeHemorragique: expect.any(Object),
            nombreDeces: expect.any(Object),
            formeHemophilie: expect.any(Object),
            fratrieNbFreres: expect.any(Object),
            fratrieNbSoeurs: expect.any(Object),
            circonstancesDecouverte: expect.any(Object),
            cutaneoMuqueux: expect.any(Object),
            hemarthrose: expect.any(Object),
            hematomePostTraumatique: expect.any(Object),
            plaiePostTraumatique: expect.any(Object),
            hemorragiePostCirconcision: expect.any(Object),
            hemorragiePostChirurgie: expect.any(Object),
            hemorragieCerebrale: expect.any(Object),
            hemorragieDigestive: expect.any(Object),
            datePremierSigneClinique: expect.any(Object),
            ageDiagnosticJours: expect.any(Object),
            ageDiagnosticMois: expect.any(Object),
            ageDiagnosticAnnees: expect.any(Object),
            dateTestConfirmation: expect.any(Object),
            hb: expect.any(Object),
            ht: expect.any(Object),
            plaquettes: expect.any(Object),
            tp: expect.any(Object),
            fibrinogene: expect.any(Object),
            tcaMT: expect.any(Object),
            tcaMTTotal: expect.any(Object),
            tcaMT2h: expect.any(Object),
            tcaTemoin2h: expect.any(Object),
            ts: expect.any(Object),
            pfa: expect.any(Object),
            dosageFacteurVIII: expect.any(Object),
            dosageFacteurIX: expect.any(Object),
            dosageFacteurVWActivite: expect.any(Object),
            dosageFacteurVWAntigene: expect.any(Object),
            formeClinique: expect.any(Object),
            severite: expect.any(Object),
            explorationMoleculaire: expect.any(Object),
            inversionIntron22: expect.any(Object),
            autreExplorationMoleculaire: expect.any(Object),
            hemarthroseSiege: expect.any(Object),
            hemarthroseType: expect.any(Object),
            hemarthroseFrequenceAn: expect.any(Object),
            hematomeSuperficiel: expect.any(Object),
            hematomeSuperficielType: expect.any(Object),
            hematomeSuperficielSiege: expect.any(Object),
            hematomePsoas: expect.any(Object),
            hematomePsoasType: expect.any(Object),
            hematomePsoasRecidive: expect.any(Object),
            hemorragiesCutaneoMuqueuses: expect.any(Object),
            hemorragiesCutaneoMuqueusesTypes: expect.any(Object),
            hemorragiesCutaneoMuqueusesFrequenceAn: expect.any(Object),
            hemorragieVisceres: expect.any(Object),
            hemorragieVisceresType: expect.any(Object),
            hemorragieVisceresExploration: expect.any(Object),
            hemorragieVisceresExamen: expect.any(Object),
            saignementSNC: expect.any(Object),
            saignementSNCEvolution: expect.any(Object),
            circoncision: expect.any(Object),
            circoncisionPreparation: expect.any(Object),
            circoncisionSuiteOperatoire: expect.any(Object),
            circoncisionAge: expect.any(Object),
            avulsionDentaire: expect.any(Object),
            avulsionDentairePreparation: expect.any(Object),
            interventionChirurgicale: expect.any(Object),
            interventionChirurgicaleType: expect.any(Object),
            accidentsHemorragiquesGraves: expect.any(Object),
            accidentsHemorragiquesGravesTypes: expect.any(Object),
            priseEnChargeTherapeutique: expect.any(Object),
            causePriseEnCharge: expect.any(Object),
            prophylaxieDoseFrequence: expect.any(Object),
            dateDebutProphylaxie: expect.any(Object),
            injectionType: expect.any(Object),
            modaliteTraitement: expect.any(Object),
            typeTraitementSubstitutif: expect.any(Object),
            agePremiereSubstitution: expect.any(Object),
            antecedentsTraitementPSL: expect.any(Object),
            plasmaFraisCongele: expect.any(Object),
            cryoprecipite: expect.any(Object),
            orthopediques: expect.any(Object),
            synovite: expect.any(Object),
            arthropathieHemophiliqueChronique: expect.any(Object),
            pseudotumeurs: expect.any(Object),
            fractures: expect.any(Object),
            coudeDroit: expect.any(Object),
            coudeGauche: expect.any(Object),
            genouDroit: expect.any(Object),
            genouGauche: expect.any(Object),
            chevilleDroite: expect.any(Object),
            chevilleGauche: expect.any(Object),
            epauleDroite: expect.any(Object),
            epauleGauche: expect.any(Object),
            poignetDroit: expect.any(Object),
            poignetGauche: expect.any(Object),
            hancheDroite: expect.any(Object),
            hancheGauche: expect.any(Object),
            pecTherapeutique: expect.any(Object),
            inhibiteurs: expect.any(Object),
            tauxInhibiteur: expect.any(Object),
            testRecuperationFAH: expect.any(Object),
            dateTestRecuperation: expect.any(Object),
            tauxRecuperation: expect.any(Object),
            antiFAHNonNeutralisant: expect.any(Object),
            antiFAHNegatif: expect.any(Object),
            rechercheACC: expect.any(Object),
            augmenterDoseFacteur: expect.any(Object),
            novoseven: expect.any(Object),
            feiba: expect.any(Object),
            corticotherapie: expect.any(Object),
            immurel: expect.any(Object),
            iti: expect.any(Object),
            posologieITI: expect.any(Object),
            dureeITI: expect.any(Object),
            observanceITI: expect.any(Object),
            causeNonObservance: expect.any(Object),
            evolutionInhibiteur: expect.any(Object),
            prophylaxieHemlibra: expect.any(Object),
            dateDebutHemlibra: expect.any(Object),
            schemaTherapeutique: expect.any(Object),
            efficaciteHemlibra: expect.any(Object),
            serologieHBC: expect.any(Object),
            serologieHVC: expect.any(Object),
            dateDecouverteVHC: expect.any(Object),
            chargeViraleVHC: expect.any(Object),
            traitementVHC: expect.any(Object),
            evolutionVHC: expect.any(Object),
            serologieHIV: expect.any(Object),
            vieSociale: expect.any(Object),
            marie: expect.any(Object),
            enfants: expect.any(Object),
            handicap: expect.any(Object),
            typeHandicap: expect.any(Object),
            activiteSportive: expect.any(Object),
            typeActiviteSportive: expect.any(Object),
            decede: expect.any(Object),
            causeDeces: expect.any(Object),
            dateDeces: expect.any(Object),
          }),
        );
      });
    });

    describe('getFicheHemophilie', () => {
      it('should return NewFicheHemophilie for default FicheHemophilie initial value', () => {
        const formGroup = service.createFicheHemophilieFormGroup(sampleWithNewData);

        const ficheHemophilie = service.getFicheHemophilie(formGroup) as any;

        expect(ficheHemophilie).toMatchObject(sampleWithNewData);
      });

      it('should return NewFicheHemophilie for empty FicheHemophilie initial value', () => {
        const formGroup = service.createFicheHemophilieFormGroup();

        const ficheHemophilie = service.getFicheHemophilie(formGroup) as any;

        expect(ficheHemophilie).toMatchObject({});
      });

      it('should return IFicheHemophilie', () => {
        const formGroup = service.createFicheHemophilieFormGroup(sampleWithRequiredData);

        const ficheHemophilie = service.getFicheHemophilie(formGroup) as any;

        expect(ficheHemophilie).toMatchObject(sampleWithRequiredData);
      });
    });

    describe('resetForm', () => {
      it('passing IFicheHemophilie should not enable id FormControl', () => {
        const formGroup = service.createFicheHemophilieFormGroup();
        expect(formGroup.controls.id.disabled).toBe(true);

        service.resetForm(formGroup, sampleWithRequiredData);

        expect(formGroup.controls.id.disabled).toBe(true);
      });

      it('passing NewFicheHemophilie should disable id FormControl', () => {
        const formGroup = service.createFicheHemophilieFormGroup(sampleWithRequiredData);
        expect(formGroup.controls.id.disabled).toBe(true);

        service.resetForm(formGroup, { id: null });

        expect(formGroup.controls.id.disabled).toBe(true);
      });
    });
  });
});
