package tn.adhes.hemophilie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FicheHemophilieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieAllPropertiesEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertFicheHemophilieAutoGeneratedPropertiesEquals(expected, actual);
        assertFicheHemophilieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieAllUpdatablePropertiesEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertFicheHemophilieUpdatableFieldsEquals(expected, actual);
        assertFicheHemophilieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieAutoGeneratedPropertiesEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertThat(expected)
            .as("Verify FicheHemophilie auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieUpdatableFieldsEquals(FicheHemophilie expected, FicheHemophilie actual) {
        assertThat(expected)
            .as("Verify FicheHemophilie relevant properties")
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getNomJeuneFille()).as("check nomJeuneFille").isEqualTo(actual.getNomJeuneFille()))
            .satisfies(e -> assertThat(e.getProfession()).as("check profession").isEqualTo(actual.getProfession()))
            .satisfies(e -> assertThat(e.getSexe()).as("check sexe").isEqualTo(actual.getSexe()))
            .satisfies(e -> assertThat(e.getDateNaissance()).as("check dateNaissance").isEqualTo(actual.getDateNaissance()))
            .satisfies(e -> assertThat(e.getAgeActuel()).as("check ageActuel").isEqualTo(actual.getAgeActuel()))
            .satisfies(e -> assertThat(e.getOrigine()).as("check origine").isEqualTo(actual.getOrigine()))
            .satisfies(e -> assertThat(e.getAutreOrigine()).as("check autreOrigine").isEqualTo(actual.getAutreOrigine()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getEtatCivil()).as("check etatCivil").isEqualTo(actual.getEtatCivil()))
            .satisfies(e -> assertThat(e.getCouvertureSociale()).as("check couvertureSociale").isEqualTo(actual.getCouvertureSociale()))
            .satisfies(e -> assertThat(e.getPrenomPere()).as("check prenomPere").isEqualTo(actual.getPrenomPere()))
            .satisfies(e -> assertThat(e.getProfessionPere()).as("check professionPere").isEqualTo(actual.getProfessionPere()))
            .satisfies(e -> assertThat(e.getNomPrenomMere()).as("check nomPrenomMere").isEqualTo(actual.getNomPrenomMere()))
            .satisfies(e -> assertThat(e.getProfessionMere()).as("check professionMere").isEqualTo(actual.getProfessionMere()))
            .satisfies(e -> assertThat(e.getMedecinTraitant()).as("check medecinTraitant").isEqualTo(actual.getMedecinTraitant()))
            .satisfies(e -> assertThat(e.getServiceOrigine()).as("check serviceOrigine").isEqualTo(actual.getServiceOrigine()))
            .satisfies(e ->
                assertThat(e.getBiologisteResponsableDg())
                    .as("check biologisteResponsableDg")
                    .isEqualTo(actual.getBiologisteResponsableDg())
            )
            .satisfies(e -> assertThat(e.getDiagnostic()).as("check diagnostic").isEqualTo(actual.getDiagnostic()))
            .satisfies(e -> assertThat(e.getAutreDiagnostic()).as("check autreDiagnostic").isEqualTo(actual.getAutreDiagnostic()))
            .satisfies(e -> assertThat(e.getAnneeDiagnostic()).as("check anneeDiagnostic").isEqualTo(actual.getAnneeDiagnostic()))
            .satisfies(e ->
                assertThat(e.getConsentementRegistre()).as("check consentementRegistre").isEqualTo(actual.getConsentementRegistre())
            )
            .satisfies(e ->
                assertThat(e.getDateEnregistrementRegistre())
                    .as("check dateEnregistrementRegistre")
                    .isEqualTo(actual.getDateEnregistrementRegistre())
            )
            .satisfies(e -> assertThat(e.getDossierNumber()).as("check dossierNumber").isEqualTo(actual.getDossierNumber()))
            .satisfies(e -> assertThat(e.getOrdreNumber()).as("check ordreNumber").isEqualTo(actual.getOrdreNumber()))
            .satisfies(e -> assertThat(e.getIndexNumber()).as("check indexNumber").isEqualTo(actual.getIndexNumber()))
            .satisfies(e -> assertThat(e.getParentsConsanguins()).as("check parentsConsanguins").isEqualTo(actual.getParentsConsanguins()))
            .satisfies(e ->
                assertThat(e.getDegreParenteConsanguins())
                    .as("check degreParenteConsanguins")
                    .isEqualTo(actual.getDegreParenteConsanguins())
            )
            .satisfies(e -> assertThat(e.getCasSimilaires()).as("check casSimilaires").isEqualTo(actual.getCasSimilaires()))
            .satisfies(e -> assertThat(e.getNombreCas()).as("check nombreCas").isEqualTo(actual.getNombreCas()))
            .satisfies(e ->
                assertThat(e.getDegreParenteCasSimilaires())
                    .as("check degreParenteCasSimilaires")
                    .isEqualTo(actual.getDegreParenteCasSimilaires())
            )
            .satisfies(e ->
                assertThat(e.getDecesSyndromeHemorragique())
                    .as("check decesSyndromeHemorragique")
                    .isEqualTo(actual.getDecesSyndromeHemorragique())
            )
            .satisfies(e -> assertThat(e.getNombreDeces()).as("check nombreDeces").isEqualTo(actual.getNombreDeces()))
            .satisfies(e -> assertThat(e.getFormeHemophilie()).as("check formeHemophilie").isEqualTo(actual.getFormeHemophilie()))
            .satisfies(e -> assertThat(e.getFratrieNbFreres()).as("check fratrieNbFreres").isEqualTo(actual.getFratrieNbFreres()))
            .satisfies(e -> assertThat(e.getFratrieNbSoeurs()).as("check fratrieNbSoeurs").isEqualTo(actual.getFratrieNbSoeurs()))
            .satisfies(e -> assertThat(e.getEnqueteFamiliale()).as("check enqueteFamiliale").isEqualTo(actual.getEnqueteFamiliale()))
            .satisfies(e ->
                assertThat(e.getExplorationSyndrome()).as("check explorationSyndrome").isEqualTo(actual.getExplorationSyndrome())
            )
            .satisfies(e -> assertThat(e.getCutaneoMuqueux()).as("check cutaneoMuqueux").isEqualTo(actual.getCutaneoMuqueux()))
            .satisfies(e -> assertThat(e.getHemarthrose()).as("check hemarthrose").isEqualTo(actual.getHemarthrose()))
            .satisfies(e ->
                assertThat(e.getHematomePostTraumatique())
                    .as("check hematomePostTraumatique")
                    .isEqualTo(actual.getHematomePostTraumatique())
            )
            .satisfies(e ->
                assertThat(e.getPlaiePostTraumatique()).as("check plaiePostTraumatique").isEqualTo(actual.getPlaiePostTraumatique())
            )
            .satisfies(e ->
                assertThat(e.getHemorragiePostCirconcision())
                    .as("check hemorragiePostCirconcision")
                    .isEqualTo(actual.getHemorragiePostCirconcision())
            )
            .satisfies(e ->
                assertThat(e.getHemorragiePostChirurgie())
                    .as("check hemorragiePostChirurgie")
                    .isEqualTo(actual.getHemorragiePostChirurgie())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieCerebrale()).as("check hemorragieCerebrale").isEqualTo(actual.getHemorragieCerebrale())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieDigestive()).as("check hemorragieDigestive").isEqualTo(actual.getHemorragieDigestive())
            )
            .satisfies(e ->
                assertThat(e.getDatePremierSigneClinique())
                    .as("check datePremierSigneClinique")
                    .isEqualTo(actual.getDatePremierSigneClinique())
            )
            .satisfies(e -> assertThat(e.getAgeDiagnosticJours()).as("check ageDiagnosticJours").isEqualTo(actual.getAgeDiagnosticJours()))
            .satisfies(e -> assertThat(e.getAgeDiagnosticMois()).as("check ageDiagnosticMois").isEqualTo(actual.getAgeDiagnosticMois()))
            .satisfies(e ->
                assertThat(e.getAgeDiagnosticAnnees()).as("check ageDiagnosticAnnees").isEqualTo(actual.getAgeDiagnosticAnnees())
            )
            .satisfies(e ->
                assertThat(e.getDateTestConfirmation()).as("check dateTestConfirmation").isEqualTo(actual.getDateTestConfirmation())
            )
            .satisfies(e -> assertThat(e.getHb()).as("check hb").isEqualTo(actual.getHb()))
            .satisfies(e -> assertThat(e.getHt()).as("check ht").isEqualTo(actual.getHt()))
            .satisfies(e -> assertThat(e.getPlaquettes()).as("check plaquettes").isEqualTo(actual.getPlaquettes()))
            .satisfies(e -> assertThat(e.getTp()).as("check tp").isEqualTo(actual.getTp()))
            .satisfies(e -> assertThat(e.getFibrinogene()).as("check fibrinogene").isEqualTo(actual.getFibrinogene()))
            .satisfies(e -> assertThat(e.getTcaMT()).as("check tcaMT").isEqualTo(actual.getTcaMT()))
            .satisfies(e -> assertThat(e.getTcaMTTotal()).as("check tcaMTTotal").isEqualTo(actual.getTcaMTTotal()))
            .satisfies(e -> assertThat(e.getTcaMT2h()).as("check tcaMT2h").isEqualTo(actual.getTcaMT2h()))
            .satisfies(e -> assertThat(e.getTcaTemoin2h()).as("check tcaTemoin2h").isEqualTo(actual.getTcaTemoin2h()))
            .satisfies(e -> assertThat(e.getTs()).as("check ts").isEqualTo(actual.getTs()))
            .satisfies(e -> assertThat(e.getPfa()).as("check pfa").isEqualTo(actual.getPfa()))
            .satisfies(e -> assertThat(e.getDosageFacteurVIII()).as("check dosageFacteurVIII").isEqualTo(actual.getDosageFacteurVIII()))
            .satisfies(e -> assertThat(e.getDosageFacteurIX()).as("check dosageFacteurIX").isEqualTo(actual.getDosageFacteurIX()))
            .satisfies(e ->
                assertThat(e.getDosageFacteurVWActivite())
                    .as("check dosageFacteurVWActivite")
                    .isEqualTo(actual.getDosageFacteurVWActivite())
            )
            .satisfies(e ->
                assertThat(e.getDosageFacteurVWAntigene())
                    .as("check dosageFacteurVWAntigene")
                    .isEqualTo(actual.getDosageFacteurVWAntigene())
            )
            .satisfies(e -> assertThat(e.getFormeClinique()).as("check formeClinique").isEqualTo(actual.getFormeClinique()))
            .satisfies(e -> assertThat(e.getSeverite()).as("check severite").isEqualTo(actual.getSeverite()))
            .satisfies(e ->
                assertThat(e.getExplorationMoleculaire()).as("check explorationMoleculaire").isEqualTo(actual.getExplorationMoleculaire())
            )
            .satisfies(e -> assertThat(e.getInversionIntron22()).as("check inversionIntron22").isEqualTo(actual.getInversionIntron22()))
            .satisfies(e ->
                assertThat(e.getAutreExplorationMoleculaire())
                    .as("check autreExplorationMoleculaire")
                    .isEqualTo(actual.getAutreExplorationMoleculaire())
            )
            .satisfies(e -> assertThat(e.getHemarthroseSiege()).as("check hemarthroseSiege").isEqualTo(actual.getHemarthroseSiege()))
            .satisfies(e -> assertThat(e.getHemarthroseType()).as("check hemarthroseType").isEqualTo(actual.getHemarthroseType()))
            .satisfies(e ->
                assertThat(e.getHemarthroseFrequenceAn()).as("check hemarthroseFrequenceAn").isEqualTo(actual.getHemarthroseFrequenceAn())
            )
            .satisfies(e ->
                assertThat(e.getHematomeSuperficiel()).as("check hematomeSuperficiel").isEqualTo(actual.getHematomeSuperficiel())
            )
            .satisfies(e ->
                assertThat(e.getHematomeSuperficielType())
                    .as("check hematomeSuperficielType")
                    .isEqualTo(actual.getHematomeSuperficielType())
            )
            .satisfies(e ->
                assertThat(e.getHematomeSuperficielSiege())
                    .as("check hematomeSuperficielSiege")
                    .isEqualTo(actual.getHematomeSuperficielSiege())
            )
            .satisfies(e -> assertThat(e.getHematomePsoas()).as("check hematomePsoas").isEqualTo(actual.getHematomePsoas()))
            .satisfies(e -> assertThat(e.getHematomePsoasType()).as("check hematomePsoasType").isEqualTo(actual.getHematomePsoasType()))
            .satisfies(e ->
                assertThat(e.getHematomePsoasRecidive()).as("check hematomePsoasRecidive").isEqualTo(actual.getHematomePsoasRecidive())
            )
            .satisfies(e ->
                assertThat(e.getHemorragiesCutaneoMuqueuses())
                    .as("check hemorragiesCutaneoMuqueuses")
                    .isEqualTo(actual.getHemorragiesCutaneoMuqueuses())
            )
            .satisfies(e ->
                assertThat(e.getHemorragiesCutaneoMuqueusesTypes())
                    .as("check hemorragiesCutaneoMuqueusesTypes")
                    .isEqualTo(actual.getHemorragiesCutaneoMuqueusesTypes())
            )
            .satisfies(e ->
                assertThat(e.getHemorragiesCutaneoMuqueusesFrequenceAn())
                    .as("check hemorragiesCutaneoMuqueusesFrequenceAn")
                    .isEqualTo(actual.getHemorragiesCutaneoMuqueusesFrequenceAn())
            )
            .satisfies(e -> assertThat(e.getHemorragieVisceres()).as("check hemorragieVisceres").isEqualTo(actual.getHemorragieVisceres()))
            .satisfies(e ->
                assertThat(e.getHemorragieVisceresType()).as("check hemorragieVisceresType").isEqualTo(actual.getHemorragieVisceresType())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieVisceresExploration())
                    .as("check hemorragieVisceresExploration")
                    .isEqualTo(actual.getHemorragieVisceresExploration())
            )
            .satisfies(e ->
                assertThat(e.getHemorragieVisceresExamen())
                    .as("check hemorragieVisceresExamen")
                    .isEqualTo(actual.getHemorragieVisceresExamen())
            )
            .satisfies(e -> assertThat(e.getSaignementSNC()).as("check saignementSNC").isEqualTo(actual.getSaignementSNC()))
            .satisfies(e ->
                assertThat(e.getSaignementSNCEvolution()).as("check saignementSNCEvolution").isEqualTo(actual.getSaignementSNCEvolution())
            )
            .satisfies(e -> assertThat(e.getCirconcision()).as("check circoncision").isEqualTo(actual.getCirconcision()))
            .satisfies(e ->
                assertThat(e.getCirconcisionPreparation())
                    .as("check circoncisionPreparation")
                    .isEqualTo(actual.getCirconcisionPreparation())
            )
            .satisfies(e ->
                assertThat(e.getCirconcisionSuiteOperatoire())
                    .as("check circoncisionSuiteOperatoire")
                    .isEqualTo(actual.getCirconcisionSuiteOperatoire())
            )
            .satisfies(e -> assertThat(e.getCirconcisionAge()).as("check circoncisionAge").isEqualTo(actual.getCirconcisionAge()))
            .satisfies(e -> assertThat(e.getAvulsionDentaire()).as("check avulsionDentaire").isEqualTo(actual.getAvulsionDentaire()))
            .satisfies(e ->
                assertThat(e.getAvulsionDentairePreparation())
                    .as("check avulsionDentairePreparation")
                    .isEqualTo(actual.getAvulsionDentairePreparation())
            )
            .satisfies(e ->
                assertThat(e.getInterventionChirurgicale())
                    .as("check interventionChirurgicale")
                    .isEqualTo(actual.getInterventionChirurgicale())
            )
            .satisfies(e ->
                assertThat(e.getInterventionChirurgicaleType())
                    .as("check interventionChirurgicaleType")
                    .isEqualTo(actual.getInterventionChirurgicaleType())
            )
            .satisfies(e ->
                assertThat(e.getAccidentsHemorragiquesGraves())
                    .as("check accidentsHemorragiquesGraves")
                    .isEqualTo(actual.getAccidentsHemorragiquesGraves())
            )
            .satisfies(e ->
                assertThat(e.getAccidentsHemorragiquesGravesTypes())
                    .as("check accidentsHemorragiquesGravesTypes")
                    .isEqualTo(actual.getAccidentsHemorragiquesGravesTypes())
            )
            .satisfies(e ->
                assertThat(e.getPriseEnChargeTherapeutique())
                    .as("check priseEnChargeTherapeutique")
                    .isEqualTo(actual.getPriseEnChargeTherapeutique())
            )
            .satisfies(e -> assertThat(e.getCausePriseEnCharge()).as("check causePriseEnCharge").isEqualTo(actual.getCausePriseEnCharge()))
            .satisfies(e ->
                assertThat(e.getProphylaxieDoseFrequence())
                    .as("check prophylaxieDoseFrequence")
                    .isEqualTo(actual.getProphylaxieDoseFrequence())
            )
            .satisfies(e ->
                assertThat(e.getDateDebutProphylaxie()).as("check dateDebutProphylaxie").isEqualTo(actual.getDateDebutProphylaxie())
            )
            .satisfies(e -> assertThat(e.getInjectionType()).as("check injectionType").isEqualTo(actual.getInjectionType()))
            .satisfies(e -> assertThat(e.getModaliteTraitement()).as("check modaliteTraitement").isEqualTo(actual.getModaliteTraitement()))
            .satisfies(e ->
                assertThat(e.getTypeTraitementSubstitutif())
                    .as("check typeTraitementSubstitutif")
                    .isEqualTo(actual.getTypeTraitementSubstitutif())
            )
            .satisfies(e ->
                assertThat(e.getAgePremiereSubstitution())
                    .as("check agePremiereSubstitution")
                    .isEqualTo(actual.getAgePremiereSubstitution())
            )
            .satisfies(e ->
                assertThat(e.getAntecedentsTraitementPSL())
                    .as("check antecedentsTraitementPSL")
                    .isEqualTo(actual.getAntecedentsTraitementPSL())
            )
            .satisfies(e -> assertThat(e.getPlasmaFraisCongele()).as("check plasmaFraisCongele").isEqualTo(actual.getPlasmaFraisCongele()))
            .satisfies(e -> assertThat(e.getCryoprecipite()).as("check cryoprecipite").isEqualTo(actual.getCryoprecipite()))
            .satisfies(e -> assertThat(e.getSynovite()).as("check synovite").isEqualTo(actual.getSynovite()))
            .satisfies(e ->
                assertThat(e.getArthropathieHemophiliqueChronique())
                    .as("check arthropathieHemophiliqueChronique")
                    .isEqualTo(actual.getArthropathieHemophiliqueChronique())
            )
            .satisfies(e -> assertThat(e.getPseudotumeurs()).as("check pseudotumeurs").isEqualTo(actual.getPseudotumeurs()))
            .satisfies(e -> assertThat(e.getFractures()).as("check fractures").isEqualTo(actual.getFractures()))
            .satisfies(e -> assertThat(e.getArticulationCible()).as("check articulationCible").isEqualTo(actual.getArticulationCible()))
            .satisfies(e -> assertThat(e.getPecTherapeutique()).as("check pecTherapeutique").isEqualTo(actual.getPecTherapeutique()))
            .satisfies(e -> assertThat(e.getInhibiteurs()).as("check inhibiteurs").isEqualTo(actual.getInhibiteurs()))
            .satisfies(e -> assertThat(e.getTauxInhibiteur()).as("check tauxInhibiteur").isEqualTo(actual.getTauxInhibiteur()))
            .satisfies(e ->
                assertThat(e.getTestRecuperationFAH()).as("check testRecuperationFAH").isEqualTo(actual.getTestRecuperationFAH())
            )
            .satisfies(e ->
                assertThat(e.getDateTestRecuperation()).as("check dateTestRecuperation").isEqualTo(actual.getDateTestRecuperation())
            )
            .satisfies(e -> assertThat(e.getTauxRecuperation()).as("check tauxRecuperation").isEqualTo(actual.getTauxRecuperation()))
            .satisfies(e ->
                assertThat(e.getAntiFAHNonNeutralisant()).as("check antiFAHNonNeutralisant").isEqualTo(actual.getAntiFAHNonNeutralisant())
            )
            .satisfies(e -> assertThat(e.getAntiFAHNegatif()).as("check antiFAHNegatif").isEqualTo(actual.getAntiFAHNegatif()))
            .satisfies(e -> assertThat(e.getRechercheACC()).as("check rechercheACC").isEqualTo(actual.getRechercheACC()))
            .satisfies(e ->
                assertThat(e.getAugmenterDoseFacteur()).as("check augmenterDoseFacteur").isEqualTo(actual.getAugmenterDoseFacteur())
            )
            .satisfies(e -> assertThat(e.getNovoseven()).as("check novoseven").isEqualTo(actual.getNovoseven()))
            .satisfies(e -> assertThat(e.getFeiba()).as("check feiba").isEqualTo(actual.getFeiba()))
            .satisfies(e -> assertThat(e.getCorticotherapie()).as("check corticotherapie").isEqualTo(actual.getCorticotherapie()))
            .satisfies(e -> assertThat(e.getImmurel()).as("check immurel").isEqualTo(actual.getImmurel()))
            .satisfies(e -> assertThat(e.getIti()).as("check iti").isEqualTo(actual.getIti()))
            .satisfies(e -> assertThat(e.getPosologieITI()).as("check posologieITI").isEqualTo(actual.getPosologieITI()))
            .satisfies(e -> assertThat(e.getDureeITI()).as("check dureeITI").isEqualTo(actual.getDureeITI()))
            .satisfies(e -> assertThat(e.getObservanceITI()).as("check observanceITI").isEqualTo(actual.getObservanceITI()))
            .satisfies(e -> assertThat(e.getCauseNonObservance()).as("check causeNonObservance").isEqualTo(actual.getCauseNonObservance()))
            .satisfies(e ->
                assertThat(e.getEvolutionInhibiteur()).as("check evolutionInhibiteur").isEqualTo(actual.getEvolutionInhibiteur())
            )
            .satisfies(e ->
                assertThat(e.getProphylaxieHemlibra()).as("check prophylaxieHemlibra").isEqualTo(actual.getProphylaxieHemlibra())
            )
            .satisfies(e -> assertThat(e.getDateDebutHemlibra()).as("check dateDebutHemlibra").isEqualTo(actual.getDateDebutHemlibra()))
            .satisfies(e ->
                assertThat(e.getSchemaTherapeutique()).as("check schemaTherapeutique").isEqualTo(actual.getSchemaTherapeutique())
            )
            .satisfies(e -> assertThat(e.getEfficaciteHemlibra()).as("check efficaciteHemlibra").isEqualTo(actual.getEfficaciteHemlibra()))
            .satisfies(e -> assertThat(e.getSerologieHBC()).as("check serologieHBC").isEqualTo(actual.getSerologieHBC()))
            .satisfies(e -> assertThat(e.getSerologieHVC()).as("check serologieHVC").isEqualTo(actual.getSerologieHVC()))
            .satisfies(e -> assertThat(e.getDateDecouverteVHC()).as("check dateDecouverteVHC").isEqualTo(actual.getDateDecouverteVHC()))
            .satisfies(e -> assertThat(e.getChargeViraleVHC()).as("check chargeViraleVHC").isEqualTo(actual.getChargeViraleVHC()))
            .satisfies(e -> assertThat(e.getTraitementVHC()).as("check traitementVHC").isEqualTo(actual.getTraitementVHC()))
            .satisfies(e -> assertThat(e.getEvolutionVHC()).as("check evolutionVHC").isEqualTo(actual.getEvolutionVHC()))
            .satisfies(e -> assertThat(e.getSerologieHIV()).as("check serologieHIV").isEqualTo(actual.getSerologieHIV()))
            .satisfies(e -> assertThat(e.getVieSociale()).as("check vieSociale").isEqualTo(actual.getVieSociale()))
            .satisfies(e -> assertThat(e.getMarie()).as("check marie").isEqualTo(actual.getMarie()))
            .satisfies(e -> assertThat(e.getEnfants()).as("check enfants").isEqualTo(actual.getEnfants()))
            .satisfies(e -> assertThat(e.getHandicap()).as("check handicap").isEqualTo(actual.getHandicap()))
            .satisfies(e -> assertThat(e.getTypeHandicap()).as("check typeHandicap").isEqualTo(actual.getTypeHandicap()))
            .satisfies(e -> assertThat(e.getActiviteSportive()).as("check activiteSportive").isEqualTo(actual.getActiviteSportive()))
            .satisfies(e ->
                assertThat(e.getTypeActiviteSportive()).as("check typeActiviteSportive").isEqualTo(actual.getTypeActiviteSportive())
            )
            .satisfies(e -> assertThat(e.getDecede()).as("check decede").isEqualTo(actual.getDecede()))
            .satisfies(e -> assertThat(e.getCauseDeces()).as("check causeDeces").isEqualTo(actual.getCauseDeces()))
            .satisfies(e -> assertThat(e.getDateDeces()).as("check dateDeces").isEqualTo(actual.getDateDeces()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheHemophilieUpdatableRelationshipsEquals(FicheHemophilie expected, FicheHemophilie actual) {
        // empty method
    }
}
