import dayjs from 'dayjs/esm';

import { IFicheFacteurXVIII, NewFicheFacteurXVIII } from './fiche-facteur-xviii.model';

export const sampleWithRequiredData: IFicheFacteurXVIII = {
  id: 886,
  etatCivil: 'NP',
  serviceClinique: 'GYNECO',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_VII',
};

export const sampleWithPartialData: IFicheFacteurXVIII = {
  id: 10452,
  indexNumber: 'bè ci',
  profession: 'pauvre bientôt généralise',
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'PUR',
  couvertureSociale: 'INDIGENT',
  sexe: 'FEMININ',
  ageActuel: 23839,
  origine: 'AUTRE',
  autreOrigine: 'vis-à-vie de propre durer',
  adresse: "plic fonctionnaire à l'ég",
  telephone: '0607504693',
  professionMere: 'diététiste observer',
  serviceOrigine: 'zzzz camarade participer',
  biologisteResponsableDg: 'ouah',
  diagnostic: 'HEMOPHILIE',
  anneeDiagnostic: 1746,
  parentsConsanguins: 'NON',
  degreParenteConsanguins: 'LOINTAIN',
  casSimilaires: 'NP',
  lienParenteCas1: 'LOINTAIN',
  degreParenteCas1: 'probablement hé',
  cas2Numero: 25831,
  lienParenteCas2: 'COUSIN',
  typeHemorragieCas2: 'remercier virer',
  cas3Numero: 7305,
  lienParenteCas3: 'COUSIN',
  degreParenteCas3: 'pschitt',
  typeHemorragieCas3: 'commis de cuisine demain',
  nombreDeces: 6280,
  lienParenteDeces1: 'COUSIN',
  lienParenteDeces2: 'COUSIN',
  causeDeces2: 'population du Québec offrir',
  lienParenteDeces3: 'FRERE',
  enqueteFamiliale: false,
  circHemorragique: false,
  decouverteFortuitePreop: false,
  precisionsDecouverteFortuite: 'blablabla prou miaou',
  jamaisSaignement: 'NP',
  agePremierSigneJours: 4518,
  agePremierSigneAnnees: 11278,
  symptomeEpistaxis: true,
  symptomeGingivorragies: false,
  symptomeMetrorragies: true,
  symptomeMelena: false,
  symptomeChuteCordon: true,
  agePremiereConsultationAnnees: 224,
  ageDiagnosticAnnees: 9671,
  tpMPlusT: 621.23,
  facteurDeficitaireAutre: 'pour que adapter chut',
  tauxFacteurDeficitaireAutre: 19130,
  tauxSupplementaire1: 6754.17,
  facteurSupplementaire3: 'absorber probablement',
  tauxSupplementaire3: 4338.69,
  mutationType: 'HOMOZYGOTE',
  mutation2Nom: 'horrible drelin grrr',
  serologieVHB: 'NP',
  serologieVHC: 'NON_FAITE',
  serologieVIH: 'NEGATIVE',
  gingivorragies: true,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 194,
  ecchymose: true,
  typeEcchymose: 'SPONTANE',
  frequenceEcchymose: 19619,
  frequenceMenorragie: 28933,
  hematemese: false,
  frequenceHematemese: 10954,
  rectorragie: true,
  frequenceRectorragie: 19109,
  hematomeMusculaire: true,
  siegeHematomeMusculaire: 'coac coac parer',
  typeHemarthrose: 'SPONTANE',
  typeSaignementSNC: 'PROVOQUE',
  frequenceSaignementSNC: 17545,
  saignementChuteCordon: false,
  frequenceSaignementChuteCordon: 13457,
  retardCicatrisationPlaies: true,
  faussesCouchesSpontaneesRecurrence: false,
  thromboseArterielle: false,
  frequenceAccidentsThrombotiques: 10171,
  hemoperitoine: false,
  frequenceHemoperitoine: 5840,
  ruptureKystesHemorragiques: true,
  frequenceRuptureKystes: 6214,
  frequenceHemorragieGrave: 28094,
  graviteParLocalisation: true,
  siegeGraviteLocalisation: 'en dedans de propre',
  chirurgiePrepare: 'OUI',
  circoncisionSuiteHemorragique: 'NP',
  ageCirconcision: 10517,
  traitementCulotsPlaquettaires: 'NP',
  traitementExacyl: 'OUI',
  traitementMartial: 'OUI',
  traitementOestroprogestatif: 'OUI',
  inhibiteurNeutralisant: 'OUI',
  titreInhibiteurUB: 13150.26,
  inhibiteurNonNeutralisant: 'NON',
  infectionVHB: 'NP',
  thrombose: false,
  reactionAllergique: true,
  autresComplications: 'touchant toujours du côté de',
  sequelles: 'OUI',
  typeSequelles: 'extra antagoniste',
  patientDecede: 'NON',
  dateDeces: dayjs('2025-05-09'),
  causeDeces: 'COVID19',
};

export const sampleWithFullData: IFicheFacteurXVIII = {
  id: 2007,
  dossierNumber: 'blablabla jeune enfant',
  ordreNumber: 'hors de',
  indexNumber: 'de la part de foule',
  prenom: 'personnel professionnel é',
  nom: 'rectangulaire disposer le',
  nomJeuneFille: 'fourbe de façon que sur',
  profession: 'au défaut de collègue mag',
  etatCivil: 'CELIBATAIRE',
  serviceClinique: 'GYNECO',
  autreServiceClinique: 'embarquer cadre remplir',
  couvertureSociale: 'INDIGENT',
  sexe: 'MASCULIN',
  dateNaissance: dayjs('2025-05-09'),
  ageActuel: 4625,
  origine: 'SFAX',
  autreOrigine: 'chef par',
  adresse: 'même si ferme',
  telephone: '+33 445710391',
  prenomPere: 'proche',
  professionPere: 'sacrifier près de siffler',
  nomPrenomMere: 'auparavant triathlète',
  professionMere: 'puisque avant-hier',
  medecinTraitant: 'mince',
  serviceOrigine: 'touriste',
  biologisteResponsableDg: 'dès que de crainte que',
  diagnostic: 'DEFICIT_FACTEUR_VII',
  autreDiagnostic: 'tellement lunatique broum',
  anneeDiagnostic: 23237,
  consentementRegistre: 'NON',
  dateEnregistrementRegistre: dayjs('2025-05-09'),
  parentsConsanguins: 'OUI',
  degreParenteConsanguins: 'TROISIEME_DEGRE',
  casSimilaires: 'OUI',
  nombreCas: 17064,
  cas1Numero: 24511,
  lienParenteCas1: 'LOINTAIN',
  degreParenteCas1: 'spécialiste démontrer',
  typeHemorragieCas1: 'de peur que réparer fréquenter',
  cas2Numero: 13686,
  lienParenteCas2: 'COUSIN',
  degreParenteCas2: 'ouf',
  typeHemorragieCas2: 'toc-toc auprès de',
  cas3Numero: 15337,
  lienParenteCas3: 'FRERE',
  degreParenteCas3: 'charitable dès que',
  typeHemorragieCas3: 'pendant esquisser',
  decesSyndromeHemorragique: 'OUI',
  nombreDeces: 764,
  deces1Numero: 8946,
  lienParenteDeces1: 'LOINTAIN',
  causeDeces1: 'pour que malade',
  deces2Numero: 15192,
  lienParenteDeces2: 'FRERE',
  causeDeces2: 'ci si bien que',
  deces3Numero: 31302,
  lienParenteDeces3: 'FRERE',
  causeDeces3: 'hé',
  enqueteFamiliale: true,
  circHemorragique: false,
  precisionsCircHemorragique: 'quand ? inscrire alors que',
  decouverteFortuitePreop: true,
  precisionsDecouverteFortuite: 'comme',
  jamaisSaignement: 'NON',
  agePremierSigneJours: 2217,
  agePremierSigneMois: 25323,
  agePremierSigneAnnees: 2116,
  symptomeEcchymose: true,
  symptomeEpistaxis: true,
  symptomeGingivorragies: true,
  symptomeMetrorragies: true,
  symptomeMelena: false,
  symptomeHemoptysie: true,
  symptomePostAmygdalectomie: false,
  symptomePostAvulsionDentaire: false,
  symptomeChuteCordon: true,
  symptomeAutre: false,
  symptomeAutreDescription: 'tard',
  datePremiereConsultation: dayjs('2025-05-08'),
  agePremiereConsultationJours: 21677,
  agePremiereConsultationMois: 29584,
  agePremiereConsultationAnnees: 4203,
  ageDiagnosticJours: 4293,
  ageDiagnosticMois: 12729,
  ageDiagnosticAnnees: 23120,
  hb: 9176.16,
  ht: 16462.95,
  plaquettes: 7652,
  colEpi: 1506.4,
  colAdp: 17464.61,
  tp: 11151.66,
  tpMPlusT: 24299.65,
  fibrinogene: 14998.2,
  tcaMT: 12816.92,
  tcaMPlusT: 14049.87,
  tcaTemoin: 30123.99,
  facteurDeficitaireAutre: 'toc à même user',
  tauxFacteurDeficitaireAutre: 12553.1,
  facteurSupplementaire1: 'délégation',
  tauxSupplementaire1: 8987.74,
  facteurSupplementaire2: 'auparavant',
  tauxSupplementaire2: 18081.37,
  facteurSupplementaire3: 'rectorat après-demain désagréable',
  tauxSupplementaire3: 16645.37,
  confirmationMoleculaire: 'NON',
  mutationPresente: true,
  mutationNom: 'infime',
  mutationType: 'HOMOZYGOTE',
  mutation2Nom: 'outre étant donné que',
  serologieVHB: 'NEGATIVE',
  serologieVHC: 'NP',
  serologieVIH: 'POSITIVE',
  epistaxis: true,
  frequenceEpistaxis: 27197,
  gingivorragies: false,
  typeGingivorragies: 'PROVOQUE',
  frequenceGingivorragies: 2438,
  ecchymose: true,
  typeEcchymose: 'PROVOQUE',
  frequenceEcchymose: 14912,
  menorragie: false,
  frequenceMenorragie: 20190,
  hematemese: false,
  frequenceHematemese: 2766,
  rectorragie: false,
  frequenceRectorragie: 1857,
  hematurie: true,
  frequenceHematurie: 14030,
  hematomeSousCutane: false,
  typeHematomeSousCutane: 'PROVOQUE',
  frequenceHematomeSousCutane: 28351,
  hematomeMusculaire: false,
  siegeHematomeMusculaire: 'loufoque afin que',
  typeHematomeMusculaire: 'PROVOQUE',
  frequenceHematomeMusculaire: 23515,
  hemarthrose: false,
  typeHemarthrose: 'SPONTANE',
  frequenceHemarthrose: 6230,
  saignementSNC: false,
  typeSaignementSNC: 'SPONTANE',
  frequenceSaignementSNC: 19130,
  saignementChuteCordon: false,
  frequenceSaignementChuteCordon: 3410,
  retardCicatrisationPlaies: false,
  frequenceRetardCicatrisationPlaies: 21618,
  autresManifestations: true,
  faussesCouchesSpontaneesRecurrence: false,
  frequenceFaussesCouches: 12003,
  accidentsThrombotiques: false,
  thromboseVeineuse: false,
  thromboseArterielle: false,
  frequenceAccidentsThrombotiques: 4233,
  hemoperitoine: true,
  frequenceHemoperitoine: 27526,
  ruptureKystesHemorragiques: true,
  frequenceRuptureKystes: 24244,
  hemorragieGrave: true,
  frequenceHemorragieGrave: 14221,
  graviteDeglobulisation: false,
  graviteEtatDeChoc: false,
  graviteParLocalisation: true,
  siegeGraviteLocalisation: 'agréable grrr main-d’œuvre',
  chirurgiePrepare: 'NON',
  chirurgieSuiteHemorragique: 'NP',
  circoncisionPrepare: 'OUI',
  circoncisionSuiteHemorragique: 'NON',
  ageCirconcision: 3535,
  traitementPFC: 'OUI',
  traitementCryoprecipite: 'OUI',
  traitementConcentreFacteurXI: 'NP',
  traitementCulotsPlaquettaires: 'OUI',
  traitementDicynone: 'OUI',
  traitementExacyl: 'OUI',
  traitementMartial: 'OUI',
  traitementOestroprogestatif: 'OUI',
  transfusionCGR: 'NON',
  alloImmunisation: 'NON',
  inhibiteurNeutralisant: 'NON',
  titreInhibiteurUB: 29300.64,
  inhibiteurNonNeutralisant: 'NON',
  infectionVIH: 'NON',
  infectionVHC: 'OUI',
  infectionVHB: 'NON',
  thrombose: false,
  reactionAllergique: true,
  autresComplications: 'hebdomadaire décharger',
  adherenceTherapeutique: 'NP',
  causeNonAdherence: 'bien que magnifique corps enseignant',
  statutSocial: 'SCOLARISE',
  marie: 'NON',
  enfants: 'NON',
  activitePhysique: 'OUI',
  typeActivitePhysique: 'tant fonctionnaire trop',
  sequelles: 'OUI',
  typeSequelles: 'quelquefois',
  patientDecede: 'NP',
  dateDeces: dayjs('2025-05-08'),
  ageDeces: 22157,
  causeDeces: 'INFECTION_AUTRE',
};

export const sampleWithNewData: NewFicheFacteurXVIII = {
  etatCivil: 'NP',
  serviceClinique: 'PUR',
  couvertureSociale: 'NP',
  sexe: 'FEMININ',
  diagnostic: 'DEFICIT_FACTEUR_XI',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
